Repository code-dot-org/code-dot-org, pull requests merged in 2018-07, with the labels that each got.

#23449 Remove react-storybook-addon-add-stories-group
  apps/.storybook/config.js
  apps/package.json
  apps/yarn.lock
Labels: code-hygiene

#23445 Remove unused `Ops` controllers
  dashboard/app/controllers/ops/cohorts_controller.rb
  dashboard/app/controllers/ops/districts_controller.rb
  dashboard/app/controllers/ops/ops_controller_base.rb
  dashboard/app/controllers/ops/segments_controller.rb
  dashboard/app/controllers/ops/workshop_attendance_controller.rb
  dashboard/app/controllers/ops/workshops_controller.rb
  dashboard/config/routes.rb
  dashboard/test/controllers/ops/cohorts_controller_test.rb
  dashboard/test/controllers/ops/districts_controller_test.rb
  dashboard/test/controllers/ops/segments_controller_test.rb
  dashboard/test/controllers/ops/workshop_attendance_controller_test.rb
  dashboard/test/controllers/ops/workshops_controller_test.rb
Labels: code-hygiene

#23401 Log school searches
  dashboard/app/controllers/api/v1/schools_controller.rb
Labels: access report

#23419 Remove primary_authentication_option aliases
  dashboard/app/models/user.rb
  dashboard/test/models/user_test.rb
Labels: code-hygiene

#23446 Convert Dialog and BaseDialog to ES6 classes
  apps/src/templates/BaseDialog.jsx
  apps/src/templates/Dialog.jsx
Labels: code-hygiene

#23447 Convert ProtectedStatefulDiv and ProtectedVisualizationDiv to ES6 classes
  apps/src/templates/ProtectedStatefulDiv.jsx
  apps/src/templates/ProtectedVisualizationDiv.jsx
Labels: code-hygiene

#23473 Add assessments to the teacher exp flag
  apps/src/util/experiments.js
Labels: teacher-dashboard

#23480 Restrict nearest workshop search to only those that are upcoming or current (not past)
  dashboard/app/controllers/pd/workshop_daily_survey_controller.rb
Labels: bug-fix, professional-learning

#23490 Downcase access report submission email address
  dashboard/app/models/census/census_submission.rb
  dashboard/test/models/census/census_submission_test.rb
Labels: access report

#23481 Assessments Tab: show survey names in dropdown
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
  dashboard/app/models/levels/level_group.rb
  dashboard/test/controllers/api/v1/assessments_controller_test.rb
  dashboard/test/models/level_group_test.rb
Labels: bug-fix, teacher-dashboard

#23483 Assessments: Add link to student name
  apps/src/templates/sectionAssessments/StudentsAssessmentsMCTable.jsx
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: teacher-dashboard

#23503 Assessments tab: show "Not started" student submissions in the status table
  apps/i18n/common/en_us.json
  apps/src/templates/sectionAssessments/SectionAssessments.jsx
  apps/src/templates/sectionAssessments/StudentsAssessmentsMCTable.jsx
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: teacher-dashboard

#23509 Assessments tab: fix link colours
  apps/src/templates/sectionAssessments/StudentsAssessmentsMCTable.jsx
Labels: teacher-dashboard

#23528 Assessments: sort submission time stamp column
  apps/src/templates/sectionAssessments/StudentsAssessmentsMCTable.jsx
Labels: teacher-dashboard

#23523 ES6ify CodeWorkspace
  apps/src/templates/CodeWorkspace.jsx
Labels: code-hygiene

#23520 Assessments: display message for an empty free response
  apps/i18n/common/en_us.json
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
Labels: teacher-dashboard

#23555 Remove duplicate string
  apps/i18n/common/en_us.json
Labels: code-hygiene

#23551 Assessments tab: Gray out text when no response given
  apps/i18n/common/en_us.json
  apps/src/templates/sectionAssessments/FreeResponsesAssessmentsTable.jsx
  apps/src/templates/sectionAssessments/FreeResponsesSurveyTable.jsx
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
Labels: bug-fix, teacher-dashboard

#23553 Revert "Revert "Assessments: Add color to multiple choice assessments table""
  apps/src/templates/sectionAssessments/MultipleChoiceAnswerCell.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceAssessmentsOverviewTable.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceSurveyOverviewTable.jsx
  apps/src/templates/sectionAssessments/SingleStudentAssessmentsMCTable.jsx
Labels: bug-fix, teacher-dashboard

#23515 Assessments: Style free responses assessments question
  apps/i18n/common/en_us.json
  apps/src/templates/sectionAssessments/FreeResponseBySurveyQuestionContainer.jsx
  apps/src/templates/sectionAssessments/FreeResponsesAssessmentsContainer.jsx
Labels: teacher-dashboard

#23561 Thanks donors on twitter from hoc.com
  pegasus/sites.v3/hourofcode.com/i18n/en.yml
  pegasus/sites.v3/hourofcode.com/public/promote/index.md
  pegasus/sites.v3/hourofcode.com/public/thanks.md
Labels: hoc

#23562 Clarify background color calculations
  apps/src/templates/sectionAssessments/MultipleChoiceAnswerCell.jsx
Labels: code-hygiene, teacher-dashboard

#23570 Bug fix: reset to all student filter when switching scripts
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: teacher-dashboard

#23587 Use dashboardapi/sections endpoints in NetSimLobby
  apps/src/netsim/NetSimLobby.js
Labels: code-hygiene

#23569 Assessments tab: Use local time in assessment status table
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
  dashboard/app/controllers/api/v1/assessments_controller.rb
  dashboard/test/controllers/api/v1/assessments_controller_test.rb
Labels: teacher-dashboard

#23604 Assessments: Non verified teachers shouldn't see spinner forever
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
Labels: bug-fix

#23605 Assessments Tab: Show a no assessments found message
  apps/i18n/common/en_us.json
  apps/src/templates/sectionAssessments/SectionAssessments.jsx
Labels: bug-fix, teacher-dashboard

#23497 Add post submit routes for jotform, prevent duplicate submissions,
  dashboard/app/controllers/pd/workshop_daily_survey_controller.rb
  dashboard/app/models/concerns/pd/jot_form_backed_form.rb
  dashboard/app/models/pd/workshop_daily_survey.rb
  dashboard/app/models/pd/workshop_facilitator_daily_survey.rb
  dashboard/app/views/pd/workshop_daily_survey/too_late.haml
  dashboard/config/routes.rb
  dashboard/test/controllers/pd/workshop_daily_survey_controller_test.rb
  dashboard/test/factories/pd_factories.rb
  dashboard/test/models/pd/workshop_daily_survey_test.rb
  dashboard/test/models/pd/workshop_facilitator_daily_survey_test.rb
Labels: professional-learning

#23609 Import Louisiana course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#23585 Launch React Text Responses Tab - merge 7/16
  apps/src/sites/code.org/pages/public/teacher-dashboard/index.js
  apps/src/util/experiments.js
  pegasus/sites.v3/code.org/public/teacher-dashboard/section_assessments.haml
  pegasus/sites.v3/code.org/public/teacher-dashboard/section_responses.haml
Labels: teacher-dashboard

#23615 Assessments tab: Prevent errors in assessments APIs returns
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
Labels: bug-fix, teacher-dashboard

#23616 Move controller helper method into model and call with safe navigation...
  dashboard/app/controllers/api/v1/pd/workshops_controller.rb
  dashboard/app/models/pd/workshop.rb
Labels: bug-fix, professional-learning

#23630 Fix several bugs in the new JotForm sync: skip placeholders in result…
  dashboard/app/helpers/pd/workshop_survey_results_helper.rb
  dashboard/app/models/concerns/pd/jot_form_backed_form.rb
  dashboard/app/models/pd/workshop_daily_survey.rb
  dashboard/app/models/pd/workshop_facilitator_daily_survey.rb
  dashboard/test/models/pd/workshop_daily_survey_test.rb
  dashboard/test/models/pd/workshop_facilitator_daily_survey_test.rb
Labels: bug-fix, professional-learning

#23647 Exit early from JotForm cronjob scripts before loading Rails if another one is running.
  dashboard/bin/fill_jotform_placeholders
  dashboard/bin/sync_jotforms
Labels: bug-fix, infrastructure

#23640 Remove temporary JotForm transition code, no longer needed
  dashboard/app/controllers/pd/workshop_daily_survey_controller.rb
  dashboard/config/routes.rb
Labels: professional-learning

#23657 Consolidate and clean up duplicate JotForm code and add concern unit tests
  dashboard/app/models/concerns/pd/jot_form_backed_form.rb
  dashboard/app/models/pd/post_course_survey.rb
  dashboard/app/models/pd/workshop_daily_survey.rb
  dashboard/app/models/pd/workshop_facilitator_daily_survey.rb
  dashboard/test/models/concerns/pd/jot_form_backed_form_test.rb
Labels: code-hygiene, professional-learning, testing

#23689 ES6ify Instructions components
  apps/src/templates/instructions/InstructionsDialogWrapper.jsx
  apps/src/templates/instructions/InstructionsWithWorkspace.jsx
  apps/test/unit/templates/instructions/InstructionsDialogWrapperTest.jsx
  apps/test/unit/templates/instructions/InstructionsWithWorkspaceTest.jsx
Labels: code-hygiene

#23668 MIGRATION: create Access Report OtherCurriculumOffering table
  dashboard/app/models/census/other_curriculum_offering.rb
  dashboard/db/migrate/20180712175948_create_census_other_curriculum_offerings.rb
  dashboard/db/schema.rb
Labels: access report

#23584 Launch React Teacher Dashboard - merge 07/16
  apps/src/sites/code.org/pages/public/teacher-dashboard/index.js
  apps/src/util/experiments.js
  dashboard/test/ui/features/teacher_dashboard.feature
  pegasus/sites.v3/code.org/public/teacher-dashboard/section_assessments.haml
  pegasus/sites.v3/code.org/public/teacher-dashboard/section_progress.haml
  pegasus/sites.v3/code.org/public/teacher-dashboard/section_responses.haml
Labels: teacher-dashboard

#23581 Track deprecated assessments API - merge 07/16
  dashboard/app/controllers/api_controller.rb
Labels: teacher-dashboard

#23724 Assessments Tab: rename components
  apps/src/templates/sectionAssessments/FreeResponsesSurveyContainer.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceAssessmentsOverviewContainer.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceByStudentContainer.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceByStudentTable.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceByStudentTable.story.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceSurveyOverviewContainer.jsx
  apps/src/templates/sectionAssessments/SectionAssessments.jsx
  apps/src/templates/sectionAssessments/SubmissionStatusAssessmentsContainer.jsx
  apps/src/templates/sectionAssessments/SubmissionStatusAssessmentsTable.jsx
  apps/src/templates/sectionAssessments/SubmissionStatusAssessmentsTable.story.jsx
  apps/test/unit/templates/sectionAssessments/SubmissionStatusAssessmentsTableTest.js
Labels: code-hygiene, teacher-dashboard

#23734 Add timestamps to JotForm survey tables
  dashboard/app/models/pd/post_course_survey.rb
  dashboard/app/models/pd/workshop_daily_survey.rb
  dashboard/app/models/pd/workshop_facilitator_daily_survey.rb
  dashboard/db/migrate/20180716214410_add_timestamps_to_jot_form_tables.rb
  dashboard/db/schema.rb
Labels: professional-learning

#23735 Projects: set up experiment for showing React PersonalProjectsTable
  apps/src/sites/studio/pages/projects/index.js
  apps/src/util/experiments.js
  dashboard/app/views/projects/index.html.haml
Labels: star-labs

#23432 New methods to access and update skip_content_moderation value
  apps/src/code-studio/initApp/project.js
  apps/src/code-studio/showProjectAdmin.js
  shared/middleware/channels_api.rb
  shared/middleware/helpers/auth_helpers.rb
  shared/middleware/helpers/storage_apps.rb
  shared/test/middleware/helpers/test_storage_apps.rb
  shared/test/test_channels.rb
Labels: star-labs

#23744 Remove calls to API in angular that are no longer needed
  apps/src/sites/code.org/pages/public/teacher-dashboard/index.js
Labels: code-hygiene, teacher-dashboard

#23763 Assessments tab: free response question details
  apps/src/templates/sectionAssessments/FreeResponseDetailsDialog.jsx
  apps/src/templates/sectionAssessments/FreeResponseDetailsDialog.story.jsx
  apps/src/templates/sectionAssessments/FreeResponsesAssessmentsContainer.jsx
  apps/src/templates/sectionAssessments/FreeResponsesSurveyContainer.jsx
  apps/src/templates/sectionAssessments/SectionAssessments.jsx
Labels: teacher-dashboard

#23768 Assessments tab: Free response detail view follow up
  apps/src/templates/sectionAssessments/FreeResponseDetailsDialog.story.jsx
  apps/src/templates/sectionAssessments/FreeResponsesAssessmentsContainer.jsx
  apps/src/templates/sectionAssessments/FreeResponsesSurveyContainer.jsx
  apps/src/templates/sectionAssessments/assessmentDataShapes.js
Labels: teacher-dashboard

#23790 Remove old versions of section_assessments and section_surveys
  dashboard/app/controllers/api_controller.rb
  dashboard/config/routes.rb
  dashboard/test/controllers/api_controller_test.rb
Labels: code-hygiene

#23806 Skip null answers and empty answers, logging a warning for null
  dashboard/lib/pd/jot_form/translation.rb
  dashboard/test/lib/pd/jot_form/translation_test.rb
Labels: professional-learning

#23812 AssessmentsTab: Multiple choice detail view v 2 / 3
  apps/src/templates/sectionAssessments/FreeResponseDetailsDialog.jsx
  apps/src/templates/sectionAssessments/FreeResponseDetailsDialog.story.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceDetailsDialog.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceDetailsDialog.story.jsx
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: teacher-dashboard

#23817 Assessments tab: component to show student answers by question
  apps/i18n/common/en_us.json
  apps/src/templates/sectionAssessments/MultipleChoiceByQuestionTable.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceByQuestionTable.story.jsx
Labels: teacher-dashboard

#23827 Assessments: Multiple choice detail view v 3/3 - student responses
  apps/src/templates/sectionAssessments/MultipleChoiceByQuestionTable.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceByQuestionTable.story.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceDetailsDialog.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceDetailsDialog.story.jsx
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: teacher-dashboard

#23833 Progress redux todos
  apps/src/templates/sectionProgress/sectionProgressRedux.js
  apps/test/unit/templates/sectionProgress/sectionProgressReduxTest.js
Labels: code-hygiene, testing

#23834 Remove TODOs I won't end up completing (Caley)
  apps/src/redux/sectionDataRedux.js
  apps/src/templates/manageStudents/manageStudentsRedux.js
Labels: code-hygiene

#23830 Level group: Remove unused function
  dashboard/app/models/levels/level_group.rb
Labels: code-hygiene

#23844 Fix missing form_id error on post course surveys
  dashboard/app/models/concerns/pd/jot_form_backed_form.rb
  dashboard/app/models/pd/post_course_survey.rb
Labels: bug-fix, professional-learning

#23843 Force sync JotForm questions once per form when filling placeholders fails
  dashboard/app/models/concerns/pd/jot_form_backed_form.rb
  dashboard/app/models/pd/survey_question.rb
  dashboard/lib/pd/jot_form/form_questions.rb
  dashboard/test/lib/pd/jot_form/form_questions_test.rb
  dashboard/test/models/concerns/pd/jot_form_backed_form_test.rb
Labels: bug-fix, professional-learning

#23755 Projects: pass real data to the new React PersonalProjectsTable
  apps/src/sites/studio/pages/projects/index.js
  apps/src/templates/projects/PersonalProjectsTable.jsx
  apps/src/templates/projects/PersonalProjectsTable.story.jsx
  apps/src/templates/projects/projectsRedux.js
  apps/test/unit/templates/projects/PersonalProjectsTableTest.js
  apps/test/unit/templates/projects/projectsReduxTest.js
  dashboard/app/controllers/api/v1/projects/personal_projects_controller.rb
  dashboard/config/routes.rb
  dashboard/lib/projects_list.rb
  dashboard/test/controllers/api/v1/projects/personal_projects_controller_test.rb
  dashboard/test/lib/projects_list_test.rb
  dashboard/test/test_helper.rb
Labels: star-labs

#23874 Projects: Test deleting abuse with the project_validator? helper
  shared/middleware/channels_api.rb
  shared/test/test_channels.rb
Labels: testing

#23876 Projects: No personal projects yet message
  apps/i18n/common/en_us.json
  apps/src/templates/projects/PersonalProjectsTable.jsx
  apps/src/templates/projects/generateFakeProjects.js
Labels: star-labs

#23820 Projects: Remove references to migratedToS3
  apps/src/code-studio/initApp/project.js
Labels: star-labs

#23911 Projects: Publish projects from React PersonalProjectsTable
  apps/src/templates/projects/PersonalProjectsTable.jsx
  apps/src/templates/projects/PersonalProjectsTable.story.jsx
  apps/src/templates/projects/PersonalProjectsTableActionsCell.jsx
  apps/src/templates/projects/projectsRedux.js
  apps/src/templates/projects/publishDialog/publishDialogRedux.js
  apps/test/unit/templates/projects/PersonalProjectsTableTest.js
  apps/test/unit/templates/projects/projectsReduxTest.js
Labels: star-labs

#23752 Progress Tab UI tests
  apps/src/templates/progress/ProgressBubble.jsx
  apps/src/templates/sectionProgress/ProgressBox.jsx
  apps/src/templates/sectionProgress/ScriptSelector.js
  apps/src/templates/sectionProgress/SectionProgressToggle.jsx
  dashboard/lib/tasks/seed.rake
  dashboard/test/ui/features/teacher_dashboard.feature
Labels: teacher-dashboard, testing

#23923 Import Ohio course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#16159 Add code.org/assets/* to http-cache config
  cookbooks/cdo-varnish/libraries/http_cache.rb
  pegasus/helpers/asset_helpers.rb
  pegasus/test/test_asset_helpers.rb
  shared/middleware/pegasus_sites.rb
Labels: js-errors

#23964 Projects: unpublish projects from React PersonalProjectsTable
  apps/src/code-studio/components/shareDialogRedux.js
  apps/src/templates/projects/PersonalProjectsTableActionsCell.jsx
  apps/src/templates/projects/projectsRedux.js
  apps/test/unit/templates/projects/projectsReduxTest.js
Labels: star-labs
