Repository code-dot-org/code-dot-org, pull requests merged in 2018-06, with the labels that each got.

#22827 Use transactional test case so the workshop created in setup_all does…
  dashboard/test/helpers/workshop_survey_results_helper_test.rb
Labels: bug-fix, testing

#22816 Move assessments out of api_controller
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  dashboard/app/controllers/api/v1/assessments_controller.rb
  dashboard/app/controllers/api_controller.rb
  dashboard/config/routes.rb
Labels: code-hygiene, teacher-dashboard

#22828 Fix template misspelling that was causing a 404 for no-attendance
  dashboard/app/controllers/pd/workshop_daily_survey_controller.rb
Labels: professional-learning

#22805 Update to experiments controller
  dashboard/app/controllers/experiments_controller.rb
Labels: bug-fix

#22823 Add migration for pd_post_course_surveys
  dashboard/app/models/pd/post_course_survey.rb
  dashboard/db/migrate/20180531011848_create_pd_post_course_survey.rb
  dashboard/db/schema.rb
Labels: professional-learning

#22824 Add support for the pd post course survey
  dashboard/app/controllers/pd/post_course_survey_controller.rb
  dashboard/app/controllers/pd/workshop_daily_survey_controller.rb
  dashboard/app/helpers/pd/jot_form/embed_helper.rb
  dashboard/app/models/concerns/pd/jot_form_backed_form.rb
  dashboard/app/models/pd/post_course_survey.rb
  dashboard/app/views/pd/post_course_survey/new.haml
  dashboard/app/views/pd/post_course_survey/thanks.haml
  dashboard/config/routes.rb
  dashboard/db/schema.rb
  dashboard/lib/pd/jot_form/jot_form_rest_client.rb
  dashboard/lib/pd/jot_form/translation.rb
Labels: professional-learning

#22841 Fix Email Preference upsert to not update entire table
  pegasus/helpers/email_preference_helpers.rb
  pegasus/test/test_email_preference_helpers.rb
Labels: bug-fix

#22368 I18nize toolbox category names
  bin/i18n/sync-codeorg-in.rb
Labels: i18n

#22853 Add redux logging experiment to list of constants
  apps/src/redux.js
  apps/src/util/experiments.js
Labels: code-hygiene

#22849 Assessments controller - use load_resource
  dashboard/app/controllers/api/v1/assessments_controller.rb
Labels: code-hygiene, teacher-dashboard

#22762 remove twitter search timelines from csedweek homepage and code.org leaderboard
  pegasus/sites.v3/code.org/public/leaderboards.haml
  pegasus/sites.v3/code.org/views/index_twitter.html
  pegasus/sites.v3/code.org/views/twitter_tall.html
  pegasus/sites.v3/csedweek.org/public/index.haml
  pegasus/sites.v3/csedweek.org/views/index_twitter.html
Labels: general-website

#22886 2 fixes: Strip JotForm answers, and make sure we return an integer form id
  dashboard/app/models/concerns/pd/jot_form_backed_form.rb
  dashboard/lib/pd/jot_form/translation.rb
Labels: professional-learning

#22893 Assessments: fix key typo in assessment responses API
  dashboard/app/controllers/api/v1/assessments_controller.rb
Labels: bug-fix, teacher-dashboard

#22895 Assessments tab: dropdown filter for assessments
  apps/i18n/common/en_us.json
  apps/src/templates/sectionAssessments/AssessmentSelector.jsx
  apps/src/templates/sectionAssessments/SectionAssessments.jsx
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/src/templates/sectionProgress/ScriptSelector.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: teacher-dashboard

#22899 Add JotForm sync cronjob
  bin/cron/sync_jotforms
  cookbooks/cdo-apps/templates/default/crontab.erb
Labels: professional-learning

#22913 Import Colorado course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#22909 Levelbuilder: Update video editing instructions
  dashboard/app/views/levels/editors/_all.html.haml
Labels: levelbuilder-improvements

#22924 Fix bug in JotForm answer processing that strips text but failed for …
  dashboard/lib/pd/jot_form/matrix_question.rb
  dashboard/lib/pd/jot_form/translation.rb
  dashboard/test/lib/pd/jot_form/translation_test.rb
Labels: bug-fix, professional-learning

#22921 Fix bug in Pd::Workshop.enrolled_in_by so it looks for email and user…
  dashboard/app/models/pd/workshop.rb
  dashboard/test/models/pd/workshop_test.rb
Labels: bug-fix, professional-learning

#22926 Fix bad require path
  cookbooks/cdo-apps/templates/default/crontab.erb
  dashboard/bin/sync_jotforms
Labels: bug-fix, professional-learning

#22885 Student multiple choice data hookup
  apps/src/templates/sectionAssessments/MultipleChoiceByStudentSection.jsx
  apps/src/templates/sectionAssessments/SectionAssessments.jsx
  apps/src/templates/sectionAssessments/StudentAssessmentOverviewTable.jsx
  apps/src/templates/sectionAssessments/assessmentDataShapes.js
  apps/src/templates/sectionAssessments/assessmentsTestHelpers.js
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: teacher-dashboard

#22954 Made several improvements to JotForm sync to reduce API load and improve resilience
  cookbooks/cdo-apps/templates/default/crontab.erb
  dashboard/app/models/concerns/pd/jot_form_backed_form.rb
  dashboard/app/models/pd/post_course_survey.rb
  dashboard/app/models/pd/workshop_daily_survey.rb
  dashboard/app/models/pd/workshop_facilitator_daily_survey.rb
  dashboard/bin/sync_jotforms
  dashboard/lib/pd/jot_form/jot_form_rest_client.rb
  dashboard/lib/pd/jot_form/translation.rb
  dashboard/test/lib/pd/jot_form/translation_test.rb
Labels: professional-learning

#22978 Remove to_s conversion because empirically string min ids are breakin…
  dashboard/lib/pd/jot_form/jot_form_rest_client.rb
Labels: bug-fix, professional-learning

#22962 Import Virginia state course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#22369 Use translated toolbox category names
  dashboard/app/helpers/levels_helper.rb
  dashboard/app/models/levels/blockly.rb
  dashboard/test/ui/features/i18n.feature
Labels: i18n

#22936 Assessment filter dropdown - followup
  apps/src/templates/sectionAssessments/SectionAssessments.jsx
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: code-hygiene, teacher-dashboard

#23035 Progress: Fix the alignment of gray bar on ProgressBubbleSet
  apps/src/templates/progress/ProgressBubble.jsx
  apps/src/templates/progress/ProgressBubbleSet.story.jsx
Labels: teacher-dashboard

#23036 Assessments: Set up basic controller tests
  dashboard/test/controllers/api/v1/assessments_controller_test.rb
Labels: teacher-dashboard

#23070 Assessments controller - move some logic to models and test part 1
  dashboard/app/controllers/api/v1/assessments_controller.rb
  dashboard/app/models/script.rb
  dashboard/test/models/script_test.rb
Labels: teacher-dashboard

#23066 Import Kentucky course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#23079 SectionLevelProgress API: Tests asserting current query count
  dashboard/test/controllers/api_controller_test.rb
Labels: performance, testing

#23085 Assessments controller tests
  dashboard/app/controllers/api/v1/assessments_controller.rb
  dashboard/app/controllers/api_controller.rb
  dashboard/test/controllers/api/v1/assessments_controller_test.rb
Labels: teacher-dashboard, testing

#23135 App Lab: Fix overflowing text in delete column dialog
  apps/src/templates/Dialog.jsx
Labels: bug-fix, star-labs

#23118 Load script from cache in assessments controller
  dashboard/app/controllers/api/v1/assessments_controller.rb
  dashboard/test/controllers/api/v1/assessments_controller_test.rb
Labels: performance, teacher-dashboard

#23141 SectionLevelProgress API: Preload PairedUserLevels
  dashboard/app/controllers/api_controller.rb
  dashboard/app/helpers/users_helper.rb
  dashboard/app/models/paired_user_level.rb
  dashboard/test/controllers/api_controller_queries_test.rb
  dashboard/test/models/paired_user_level_test.rb
Labels: performance

#23089 Assessments: Students Assessments Multiple Choice Table Data Hookup
  apps/src/templates/sectionAssessments/SectionAssessments.jsx
  apps/src/templates/sectionAssessments/StudentsAssessmentsMCTable.jsx
  apps/src/templates/sectionAssessments/StudentsMCSummaryContainer.jsx
  apps/src/templates/sectionAssessments/assessmentDataShapes.js
  apps/src/templates/sectionAssessments/assessmentsTestHelpers.js
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/StudentsAssessmentsMCTableTest.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: teacher-dashboard

#23166 Start survey button opens survey URL in a new tab
  apps/src/code-studio/pd/professional_learning_landing/LandingPage.jsx
  apps/src/templates/studioHomepages/TwoColumnActionBlock.jsx
  apps/test/unit/code-studio/pd/professional_learning_landing/landingPageTest.js
Labels: bug-fix

#23172 Assessments Tab: Surveys multiple choice overview table
  apps/src/templates/sectionAssessments/SectionAssessments.jsx
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: teacher-dashboard

#23165 Enable daily surveys for TeacherCon and add tests
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_management.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_table.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/components/workshop_managementTest.js
  dashboard/app/controllers/api/v1/pd/workshop_survey_report_controller.rb
  dashboard/app/models/pd/enrollment.rb
  dashboard/app/models/pd/workshop.rb
  dashboard/test/controllers/api/v1/pd/workshop_survey_report_controller_test.rb
  dashboard/test/models/pd/enrollment_test.rb
Labels: professional-learning

#23176 Switch from deprecated before_filter callback to before_action
  dashboard/app/controllers/api/v1/assessments_controller.rb
Labels: bug-fix

#23182 Use localized assessment name on assessments tab
  dashboard/app/controllers/api/v1/assessments_controller.rb
  dashboard/test/controllers/api/v1/assessments_controller_test.rb
Labels: bug-fix, teacher-dashboard

#23197 Assessments Tab: Fix filter bug
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: teacher-dashboard

#23203 Assessments Tab: Show all correct answers
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
Labels: bug-fix, teacher-dashboard

#23186 Assessments: Free responses assessments table data hookup
  apps/src/templates/sectionAssessments/FreeResponsesAssessmentsContainer.jsx
  apps/src/templates/sectionAssessments/FreeResponsesAssessmentsTable.jsx
  apps/src/templates/sectionAssessments/SectionAssessments.jsx
  apps/src/templates/sectionAssessments/assessmentDataShapes.js
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: teacher-dashboard

#23216 Assessments tab: consistency of types
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
  dashboard/app/controllers/api/v1/assessments_controller.rb
  dashboard/test/controllers/api/v1/assessments_controller_test.rb
Labels: code-hygiene, teacher-dashboard

#23218 Fix test that relied on indeterminate order
  dashboard/test/models/pd/workshop_test.rb
Labels: professional-learning, testing

#23225 Hotfix: Fix bug in pd_workshop nearest scopes that were omitting attributes.
  dashboard/app/models/pd/workshop.rb
  dashboard/test/controllers/pd/workshop_daily_survey_controller_test.rb
  dashboard/test/models/pd/workshop_test.rb
Labels: bug-fix, professional-learning

#23220 Assessments: Data hookup for multiple choice overview table
  apps/src/templates/sectionAssessments/MCAssessmentsOverviewContainer.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceAssessmentsOverviewTable.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceAssessmentsOverviewTable.story.jsx
  apps/src/templates/sectionAssessments/SectionAssessments.jsx
  apps/src/templates/sectionAssessments/assessmentDataShapes.js
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/MultipleChoiceAssessmentOverviewTableTest.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: teacher-dashboard

#23226 Assessments Tab: Question numbers should correspond to the numbers in the assessment
  apps/src/templates/sectionAssessments/FreeResponsesAssessmentsContainer.jsx
  apps/src/templates/sectionAssessments/SingleStudentAssessmentsMCTable.jsx
  apps/src/templates/sectionAssessments/assessmentsTestHelpers.js
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
  dashboard/app/controllers/api/v1/assessments_controller.rb
  dashboard/test/controllers/api/v1/assessments_controller_test.rb
Labels: bug-fix, teacher-dashboard

#23234 Assessment Tab: Add numbers to questions on overview table
  apps/src/templates/sectionAssessments/MultipleChoiceAssessmentsOverviewTable.jsx
  apps/src/templates/sectionAssessments/assessmentDataShapes.js
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: teacher-dashboard

#23213 I18n sync In & Up 06/20
  dashboard/config/locales/authored_hints.en.yml
  dashboard/config/locales/block_categories.en.yml
  dashboard/config/locales/callouts.en.yml
  dashboard/config/locales/instructions.en.yml
  dashboard/config/locales/markdown_instructions.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/authored_hints.yml
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/block_categories.yml
  i18n/locales/source/dashboard/callouts.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/dsls.yml
  i18n/locales/source/dashboard/instructions.yml
  i18n/locales/source/dashboard/markdown_instructions.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#23265 Assessment tab free response questions - use . instead of :
  apps/src/templates/sectionAssessments/FreeResponsesAssessmentsContainer.jsx
Labels: teacher-dashboard

#23268 Assessments tab: Add question numbers to surveys
  apps/src/templates/sectionAssessments/FreeResponseBySurveyQuestionContainer.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceAssessmentsOverviewTable.story.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceSurveyOverviewTable.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceSurveyOverviewTable.story.jsx
  apps/src/templates/sectionAssessments/assessmentsTestHelpers.js
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
  dashboard/app/models/levels/level_group.rb
  dashboard/test/controllers/api/v1/assessments_controller_test.rb
  dashboard/test/models/level_group_test.rb
Labels: teacher-dashboard

#23295 Add detection for apps package hash mismatch from file system changes…
  lib/cdo/aws/s3_packaging.rb
  lib/rake/package.rake
  shared/test/test_s3_packaging.rb
Labels: bug-fix, infrastructure

#23314 Personal projects table
  apps/src/templates/projects/PersonalProjectsTable.jsx
  apps/src/templates/projects/PersonalProjectsTable.story.jsx
  apps/src/templates/projects/generateFakeProjects.js
Labels: star-labs

#23312 Fix bug where course_id is not cleared from section if params[:course…
  dashboard/app/controllers/api/v1/sections_controller.rb
  dashboard/test/controllers/api/v1/sections_controller_test.rb
Labels: bug-fix

#23311 Web Lab: Can reset level progress even though Bramble initialization fails
  apps/src/weblab/WebLab.js
  apps/src/weblab/brambleHost.js
Labels: bug-fix

#23318 Personal projects table - style tweaks
  apps/src/templates/projects/PersonalProjectsTable.jsx
Labels: star-labs

#16277 Tests: Re-enable netsim_lobby.feature on Circle
  dashboard/test/ui/features/netsim_lobby.feature
Labels: testing

#23315 Add auth for RegionalPartner API
  dashboard/app/controllers/api/v1/regional_partners_controller.rb
  dashboard/test/controllers/api/v1/regional_partners_controller_test.rb
Labels: bug-fix

#23300 Set query timeout for under16 email script
  bin/oneoff/wipe_data/opt_out_petition_emails_under_16
Labels: GDPR

#23329 UserPermissionGrantee
  dashboard/app/model/concerns/user_permission_grantee.rb
  dashboard/app/models/user.rb
  dashboard/lib/user_permission_helper.rb
  dashboard/test/app/model/concerns/user_permission_grantee_test.rb
  dashboard/test/lib/user_permission_helper_test.rb
  dashboard/test/models/user_test.rb
Labels: code-hygiene

#23330 Consolidate matrix question summaries: remove parent and prepend head…
  dashboard/lib/pd/jot_form/matrix_question.rb
  dashboard/test/helpers/workshop_survey_results_helper_test.rb
  dashboard/test/lib/pd/jot_form/form_questions_test.rb
  dashboard/test/lib/pd/jot_form/matrix_question_test.rb
Labels: professional-learning

#23336 Assessments Tab: loading states
  apps/src/templates/sectionAssessments/SectionAssessments.jsx
Labels: teacher-dashboard

#23339 Assessments Tab: remove ability to sort tables
  apps/src/templates/sectionAssessments/FreeResponsesSurveyTable.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceAssessmentsOverviewTable.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceSurveyOverviewTable.jsx
  apps/src/templates/sectionAssessments/SingleStudentAssessmentsMCTable.jsx
  apps/src/templates/sectionAssessments/StudentsAssessmentsMCTable.jsx
Labels: teacher-dashboard

#23338 Remove deprecated create_professional_development_workshop user permission
  bin/oneoff/import-permissions
  dashboard/app/models/user_permission.rb
Labels: code-hygiene, professional-learning

#23346 Assessments Tab: not answered column not calculated correctly
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: bug-fix, teacher-dashboard

#23349 Assessments Tab: bug fix - page errors when student results are in progress
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  dashboard/app/controllers/api/v1/assessments_controller.rb
  dashboard/test/controllers/api/v1/assessments_controller_test.rb
Labels: bug-fix, teacher-dashboard

#23353 Assessments tab: total student submission counts
  apps/i18n/common/en_us.json
  apps/src/redux/sectionDataRedux.js
  apps/src/templates/sectionAssessments/MCAssessmentsOverviewContainer.jsx
  apps/src/templates/sectionAssessments/MCSurveyOverviewContainer.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceByStudentContainer.jsx
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: teacher-dashboard

#23326 Change Zendesk subject if abuse is reported on a featured project
  dashboard/app/controllers/report_abuse_controller.rb
  dashboard/app/models/featured_project.rb
Labels: star-labs

#23368 Remove useDeprecatedGlobalStyles prop from BaseDialog
  apps/src/gamelab/AnimationPicker/AnimationPicker.jsx
  apps/src/gamelab/ErrorDialogStack.jsx
  apps/src/templates/BaseDialog.jsx
  apps/src/templates/BaseDialog.story.jsx
Labels: star-labs

#23327 Publish Dialog updated to use new components and styles
  apps/src/templates/BaseDialog.jsx
  apps/src/templates/Button.jsx
  apps/src/templates/Button.story.jsx
  apps/src/templates/publishDialog/PublishDialog.jsx
  dashboard/test/ui/features/projects/applab_project.feature
  dashboard/test/ui/features/projects/project_sharing.feature
  dashboard/test/ui/features/step_definitions/projects.rb
Labels: Storybook-organization, ui-style

#23375 Remove unnecessary factory step
  dashboard/test/factories/factories.rb
Labels: code-hygiene

#23383 Check for an orange 'Start Workshop' button to detect race condition …
  dashboard/test/ui/features/pd/workshop_dashboard.feature
Labels: professional-learning, testing

#23390 Add skip_content_moderation column to storage_apps table
  pegasus/migrations/133_add_skip_content_moderation_to_storage_apps.rb
Labels: star-labs

#23404 Notify DotD when the commit_content job fails.
  bin/cron/commit_content
Labels: content-pipeline

#23376 Debounce resize handlers to 100ms (trailing edge)
  apps/src/code-studio/components/SmallFooter.jsx
  apps/src/code-studio/responsive.js
  apps/src/templates/VisualizationOverlay.jsx
Labels: performance

#23411 Make the teachercon registration state selection more robust [test eyes]
  dashboard/test/ui/features/pd/teachercon_registration.feature
Labels: professional-learning, testing

#23425 Clean up RegistrationController tests
  dashboard/test/controllers/registrations_controller/demigrate_from_multi_auth_test.rb
  dashboard/test/controllers/registrations_controller/migrate_to_multi_auth_test.rb
  dashboard/test/controllers/registrations_controller/set_email_test.rb
  dashboard/test/controllers/registrations_controller_integration_test.rb
  dashboard/test/controllers/registrations_controller_test.rb
Labels: code-hygiene

#23439 Assessments Tab: Update string to be more clear
  apps/i18n/common/en_us.json
Labels: teacher-dashboard

#23436 Assessments Tab: Export assessments and surveys to CSV
  apps/i18n/common/en_us.json
  apps/src/templates/sectionAssessments/SectionAssessments.jsx
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: teacher-dashboard
