Repository code-dot-org/code-dot-org, pull requests merged in 2018-11, with the labels that each got.

#25793 I18n Sync In & Up 11/02
  dashboard/config/locales/authored_hints.en.yml
  dashboard/config/locales/blocks.en.yml
  dashboard/config/locales/callouts.en.yml
  dashboard/config/locales/display_name.en.yml
  dashboard/config/locales/long_instructions.en.yml
  dashboard/config/locales/short_instructions.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/authored_hints.yml
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/callouts.yml
  i18n/locales/source/dashboard/display_name.yml
  i18n/locales/source/dashboard/dsls.yml
  i18n/locales/source/dashboard/long_instructions.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/dashboard/short_instructions.yml
  i18n/locales/source/dashboard/unplugged.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#25834 I18n sync In & Up 11/05
  dashboard/config/locales/blocks.en.yml
  dashboard/config/locales/long_instructions.en.yml
  dashboard/config/locales/short_instructions.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/long_instructions.yml
  i18n/locales/source/dashboard/short_instructions.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#25570 Update HOC tiles on /courses and /sign_in
  apps/src/sites/studio/pages/courses/index.js
  apps/src/templates/studioHomepages/CourseBlocks.jsx
  apps/src/templates/studioHomepages/Courses.jsx
  apps/src/templates/studioHomepages/CoursesStudentEnglish.jsx
  apps/src/templates/studioHomepages/CoursesTeacherEnglish.jsx
  dashboard/app/controllers/sessions_controller.rb
  dashboard/app/views/courses/index.html.haml
  dashboard/app/views/devise/sessions/new.html.haml
  dashboard/app/views/home/_all_courses.html.haml
  dashboard/app/views/shared/_course_tall_block.haml
  dashboard/config/locales/en.yml
  dashboard/test/controllers/courses_controller_test.rb
  dashboard/test/fixtures/script.yml
  lib/cdo/script_constants.rb
  lib/test/test_script_constants.rb
  pegasus/test/test_section_api_helpers.rb
  shared/css/course-blocks.scss
Labels: hoc

#25967 Congrats: remove excess styling to fix images on IE11
  apps/src/templates/VerticalImageResourceCard.jsx
Labels: bug-fix

#25986 Dance Landing: kabob case rather than kabob-snake_combo for dance haml classes
  pegasus/sites.v3/code.org/public/css/dance-landing/dance.css
  pegasus/sites.v3/code.org/public/dance.haml
Labels: code-hygiene

#26006 I18n sync In & Up 11/12
  dashboard/config/locales/authored_hints.en.yml
  dashboard/config/locales/blocks.en.yml
  dashboard/config/locales/callouts.en.yml
  dashboard/config/locales/display_name.en.yml
  dashboard/config/locales/long_instructions.en.yml
  dashboard/config/locales/short_instructions.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/dance.json
  i18n/locales/source/dashboard/authored_hints.yml
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/callouts.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/display_name.yml
  i18n/locales/source/dashboard/dsls.yml
  i18n/locales/source/dashboard/long_instructions.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/dashboard/short_instructions.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#26060 Artist Tweets: fix typo in Ariana song and add Katy Perry
  apps/src/code-studio/dancePartySongArtistTags.js
Labels: bug-fix

#26107 Public Gallery: correct string to "view all projects" in Dance section
  apps/src/templates/projects/ProjectCardGrid.jsx
Labels: bug-fix

#26133 Projects: string to symbol for fetching published projects
  dashboard/lib/projects_list.rb
Labels: bug-fix

#26137 Project Gallery: publishable Minecraft Aquatic
  dashboard/lib/projects_list.rb
Labels: bug-fix

#26173 Project Gallery: only restrict advanced project types if sharing is disabled
  dashboard/lib/projects_list.rb
  dashboard/test/lib/projects_list_test.rb
Labels: bug-fix

#26157 I18n sync In & Up 11/19
  dashboard/config/locales/authored_hints.en.yml
  dashboard/config/locales/block_categories.en.yml
  dashboard/config/locales/blocks.en.yml
  dashboard/config/locales/callouts.en.yml
  dashboard/config/locales/display_name.en.yml
  dashboard/config/locales/long_instructions.en.yml
  dashboard/config/locales/short_instructions.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/authored_hints.yml
  i18n/locales/source/dashboard/block_categories.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/callouts.yml
  i18n/locales/source/dashboard/display_name.yml
  i18n/locales/source/dashboard/dsls.yml
  i18n/locales/source/dashboard/long_instructions.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/dashboard/short_instructions.yml
  i18n/locales/source/dashboard/slides.yml
  i18n/locales/source/dashboard/unplugged.yml
Labels: i18n

#26220 Separate tutorial landing page UI tests
  dashboard/test/ui/features/other_sites.feature
  dashboard/test/ui/features/tutorial_landing_pages.feature
Labels: testing
