Repository code-dot-org/code-dot-org, pull requests merged in 2018-09, with the labels that each got.

#24594 Import Wyoming course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#24577 Projects: Personal projects table UI tests
  apps/src/templates/projects/PersonalProjectsNameCell.jsx
  apps/src/templates/projects/PersonalProjectsPublishedCell.jsx
  apps/src/templates/projects/PersonalProjectsTableActionsCell.jsx
  apps/src/templates/projects/deleteDialog/DeleteProjectDialog.jsx
  apps/src/templates/tables/QuickActionsCell.jsx
  dashboard/test/ui/features/projects/personal_project_gallery.feature
  dashboard/test/ui/features/step_definitions/projects.rb
Labels: star-labs, testing

#24680 Projects: upload a new thumbnail image in app lab project UI test
  dashboard/test/ui/features/projects/applab_project.feature
Labels: testing

#24738 Projects: UI test coverage for signed out public gallery- no view more links
  apps/src/templates/projects/ProjectAppTypeArea.jsx
  dashboard/test/ui/features/projects/public_project_gallery_project_validator.feature
  dashboard/test/ui/features/projects/public_project_gallery_signed_out.feature
  dashboard/test/ui/features/step_definitions/projects.rb
Labels: testing

#24711 Update OAuth tokens for migrated users
  dashboard/app/controllers/api_controller.rb
  dashboard/app/models/authentication_option.rb
  dashboard/app/models/user.rb
  dashboard/lib/user_multi_auth_helper.rb
  dashboard/test/models/authentication_option_test.rb
  dashboard/test/models/user_test.rb
Labels: bug-fix

#24767 Fix missing organizer bug in workshop reports. Omit organizer info…
  dashboard/lib/pd/payment/workshop_summary.rb
  dashboard/test/lib/pd/payment/workshop_summary_test.rb
Labels: bug-fix

#24856 Re-enable skipped Spanish UI tests for header and hamburger
  dashboard/test/ui/features/hamburger.feature
  dashboard/test/ui/features/header.feature
Labels: testing

#24862 Delete teacher acct dialog markdown
  apps/i18n/common/en_us.json
  apps/src/lib/ui/accounts/DeleteAccountHelpers.jsx
Labels: i18n

#24902 Image Moderation: Show correct (dis/en)able auto content moderation button
  dashboard/app/views/levels/_admin.html.haml
Labels: bug-fix

#24947 Confirm Remove Student - markdown conversion
  apps/i18n/common/en_us.json
  apps/src/templates/manageStudents/ConfirmRemoveStudentDialog.jsx
  apps/test/unit/templates/manageStudents/ConfirmRemoveStudentDialogTest.jsx
Labels: i18n

#24973 Update omniauth tokens in google_oauth2 and clever callbacks on login
  dashboard/app/controllers/omniauth_callbacks_controller.rb
Labels: bug-fix

#24962 Create Header: UI tests for create button visibility and dropdown options
  dashboard/test/ui/features/create_dropdown.feature
  dashboard/test/ui/features/step_definitions/steps.rb
  shared/haml/user_header.haml
Labels: testing

#24977 add markdown component
  apps/src/templates/sectionAssessments/MultipleChoiceDetailsDialog.jsx
Labels: i18n

#25027 Use locale rather than request.language to set the Pegasus language selector
  pegasus/sites.v3/code.org/views/language.haml
Labels: bug-fix, i18n

#24950 Add teacher1920 application email support
  apps/src/code-studio/pd/application_dashboard/summary_table.jsx
  apps/src/code-studio/pd/form_components/FormController.jsx
  cookbooks/cdo-apps/templates/default/crontab.erb
  dashboard/app/controllers/api/v1/pd/application/principal_approval_applications_controller.rb
  dashboard/app/controllers/api/v1/pd/application/teacher_applications_controller.rb
  dashboard/app/controllers/api/v1/pd/applications_controller.rb
  dashboard/app/mailers/pd/application/teacher1920_application_mailer.rb
  dashboard/app/models/pd/application/application_base.rb
  dashboard/app/models/pd/application/email.rb
  dashboard/app/models/pd/application/facilitator1819_application.rb
  dashboard/app/models/pd/application/principal_approval1920_application.rb
  dashboard/app/models/pd/application/teacher1819_application.rb
  dashboard/app/models/pd/application/teacher1920_application.rb
  dashboard/app/models/pd/application/teacher_application_base.rb
  dashboard/app/models/pd/application/workshop_autoenrolled_application.rb
  dashboard/app/views/pd/application/teacher1920_application_mailer/_expectations.html.haml
  dashboard/app/views/pd/application/teacher1920_application_mailer/_partner_signature.html.haml
  dashboard/app/views/pd/application/teacher1920_application_mailer/accepted.html.haml
  dashboard/app/views/pd/application/teacher1920_application_mailer/accepted_no_cost_registration.html.haml
  dashboard/app/views/pd/application/teacher1920_application_mailer/confirmation.html.haml
  dashboard/app/views/pd/application/teacher1920_application_mailer/declined.html.haml
  dashboard/app/views/pd/application/teacher1920_application_mailer/principal_approval.html.haml
  dashboard/app/views/pd/application/teacher1920_application_mailer/principal_approval_completed.html.haml
  dashboard/app/views/pd/application/teacher1920_application_mailer/principal_approval_completed_partner.html.haml
  dashboard/app/views/pd/application/teacher1920_application_mailer/principal_approval_received.html.haml
  dashboard/app/views/pd/application/teacher1920_application_mailer/registration_sent.html.haml
  dashboard/app/views/pd/application/teacher1920_application_mailer/waitlisted.html.haml
  dashboard/bin/scheduled_pd_application_emails
  dashboard/test/controllers/api/v1/pd/application/principal_approval_applications_controller_test.rb
  dashboard/test/controllers/api/v1/pd/applications_controller_test.rb
  dashboard/test/factories/factories.rb
  dashboard/test/factories/pd_factories.rb
  dashboard/test/mailers/previews/pd_teacher1819_application_mailer_preview.rb
  dashboard/test/mailers/previews/pd_teacher1920_application_mailer_preview.rb
  dashboard/test/models/pd/application/application_base_test.rb
  dashboard/test/models/pd/application/facilitator1819_application_test.rb
  dashboard/test/models/pd/application/principal_approval1920_application_test.rb
  dashboard/test/models/pd/application/teacher1819_application_test.rb
  dashboard/test/models/pd/application/teacher1920_application_test.rb
  dashboard/test/ui/features/pd/teacher_application.feature
  dashboard/test/ui/features/step_definitions/pd.rb
  lib/cdo/poste.rb
  lib/cdo/shared_constants/pd/teacher1920_application_constants.rb
Labels: professional-learning

#25025 Fix method missing bug in JotForm fill placeholders code
  dashboard/app/models/concerns/pd/jot_form_backed_form.rb
  dashboard/test/models/concerns/pd/jot_form_backed_form_test.rb
Labels: bug-fix, professional-learning

#25037 Upgrade React Datepicker
  apps/package.json
  apps/yarn.lock
Labels: bug-fix, professional-learning

#25036 Remove missing label warnings in the LabeledFormComponent...
  apps/src/code-studio/pd/form_components/LabeledFormComponent.jsx
Labels: bug-fix, professional-learning

#25061 Add cc and bcc support to deliver_poste_messages and the dashboard email template
  bin/cron/deliver_poste_messages
  pegasus/emails/dashboard.html
Labels: poste

#25079 Update teacher application email copy
  dashboard/app/views/pd/application/teacher1920_application_mailer/principal_approval.html.haml
  dashboard/app/views/pd/application/teacher1920_application_mailer/registration_sent.html.haml
Labels: professional-learning

#25012 Removed unused strings in i18n
  apps/i18n/common/en_us.json
Labels: code-hygiene

#25054 Add new status strings in the client, and clean up styles
  apps/src/code-studio/pd/application_dashboard/constants.js
  apps/src/code-studio/pd/application_dashboard/detail_view_contents.jsx
  apps/src/code-studio/pd/application_dashboard/quick_view.jsx
  apps/src/code-studio/pd/application_dashboard/quick_view_table.jsx
  apps/src/code-studio/pd/application_dashboard/summary.jsx
  apps/src/code-studio/pd/application_dashboard/summary_table.jsx
  apps/test/unit/code-studio/pd/application_dashboard/detail_view_contentsTest.js
  apps/test/unit/code-studio/pd/application_dashboard/summaryTest.js
Labels: professional-learning

#25122 Update teacher application email copy
  dashboard/app/mailers/pd/application/teacher1920_application_mailer.rb
  dashboard/app/models/pd/application/teacher1920_application.rb
  dashboard/app/views/pd/application/teacher1920_application_mailer/_partner_signature.html.haml
  dashboard/test/mailers/previews/pd_teacher1920_application_mailer_preview.rb
  dashboard/test/models/pd/application/teacher1920_application_test.rb
Labels: professional-learning
