Repository code-dot-org/code-dot-org, pull requests merged in 2018-10, with the labels that each got.

#25128 Fix relative URL email link and add fallback for contact_email
  dashboard/app/models/pd/application/teacher1920_application.rb
  dashboard/app/models/regional_partner.rb
  dashboard/app/views/pd/application/teacher1920_application_mailer/_partner_signature.html.haml
  dashboard/test/models/regional_partner_test.rb
Labels: professional-learning

#25124 Add migration to remove pd_applications.decision_notification_email_sent_at
  dashboard/app/models/pd/application/application_base.rb
  dashboard/app/models/pd/application/facilitator1819_application.rb
  dashboard/app/models/pd/application/principal_approval1819_application.rb
  dashboard/app/models/pd/application/principal_approval1920_application.rb
  dashboard/app/models/pd/application/principal_approval_application_base.rb
  dashboard/app/models/pd/application/teacher1819_application.rb
  dashboard/app/models/pd/application/teacher1920_application.rb
  dashboard/app/models/pd/application/teacher_application_base.rb
  dashboard/app/models/pd/application/workshop_autoenrolled_application.rb
  dashboard/db/migrate/20180927225146_remove_pd_applications_decision_notification_email_sent_at.rb
  dashboard/db/schema.rb
Labels: professional-learning

#25123 Remove period from principal approval option text
  apps/src/code-studio/pd/application/principalApproval1920/PrincipalApproval1920Component.jsx
  dashboard/app/models/pd/application/principal_approval1920_application.rb
  dashboard/test/controllers/api/v1/pd/application/principal_approval_applications_controller_test.rb
Labels: professional-learning

#25144 Update erroneous principal approval string constant [ci skip]
  dashboard/test/controllers/api/v1/pd/application/principal_approval_applications_controller_test.rb
  lib/cdo/shared_constants/pd/principal_approval_common_application_constants.rb
Labels: bug-fix, professional-learning

#25142 Fix broken teacher application email link [ci skip]
  dashboard/app/views/pd/application/teacher1920_application_mailer/_partner_signature.html.haml
Labels: professional-learning

#25147 Send principal_approval_completed_partner email
  dashboard/app/controllers/api/v1/pd/application/principal_approval_applications_controller.rb
  dashboard/app/mailers/pd/application/teacher1920_application_mailer.rb
  dashboard/app/models/pd/application/teacher1920_application.rb
  dashboard/test/controllers/api/v1/pd/application/principal_approval_applications_controller_test.rb
  dashboard/test/models/pd/application/teacher1920_application_test.rb
Labels: professional-learning

#25154 Add migration to delete the pd_applications email column, 2nd attempt
  dashboard/app/models/pd/application/application_base.rb
  dashboard/app/models/pd/application/facilitator1819_application.rb
  dashboard/app/models/pd/application/principal_approval1819_application.rb
  dashboard/app/models/pd/application/principal_approval1920_application.rb
  dashboard/app/models/pd/application/principal_approval_application_base.rb
  dashboard/app/models/pd/application/teacher1819_application.rb
  dashboard/app/models/pd/application/teacher1920_application.rb
  dashboard/app/models/pd/application/teacher_application_base.rb
  dashboard/app/models/pd/application/workshop_autoenrolled_application.rb
  dashboard/db/migrate/20181001195320_remove_pd_applications_decision_notification_email_sent_at_if_it_exists.rb
  dashboard/db/schema.rb
Labels: professional-learning

#25158 Autoload email constants to remove duplicate const warnings
  dashboard/app/models/email_preference.rb
  lib/cdo/shared_constants/email_preference_constants.rb
  pegasus/helpers/email_preference_helpers.rb
Labels: code-hygiene

#25160 Add logic to skip sending auto-emails for partners designated send_by_partner
  dashboard/app/models/pd/application/teacher1920_application.rb
  dashboard/test/models/pd/application/teacher1920_application_test.rb
Labels: professional-learning

#25202 Fix UI tests broken after new section rename
  dashboard/test/ui/features/teacher_dashboard.feature
Labels: testing

#25194 Simplify pre-workshop survey results unit and lesson short name logic…
  dashboard/app/models/pd/pre_workshop_survey.rb
  dashboard/test/models/pd/pre_workshop_survey_test.rb
Labels: bug-fix, professional-learning

#25219 Support unit not started in pre-workshop-survey parsing…
  dashboard/app/models/pd/pre_workshop_survey.rb
  dashboard/test/models/pd/pre_workshop_survey_test.rb
Labels: bug-fix, professional-learning

#25224 Make sure workshop admins always see the regional partner selector
  apps/src/code-studio/pd/application_dashboard/summary.jsx
Labels: professional-learning

#25244 Detect changes to shared_constants along with apps directory to trigger a new apps build
  deployment.rb
  lib/cdo/rake_utils.rb
  lib/rake/build.rake
Labels: deploy

#25250 Student sign in cards: fix translation missing error
  pegasus/sites.v3/code.org/public/teacher-dashboard/signin_cards.haml
Labels: bug-fix

#25253 Fix bug so workshop admins who are also facilitators can see all facilitator survey results
  dashboard/app/controllers/api/v1/pd/workshop_survey_report_controller.rb
  dashboard/test/controllers/api/v1/pd/workshop_survey_report_controller_test.rb
Labels: bug-fix, professional-learning

#25254 Project UI tests: improvements to project gallery ui tests
  apps/src/templates/projects/ProjectAppTypeArea.jsx
  apps/src/templates/projects/ProjectCard.jsx
  dashboard/test/ui/features/projects/public_project_gallery_project_validator.feature
  dashboard/test/ui/features/projects/public_project_gallery_signed_out.feature
  dashboard/test/ui/features/step_definitions/projects.rb
Labels: testing

#25259 Require lesson whenever a unit is selected in the pre-workshop survey…
  apps/src/code-studio/pd/form_components/FormController.jsx
  apps/src/code-studio/pd/pre_workshop_survey/PreWorkshopQuestions.jsx
  dashboard/app/models/pd/pre_workshop_survey.rb
  dashboard/test/models/pd/pre_workshop_survey_test.rb
Labels: bug-fix, professional-learning

#25282 Add send email and not required principal approval buttons to the
  apps/src/code-studio/pd/application_dashboard/detail_view_application_specific_questions.jsx
  apps/src/code-studio/pd/application_dashboard/detail_view_contents.jsx
  apps/src/code-studio/pd/application_dashboard/principal_approval_buttons.jsx
  apps/src/code-studio/pd/application_dashboard/quick_view.jsx
  apps/src/code-studio/pd/application_dashboard/quick_view_table.jsx
  apps/src/code-studio/pd/application_dashboard/send_principal_approval_button.jsx
  apps/test/unit/code-studio/pd/application_dashboard/quick_viewTest.js
  dashboard/app/controllers/api/v1/pd/application/teacher_applications_controller.rb
  dashboard/app/controllers/api/v1/pd/forms_controller.rb
  dashboard/app/controllers/pd/teachercon1819_registration_controller.rb
  dashboard/app/models/ability.rb
  dashboard/app/models/pd/application/application_base.rb
  dashboard/app/models/pd/application/principal_approval1920_application.rb
  dashboard/app/models/pd/application/teacher1920_application.rb
  dashboard/app/serializers/api/v1/pd/application_quick_view_serializer.rb
  dashboard/app/serializers/api/v1/pd/application_serializer.rb
  dashboard/config/routes.rb
  dashboard/test/controllers/api/v1/pd/application/teacher_applications_controller_test.rb
  dashboard/test/models/pd/application/teacher1920_application_test.rb
  lib/cdo/shared_constants/pd/principal_approval1920_application_constants.rb
Labels: professional-learning

#25305 Header: fix signin button margin-top
  shared/css/header.scss
Labels: bug-fix

#25347 Clear school_id in signup form if school isn't found in search
  apps/src/sites/studio/pages/devise/registrations/_finish_sign_up.js
Labels: bug-fix

#25348 Bump study group version numbers
  apps/src/sites/studio/pages/devise/registrations/_finish_sign_up.js
  apps/src/sites/studio/pages/signup.js
Labels: bug-fix

#25387 Pegasus: fix Javascript error on /promote
  pegasus/sites.v3/code.org/views/stats_carousel.haml
Labels: bug-fix

#25402 Congrats: check age and handle if unknown
  apps/src/sites/studio/pages/congrats/index.js
  apps/src/templates/Certificate.jsx
  apps/src/templates/Congrats.jsx
  apps/src/templates/SocialShare.jsx
  apps/src/templates/StudentsBeyondHoc.jsx
  dashboard/app/views/congrats/index.html.haml
Labels: bug-fix

#25419 I18n sync In & Up 10/15
  dashboard/config/locales/authored_hints.en.yml
  dashboard/config/locales/blocks.en.yml
  dashboard/config/locales/callouts.en.yml
  dashboard/config/locales/display_name.en.yml
  dashboard/config/locales/long_instructions.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/gamelab.json
  i18n/locales/source/dashboard/authored_hints.yml
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/callouts.yml
  i18n/locales/source/dashboard/display_name.yml
  i18n/locales/source/dashboard/dsls.yml
  i18n/locales/source/dashboard/long_instructions.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#25471 move new hoc posters into their own view with localized paths
  pegasus/sites.v3/hourofcode.com/i18n/en.yml
  pegasus/sites.v3/hourofcode.com/public/promote/previous-posters.md
  pegasus/sites.v3/hourofcode.com/public/promote/resources.md
  pegasus/sites.v3/hourofcode.com/views/promote_new_posters.haml
Labels: general-website, hoc, i18n

#25512 Congrats: show correct cards for <13 finished MC 2017
  apps/src/templates/StudentsBeyondHoc.jsx
Labels: bug-fix

#25537 I18n sync In & Up 10/22
  dashboard/config/locales/authored_hints.en.yml
  dashboard/config/locales/blocks.en.yml
  dashboard/config/locales/callouts.en.yml
  dashboard/config/locales/display_name.en.yml
  dashboard/config/locales/failure_message_overrides.en.yml
  dashboard/config/locales/long_instructions.en.yml
  dashboard/config/locales/short_instructions.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/authored_hints.yml
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/callouts.yml
  i18n/locales/source/dashboard/display_name.yml
  i18n/locales/source/dashboard/failure_message_overrides.yml
  i18n/locales/source/dashboard/long_instructions.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/dashboard/short_instructions.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#25574 Enabled slovak in dashboard
  dashboard/config/locales.yml
Labels: i18n

#25518 Minecraft Aquatics on /hourofcode/overview
  pegasus/sites.v3/code.org/views/top_hoc_tutorials.haml
Labels: hoc

#25650 Update #submit to .submit on finish signup button
  dashboard/app/views/devise/registrations/_finish_sign_up.html.haml
Labels: bug-fix

#25522 Conditionally display MC Aquatic assets on /courses and /sign_up
  apps/src/sites/studio/pages/courses/index.js
  apps/src/templates/studioHomepages/CourseBlocks.jsx
  apps/src/templates/studioHomepages/Courses.jsx
  apps/src/templates/studioHomepages/CoursesStudentEnglish.jsx
  apps/src/templates/studioHomepages/CoursesTeacherEnglish.jsx
  dashboard/app/views/courses/index.html.haml
  dashboard/app/views/devise/sessions/new.html.haml
  dashboard/app/views/home/_all_courses.html.haml
  dashboard/app/views/shared/_course_tall_block.haml
  dashboard/config/locales/en.yml
  dashboard/config/locales/scripts.en.yml
  dashboard/test/controllers/courses_controller_test.rb
  dashboard/test/fixtures/script.yml
Labels: hoc

#25683 I18n sync In & Up 10/30
  dashboard/config/locales/authored_hints.en.yml
  dashboard/config/locales/blocks.en.yml
  dashboard/config/locales/callouts.en.yml
  dashboard/config/locales/display_name.en.yml
  dashboard/config/locales/long_instructions.en.yml
  dashboard/config/locales/short_instructions.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/dance.json
  i18n/locales/source/dashboard/authored_hints.yml
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/callouts.yml
  i18n/locales/source/dashboard/display_name.yml
  i18n/locales/source/dashboard/dsls.yml
  i18n/locales/source/dashboard/long_instructions.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/dashboard/short_instructions.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#25418 Display translated block texts
  dashboard/app/models/levels/blockly.rb
  dashboard/test/models/blockly_test.rb
Labels: i18n
