Repository code-dot-org/code-dot-org, pull requests merged in 2018-08, with the labels that each got.

#23875 Fix adhoc report when an instance has been terminated
  bin/cron/stop_inactive_adhoc_instances
Labels: adhoc

#24053 Manage Students: fix share column show/hide by default bug
  apps/src/templates/teacherDashboard/sections.js
Labels: teacher-dashboard

#24089 Reorder requires to fix service crash
  dashboard/bin/sqs/process_queues
Labels: bug-fix

#24059 Projects: part 1 for renaming, extract PersonalProjectsNameCell
  apps/src/templates/projects/PersonalProjectsNameCell.jsx
  apps/src/templates/projects/PersonalProjectsTable.jsx
  apps/src/templates/projects/PersonalProjectsTableActionsCell.jsx
  apps/src/templates/projects/projectsRedux.js
  apps/test/unit/templates/projects/projectsReduxTest.js
Labels: star-labs

#24104 Teacher Dashboard: increase ScriptSelector width
  apps/src/templates/sectionProgress/ScriptSelector.js
Labels: teacher-dashboard

#24102 Remove new_destroy_flow param from DELETE /users endpoint
  apps/src/lib/ui/accounts/DeleteAccount.jsx
  dashboard/app/controllers/registrations_controller.rb
  dashboard/test/controllers/registrations_controller/destroy_test.rb
  dashboard/test/controllers/registrations_controller_test.rb
Labels: code-hygiene

#24113 Add cap for CSD local summer workshops to match CSP
  dashboard/app/models/pd/workshop_constants.rb
Labels: professional-learning

#24121 Fix clever link
  apps/src/templates/teacherDashboard/RosterDialog.jsx
Labels: bug-fix

#24134 Projects: project name links to edit page not overview
  apps/src/templates/projects/PersonalProjectsNameCell.jsx
Labels: bug-fix, star-labs

#24022 Add memory-profiler and add ability to selectively enable rack-mini-profiler
  Gemfile
  Gemfile.lock
  cookbooks/cdo-varnish/libraries/http_cache.rb
  dashboard/app/controllers/application_controller.rb
  dashboard/config/initializers/mini_profiler.rb
Labels: performance

#24139 Import New York course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#24140 Import Kansas course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#24143 Import Missouri course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#24164 Teacher Dashboard: Fix section selection dropdown so it populates for all tabs
  apps/src/sites/code.org/pages/public/teacher-dashboard/index.js
Labels: bug-fix, teacher-dashboard

#24185 Fix pre-workshop survey: update outdated course names, improve error …
  dashboard/app/mailers/pd/workshop_mailer.rb
  dashboard/app/models/pd/workshop.rb
  dashboard/app/models/pd/workshop_constants.rb
  dashboard/app/views/pd/workshop_mailer/_pre_workshop_survey.html.haml
  dashboard/app/views/pd/workshop_mailer/_supply_list.html.haml
  dashboard/app/views/pd/workshop_mailer/teacher_enrollment_reminder.html.haml
  dashboard/test/models/pd/workshop_test.rb
Labels: bug-fix, professional-learning

#24195 Projects: table thumbnail links to the edit page
  apps/src/templates/projects/PersonalProjectsTable.jsx
Labels: star-labs

#24200 Projects: make App Lab thumbnails fit in the table
  apps/src/templates/projects/PersonalProjectsTable.jsx
Labels: star-labs

#24198 Projects: checkmark icon for published projects
  apps/src/templates/projects/PersonalProjectsTable.jsx
Labels: star-labs

#23257 Import Montana CS course offerings.
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#24216 Projects: rename edits original name
  apps/src/templates/projects/PersonalProjectsNameCell.jsx
  apps/src/templates/projects/PersonalProjectsTable.jsx
  apps/src/templates/projects/projectsRedux.js
  apps/test/unit/templates/projects/projectsReduxTest.js
Labels: bug-fix, star-labs

#24219 Projects: more comprehensive and specific project types in projects table
  apps/src/templates/projects/PersonalProjectsTable.jsx
  apps/src/templates/projects/projectConstants.js
Labels: bug-fix, star-labs

#24193 Add button and confirmation dialog for canceling a workshop enrollment
  apps/Gruntfile.js
  apps/src/code-studio/pd/application_dashboard/detail_view_contents.jsx
  apps/src/code-studio/pd/components/confirmation_dialog.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_enrollment_school_info.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_management.jsx
  apps/src/code-studio/pd/workshop_dashboard/workshop.jsx
  apps/src/code-studio/pd/workshop_enrollment/enrollmentCancelButton.jsx
  apps/src/sites/studio/pages/pd/workshop_enrollment/cancel.js
  apps/test/unit/code-studio/pd/workshop_dashboard/components/workshop_managementTest.js
  dashboard/app/controllers/api/v1/pd/workshop_enrollments_controller.rb
  dashboard/app/controllers/pd/workshop_enrollment_controller.rb
  dashboard/app/models/pd/workshop.rb
  dashboard/app/views/pd/workshop_enrollment/cancel.html.haml
  dashboard/app/views/pd/workshop_enrollment/not_found.html.haml
  dashboard/app/views/pd/workshop_enrollment/thanks.html.haml
  dashboard/config/routes.rb
  dashboard/test/controllers/api/v1/pd/workshop_enrollments_controller_test.rb
  dashboard/test/controllers/pd/workshop_enrollment_controller_test.rb
  dashboard/test/models/pd/workshop_test.rb
Labels: professional-learning

#24208 Import North Dakota course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#24238 Use expects instead of stubs.once
  dashboard/test/lib/expired_deleted_account_purger_test.rb
Labels: code-hygiene

#24229 Projects: hide (un)publish action for unpublishable project types
  apps/script/generateSharedConstants.rb
  apps/src/sites/studio/pages/projects/index.js
  apps/src/templates/projects/PersonalProjectsTable.jsx
  apps/src/templates/projects/PersonalProjectsTable.story.jsx
  apps/src/templates/projects/PersonalProjectsTableActionsCell.jsx
  apps/test/unit/templates/projects/PersonalProjectsTableTest.js
  dashboard/app/views/projects/index.html.haml
Labels: bug-fix, star-labs

#24257 Projects: set up table variants for (un)publishing via buttons vs. dropdown
  apps/src/sites/studio/pages/projects/index.js
  apps/src/templates/projects/PersonalProjectsPublishedCell.jsx
  apps/src/templates/projects/PersonalProjectsTable.jsx
  apps/src/templates/projects/PersonalProjectsTable.story.jsx
  apps/src/templates/projects/projectConstants.js
  apps/test/unit/templates/projects/PersonalProjectsTableTest.js
Labels: star-labs

#24275 Import Oregon course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#24276 Import Pennsylvania course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#24278 Import Wisconsin course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#24380 Fix contact rollups to use users_view
  lib/cdo/contact_rollups.rb
Labels: bug-fix

#24400 Import Rhode Island course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#24432 Update North Carolina course offering import
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#24427 Add Ohio to inferred no exclusion list.
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#24160 Setup initial (hidden) 19-20 teacher application
  Gemfile
  Gemfile.lock
  apps/Gruntfile.js
  apps/script/generateSharedConstants.rb
  apps/src/code-studio/pd/application/teacher1920/Section1AboutYou.jsx
  apps/src/code-studio/pd/application/teacher1920/Section2YourSchool.jsx
  apps/src/code-studio/pd/application/teacher1920/Section3ChooseYourProgram.jsx
  apps/src/code-studio/pd/application/teacher1920/Section4SummerWorkshop.jsx
  apps/src/code-studio/pd/application/teacher1920/Section5Submission.jsx
  apps/src/code-studio/pd/application/teacher1920/Teacher1920Application.jsx
  apps/src/code-studio/pd/application/teacher1920/TeacherApplicationConstants.js
  apps/src/sites/studio/pages/pd/application/teacher_application/new_1920_preview.js
  dashboard/app/controllers/pd/application/teacher_application_controller.rb
  dashboard/app/models/pd/application/application_constants.rb
  dashboard/app/models/pd/application/facilitator1819_application.rb
  dashboard/app/models/pd/application/principal_approval1819_application.rb
  dashboard/app/models/pd/application/teacher1819_application.rb
  dashboard/app/models/pd/application/teacher1920_application.rb
  dashboard/app/models/pd/application/teacher_application_base.rb
  dashboard/app/models/pd/teachercon1819_registration.rb
  dashboard/app/views/pd/application/teacher_application/new_1920_preview.html.haml
  dashboard/config/application.rb
  dashboard/config/routes.rb
  dashboard/test/controllers/api/v1/pd/applications_controller_test.rb
  dashboard/test/models/pd/application/teacher1819_application_test.rb
  lib/cdo/shared_constants/pd/facilitator1819_application_constants.rb
  lib/cdo/shared_constants/pd/principal_approval1819_application_constants.rb
  lib/cdo/shared_constants/pd/teacher1819_application_constants.rb
  lib/cdo/shared_constants/pd/teacher1920_application_constants.rb
  lib/cdo/shared_constants/pd/teacher_common_application_constants.rb
  lib/cdo/shared_constants/pd/teachercon1819_registration_constants.rb
Labels: professional-learning

#24475 Do not parse/yield Clever API response if error occurs
  dashboard/app/controllers/api_controller.rb
Labels: bug-fix

#24486 Increase max execution timeout for a specific query.
  lib/cdo/contact_rollups.rb
Labels: performance

#24508 Projects: Star Wars - blocks projects show correct type in tables
  apps/src/templates/projects/projectConstants.js
Labels: bug-fix, star-labs

#24459 Disconnected OAuth AuthenticationOption bug
  dashboard/app/models/user.rb
  dashboard/lib/user_multi_auth_helper.rb
  dashboard/test/lib/user_multi_auth_helper_test.rb
  dashboard/test/models/user_test.rb
Labels: bug-fix

#24527 Projects: A/B publish experiment, log page loads not table renders
  apps/src/sites/studio/pages/projects/index.js
  apps/src/templates/projects/PersonalProjectsTable.jsx
Labels: bug-fix, star-labs

#24528 Projects: remove un-used code to fix publish dialog
  apps/src/sites/studio/pages/projects/index.js
Labels: bug-fix, star-labs

#24516 Validate cred type/auth id combo for AuthenticationOption
  dashboard/app/models/authentication_option.rb
  dashboard/test/controllers/omniauth_callbacks_controller_test.rb
  dashboard/test/models/authentication_option_test.rb
Labels: bug-fix

#24582 Remove dead code
  apps/src/code-studio/plc/evaluation_creation.js
  apps/src/code-studio/plc/perform_evaluation.js
  apps/src/code-studio/plc/task_creation.js
  apps/src/sites/studio/pages/plc.js
  apps/style/code-studio/levelbuilder.scss
  apps/style/code-studio/plc.scss
  apps/style/code-studio/plc/common.scss
  apps/style/code-studio/plc/content_creation.scss
Labels: code-hygiene
