Repository code-dot-org/code-dot-org, pull requests merged in 2018-04, with the labels that each got.

#21600 Progress: Variable column widths
  apps/src/templates/sectionProgress/VirtualizedDetailView.jsx
Labels: star-labs

#21616 CircleCI: Set special s3 buckets after unit tests
  .circleci/config.yml
  lib/rake/test.rake
Labels: testing

#21610 Update TC/FiT cohort view with bug bash feedback
  apps/src/code-studio/pd/application_dashboard/admin_cohort_view.jsx
  apps/src/code-studio/pd/application_dashboard/admin_cohort_view_table.jsx
  apps/src/code-studio/pd/downloadCsv.js
  dashboard/app/controllers/api/v1/pd/applications_controller.rb
  dashboard/app/models/pd/application/application_base.rb
  dashboard/app/models/pd/application/facilitator1819_application.rb
  dashboard/app/models/pd/application/workshop_autoenrolled_application.rb
  dashboard/app/models/pd/fit_weekend1819_registration.rb
  dashboard/app/models/pd/teachercon1819_registration.rb
  dashboard/app/serializers/api/v1/pd/tc_fit_cohort_view_serializer.rb
  dashboard/app/serializers/api/v1/pd/tc_fit_cohort_view_teachercon_registration_serializer.rb
Labels: professional-learning

#21624 Allow workshop organizers to edit workshop attendance after the workshop has ended
  apps/src/code-studio/pd/workshop_dashboard/attendance/workshop_attendance.jsx
Labels: professional-learning

#21609 Progress: populate table with real student names
  apps/src/templates/sectionProgress/SectionProgress.jsx
  apps/src/templates/sectionProgress/VirtualizedDetailView.jsx
Labels: star-labs

#21629 Add summary to workshop attendance page
  apps/src/code-studio/pd/workshop_dashboard/attendance/session_attendance.jsx
  apps/src/code-studio/pd/workshop_dashboard/attendance/workshop_attendance.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/attendance/session_attendance_test.jsx
  dashboard/app/serializers/api/v1/pd/workshop_summary_serializer.rb
Labels: adhoc, professional-learning

#21618 Progress: Real data lesson numbers and level icons
  apps/src/templates/sectionProgress/VirtualizedDetailView.jsx
Labels: star-labs

#21639 restore finishIcon on reset
  apps/src/maze/animationsController.js
Labels: bug-fix

#21655 Fix bug in progress tab data fetching
  apps/src/templates/sectionProgress/sectionProgressRedux.js
Labels: bug-fix, star-labs

#21320 Student account creation: share setting default
  dashboard/app/models/user.rb
  dashboard/test/models/sections/section_test.rb
  dashboard/test/models/user_test.rb
Labels: star-labs

#21516 Manage Students: remove showShareColumn experiment flag
  apps/src/templates/manageStudents/ManageStudentsAgeCell.jsx
  apps/src/templates/manageStudents/ManageStudentsTable.jsx
  apps/src/templates/teacherDashboard/sections.js
  apps/src/util/experiments.js
  apps/test/unit/templates/manageStudents/ManageStudentsAgeCellTest.js
Labels: star-labs

#21658 Progress: code cleanliness
  apps/src/templates/sectionProgress/ScriptSelector.js
  apps/src/templates/sectionProgress/SectionProgress.jsx
  apps/src/templates/sectionProgress/sectionProgressRedux.js
  apps/test/unit/templates/sectionProgress/sectionProgressReduxTest.js
Labels: code-hygiene, star-labs

#21660 Progress: Default the script id to what's been assigned to the section
  apps/src/templates/sectionProgress/ScriptSelector.js
  apps/src/templates/sectionProgress/SectionProgress.jsx
  apps/src/templates/sectionProgress/sectionProgressRedux.js
  apps/test/unit/templates/sectionProgress/sectionProgressReduxTest.js
Labels: star-labs

#21445 remove legacy tutorials Google Sheets
  pegasus/rake/seed.rake
  pegasus/routes/hoc_routes.rb
  pegasus/src/database.rb
Labels: content-pipeline

#21634 Reduce project gallery UI test flakiness
  apps/src/templates/projects/ProjectCard.jsx
  dashboard/test/ui/features/projects/project_gallery.feature
Labels: testing

#21684 ManageStudents: add multiple students bug fixes
  apps/src/templates/manageStudents/manageStudentsRedux.js
  apps/test/unit/templates/manageStudents/manageStudentsReduxTest.js
Labels: bug-fix, star-labs

#21690 Filter allowed courses for facilitators creating workshops
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_form.jsx
  apps/src/code-studio/pd/workshop_dashboard/reducers.js
  apps/src/code-studio/pd/workshop_dashboard/workshop_dashboard.jsx
  dashboard/app/controllers/pd/workshop_dashboard_controller.rb
Labels: professional-learning

#21702 DRY up permission tests
  apps/test/unit/code-studio/pd/permissionTest.js
Labels: code-hygiene, professional-learning, testing

#21700 Progress: prototype SummaryView
  apps/src/templates/sectionProgress/ProgressBox.jsx
  apps/src/templates/sectionProgress/SectionProgress.jsx
  apps/src/templates/sectionProgress/VirtualizedSummaryView.jsx
Labels: star-labs

#21656 Progress: render ProgressBubbleSet to show student progress
  apps/src/code-studio/progressRedux.js
  apps/src/templates/sectionProgress/SectionProgress.jsx
  apps/src/templates/sectionProgress/SectionScriptProgress.js
  apps/src/templates/sectionProgress/StudentProgressDetailCell.jsx
  apps/src/templates/sectionProgress/VirtualizedDetailView.jsx
Labels: star-labs

#21715 add debugging output to project_gallery.feature
  dashboard/test/ui/features/projects/project_gallery.feature
Labels: testing

#21721 Rename button_list to ButtonList to be consistent with other components
  apps/src/code-studio/pd/form_components/ButtonList.jsx
  apps/src/code-studio/pd/form_components/ButtonList.story.jsx
  apps/src/code-studio/pd/form_components/FormComponent.jsx
  apps/src/code-studio/pd/teacher_application/SummerProgramContent.jsx
  apps/src/code-studio/pd/teacher_application/teacher_application.jsx
  apps/src/code-studio/pd/workshop_survey/VariableFormGroup.jsx
  apps/test/unit/code-studio/pd/form_components/ButtonListTest.js
Labels: code-hygiene

#21704 Ask for school district name for teacher application custom schools
  apps/src/code-studio/pd/application/teacher1819/Section2YourSchool.jsx
  dashboard/app/models/pd/application/teacher1819_application.rb
  dashboard/test/ui/features/pd/teacher_application.feature
  lib/cdo/shared_constants/pd/teacher1819_application_constants.rb
Labels: professional-learning

#21735 Progress Tab: Fix warning and props style
  apps/src/templates/sectionProgress/ScriptSelector.js
  apps/src/templates/sectionProgress/SectionProgress.jsx
  apps/src/templates/sectionProgress/StudentProgressDetailCell.jsx
  apps/src/templates/sectionProgress/StudentProgressSummaryCell.jsx
Labels: star-labs

#21555 Move video thumbnail generation to levelbuilder
  cookbooks/cdo-apps/templates/default/crontab.erb
  dashboard/app/models/video.rb
  dashboard/app/views/videos/index.html.haml
  dashboard/test/controllers/videos_controller_test.rb
Labels: content-pipeline

#21760 Progress: styles for summary view
  apps/src/templates/sectionProgress/ProgressBox.jsx
  apps/src/templates/sectionProgress/StudentProgressSummaryCell.jsx
  apps/src/templates/sectionProgress/VirtualizedSummaryView.jsx
Labels: star-labs

#21773 Don't wipe regional partner association on teacher application form_data update
  dashboard/app/controllers/api/v1/pd/applications_controller.rb
  dashboard/test/controllers/api/v1/pd/applications_controller_test.rb
Labels: bug-fix, professional-learning

#21784 Progress: Dynamic table height for Summary and Detail View
  apps/src/templates/sectionProgress/VirtualizedDetailView.jsx
  apps/src/templates/sectionProgress/VirtualizedSummaryView.jsx
Labels: star-labs

#21807 Progress: link to overview with view course
  apps/src/templates/SmallChevronLink.jsx
  apps/src/templates/sectionProgress/SectionProgress.jsx
  apps/src/templates/sectionProgress/sectionProgressRedux.js
  dashboard/app/controllers/api_controller.rb
Labels: star-labs

#21814 Progress: Arrows next to lesson numbers
  apps/src/templates/sectionProgress/VirtualizedDetailView.jsx
  apps/src/templates/sectionProgress/multiGridConstants.js
  apps/src/templates/sectionProgress/sectionProgressRedux.js
Labels: star-labs

#21829 Progress: Fix props warning and use correct default icon
  apps/src/templates/sectionProgress/VirtualizedDetailView.jsx
Labels: star-labs

#21820 VCR fails on missing cassette in CI environments
  shared/test/common_test_helper.rb
Labels: testing

#21836 Style nit: follow up from previous PR
  apps/src/templates/sectionProgress/VirtualizedDetailView.jsx
Labels: code-hygiene

#21825 Disable tooltips on progress bubbles in section progress tab
  apps/src/templates/progress/ProgressBubble.jsx
  apps/src/templates/progress/ProgressBubble.story.jsx
  apps/src/templates/progress/ProgressBubbleSet.jsx
  apps/src/templates/sectionProgress/StudentProgressDetailCell.jsx
Labels: star-labs

#21830 Add eyes tests for creating new workshops [test eyes]
  apps/package.json
  apps/src/code-studio/pd/workshop_dashboard/components/facilitator_list_form_part.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_form.jsx
  apps/yarn.lock
  dashboard/test/ui/features/pd/workshop_dashboard.feature
  dashboard/test/ui/features/step_definitions/pd.rb
Labels: professional-learning, testing

#21865 Progress: use lesson names in lesson selector dropdown
  apps/i18n/common/en_us.json
  apps/src/templates/sectionProgress/LessonSelector.jsx
  apps/src/templates/sectionProgress/SectionProgress.jsx
Labels: star-labs

#21894 Move public thumbnail tests to own file
  shared/test/fixtures/vcr/files/metadata_cached.yml
  shared/test/fixtures/vcr/publicthumbnails/adult_thumbnail.yml
  shared/test/fixtures/vcr/publicthumbnails/bad_channel_thumbnail.yml
  shared/test/fixtures/vcr/publicthumbnails/everyone_thumbnail.yml
  shared/test/fixtures/vcr/publicthumbnails/racy_thumbnail.yml
  shared/test/middleware/files_api/test_public_thumbnails.rb
  shared/test/test_files.rb
Labels: testing

#21899 Add regional partner to TC/FiT cohort CSV download
  apps/src/code-studio/pd/application_dashboard/admin_cohort_view.jsx
Labels: professional-learning

#21897 Progress: clicking on SummaryView lesson number jumps to DetailView
  apps/src/templates/sectionProgress/LessonSelector.jsx
  apps/src/templates/sectionProgress/SectionProgressLessonNumberCell.jsx
  apps/src/templates/sectionProgress/VirtualizedSummaryView.jsx
  apps/src/templates/sectionProgress/multiGridConstants.js
  apps/src/templates/sectionProgress/sectionProgressRedux.js
Labels: star-labs

#21916 Progress: lesson of interest Redux test
  apps/test/unit/templates/sectionProgress/sectionProgressReduxTest.js
Labels: star-labs, testing

#21949 Progress: hide/show csf light green box based on selected script
  apps/src/templates/sectionProgress/SectionProgress.jsx
Labels: star-labs

#21976 Show partner filter dropdown to program managers with multiple partners
  apps/src/code-studio/pd/application_dashboard/application_dashboard.jsx
  apps/src/code-studio/pd/application_dashboard/cohort_view.jsx
  apps/src/code-studio/pd/application_dashboard/constants.js
  apps/src/code-studio/pd/application_dashboard/quick_view.jsx
  apps/src/code-studio/pd/application_dashboard/reducers.js
  apps/src/code-studio/pd/application_dashboard/regional_partner_dropdown.jsx
  apps/src/code-studio/pd/application_dashboard/summary.jsx
  dashboard/app/controllers/pd/application_dashboard_controller.rb
Labels: professional-learning

#20014 Update MySQL to version 5.7
  .circleci/Dockerfile
  .circleci/config.yml
  cookbooks/cdo-mysql/.kitchen.yml
  cookbooks/cdo-mysql/Berksfile
  cookbooks/cdo-mysql/metadata.rb
  cookbooks/cdo-mysql/recipes/client.rb
  cookbooks/cdo-mysql/recipes/repo.rb
  cookbooks/cdo-mysql/recipes/server.rb
  cookbooks/cdo-mysql/test/integration/default/serverspec/ruby_spec.rb
  cookbooks/cdo-mysql/test/integration/stop/serverspec/ruby_spec.rb
Labels: infrastructure

#22011 import Utah CS course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#22017 Import Florida CS course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#22014 Progress: Clean up section data and remove where not needed
  apps/src/templates/sectionProgress/StudentProgressSummaryCell.jsx
  apps/src/templates/sectionProgress/VirtualizedDetailView.jsx
  apps/src/templates/sectionProgress/VirtualizedSummaryView.jsx
  apps/src/templates/sectionProgress/sectionProgressRedux.js
Labels: code-hygiene

#22033 Show partner filter dropdown to program managers with multiple partners, take 2
  apps/src/code-studio/pd/application_dashboard/application_dashboard.jsx
  apps/src/code-studio/pd/application_dashboard/cohort_view.jsx
  apps/src/code-studio/pd/application_dashboard/constants.js
  apps/src/code-studio/pd/application_dashboard/detail_view_contents.jsx
  apps/src/code-studio/pd/application_dashboard/quick_view.jsx
  apps/src/code-studio/pd/application_dashboard/reducers.js
  apps/src/code-studio/pd/application_dashboard/regional_partner_dropdown.jsx
  apps/src/code-studio/pd/application_dashboard/summary.jsx
  dashboard/app/controllers/pd/application_dashboard_controller.rb
Labels: professional-learning

#22022 Import Connecticut course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#22047 Use Timecop.freeze instead of travel to fix race condition
  dashboard/test/models/sections/section_test.rb
Labels: bug-fix, testing

#22051 Disable weblab/versions.feature while I investigate
  dashboard/test/ui/features/weblab/versions.feature
Labels: testing

#22070 Disable weblab_submittable.feature during investigation
  dashboard/test/ui/features/weblab_submittable.feature
Labels: testing

#22083 Progress: more consistent styling for teal links
  pegasus/sites.v3/code.org/public/teacher-dashboard/nav.haml
Labels: teacher-dashboard

#22094 Progress: refactor cell renderers to be less confusing
  apps/src/templates/sectionProgress/VirtualizedDetailView.jsx
  apps/src/templates/sectionProgress/VirtualizedSummaryView.jsx
Labels: teacher-dashboard

#22098 Switch from camelCase to under_scores for loadingAnimations.feature
  dashboard/test/ui/features/gamelab/loading_animations.feature
Labels: code-hygiene
