Repository code-dot-org/code-dot-org, pull requests merged in 2019-12, with the labels that each got.

#32151 Update the HoC "How-To" page
  pegasus/sites.v3/hourofcode.com/public/how-to/2019.md.partial
Labels: content-change

#32164 Homepage stats: 20M of our students are young women
  pegasus/sites.v3/code.org/views/stats_homepage.haml
Labels: content-change

#32091 Do batch inserts in create_rollup_tables
  bin/cron/create_rollup_tables
Labels: performance

#32168 Update social image for code.org
  pegasus/src/social_metadata.rb
  shared/images/social-media/codeorg2019_social.png
Labels: content-change

#31747 [student-libraries] Set up a controller to return a class set of libraries
  apps/src/code-studio/components/libraries/LibraryClientApi.js
  apps/src/code-studio/components/libraries/LibraryManagerDialog.jsx
  dashboard/app/controllers/api/v1/projects/section_projects_controller.rb
  dashboard/app/controllers/api/v1/section_libraries_controller.rb
  dashboard/config/routes.rb
  dashboard/lib/projects_list.rb
  dashboard/test/controllers/api/v1/projects/section_projects_controller_test.rb
  dashboard/test/controllers/api/v1/section_libraries_controller_test.rb
  dashboard/test/lib/projects_list_test.rb
Labels: star-labs

#32185 Script: Import new NY regional partner mappings
  bin/oneoff/data_fix/ny_rp_mappings_2019-11-27.csv
  bin/oneoff/data_fix/ny_rp_mappings_2019-11-27.rb
Labels: data

#32177 Add spritelab animation bucket to Cloudformation config
  aws/cloudformation/s3_buckets.yml
Labels: star-labs

#32175 [Applab Datasets] Fix off-by-one error in upload scripts
  bin/cron/applab_datasets/weather
  bin/oneoff/applab_datasets/upload_csv_to_firebase
Labels: star-labs

#32143 Prevent rename of visible levels
  dashboard/app/controllers/levels_controller.rb
  dashboard/app/views/levels/edit.html.haml
  dashboard/test/controllers/levels_controller_test.rb
Labels: feature

#32220 Revert "[Applab Dataset] Crontab configuration for Weather"
  bin/cron/applab_datasets/weather
  cookbooks/cdo-apps/templates/default/crontab.erb
Labels: star-labs

#32268 Fixed rotate screen issue in Android.
  apps/src/StudioApp.js
  apps/src/maze/maze.js
Labels: star-labs

#32266 Upgrade Babel to version 7
  apps/.babelrc
  apps/Gruntfile.js
  apps/babel.config.json
  apps/package.json
  apps/src/code-studio/assets.js
  apps/src/templates/teacherDashboard/urlHelpers.js
  apps/src/util/htmlToCanvasWrapper.js
  apps/src/util/idempotent-babel-polyfill.js
  apps/test/integration-tests.js
  apps/test/scratch-tests.js
  apps/test/storybook-tests.js
  apps/test/unit-tests.js
  apps/test/unit/code-studio/pd/workshop_enrollment/enroll_formTest.js
  apps/yarn.lock
Labels: dependencies

#32319 Manually restoring translated strings from redactions
  dashboard/config/locales/blocks.fr-FR.yml
  dashboard/config/locales/blocks.ja-JP.yml
  dashboard/config/locales/blocks.nl-NL.yml
Labels: i18n

#32322 Dance sub-tagline translations
  pegasus/sites.v3/hourofcode.com/i18n/ar.yml
  pegasus/sites.v3/hourofcode.com/i18n/cn.yml
  pegasus/sites.v3/hourofcode.com/i18n/cs.yml
  pegasus/sites.v3/hourofcode.com/i18n/da.yml
  pegasus/sites.v3/hourofcode.com/i18n/de.yml
  pegasus/sites.v3/hourofcode.com/i18n/el.yml
  pegasus/sites.v3/hourofcode.com/i18n/fi.yml
  pegasus/sites.v3/hourofcode.com/i18n/fr.yml
  pegasus/sites.v3/hourofcode.com/i18n/hi.yml
  pegasus/sites.v3/hourofcode.com/i18n/hu.yml
  pegasus/sites.v3/hourofcode.com/i18n/id.yml
  pegasus/sites.v3/hourofcode.com/i18n/it.yml
  pegasus/sites.v3/hourofcode.com/i18n/ja.yml
  pegasus/sites.v3/hourofcode.com/i18n/ko.yml
  pegasus/sites.v3/hourofcode.com/i18n/ms.yml
  pegasus/sites.v3/hourofcode.com/i18n/nl.yml
  pegasus/sites.v3/hourofcode.com/i18n/ph.yml
  pegasus/sites.v3/hourofcode.com/i18n/pl.yml
  pegasus/sites.v3/hourofcode.com/i18n/ro.yml
  pegasus/sites.v3/hourofcode.com/i18n/ru.yml
  pegasus/sites.v3/hourofcode.com/i18n/sv.yml
  pegasus/sites.v3/hourofcode.com/i18n/th.yml
  pegasus/sites.v3/hourofcode.com/i18n/tr.yml
  pegasus/sites.v3/hourofcode.com/i18n/uk.yml
  pegasus/sites.v3/hourofcode.com/i18n/ur.yml
  pegasus/sites.v3/hourofcode.com/i18n/vi.yml
  pegasus/sites.v3/hourofcode.com/i18n/zh.yml
Labels: i18n

#32292 Small refactor of AdvancedShareOptions to prep for adding libraries.
  apps/i18n/common/en_us.json
  apps/src/code-studio/components/AdvancedShareOptions.jsx
Labels: star-labs

#32328 Move libraries to the advanced share menu
  apps/i18n/common/en_us.json
  apps/src/code-studio/components/AdvancedShareOptions.jsx
  apps/src/code-studio/components/ShareAllowedDialog.jsx
Labels: star-labs

#32200 [Applab Data Tab] Don't parse column names from records
  apps/src/applab/applab.js
  apps/src/storage/dataBrowser/DataTable.jsx
  apps/src/storage/dataBrowser/DataTableView.jsx
  apps/src/storage/dataBrowser/PreviewModal.jsx
  apps/src/storage/firebaseMetadata.js
  apps/src/storage/firebaseStorage.js
Labels: star-labs

#32332 Export app firehose analytics
  apps/src/code-studio/components/ExportDialog/Dialog.jsx
Labels: star-labs

#32334 Export fix for Android 10
  apps/src/templates/export/expo/App.js.ejs
  apps/src/templates/export/expo/package.exported_json
Labels: star-labs

#32367 [Data Viz] Don't color row values for Cross Tab
  apps/src/storage/dataBrowser/dataVisualizer/CrossTabChart.jsx
Labels: star-labs

#32385 Update principal approval and reminder emails
  dashboard/app/views/pd/application/teacher_application_mailer/principal_approval.html.haml
  dashboard/app/views/pd/application/teacher_application_mailer/principal_approval_teacher_reminder.html.haml
Labels: content-change

#32387 Add two questions to the CSF Intro enrollment form
  apps/src/code-studio/pd/workshop_enrollment/enroll_form.jsx
  apps/test/unit/code-studio/pd/workshop_enrollment/enroll_formTest.js
  dashboard/app/controllers/api/v1/pd/workshop_enrollments_controller.rb
  dashboard/app/models/pd/enrollment.rb
  dashboard/test/controllers/api/v1/pd/workshop_enrollments_controller_test.rb
Labels: feature, professional-learning

#32388 add z-index to watcher dropdown
  apps/src/templates/watchers/Watchers.jsx
Labels: star-labs

#32366 [DataViz] Implement chart title
  apps/package.json
  apps/src/storage/dataBrowser/dataVisualizer/CrossTabChart.jsx
  apps/src/storage/dataBrowser/dataVisualizer/GoogleChartWrapper.jsx
  apps/src/storage/dataBrowser/dataVisualizer/VisualizerModal.jsx
  apps/yarn.lock
Labels: star-labs

#32363 [DataViz] Update modal UI
  apps/src/storage/dataBrowser/dataStyles.js
  apps/src/storage/dataBrowser/dataVisualizer/DropdownField.jsx
  apps/src/storage/dataBrowser/dataVisualizer/VisualizerModal.jsx
  apps/src/storage/dataBrowser/dataVisualizer/placeholder.png
Labels: star-labs

#32396 Add microbit firmata (1)
  apps/src/third-party/maker/MBFirmataClient.js
Labels: star-labs

#32386 Prevent export applab app to expo with data apis
  apps/src/applab/Exporter.js
  apps/src/code-studio/components/ExportDialog/Dialog.jsx
Labels: star-labs

#32155 Fix interpreter call stack issue
  apps/package.json
  apps/src/lib/tools/jsinterpreter/CustomMarshalingInterpreter.js
  apps/test/unit/lib/tools/jsinterpreter/CustomMarshalingInterpreterTest.js
  apps/yarn.lock
Labels: star-labs

#32401 MicroBit Detect Board and Buttons A/B (2)
  apps/src/lib/kits/maker/Button.js
  apps/src/lib/kits/maker/MicroBitBoard.js
  apps/src/lib/kits/maker/MicroBitComponents.js
  apps/src/lib/kits/maker/PlaygroundComponents.js
  apps/src/lib/kits/maker/toolkit.js
  apps/test/unit/lib/kits/maker/ButtonTest.js
Labels: star-labs

#32420 [DataViz] I18n for DataViz
  apps/i18n/common/en_us.json
  apps/src/storage/dataBrowser/dataUtils.js
  apps/src/storage/dataBrowser/dataVisualizer/DataVisualizer.jsx
  apps/src/storage/dataBrowser/dataVisualizer/DropdownField.jsx
  apps/src/storage/dataBrowser/dataVisualizer/GoogleChartWrapper.jsx
  apps/src/storage/dataBrowser/dataVisualizer/VisualizerModal.jsx
  apps/test/unit/storage/dataBrowser/dataVisualizer/GoogleChartWrapperTest.js
Labels: star-labs

#32383 Fix automated export to teacher application summary sheet
  bin/cron/teacher_applications_to_gdrive
  bin/cron/teacher_applications_to_s3
  cookbooks/cdo-apps/templates/default/crontab.erb
Labels: bug-fix, professional-learning

#32381 Use Rails URL building logic to construct i18n URLs
  bin/i18n/i18n_script_utils.rb
  dashboard/app/helpers/levels_helper.rb
  dashboard/test/helpers/levels_helper_test.rb
Labels: i18n

#32436 Revert "Revert "MicroBit Detect Board and Buttons A/B (2)""
  apps/src/lib/kits/maker/Button.js
  apps/src/lib/kits/maker/CircuitPlaygroundBoard.js
  apps/src/lib/kits/maker/FakeBoard.js
  apps/src/lib/kits/maker/MicroBitBoard.js
  apps/src/lib/kits/maker/MicroBitComponents.js
  apps/src/lib/kits/maker/PlaygroundComponents.js
  apps/src/lib/kits/maker/toolkit.js
  apps/test/unit/lib/kits/maker/ButtonTest.js
  apps/test/unit/lib/kits/maker/MakerBoardTest.js
Labels: star-labs

#32459 Point gdrive script at new doc
  bin/cron/teacher_applications_to_gdrive
Labels: professional-learning

#32416 Upgrade to Expo SDK 36, fix WebView usage with iOS devices and file URLs
  apps/package.json
  apps/src/templates/export/expo/App.js.ejs
  apps/src/templates/export/expo/package.exported_json
  apps/src/util/exporter.js
  apps/src/util/exporterConstants.js
  apps/yarn.lock
Labels: star-labs

#32409 MicroBit Basic LED component support (3)
  apps/src/lib/kits/maker/LedMatrix.js
  apps/src/lib/kits/maker/MicroBitComponents.js
Labels: star-labs

#32412 Reset and Re-enable MB components (4)
  apps/src/lib/kits/maker/LedMatrix.js
  apps/src/lib/kits/maker/MicroBitBoard.js
  apps/src/lib/kits/maker/MicroBitComponents.js
  apps/src/lib/kits/maker/toolkit.js
Labels: star-labs

#32439 SharedFunction definitions no longer show up on a student's page after editing the toolbox with the WYSIWYG editor.
  apps/src/p5lab/P5Lab.js
Labels: star-labs

#32395 Disallow behavior editing if there is a toolbox with no categories
  apps/src/p5lab/spritelab/blocks.js
Labels: star-labs

#32471 Add link to last year's dance party tutorial on /dance
  pegasus/sites.v3/code.org/public/css/dance-landing/dance.css
  pegasus/sites.v3/code.org/public/dance.haml
Labels: content-change

#32453 Show workshop created_at date on workshop dashboard
  apps/src/code-studio/pd/workshop_dashboard/workshop.jsx
  dashboard/app/serializers/api/v1/pd/workshop_serializer.rb
  dashboard/test/controllers/api/v1/pd/workshops_controller_test.rb
Labels: feature, professional-learning

#32476 Deflake ProxyHelperTest
  dashboard/test/helpers/proxy_helper_test.rb
Labels: testing

#32458 Restore the "Go Beyond" announcement
  apps/i18n/common/en_us.json
  apps/src/templates/studioHomepages/TwoColumnActionBlock.jsx
  shared/images/teacher-announcement/hoc2019-csforgood.png
  shared/images/teacher-announcement/hoc2019-danceparty.png
  shared/images/teacher-announcement/hoc2019-posthoc.png
Labels: content-change

#31990 Break apart workshop.jsx
  apps/src/code-studio/pd/workshop_dashboard/AttendancePanel.jsx
  apps/src/code-studio/pd/workshop_dashboard/DetailsPanel.jsx
  apps/src/code-studio/pd/workshop_dashboard/EndWorkshopPanel.jsx
  apps/src/code-studio/pd/workshop_dashboard/EnrollmentsPanel.jsx
  apps/src/code-studio/pd/workshop_dashboard/IntroPanel.jsx
  apps/src/code-studio/pd/workshop_dashboard/SignUpPanel.jsx
  apps/src/code-studio/pd/workshop_dashboard/WorkshopPanel.jsx
  apps/src/code-studio/pd/workshop_dashboard/workshop.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/AttendancePanelTest.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/DetailsPanelTest.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/EndWorkshopPanelTest.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/EnrollmentsPanelTest.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/IntroPanelTest.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/SignUpPanelTest.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/workshopFactory.js
  apps/test/unit/lib/util/urlHelpersTest.js
  apps/test/util/testUtils.js
Labels: code-hygiene, refactor

#32493 Temporary static override for "Hours of Code served"
  lib/cdo/properties.rb
Labels: general-website

#32443 State management for Data Visualizer
  apps/src/storage/dataBrowser/TableControls.jsx
  apps/src/storage/dataBrowser/dataVisualizer/VisualizerModal.jsx
  apps/test/unit/storage/dataBrowser/TableControlsTest.js
  apps/test/unit/storage/dataBrowser/dataVisualizer/VisualizerModalTest.js
Labels: feature, star-labs

#32506 Restore created_at on workshop dashboard
  apps/src/code-studio/pd/workshop_dashboard/workshop.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/fakeWorkshopServer.js
  apps/test/unit/code-studio/pd/workshop_dashboard/workshopFactory.js
  apps/test/unit/code-studio/pd/workshop_dashboard/workshopTest.jsx
Labels: bug-fix, professional-learning

#32494 Clean up unused about_stats
  bin/cron/analyze_hoc_activity
  lib/cdo/properties.rb
  pegasus/sites.v3/code.org/public/diversity.md.erb
  pegasus/sites.v3/code.org/public/equityDocs/index.md.erb
Labels: code-hygiene, refactor

#32405 Implement Chart Title
  apps/package.json
  apps/src/storage/dataBrowser/dataVisualizer/CrossTabChart.jsx
  apps/src/storage/dataBrowser/dataVisualizer/GoogleChartWrapper.jsx
  apps/src/storage/dataBrowser/dataVisualizer/VisualizerModal.jsx
  apps/test/unit/storage/dataBrowser/dataVisualizer/GoogleChartWrapperTest.js
  apps/yarn.lock
Labels: star-labs
