Repository code-dot-org/code-dot-org, pull requests merged in 2019-03, with the labels that each got.

#27406 Deeper Learning: Only destroy unassigned peer reviews on unsubmit
  dashboard/app/models/user_level.rb
  dashboard/test/models/user_level_test.rb
Labels: professional-learning

#27287 Teacher app: Rescore taught in past
  bin/oneoff/rescore_taught_in_past
  dashboard/app/models/pd/application/teacher1920_application.rb
  dashboard/test/models/pd/application/teacher1920_application_test.rb
Labels: professional-learning

#27407 Deeper learning: Remove deprecated UI
  apps/src/code-studio/peer_reviews/PeerReviewDashboard.jsx
  apps/src/code-studio/peer_reviews/PeerReviewSubmissionData.jsx
  apps/src/code-studio/peer_reviews/PeerReviewSubmissionData.story.jsx
  apps/src/code-studio/peer_reviews/PeerReviewSubmissions.jsx
  apps/src/sites/studio/pages/peer_reviews/dashboard.js
  apps/test/unit/code-studio/peer_reviews/PeerReviewSubmissionsTest.jsx
  dashboard/app/controllers/api/v1/peer_review_submissions_controller.rb
  dashboard/app/models/peer_review.rb
  dashboard/test/controllers/api/v1/peer_review_submissions_controller_test.rb
  dashboard/test/models/peer_review_test.rb
Labels: professional-learning

#27432 Remove unused Honeybadger notification
  dashboard/app/models/user.rb
  dashboard/test/models/peer_review_test.rb
Labels: code-hygiene

#27441 Deeper Learning: Display relative review time
  apps/src/code-studio/peer_reviews/PeerReviewLinkSection.jsx
  apps/test/unit/code-studio/peer_reviews/PeerReviewSubmissionsTest.jsx
  dashboard/app/models/peer_review.rb
  dashboard/test/controllers/api/v1/peer_review_submissions_controller_test.rb
  dashboard/test/models/peer_review_test.rb
Labels: professional-learning

#27437 Deeper Learning: Refactor PeerReview creation
  dashboard/app/models/user.rb
  dashboard/app/models/user_level.rb
  dashboard/test/models/peer_review_test.rb
Labels: code-hygiene, professional-learning

#27439 Deeper Learning: Don't reopen accepted submissions
  dashboard/app/models/peer_review.rb
  dashboard/test/models/peer_review_test.rb
Labels: professional-learning

#27457 Workshop Surveys: Use question name if question text is unavailable
  dashboard/lib/pd/jot_form/translation.rb
  dashboard/test/lib/pd/jot_form/translation_test.rb
Labels: professional-learning

#27238 Scholarship Info: add dropdown to workshop dashboard
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_enrollment.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_enrollment_school_info.jsx
  apps/src/code-studio/pd/workshop_dashboard/types.js
  apps/src/code-studio/pd/workshop_dashboard/workshop.jsx
  dashboard/app/controllers/api/v1/pd/workshop_enrollments_controller.rb
  dashboard/app/models/ability.rb
  dashboard/app/models/pd/application/teacher_application_base.rb
  dashboard/app/models/pd/enrollment.rb
  dashboard/app/models/pd/scholarship_info.rb
  dashboard/app/models/pd/workshop.rb
  dashboard/app/serializers/api/v1/pd/workshop_enrollment_serializer.rb
  dashboard/config/routes.rb
  dashboard/test/controllers/api/v1/pd/workshop_enrollments_controller_test.rb
  dashboard/test/models/pd/application/teacher1920_application_test.rb
  dashboard/test/models/pd/enrollment_test.rb
  dashboard/test/models/pd/scholarship_info_test.rb
Labels: professional-learning

#27491 Remove unused Section#add_and_remove_student
  dashboard/app/models/sections/section.rb
  dashboard/test/models/sections/section_test.rb
Labels: code-hygiene

#27493 Deeper Learning: Remove nightly PeerReview backfill
  bin/cron/backfill_missing_peer_reviews
  cookbooks/cdo-apps/templates/default/crontab.erb
  dashboard/app/models/peer_review.rb
Labels: code-hygiene, professional-learning

#27511 Bug-fix: Missing strings from Minecraft landing page
  pegasus/cache/i18n/en-US.yml
  pegasus/sites.v3/code.org/views/minecraft_2018.haml
  pegasus/sites.v3/hourofcode.com/i18n/en.yml
Labels: bug-fix

#27649 Delete unused empty string
  pegasus/sites.v3/code.org/views/minecraft_2018.haml
Labels: code-hygiene

#27664 JotForm Monitoring: RenderJotFormView event
  dashboard/app/controllers/pd/post_course_survey_controller.rb
  dashboard/app/controllers/pd/workshop_daily_survey_controller.rb
  dashboard/test/controllers/pd/post_course_survey_controller_test.rb
  dashboard/test/controllers/pd/workshop_daily_survey_controller_test.rb
Labels: professional-learning
