Repository code-dot-org/code-dot-org, pull requests merged in 2019-07, with the labels that each got.

#29385 Call the callback once for *each* overlap/clicked sprite
  apps/src/gamelab/spritelab/spriteUtils.js
  apps/test/unit/gamelab/spritelab/spriteUtilsTest.js
Labels: star-labs

#29404 Pull spritelab preview code out of gamelab.js
  apps/src/gamelab/GameLab.js
  apps/src/gamelab/spritelab/Spritelab.js
  apps/test/unit/gamelab/GameLabTest.js
  apps/test/unit/gamelab/spritelab/SpritelabTest.js
Labels: star-labs

#29429 Clicking 'Draw' in Sprite Lab costume picker opens to a new animation in the costume tab
  apps/src/gamelab/actions.js
  apps/src/gamelab/blocks.js
Labels: star-labs

#29375 Removing inspector flag
  apps/src/applab/applab.js
  apps/src/gamelab/GameLab.js
  apps/src/lib/tools/jsdebugger/DebugConsole.jsx
  apps/src/lib/tools/jsdebugger/JsDebugger.jsx
  apps/src/lib/tools/jsdebugger/redux.js
  apps/test/integration/levelSolutions/applab/ec_data_blocks.js
  apps/test/integration/levelSolutions/applab/ec_data_browser.js
  apps/test/integration/levelSolutions/applab/ec_setprop.js
  apps/test/integration/levelSolutions/applab/ec_simple.js
  apps/test/integration/levelSolutions/applab/ec_variables.js
  apps/test/integration/levelSolutions/applab/helper_libraries.js
  apps/test/integration/levelSolutions/applab/timeout_api_blocks.js
  apps/test/integration/levelSolutions/gamelab/collision_blocks.js
  apps/test/integration/levelSolutions/gamelab/timeout_api_blocks.js
  apps/test/integration/levelSolutions/gamelab/world_blocks.js
  apps/test/unit/lib/tools/jsdebugger/DebugConsoleTest.js
  apps/test/unit/lib/tools/jsdebugger/reduxTest.js
  dashboard/test/ui/features/applab/scenarios.feature
Labels: star-labs

#29482 Email: Send Poste activity metrics to New Relic
  bin/cron/deliver_poste_messages
Labels: professional-learning

#29497 New PD Certificate Image
  dashboard/app/assets/images/pd_workshop_certificate_generic.png
  dashboard/lib/pd/certificate_renderer.rb
Labels: professional-learning

#29510 Use workshop subject constants on the client
  apps/script/generateSharedConstants.rb
  apps/src/code-studio/pd/application/facilitator1920/Section3ExperienceAndCommitments.jsx
  apps/src/code-studio/pd/application/teacher1920/Section4ProfessionalLearningProgramRequirements.jsx
  apps/src/code-studio/pd/application_dashboard/workshop_assignment_loader.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_enrollment_school_info.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_management.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_table.jsx
  apps/src/code-studio/pd/workshop_survey/WorkshopSurvey.jsx
  lib/cdo/shared_constants/pd/shared_workshop_constants.rb
Labels: code-hygiene

#29029 Export supports resuming or canceling previous builds using new generatedProperties
  apps/package.json
  apps/src/applab/Exporter.js
  apps/src/applab/applab.js
  apps/src/code-studio/appOptions.js
  apps/src/code-studio/components/AdvancedShareOptions.jsx
  apps/src/code-studio/components/ExportDialog.jsx
  apps/src/code-studio/components/exportDialogRedux.js
  apps/src/code-studio/components/header/ProjectExport.jsx
  apps/src/code-studio/headerExport.js
  apps/src/code-studio/initApp/loadApp.js
  apps/src/code-studio/initApp/project.js
  apps/src/gamelab/Exporter.js
  apps/src/gamelab/GameLab.js
  apps/src/redux/pageConstants.js
  apps/src/sites/studio/pages/init/loadGamelab.js
  apps/src/templates/export/expo/app.json.ejs
  apps/src/util/exporter.js
  apps/test/unit/code-studio/components/ExportDialogTest.js
  apps/test/unit/code-studio/initApp/projectTest.js
  apps/yarn.lock
Labels: star-labs

#29537 Revert "Export supports resuming or canceling previous builds using new generatedProperties"
  apps/package.json
  apps/src/applab/Exporter.js
  apps/src/applab/applab.js
  apps/src/code-studio/appOptions.js
  apps/src/code-studio/components/AdvancedShareOptions.jsx
  apps/src/code-studio/components/ExportDialog.jsx
  apps/src/code-studio/components/exportDialogRedux.js
  apps/src/code-studio/components/header/ProjectExport.jsx
  apps/src/code-studio/headerExport.js
  apps/src/code-studio/initApp/loadApp.js
  apps/src/code-studio/initApp/project.js
  apps/src/gamelab/Exporter.js
  apps/src/gamelab/GameLab.js
  apps/src/redux/pageConstants.js
  apps/src/sites/studio/pages/init/loadGamelab.js
  apps/src/templates/export/expo/app.json.ejs
  apps/src/util/exporter.js
  apps/test/unit/code-studio/components/ExportDialogTest.js
  apps/test/unit/code-studio/initApp/projectTest.js
  apps/yarn.lock
Labels: star-labs

#29560 I18n sync In & Up 07/09
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2017/coursec-2017.json
  i18n/locales/source/course_content/2017/coursed-2017.json
  i18n/locales/source/course_content/2017/coursee-2017.json
  i18n/locales/source/course_content/2017/coursef-2017.json
  i18n/locales/source/course_content/2017/csd1-2017.json
  i18n/locales/source/course_content/2017/csd2-2017.json
  i18n/locales/source/course_content/2017/csd3-2017.json
  i18n/locales/source/course_content/2017/csd4-2017.json
  i18n/locales/source/course_content/2017/csd5-2017.json
  i18n/locales/source/course_content/2017/csd6-2017.json
  i18n/locales/source/course_content/2017/express-2017.json
  i18n/locales/source/course_content/2017/pre-express-2017.json
  i18n/locales/source/course_content/2018/coursed-2018.json
  i18n/locales/source/course_content/2018/coursee-2018.json
  i18n/locales/source/course_content/2018/coursef-2018.json
  i18n/locales/source/course_content/2018/csd2-2018.json
  i18n/locales/source/course_content/2018/csd3-2018.json
  i18n/locales/source/course_content/2018/csd4-2018.json
  i18n/locales/source/course_content/2018/csd5-2018.json
  i18n/locales/source/course_content/2018/csd6-2018.json
  i18n/locales/source/course_content/2018/express-2018.json
  i18n/locales/source/course_content/2019/coursea-2019.json
  i18n/locales/source/course_content/2019/courseb-2019.json
  i18n/locales/source/course_content/2019/coursec-2019.json
  i18n/locales/source/course_content/2019/coursed-2019.json
  i18n/locales/source/course_content/2019/coursee-2019.json
  i18n/locales/source/course_content/2019/coursef-2019.json
  i18n/locales/source/course_content/2019/csd2-2019.json
  i18n/locales/source/course_content/2019/csd3-2019.json
  i18n/locales/source/course_content/2019/csd4-2019.json
  i18n/locales/source/course_content/2019/csd5-2019.json
  i18n/locales/source/course_content/2019/csd6-2019.json
  i18n/locales/source/course_content/2019/express-2019.json
  i18n/locales/source/course_content/Hour of Code/dance-extras.json
  i18n/locales/source/course_content/Hour of Code/hoc-encryption.json
  i18n/locales/source/course_content/other/K5-OnlinePD.json
  i18n/locales/source/course_content/other/applab-1hour.json
  i18n/locales/source/course_content/other/applab-2hour.json
  i18n/locales/source/course_content/other/fesbinary.json
  i18n/locales/source/course_content/other/netsim.json
  i18n/locales/source/dashboard/block_categories.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#29540 Restore export work with pixelation fix
  apps/package.json
  apps/src/applab/Exporter.js
  apps/src/applab/applab.js
  apps/src/code-studio/appOptions.js
  apps/src/code-studio/components/AdvancedShareOptions.jsx
  apps/src/code-studio/components/ExportDialog.jsx
  apps/src/code-studio/components/exportDialogRedux.js
  apps/src/code-studio/components/header/ProjectExport.jsx
  apps/src/code-studio/headerExport.js
  apps/src/code-studio/initApp/loadApp.js
  apps/src/code-studio/initApp/project.js
  apps/src/gamelab/Exporter.js
  apps/src/gamelab/GameLab.js
  apps/src/redux/pageConstants.js
  apps/src/sites/studio/pages/init/loadGamelab.js
  apps/src/templates/export/expo/app.json.ejs
  apps/src/util/exporter.js
  apps/test/unit/code-studio/components/ExportDialogTest.js
  apps/test/unit/code-studio/initApp/projectTest.js
  apps/yarn.lock
  dashboard/public/pixelation/pixelation.js
Labels: star-labs

#29564 Re-enable pixelation.feature UI tests on CI
  dashboard/test/ui/features/pixelation.feature
Labels: star-labs, testing

#29511 Professional Learning: FiT workshops have no exit surveys
  dashboard/app/models/pd/enrollment.rb
  dashboard/app/models/pd/workshop.rb
  dashboard/test/controllers/pd/professional_learning_landing_controller_test.rb
  dashboard/test/models/pd/enrollment_test.rb
  dashboard/test/models/pd/workshop_test.rb
Labels: professional-learning

#29577 Droplet with node version 8.15.0.
  apps/lib/droplet/droplet-full.js
  apps/lib/droplet/droplet-full.min.js
  apps/lib/droplet/droplet-full.min.js.map
Labels: star-labs

#29580 Bump Expo SDK version for exported projects (from v31 to v33)
  apps/src/templates/export/expo/App.js.ejs
  apps/src/templates/export/expo/package.exported_json
  apps/src/util/exporter.js
Labels: star-labs

#29491 Preload background images for Sprite Lab
  apps/src/gamelab/GameLab.js
  apps/src/gamelab/GameLabP5.js
  apps/src/gamelab/spritelab/Spritelab.js
  apps/src/gamelab/spritelab/backgrounds.json
  apps/src/gamelab/spritelab/worldCommands.js
Labels: star-labs

#29533 Paginate Data Table in App Lab Data Tab
  apps/i18n/common/en_us.json
  apps/src/storage/dataBrowser/DataTable.jsx
  apps/src/templates/PaginationWrapper.jsx
Labels: star-labs

#29603 Surveys: Redirect to JotForm forms instead of embedding them (experiment)
  dashboard/app/controllers/pd/misc_survey_controller.rb
  dashboard/app/controllers/pd/post_course_survey_controller.rb
  dashboard/app/controllers/pd/workshop_daily_survey_controller.rb
  dashboard/app/helpers/pd/jot_form/embed_helper.rb
Labels: professional-learning

#29551 Increase max_table_rows for App Lab data tables
  config.yml.erb
Labels: star-labs

#29601 show 1 page even if there are no rows
  apps/src/storage/dataBrowser/DataTable.jsx
Labels: star-labs

#29600 Added new allowed hostnames for startWebRequest
  dashboard/app/controllers/xhr_proxy_controller.rb
Labels: star-labs

#29592 School Info Completeness: refactor user school infos update method
  dashboard/app/controllers/api/v1/user_school_infos_controller.rb
Labels: code-hygiene

#29628 Bugfix: Survey report works when related workshops contain no info for workshop facilitator
  dashboard/app/helpers/pd/workshop_survey_results_helper.rb
  dashboard/test/helpers/pd/workshop_survey_results_helper_test.rb
Labels: bug-fix, professional-learning

#29648 Remove fake-fetch
  apps/package.json
  apps/test/unit/applab/ExporterTest.js
  apps/yarn.lock
Labels: testing

#29658 [React 16] Updated package.json to match minimum-needed version for react-portal, react-redux, and react-lazy-load
  apps/package.json
  apps/yarn.lock
Labels: star-labs

#29670 Tests: JsDebuggerTest passes in Chrome browser
  apps/src/dom.js
  apps/test/unit/lib/tools/jsdebugger/JsDebuggerTest.js
Labels: testing

#29679 Updated several dependencies to React 16 compatible versions
  apps/package.json
  apps/yarn.lock
Labels: star-labs

#29675 Remove sinon-chai-in-order
  apps/package.json
  apps/test/unit/code-studio/pd/form_components/UsPhoneNumberInputTest.js
  apps/test/util/configuredChai.js
  apps/test/util/reconfiguredChai.js
  apps/yarn.lock
Labels: testing

#29640 Upgrade to sinon 4
  apps/package.json
  apps/yarn.lock
Labels: testing

#29693 Upgrade to sinon 4
  apps/package.json
  apps/test/integration/levelSolutions/gamelab/collision_blocks.js
  apps/yarn.lock
Labels: testing

#29642 Upgrade to sinon 5
  apps/package.json
  apps/test/unit/code-studio/pd/form_components/FormControllerTest.js
  apps/test/unit/code-studio/pd/form_components/SingleCheckboxTest.js
  apps/test/unit/code-studio/pd/workshop_dashboard/components/workshop_managementTest.js
  apps/test/unit/code-studio/stageLockReduxTest.js
  apps/test/unit/lib/kits/maker/LedTest.js
  apps/test/unit/lib/kits/maker/NeoPixelTest.js
  apps/test/unit/lib/kits/maker/PiezoTest.js
  apps/test/unit/lib/kits/maker/PlaygroundComponentsTest.js
  apps/test/unit/lib/kits/maker/TouchSensorTest.js
  apps/test/unit/lib/util/timeoutApiTest.js
  apps/test/unit/templates/CodeWorkspaceTest.js
  apps/test/unit/templates/DropdownButtonTest.js
  apps/test/unit/templates/instructions/InstructionsWithWorkspaceTest.jsx
  apps/test/unit/templates/progress/HiddenForSectionToggleTest.jsx
  apps/test/unit/templates/teacherDashboard/AssignmentSelectorTest.js
  apps/test/unit/watchers/AutocompleteSelectorTest.js
  apps/yarn.lock
Labels: testing

#29681 [React 16] Upgrade react color to latest for React 16 compatibility
  apps/package.json
  apps/yarn.lock
Labels: star-labs

#29550 Add Spritelab App Entrypoint
  apps/Gruntfile.js
  apps/i18n/spritelab/en_us.json
  apps/script/checkEntryPoints.js
  apps/src/sites/studio/pages/init/loadSpritelab.js
  apps/src/sites/studio/pages/levels-spritelab-main.js
  apps/src/spritelab/SpriteLab.js
  apps/src/spritelab/locale.js
  apps/src/spritelab/style.scss
  dashboard/app/models/game.rb
Labels: star-labs

#29704 Stop overwriting custom submit buttons for PD external levels
  dashboard/app/views/levels/_external.html.haml
Labels: bug-fix

#29714 Surveys: Run sync_jotforms every half-hour
  cookbooks/cdo-apps/templates/default/crontab.erb
Labels: professional-learning

#29706 I18n sync In & Up 07/15
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2017/coursee-2017.json
  i18n/locales/source/course_content/2017/coursef-2017.json
  i18n/locales/source/course_content/2017/express-2017.json
  i18n/locales/source/course_content/2019/csd3-2019.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#29723 Remove @cdo/apps alias from package.json
  apps/package.json
  apps/src/package.json
  apps/yarn.lock
Labels: code-hygiene

#29718 Fix: Workshops without subjects have exit surveys
  dashboard/app/models/pd/enrollment.rb
  dashboard/test/controllers/pd/professional_learning_landing_controller_test.rb
  dashboard/test/models/pd/enrollment_test.rb
Labels: professional-learning

#29726 Added opentdb and pokeapi to allow-list for applab
  dashboard/app/controllers/xhr_proxy_controller.rb
Labels: star-labs

#29680 Use path alias for gamelab imports
  apps/src/code-studio/components/ShareAllowedDialog.jsx
  apps/src/gamelab/AnimationJsonViewer.jsx
  apps/src/gamelab/AnimationPicker/AnimationPicker.jsx
  apps/src/gamelab/AnimationPicker/AnimationPickerBody.jsx
  apps/src/gamelab/AnimationPicker/AnimationPickerListItem.jsx
  apps/src/gamelab/AnimationPicker/AnimationPickerSearchBar.jsx
  apps/src/gamelab/AnimationPicker/animationPickerModule.js
  apps/src/gamelab/AnimationPicker/styles.js
  apps/src/gamelab/AnimationTab/AnimationList.jsx
  apps/src/gamelab/AnimationTab/AnimationListItem.jsx
  apps/src/gamelab/AnimationTab/AnimationTab.jsx
  apps/src/gamelab/AnimationTab/DeleteAnimationDialog.jsx
  apps/src/gamelab/AnimationTab/ListItemButtons.jsx
  apps/src/gamelab/AnimationTab/ListItemThumbnail.jsx
  apps/src/gamelab/AnimationTab/NewListItem.jsx
  apps/src/gamelab/ErrorDialogStack.jsx
  apps/src/gamelab/Exporter.js
  apps/src/gamelab/GameLab.js
  apps/src/gamelab/GameLabP5.js
  apps/src/gamelab/GameLabView.jsx
  apps/src/gamelab/GameLabVisualizationColumn.jsx
  apps/src/gamelab/GameLabVisualizationHeader.jsx
  apps/src/gamelab/MobileControls.js
  apps/src/gamelab/actions.js
  apps/src/gamelab/animationListModule.js
  apps/src/gamelab/api-entry.js
  apps/src/gamelab/blocks.js
  apps/src/gamelab/commands.js
  apps/src/gamelab/constants.js
  apps/src/gamelab/dropletConfig.js
  apps/src/gamelab/levels.js
  apps/src/gamelab/locationPickerModule.js
  apps/src/gamelab/reducers.js
  apps/src/gamelab/spritelab/Spritelab.js
  apps/src/gamelab/spritelab/worldCommands.js
Labels: star-labs

#29720 Professional Learning: Facilitator workshops have no exit surveys
  dashboard/app/models/pd/enrollment.rb
  dashboard/app/models/pd/workshop.rb
  dashboard/test/controllers/pd/professional_learning_landing_controller_test.rb
  dashboard/test/models/pd/enrollment_test.rb
  dashboard/test/models/pd/workshop_test.rb
Labels: professional-learning

#29745 Don't update preview if code is running
  apps/src/gamelab/spritelab/Spritelab.js
  apps/test/unit/gamelab/spritelab/SpritelabTest.js
Labels: star-labs

#29686 Bump snack-sdk to 2.2.1-apkurl-v4, fix Expo build issues with dependencies, icon, and splash
  apps/package.json
  apps/src/util/exporter.js
  apps/yarn.lock
Labels: star-labs

#29613 Refactor applab themeColors to themeValues (consolidate theme values)
  apps/src/applab/designElements/button.jsx
  apps/src/applab/designElements/dropdown.jsx
  apps/src/applab/designElements/elementUtils.js
  apps/src/applab/designElements/label.jsx
  apps/src/applab/designElements/screen.jsx
  apps/src/applab/designElements/textInput.jsx
  apps/src/applab/designElements/textarea.jsx
  apps/src/applab/themeColor.js
  apps/src/applab/themeValues.js
Labels: star-labs

#29579 Refactor ExportDialog pages into separate components
  apps/src/code-studio/components/ExportDialog/Dialog.jsx
  apps/src/code-studio/components/ExportDialog/GeneratingPage.jsx
  apps/src/code-studio/components/ExportDialog/IconPage.jsx
  apps/src/code-studio/components/ExportDialog/IntroPage.jsx
  apps/src/code-studio/components/ExportDialog/PlatformPage.jsx
  apps/src/code-studio/components/ExportDialog/PublishPage.jsx
  apps/src/code-studio/components/ExportDialog/styles.js
  apps/src/code-studio/headerExport.js
  apps/test/unit/code-studio/components/ExportDialogTest.js
Labels: star-labs

#29731 Add Spritelab app entrypoint
  apps/Gruntfile.js
  apps/i18n/gamelab/en_us.json
  apps/i18n/spritelab/en_us.json
  apps/script/checkEntryPoints.js
  apps/src/gamelab/GameLab.js
  apps/src/sites/studio/pages/init/loadSpritelab.js
  apps/src/sites/studio/pages/levels-spritelab-main.js
  apps/src/spritelab/SpriteLab.js
  apps/src/spritelab/locale-do-not-import.js
  apps/style/spritelab/style.scss
  apps/webpack.js
  dashboard/app/models/game.rb
Labels: star-labs

#29779 Tests: Deflake TeacherAttendanceReportControllerTest
  dashboard/test/controllers/api/v1/pd/teacher_attendance_report_controller_test.rb
Labels: testing

#29588 Update dropdowns to extend outside the coding workspace
  apps/lib/droplet/droplet-full.js
  apps/lib/droplet/droplet-full.min.js
  apps/lib/droplet/droplet-full.min.js.map
  apps/lib/droplet/droplet.min.css
  apps/src/StudioApp.js
  apps/src/templates/CodeWorkspaceContainer.jsx
  apps/style/applab/style.scss
  apps/style/common.scss
Labels: star-labs

#29793 Tests: Minimal setup in WorkshopDailySurveyControllerTest
  dashboard/test/controllers/pd/workshop_daily_survey_controller_test.rb
Labels: testing

#29581 Enable Applab themes for everyone
  apps/src/applab/designElements/library.js
  apps/src/applab/designElements/screen.jsx
  apps/src/applab/designProperties.jsx
  apps/test/integration/levelSolutions/applab/ec_design.js
  apps/test/unit/applab/designModeThemesTest.js
Labels: star-labs

#29732 [React 16] Migrated reactabular to sub-packages
  apps/package.json
  apps/src/code-studio/pd/application_dashboard/admin_cohort_view_table.jsx
  apps/src/code-studio/pd/application_dashboard/cohort_view_table.jsx
  apps/src/code-studio/pd/application_dashboard/quick_view_table.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_table.jsx
  apps/src/code-studio/pd/workshop_dashboard/reports/report_table.jsx
  apps/src/netsim/NetSimLogBrowserTable.jsx
  apps/src/templates/census2017/CensusInaccuracyReviewDetails.jsx
  apps/src/templates/census2017/CensusInaccuracyReviewTable.jsx
  apps/src/templates/manageStudents/ManageStudentsTable.jsx
  apps/src/templates/manageStudents/MoveStudents.jsx
  apps/src/templates/projects/FeaturedProjectsTable.jsx
  apps/src/templates/projects/PersonalProjectsTable.jsx
  apps/src/templates/projects/ProjectsList.jsx
  apps/src/templates/sectionAssessments/FreeResponsesAssessmentsTable.jsx
  apps/src/templates/sectionAssessments/FreeResponsesSurveyTable.jsx
  apps/src/templates/sectionAssessments/MatchAssessmentsOverviewTable.jsx
  apps/src/templates/sectionAssessments/MatchByStudentTable.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceAssessmentsOverviewTable.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceByQuestionTable.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceByStudentTable.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceSurveyOverviewTable.jsx
  apps/src/templates/sectionAssessments/SubmissionStatusAssessmentsTable.jsx
  apps/src/templates/tables/wrapped_sortable.js
  apps/src/templates/teacherDashboard/OwnedSectionsTable.jsx
  apps/src/templates/teacherDashboard/StatsTable.jsx
  apps/src/templates/textResponses/TextResponsesTable.jsx
  apps/test/unit/templates/teacherDashboard/OwnedSectionsTableTest.js
  apps/yarn.lock
Labels: star-labs

#29737 Pass categoryName to FieldVariable
  apps/i18n/common/en_us.json
  apps/lib/blockly/en_us.js
  apps/package.json
  apps/src/gamelab/blocks.js
  apps/yarn.lock
Labels: star-labs

#29831 Add SpriteLab entrypoint
  apps/Gruntfile.js
  apps/i18n/common/en_us.json
  apps/i18n/gamelab/en_us.json
  apps/i18n/spritelab/en_us.json
  apps/script/checkEntryPoints.js
  apps/src/code-studio/initApp/loadApp.js
  apps/src/code-studio/initApp/project.js
  apps/src/code-studio/reporting.js
  apps/src/gamelab/GameLab.js
  apps/src/sites/studio/pages/init/loadSpritelab.js
  apps/src/sites/studio/pages/levels-spritelab-main.js
  apps/src/spritelab/SpriteLab.js
  apps/src/spritelab/locale-do-not-import.js
  apps/src/util/unsupportedBrowserWarning.js
  apps/style/spritelab/style.scss
  apps/test/unit/code-studio/initApp/projectTest.js
  apps/webpack.js
  dashboard/app/models/game.rb
Labels: star-labs

#29835 Stop logging an error message if an empty string is passed to the safe browsing api
  dashboard/app/controllers/safe_browsing_controller.rb
Labels: star-labs

#29861 Surveys: Turn experimental JotForm redirect into a form-specific A/B test
  dashboard/app/helpers/pd/jot_form/embed_helper.rb
Labels: professional-learning

#29848 PL: Send count of active workshops to New Relic
  dashboard/app/models/pd/workshop.rb
  dashboard/test/models/pd/workshop_test.rb
Labels: professional-learning

#29838 I18n sync In & Up 07/22
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2017/coursee-2017.json
  i18n/locales/source/course_content/2017/coursef-2017.json
  i18n/locales/source/course_content/2017/express-2017.json
  i18n/locales/source/course_content/2018/coursee-2018.json
  i18n/locales/source/course_content/2018/coursef-2018.json
  i18n/locales/source/course_content/2018/express-2018.json
  i18n/locales/source/course_content/other/K5-OnlinePD.json
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#29852 Added donordrive.com to allowlist. Zendesk: 245208
  dashboard/app/controllers/xhr_proxy_controller.rb
Labels: star-labs

#29884 Add animation i18n strings to common
  apps/i18n/common/en_us.json
Labels: star-labs

#29882 Ingest FiT workshop pre- and post- surveys
  dashboard/app/models/pd/misc_survey.rb
Labels: data

#29827 Export: allow student to upload icon image for exported app
  apps/src/applab/Exporter.js
  apps/src/code-studio/components/ExportDialog/Dialog.jsx
  apps/src/code-studio/components/ExportDialog/IconPage.jsx
  apps/src/gamelab/Exporter.js
  apps/test/unit/code-studio/components/ExportDialogTest.js
Labels: star-labs

#29849 Update droplet dropdowns to extend outside the coding workspace (reintroduces reverted PR)
  apps/lib/droplet/droplet-full.js
  apps/lib/droplet/droplet-full.min.js
  apps/lib/droplet/droplet-full.min.js.map
  apps/lib/droplet/droplet.min.css
  apps/src/templates/CodeWorkspace.jsx
  apps/src/templates/CodeWorkspaceContainer.jsx
  apps/style/JsDebuggerUi.scss
  apps/style/applab/style.scss
  apps/style/common.scss
Labels: star-labs

#29911 Fix JotForm redirect experiment A/B test
  dashboard/app/helpers/pd/jot_form/embed_helper.rb
  dashboard/test/helpers/pd/jot_form/embed_helper_test.rb
Labels: professional-learning

#29786 Applab: fix dontMarshalApi functions for export
  apps/src/applab/api.js
  apps/src/applab/dontMarshalApi.js
  apps/src/applab/dropletConfig.js
  apps/test/integration/levelSolutions/applab/ec_simple.js
  apps/test/unit/applab/ExporterTest.js
  apps/test/unit/applab/dontMarshalApiTest.js
Labels: star-labs

#29931 Default values for randomNumber
  apps/src/dropletUtils.js
Labels: star-labs

#29990 School Info Completeness: close confirmation dialog when dismiss button is clicked
  apps/src/lib/ui/SchoolInfoInterstitial.jsx
  apps/test/unit/lib/ui/SchoolInfoInterstitialTest.jsx
Labels: bug-fix

#30005 Include all CSP 19-20 units in ScriptConstants
  lib/cdo/script_constants.rb
Labels: bug-fix

#29876 PL: Send count of active workshops to New Relic
  dashboard/app/models/pd/workshop.rb
  dashboard/test/models/pd/workshop_test.rb
Labels: professional-learning

#29992 School Info Completeness: Change from nces school to non nces school
  apps/src/lib/ui/SchoolInfoInterstitial.jsx
  apps/src/templates/CountryAutocompleteDropdown.jsx
  apps/test/unit/lib/ui/SchoolInfoInterstitialTest.jsx
Labels: bug-fix

#29991 School Info Completeness: submit sii form with only non-US country
  apps/src/lib/ui/SchoolInfoInterstitial.jsx
  apps/test/unit/lib/ui/SchoolInfoInterstitialTest.jsx
Labels: bug-fix

#29918 Create P5Lab as a common base class for Game Lab and Sprite Lab
  apps/src/p5lab/P5Lab.js
  apps/src/p5lab/gamelab/GameLab.js
  apps/src/p5lab/spritelab/SpriteLab.js
  apps/src/sites/studio/pages/init/loadSpritelab.js
Labels: star-labs

#29925 Move spritelab out of GameLabP5
  apps/src/p5lab/P5Lab.js
  apps/src/p5lab/gamelab/GameLabP5.js
  apps/src/p5lab/gamelab/spritelab/Spritelab.js
  apps/src/p5lab/spritelab/SpriteLab.js
  apps/src/p5lab/spritelab/actionCommands.js
  apps/src/p5lab/spritelab/backgrounds.json
  apps/src/p5lab/spritelab/behaviorCommands.js
  apps/src/p5lab/spritelab/commands.js
  apps/src/p5lab/spritelab/eventCommands.js
  apps/src/p5lab/spritelab/locationCommands.js
  apps/src/p5lab/spritelab/spriteCommands.js
  apps/src/p5lab/spritelab/spriteUtils.js
  apps/src/p5lab/spritelab/validationCommands.js
  apps/src/p5lab/spritelab/worldCommands.js
  apps/test/unit/gamelab/GameLabTest.js
  apps/test/unit/gamelab/spritelab/SpritelabTest.js
  apps/test/unit/spritelab/SpritelabTest.js
  apps/test/unit/spritelab/TextConsoleTest.js
  apps/test/unit/spritelab/actionCommandsTest.js
  apps/test/unit/spritelab/locationCommandsTest.js
  apps/test/unit/spritelab/spriteCommandsTest.js
  apps/test/unit/spritelab/spriteUtilsTest.js
Labels: star-labs

#29995 I18n sync In & Up 07/29
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/gamelab.json
  i18n/locales/source/blockly-mooc/netsim.json
  i18n/locales/source/course_content/2019/coursec-2019.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#30040 fix valueTypeTabShapeMap imports
  apps/src/sites/studio/pages/blocks/edit.js
  apps/src/sites/studio/pages/blocks/index.js
  apps/src/sites/studio/pages/shared_blockly_functions/edit.js
Labels: star-labs
