Repository code-dot-org/code-dot-org, pull requests merged in 2019-11, with the labels that each got.

#31631 [Data Viz] Add Cross Tab chart type
  apps/src/applab/GoogleChart.js
  apps/src/storage/dataBrowser/DataVisualizer.jsx
  apps/test/unit/storage/dataBrowser/DataVisualizerTest.js
Labels: star-labs

#31633 creating _markdown versions of source strings
  dashboard/config/locales/en.yml
Labels: i18n

#31604 [student-libraries] Final update to the libraries data model
  apps/src/StudioApp.js
  apps/src/code-studio/components/libraries/LibraryClientApi.js
  apps/src/code-studio/components/libraries/LibraryManagerDialog.jsx
  apps/src/code-studio/components/libraries/libraryParser.js
  apps/src/code-studio/initApp/project.js
  apps/test/unit/StudioAppTest.js
  apps/test/unit/code-studio/components/libraries/libraryParserTest.js
  apps/test/unit/code-studio/components/libraries/sampleLibrary.json
Labels: star-labs

#31605 [student-libraries] Multiple single-line comments in a row are now parsed as a multiline comment.
  apps/src/lib/tools/jsinterpreter/JSInterpreter.js
  apps/test/unit/lib/tools/jsinterpreter/JSInterpreterTest.js
Labels: star-labs

#31621 Optimize volunteer map query performance
  pegasus/forms/volunteer_engineer_submission_2015.rb
  pegasus/test/test_form_routes.rb
Labels: performance

#31649 [Applab Datasets] For duplicate tables, show error message properly
  apps/src/storage/dataBrowser/DataLibraryPane.jsx
Labels: star-labs

#31437 [Data Viz] Implement Scatter Plot Chart type
  apps/src/storage/dataBrowser/DataVisualizer.jsx
  apps/test/unit/storage/dataBrowser/DataVisualizerTest.js
Labels: star-labs

#31597 [student-libraries] Removed/disabled unimplemented components.
  apps/src/blockTooltips/DropletBlockTooltipManager.js
  apps/src/blockTooltips/DropletFunctionTooltip.html.ejs
  apps/src/blockTooltips/DropletFunctionTooltip.js
  apps/src/code-studio/components/libraries/LibraryListItem.jsx
  apps/src/code-studio/components/libraries/LibraryManagerDialog.jsx
Labels: star-labs

#31665 [Applab Dataset] Added levelbuilder setting for importing a data table
  dashboard/app/models/levels/applab.rb
  dashboard/app/views/levels/editors/_applab.html.haml
  dashboard/app/views/levels/editors/_droplet.html.haml
Labels: star-labs

#31640 Teacher Application: Enrollment reminder emails
  dashboard/app/mailers/pd/application/teacher_application_mailer.rb
  dashboard/app/views/pd/application/teacher_application_mailer/registration_reminder.html.haml
  dashboard/bin/scheduled_pd_application_emails
  dashboard/lib/services/README.md
  dashboard/lib/services/registration_reminder.rb
  dashboard/test/lib/services/registration_reminder_test.rb
  dashboard/test/mailers/previews/pd_teacher_application_mailer_preview.rb
Labels: feature, ruby

#31629 [student-libraries] Give levelbuilders the option to use libraries without the experiment flag
  apps/src/applab/applab.js
  apps/src/code-studio/components/ShareAllowedDialog.jsx
  apps/src/lib/ui/SettingsCog.jsx
  apps/src/p5lab/P5Lab.js
  apps/src/redux/pageConstants.js
  dashboard/app/models/levels/applab.rb
  dashboard/app/models/levels/gamelab.rb
  dashboard/app/views/levels/editors/_droplet.html.haml
Labels: star-labs

#31666 Revert "Revert "[Data Viz] Implement Scatter Plot Chart type""
  apps/src/storage/dataBrowser/DataVisualizer.jsx
  apps/test/unit/storage/dataBrowser/DataVisualizerTest.js
Labels: star-labs

#31612 Switch to karma-coverage-istanbul-reporter
  apps/Gruntfile.js
  apps/karma.conf.js
  apps/package.json
  apps/webpack.js
  apps/yarn.lock
Labels: testing

#31682 Add new song manifest to dance party
  apps/src/dance/Dance.js
  apps/src/dance/songs.js
Labels: star-labs

#31698 Update to dance party 45
  apps/package.json
  apps/yarn.lock
Labels: star-labs

#31710 [DataViz] Implement CrossTabChart as React component, not using GoogleChart
  apps/src/applab/GoogleChart.js
  apps/src/storage/dataBrowser/CrossTabChart.jsx
  apps/src/storage/dataBrowser/DataVisualizer.jsx
  apps/test/unit/storage/dataBrowser/CrossTabChartTest.js
  apps/test/unit/storage/dataBrowser/DataVisualizerTest.js
Labels: star-labs

#31679 I18n sync In & Up 11/04
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/dance.json
  i18n/locales/source/blockly-mooc/fish.json
  i18n/locales/source/course_content/2019/csd3-2019.json
  i18n/locales/source/course_content/2019/dance-extras-2019.json
  i18n/locales/source/course_content/Hour of Code/dance-2019.json
  i18n/locales/source/course_content/Hour of Code/dance-extras-2019.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/block_categories.json
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#31726 Fix continue button on external video levels
  apps/src/sites/studio/pages/levels/_external.js
  dashboard/lib/tasks/seed.rake
  dashboard/test/ui/features/level_navigation.feature
Labels: bug-fix

#31754 Provide fallback value when organizer no longer exists
  apps/src/code-studio/pd/professional_learning_landing/EnrolledWorkshops.story.jsx
  apps/src/code-studio/pd/workshop_dashboard/types.js
  apps/test/unit/code-studio/pd/professional_learning_landing/EnrolledWorkshopsTest.jsx
  dashboard/app/serializers/api/v1/pd/workshop_serializer.rb
Labels: bug-fix

#31606 [student-libraries] Added error handling for expected error cases in library publish.
  apps/i18n/common/en_us.json
  apps/src/code-studio/components/libraries/LibraryCreationDialog.jsx
  apps/test/unit/code-studio/components/libraries/LibraryCreationDialogTest.js
Labels: star-labs

#31672 [Applab Datasets] Added table names to the levelbuilder page
  apps/src/sites/studio/pages/levels/editors/_applab.js
  apps/src/storage/dataBrowser/datasetManifest.json
  dashboard/app/views/levels/editors/_applab.html.haml
Labels: star-labs

#31742 Add new songs to dance part extras
  apps/src/dance/Dance.js
Labels: star-labs

#31745 Use new song manifest in LB
  dashboard/app/models/levels/dancelab.rb
Labels: star-labs

#31717 [Data Viz] Cross Tab styling
  apps/src/storage/dataBrowser/CrossTabChart.jsx
  apps/src/storage/dataBrowser/DataVisualizer.jsx
  apps/test/unit/storage/dataBrowser/CrossTabChartTest.js
Labels: star-labs

#31764 Bump dance for new character
  apps/package.json
  apps/src/dance/Dance.js
  apps/yarn.lock
  dashboard/config/scripts/levels/CourseD_Dance_Party_01.level
  dashboard/config/scripts/levels/CourseD_Dance_Party_02.level
  dashboard/config/scripts/levels/CourseD_Dance_Party_03.level
  dashboard/config/scripts/levels/CourseD_Dance_Party_04.level
  dashboard/config/scripts/levels/CourseD_Dance_Party_06.level
  dashboard/config/scripts/levels/CourseD_Dance_Party_08.level
  dashboard/config/scripts/levels/CourseD_Dance_Party_09.level
  dashboard/config/scripts/levels/CourseD_Dance_Party_10.level
  dashboard/config/scripts/levels/CourseD_Dance_Party_11.level
  dashboard/config/scripts/levels/CourseD_Dance_Party_11_5.level
  dashboard/config/scripts/levels/CourseD_Dance_Party_11b.level
  dashboard/config/scripts/levels/Dance_2019_01.level
  dashboard/config/scripts/levels/Dance_2019_02.level
  dashboard/config/scripts/levels/Dance_2019_03.level
  dashboard/config/scripts/levels/Dance_2019_04.level
  dashboard/config/scripts/levels/Dance_2019_05.level
  dashboard/config/scripts/levels/Dance_2019_06.level
  dashboard/config/scripts/levels/Dance_2019_07.level
  dashboard/config/scripts/levels/Dance_2019_08.level
  dashboard/config/scripts/levels/Dance_2019_08f.level
  dashboard/config/scripts/levels/Dance_2019_09.level
  dashboard/config/scripts/levels/Dance_Party_01.level
  dashboard/config/scripts/levels/Dance_Party_02.level
  dashboard/config/scripts/levels/Dance_Party_03.level
  dashboard/config/scripts/levels/Dance_Party_04.level
  dashboard/config/scripts/levels/Dance_Party_06.level
  dashboard/config/scripts/levels/Dance_Party_08.level
  dashboard/config/scripts/levels/Dance_Party_09.level
  dashboard/config/scripts/levels/Dance_Party_10.level
  dashboard/config/scripts/levels/Dance_Party_11.5_test.level
  dashboard/config/scripts/levels/Dance_Party_11.level
  dashboard/config/scripts/levels/Dance_Party_11_5.level
  dashboard/config/scripts/levels/Dance_Party_11b.level
  dashboard/config/scripts/levels/Ryan_Demo.level
Labels: star-labs

#31802 I18n sync In & Up 11/09
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2017/coursed-2017.json
  i18n/locales/source/course_content/2017/coursef-2017.json
  i18n/locales/source/course_content/2017/csd2-2017.json
  i18n/locales/source/course_content/2017/csd3-2017.json
  i18n/locales/source/course_content/2017/csd6-2017.json
  i18n/locales/source/course_content/2017/express-2017.json
  i18n/locales/source/course_content/2018/coursed-2018.json
  i18n/locales/source/course_content/2018/coursef-2018.json
  i18n/locales/source/course_content/2018/csd2-2018.json
  i18n/locales/source/course_content/2018/csd3-2018.json
  i18n/locales/source/course_content/2018/csd6-2018.json
  i18n/locales/source/course_content/2018/express-2018.json
  i18n/locales/source/course_content/2019/coursed-2019.json
  i18n/locales/source/course_content/2019/coursee-2019.json
  i18n/locales/source/course_content/2019/coursef-2019.json
  i18n/locales/source/course_content/2019/csd2-2019.json
  i18n/locales/source/course_content/2019/csd3-2019.json
  i18n/locales/source/course_content/2019/csd6-2019.json
  i18n/locales/source/course_content/2019/express-2019.json
  i18n/locales/source/course_content/Hour of Code/dance-2019.json
  i18n/locales/source/course_content/Hour of Code/dance.json
  i18n/locales/source/course_content/other/fesbinary.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#31821 Teacher Homepage: HOC 2019 announcement
  apps/i18n/common/en_us.json
  apps/src/templates/studioHomepages/TeacherHomepage.jsx
  apps/src/templates/studioHomepages/TwoColumnActionBlock.jsx
  shared/images/teacher-announcement/hoc2019-csforgood.png
Labels: content-change

#31801 alternateMoves block
  apps/package.json
  apps/yarn.lock
  dashboard/config/blocks/Dancelab/Dancelab_alternateMoves.json
Labels: star-labs

#31824 I18n sync In & Up 11/11
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/course_content/Hour of Code/dance-2019.json
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#31810 Remove broken "smaller posters" from hourofcode.com
  i18n/locales/source/hourofcode/promote/resources.md
  pegasus/sites.v3/hourofcode.com/public/promote/resources.md.partial
Labels: content-change

#31863 UI test clean up: remove display toast step
  dashboard/test/ui/features/step_definitions/steps.rb
Labels: code-hygiene

#31877 Fix counselor/admin workshop survey
  pegasus/sites.v3/code.org/public/pd-workshop-survey/counselor-admin/splat.haml
Labels: bug-fix

#31885 Fix 500 on hourofcode.org/events/<year>/*
  pegasus/sites.v3/hourofcode.com/public/events/2014/splat.haml
  pegasus/sites.v3/hourofcode.com/public/events/2015/splat.haml
  pegasus/sites.v3/hourofcode.com/public/events/2016/splat.haml
Labels: bug-fix

#31886 Remove the Poste dashboard
  pegasus/sites.v3/code.org/public/poste.moved
  pegasus/sites.v3/code.org/public/private/index.md.erb
  pegasus/sites.v3/code.org/public/private/poste/index.haml
  pegasus/sites.v3/code.org/public/private/poste/list.haml
  pegasus/sites.v3/code.org/public/private/poste/mail/all-mail.haml
  pegasus/sites.v3/code.org/public/private/poste/mail/all-tests.haml
  pegasus/sites.v3/code.org/public/private/poste/mail/index.haml
  pegasus/sites.v3/code.org/public/private/poste/mail/message-786.haml
  pegasus/sites.v3/code.org/public/private/poste/send.md.erb
  pegasus/sites.v3/code.org/public/private/poste/stats.haml
Labels: code-hygiene, poste

#31268 Improvements to /learn/local
  apps/Gruntfile.js
  apps/src/lib/ui/classroomMap.js
  apps/src/sites/code.org/pages/public/learn/local.js
  apps/test/unit/lib/ui/classroomMapTest.js
  pegasus/sites.v3/code.org/public/js/class-search.js
  pegasus/sites.v3/code.org/public/learn/local.haml
Labels: code-hygiene

#31890 Update the Regional Partner Playbook nav
  pegasus/sites.v3/code.org/views/regional_partner_playbook_nav.haml
Labels: content-change, professional-learning

#31805 [Applab] Clear Firebase data on puzzle reset
  apps/firebase/rules.bolt
  apps/src/applab/applab.js
  apps/src/storage/firebaseStorage.js
  apps/test/unit/storage/FirebaseStorageTest.js
  dashboard/test/ui/features/applab/data_blocks.feature
Labels: star-labs

#31857 [Applab Datasets] Import data library tables on first load
  apps/src/applab/applab.js
  apps/src/storage/firebaseStorage.js
Labels: star-labs

#31896 Handle submissionless rows gracefully in Peer Review CSV
  dashboard/app/controllers/api/v1/peer_review_submissions_controller.rb
  dashboard/test/controllers/api/v1/peer_review_submissions_controller_test.rb
Labels: bug-fix

#31907 Impose max call stack size in JS interpreter
  apps/src/lib/tools/jsinterpreter/JSInterpreter.js
Labels: star-labs

#31846 [student-libraries] add 'view code' option when importing libraries
  apps/src/code-studio/components/libraries/LibraryListItem.jsx
  apps/src/code-studio/components/libraries/LibraryManagerDialog.jsx
  apps/src/code-studio/components/libraries/LibraryViewCode.jsx
  apps/test/unit/code-studio/components/libraries/libraryManagerDialogTest.js
Labels: star-labs

#31917 Remove newSongs flag
  apps/src/dance/Dance.js
Labels: star-labs

#31887 [Artist] smaller steps threshold for preview
  apps/src/turtle/artist.js
Labels: star-labs

#31915 cache Dance Party 2019 in CloudFront
  cookbooks/cdo-varnish/libraries/http_cache.rb
  cookbooks/cdo-varnish/test/shared/shared.rb
Labels: star-labs

#31927 Bump dance party to version 51
  apps/package.json
  apps/yarn.lock
Labels: star-labs

#31928 Fix continue button on external markdown levels
  apps/src/sites/studio/pages/levels/_external.js
  dashboard/test/ui/features/level_navigation.feature
Labels: bug-fix

#31930 Engineering adjustments to middle-high-2020 page
  pegasus/sites.v3/code.org/public/educate/professional-learning/middle-high-2020.md.erb
  pegasus/sites.v3/code.org/views/regional_partner_zip_form_2020.haml
Labels: content-change

#31953 Middle-high PL page split test: Merge control and experiment into one page
  pegasus/sites.v3/code.org/public/educate/professional-learning/middle-high.md.erb
Labels: content-change

#31851 [Applab Datasets] Fix TableControls for current tables
  apps/src/storage/dataBrowser/DataTableView.jsx
  apps/src/storage/dataBrowser/TableControls.jsx
Labels: star-labs

#31924 Arrow buttons now work on touchscreen laptops.
  apps/src/dom.js
Labels: star-labs

#31830 [Applab Datasets] Weather script
  apps/src/storage/dataBrowser/datasetManifest.json
  bin/applab_datasets/upload_to_firebase
  bin/cron/applab_datasets/weather
  bin/oneoff/applab_datasets/cats.csv
  bin/oneoff/applab_datasets/dogs.csv
  bin/oneoff/applab_datasets/states.csv
  bin/oneoff/applab_datasets/upload_csv_to_firebase
Labels: star-labs

#31855 Migrating 'html_safe' strings to use the markdown version instead
  dashboard/app/assets/stylesheets/application.scss
  dashboard/app/assets/stylesheets/interstitial.scss
  dashboard/app/views/api/accept_terms_reminder.haml
  dashboard/app/views/devise/registrations/_finish_sign_up.html.haml
  dashboard/app/views/devise/registrations/_new_sign_up_form.html.haml
  dashboard/app/views/devise/registrations/_old_sign_up_form.html.haml
  dashboard/app/views/devise/registrations/_sign_up.html.haml
  dashboard/app/views/devise/registrations/edit.html.haml
  dashboard/app/views/layouts/_terms_interstitial.html.haml
  dashboard/app/views/zendesk_session/index.html.haml
  lib/cdo/i18n_backend.rb
Labels: i18n

#31919 Only use songManifest2019.json
  apps/src/dance/Dance.js
  apps/src/dance/songs.js
Labels: star-labs

#31966 Update log for 2019 to measure new plays
  apps/src/dance/Dance.js
Labels: star-labs

#31986 Re-enable: Arrow buttons now work on touchscreen laptops. Includes IE fix.
  apps/src/dom.js
Labels: star-labs

#31974 I18n sync In & Up 11/18
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2019/csd2-2019.json
  i18n/locales/source/course_content/2019/csd3-2019.json
  i18n/locales/source/course_content/2019/dance-extras-2019.json
  i18n/locales/source/course_content/Hour of Code/dance-2019.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/hourofcode/international-partners.md
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#32002 Update twitter names
  apps/src/code-studio/dancePartySongArtistTags.js
Labels: star-labs

#31999 Update the dance-party version to include paint-drip
  apps/package.json
  apps/yarn.lock
Labels: star-labs

#32008 Assignment Updates: showAssignButton shouldn't hide the section selection dropdown
  apps/src/code-studio/components/progress/ScriptOverviewTopRow.jsx
Labels: bug-fix

#31998 [Data Viz] Change table name in weather script
  bin/cron/applab_datasets/weather
Labels: star-labs

#31987 [Data Viz] Ignore empty cells
  apps/src/storage/dataBrowser/DataVisualizer.jsx
  apps/test/unit/storage/dataBrowser/DataVisualizerTest.js
Labels: star-labs

#31876 Assignment Updates: delete AssignToSection
  apps/src/templates/courseOverview/AssignToSection.js
  apps/src/templates/courseOverview/AssignToSection.story.jsx
  apps/test/unit/templates/courseOverview/AssignToSectionTest.js
Labels: code-hygiene

#31871 Assignment Updates: delete LabeledSectionSelector
  apps/src/code-studio/components/progress/LabeledSectionSelector.jsx
Labels: code-hygiene

#32007 I18n sync In & Up 11/19
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/course_content/Hour of Code/oceans.json
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#32033 Assignment Updates: better accommodate long section names
  apps/src/lib/ui/PopUpMenu.jsx
  apps/src/templates/teacherDashboard/TeacherSectionSelector.jsx
  apps/src/templates/teacherDashboard/TeacherSectionSelectorMenuItem.jsx
Labels: bug-fix

#32043 Added api.spacexdata.com to the allowlist for applab
  dashboard/app/controllers/xhr_proxy_controller.rb
Labels: star-labs

#31971 [student-libraries] Allow exporting nested libraries
  apps/src/code-studio/components/libraries/LibraryCreationDialog.jsx
  apps/test/unit/code-studio/components/libraries/LibraryCreationDialogTest.js
Labels: star-labs

#32050 Added oldtownroadremix_lilnasx_long to songs that should tag LilNasX
  apps/src/code-studio/dancePartySongArtistTags.js
Labels: star-labs

#32076 Remove unused file reactTestUtils.js
  apps/test/util/reactTestUtils.js
Labels: code-hygiene, testing

#32055 [Applab Dataset] Crontab configuration for Weather
  bin/cron/applab_datasets/weather
  cookbooks/cdo-apps/templates/default/crontab.erb
Labels: star-labs

#32083 Add two indexes to pd_attendances
  dashboard/app/models/pd/attendance.rb
  dashboard/db/migrate/20191122183555_add_indexes_to_attendances.rb
  dashboard/db/schema.rb
Labels: performance

#32119 I18n sync In & Up 11/25
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2019/coursee-2019.json
  i18n/locales/source/course_content/2019/coursef-2019.json
  i18n/locales/source/course_content/2019/express-2019.json
  i18n/locales/source/course_content/Hour of Code/dance-extras-2019.json
  i18n/locales/source/course_content/Hour of Code/oceans.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/dashboard/slides.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/hourofcode/promote/stats.md
Labels: i18n

#32140 Update dance party version to use new dance party sprite layouts
  apps/package.json
  apps/yarn.lock
  dashboard/config/blocks/Dancelab/Dancelab_makeNewDanceSpriteGroup.json
Labels: star-labs

#32149 [Applab Datasets] Delete columns before pushing new ones to Firebase
  shared/middleware/helpers/firebase_helper.rb
  shared/test/middleware/helpers/test_firebase_helper.rb
Labels: star-labs

#32150 Fix broken link on hourofcode.com/us/how-to/afterschool
  pegasus/sites.v3/hourofcode.com/public/how-to/afterschool.md.partial
Labels: content-change

#32167 [Spritelab] hide edit button for behaviors if toolbox doesn't have categories
  apps/src/p5lab/spritelab/blocks.js
Labels: star-labs

#32152 [Data Viz] Separate Chart logic from modal
  apps/package.json
  apps/src/storage/dataBrowser/DataVisualizer.jsx
  apps/src/storage/dataBrowser/TableControls.jsx
  apps/src/storage/dataBrowser/dataUtils.js
  apps/src/storage/dataBrowser/dataVisualizer/CrossTabChart.jsx
  apps/src/storage/dataBrowser/dataVisualizer/DataVisualizer.jsx
  apps/src/storage/dataBrowser/dataVisualizer/DropdownField.jsx
  apps/src/storage/dataBrowser/dataVisualizer/GoogleChartWrapper.jsx
  apps/src/storage/dataBrowser/dataVisualizer/VisualizerModal.jsx
  apps/test/unit/storage/dataBrowser/DataVisualizerTest.js
  apps/test/unit/storage/dataBrowser/dataVisualizer/CrossTabChartTest.js
  apps/test/unit/storage/dataBrowser/dataVisualizer/GoogleChartWrapperTest.js
  apps/test/unit/storage/dataBrowser/dataVisualizer/VisualizerModalTest.js
  apps/test/unit/storage/dataUtilsTest.js
  apps/yarn.lock
Labels: star-labs

#32133 [Data Tab][Cleanup] Rename getColumnNames and onColumnNames
  apps/src/applab/applab.js
  apps/src/storage/firebaseMetadata.js
  apps/test/unit/storage/firebaseMetadataTest.js
Labels: star-labs

#32161 Add a link to last year's dance party tutorial to /dance page
  pegasus/cache/i18n/en-US.yml
  pegasus/sites.v3/code.org/public/dance.haml
Labels: content-change
