Repository code-dot-org/code-dot-org, pull requests merged in 2019-04, with the labels that each got.

#27788 Tests: Use a videos fixture instead of seeding videos.csv
  dashboard/lib/tasks/seed.rake
  dashboard/test/fixtures/video.yml
  lib/rake/test.rake
Labels: testing

#26828 Add total attendance column to workshop dashboard for local summer workshops
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_enrollment_school_info.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/components/workshop_enrollment_school_infoTest.js
  dashboard/test/serializers/api/v1/pd/workshop_enrollment_serializer_test.rb
Labels: professional-learning

#27376 Make authored hints id a required field in a level
  dashboard/app/views/levels/editors/_authored_hints.haml
Labels: i18n

#27764 Surveys: Monitor embedded JotForm load success rates
  apps/Gruntfile.js
  apps/script/checkEntryPoints.js
  apps/src/logToCloud.js
  apps/src/sites/studio/pages/jotformLoader.js
  dashboard/app/views/pd/post_course_survey/new.haml
  dashboard/app/views/pd/workshop_daily_survey/new_facilitator.html.haml
  dashboard/app/views/pd/workshop_daily_survey/new_general.haml
Labels: professional-learning

#27870 Cleanup: Simplify ChartApi.js
  apps/src/applab/ChartApi.js
Labels: code-hygiene

#27892 Testing: Avoid unneeded dependencies in entry test bundles
  apps/Gruntfile.js
  apps/test/integration-tests.js
  apps/test/unit-tests.js
  apps/test/util/clearTimeoutsBetweenTests.js
  apps/test/util/testUtils.js
  apps/test/util/throwOnConsole.js
Labels: testing

#27893 Testing: Even smaller entry bundle sizes
  apps/test/unit/lib/kits/maker/ui/SetupChecklistTest.js
  apps/test/unit/templates/teacherDashboard/teacherSectionsReduxTest.js
  apps/test/util/throwOnConsole.js
Labels: testing

#27867 Cleanup: Simplify GoogleChart.js
  apps/src/applab/ChartApi.js
  apps/src/applab/GoogleChart.js
Labels: code-hygiene

#27985 Free response assessments table is now sortable by student name
  apps/src/templates/sectionAssessments/FreeResponsesAssessmentsTable.jsx
Labels: learning-platform

#27981 Sample data: Add channels and fake teacher feedback
  dashboard/lib/sample_data.rb
Labels: testing

#28000 Hide assign button for unassignable scripts and courses
  apps/src/code-studio/components/progress/ScriptOverview.jsx
  apps/src/code-studio/components/progress/ScriptOverviewTopRow.jsx
  apps/src/code-studio/progress.js
  apps/src/sites/studio/pages/courses/show.js
  apps/src/templates/courseOverview/AssignToSection.js
  apps/src/templates/courseOverview/CourseOverview.js
  apps/src/templates/courseOverview/CourseOverviewTopRow.js
  apps/test/unit/code-studio/components/progress/ScriptOverviewTopRowTest.jsx
  apps/test/unit/templates/courseOverview/CourseOverviewTopRowTest.js
  dashboard/app/models/course.rb
  dashboard/app/models/script.rb
  dashboard/test/controllers/courses_controller_test.rb
  dashboard/test/models/course_test.rb
  dashboard/test/models/script_test.rb
Labels: learning-platform

#27993 Tests: Use reconfiguredChai.js in all of test/unit/code-studio
  apps/test/unit/code-studio/components/DownloadReplayVideoButton.js
  apps/test/unit/code-studio/components/ReportAbuseFormTest.js
  apps/test/unit/code-studio/components/ShareDialogTest.js
  apps/test/unit/code-studio/components/SoundLibraryTest.js
  apps/test/unit/code-studio/components/SoundListEntryTest.js
  apps/test/unit/code-studio/components/SoundPickerTest.js
  apps/test/unit/code-studio/components/pairing/PairingTest.js
  apps/test/unit/code-studio/components/progress/MiniViewTest.js
  apps/test/unit/code-studio/components/progress/ScriptOverviewHeaderTest.js
  apps/test/unit/code-studio/components/progress/ScriptTeacherPanelTest.jsx
  apps/test/unit/code-studio/components/progress/StageLockDialogTest.jsx
  apps/test/unit/code-studio/components/progress/ViewAsToggleTest.jsx
  apps/test/unit/code-studio/initApp/loadAppTest.js
  apps/test/unit/code-studio/initApp/projectTest.js
  apps/test/unit/code-studio/pd/application_dashboard/admin_cohort_viewTest.js
  apps/test/unit/code-studio/pd/application_dashboard/detail_view_contentsTest.js
  apps/test/unit/code-studio/pd/components/markdownSpanTest.js
  apps/test/unit/code-studio/pd/form_components/ButtonListTest.js
  apps/test/unit/code-studio/pd/form_components/FormControllerTest.js
  apps/test/unit/code-studio/pd/form_components/SingleCheckboxTest.js
  apps/test/unit/code-studio/pd/professional_learning_landing/landingPageTest.js
  apps/test/unit/code-studio/pd/regional_partner_contact/RegionalPartnerContactTest.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/attendance/session_attendance_row_test.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/attendance/session_attendance_test.jsx
  apps/test/unit/code-studio/plc/headerTest.jsx
  apps/test/util/assertions.js
Labels: testing

#28143 PL: Require sign in to enroll in any workshop
  apps/src/code-studio/pd/workshop_enrollment/sign_in_prompt.jsx
  apps/src/code-studio/pd/workshop_enrollment/workshop_enrollment.jsx
  dashboard/app/controllers/pd/workshop_enrollment_controller.rb
  dashboard/test/controllers/pd/workshop_enrollment_controller_test.rb
Labels: professional-learning

#28183 Deeper Learning: Paginated results
  apps/package.json
  apps/src/code-studio/peer_reviews/PeerReviewSubmissions.jsx
  apps/src/lib/ui/Pagination.jsx
  apps/src/lib/ui/Pagination.scss
  apps/test/unit/code-studio/peer_reviews/PeerReviewSubmissionsTest.jsx
  apps/yarn.lock
  dashboard/app/controllers/api/v1/peer_review_submissions_controller.rb
  dashboard/test/controllers/api/v1/peer_review_submissions_controller_test.rb
Labels: professional-learning

#28230 Fix initial sort of assessment submissions table
  apps/src/templates/sectionAssessments/SubmissionStatusAssessmentsTable.jsx
Labels: teacher-dashboard

#28249 Fix sorting by date bug in assessments submissions table
  apps/src/templates/sectionAssessments/SubmissionStatusAssessmentsTable.jsx
  apps/src/templates/sectionAssessments/assessmentsTestHelpers.js
  apps/src/templates/sectionAssessments/sectionAssessmentsRedux.js
  apps/test/unit/templates/sectionAssessments/SubmissionStatusAssessmentsTableTest.js
  apps/test/unit/templates/sectionAssessments/sectionAssessmentsReduxTest.js
Labels: teacher-dashboard

#28277 Fix assign course dialog not closing
  apps/src/templates/courseOverview/AssignToSection.js
Labels: teacher-dashboard

#28271 Add deprecated note to unplugged in Levelbuilder
  dashboard/app/views/levels/new.html.haml
Labels: levelbuilder-improvements
