Repository code-dot-org/code-dot-org, pull requests merged in 2019-02, with the labels that each got.

#26329 New Workshop Form: add "Deep Dive" as CSF subject option
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_form.jsx
Labels: professional-learning

#26886 I18n sync In & Up 02/04
  dashboard/config/locales/blocks.en.yml
  dashboard/config/locales/callouts.en.yml
  dashboard/config/locales/long_instructions.en.yml
  dashboard/config/locales/short_instructions.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/callouts.yml
  i18n/locales/source/dashboard/dsls.yml
  i18n/locales/source/dashboard/long_instructions.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/dashboard/short_instructions.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#26973 Teacher Application: Scholarship dropdown tests
  apps/test/unit/code-studio/pd/application_dashboard/detail_view_contentsTest.js
  apps/test/unit/lib/ui/SettingsCogTest.js
  apps/test/util/reactTestUtils.js
Labels: testing

#26990 Bug fix: Minecraft Course aquatic Stage 1 Puzzle 5 - Dutch
  dashboard/config/locales/blocks.nl-NL.yml
  dashboard/config/locales/long_instructions.nl-NL.yml
Labels: i18n

#26991 I18n sync In & Up 02/11
  dashboard/config/locales/authored_hints.en.yml
  dashboard/config/locales/blocks.en.yml
  dashboard/config/locales/display_name.en.yml
  dashboard/config/locales/long_instructions.en.yml
  dashboard/config/locales/short_instructions.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/authored_hints.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/display_name.yml
  i18n/locales/source/dashboard/dsls.yml
  i18n/locales/source/dashboard/long_instructions.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/dashboard/short_instructions.yml
Labels: i18n

#27093 Mailer previews: show 3- and 10-day csf workshop reminder previews
  dashboard/test/mailers/previews/pd_workshop_mailer_preview.rb
Labels: professional-learning

#27050 Scholarship Info: migration to create table of PD Scholarship Info
  dashboard/db/migrate/20190214005506_create_pd_scholarship_infos.rb
  dashboard/db/schema.rb
Labels: professional-learning

#27115 Organizer Survey Results: Temporary message about missing survey data
  apps/src/code-studio/pd/workshop_dashboard/components/survey_results_header.jsx
Labels: professional-learning

#27117 Regional Partner Admin: Link to regional partner search by region
  dashboard/app/views/regional_partners/index.html.haml
Labels: professional-learning

#27121 Hygiene: Correct erroneous comment
  dashboard/app/controllers/pd/international_opt_in_controller.rb
Labels: code-hygiene

#27040 Add a test and incorporate past PR feedback
  dashboard/app/helpers/pd/workshop_survey_results_helper.rb
  dashboard/test/helpers/pd/workshop_survey_results_helper_test.rb
Labels: professional-learning

#27151 International Workshop Attendance Form: More reliable workshop date validation
  apps/src/code-studio/pd/international_opt_in/InternationalOptIn.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/date_picker.jsx
  dashboard/app/models/pd/international_opt_in.rb
  dashboard/test/controllers/api/v1/pd/international_opt_ins_controller_test.rb
  dashboard/test/models/pd/international_opt_in_test.rb
Labels: professional-learning

#27154 Teacher Application: Question Tweaks
  apps/src/code-studio/pd/application/teacher1920/Section1AboutYou.jsx
  apps/src/code-studio/pd/application/teacher1920/Section3TeachingBackground.jsx
  dashboard/app/models/pd/application/teacher1920_application.rb
  dashboard/test/controllers/api/v1/pd/applications_controller_test.rb
  dashboard/test/factories/pd_factories.rb
  dashboard/test/models/pd/application/teacher1920_application_test.rb
  dashboard/test/ui/features/pd/teacher_application.feature
  lib/cdo/shared_constants/pd/teacher1920_application_constants.rb
Labels: professional-learning

#27165 Teacher Application: Remove subjectsLicensedToTeach question
  apps/src/code-studio/pd/application/teacher1920/Section3TeachingBackground.jsx
  dashboard/app/models/pd/application/teacher1920_application.rb
  dashboard/test/controllers/api/v1/pd/applications_controller_test.rb
  dashboard/test/models/pd/application/teacher1920_application_test.rb
  dashboard/test/ui/features/pd/teacher_application.feature
  lib/cdo/shared_constants/pd/teacher1920_application_constants.rb
Labels: professional-learning

#27164 Teacher Application: Inline first name and last name fields
  apps/src/code-studio/pd/application/teacher1920/Section1AboutYou.jsx
Labels: professional-learning

#27163 Teacher Application: Warn when navigating away without completing application
  apps/src/code-studio/pd/application/teacher1920/Teacher1920Application.jsx
Labels: professional-learning

#26778 Import Maryland course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#27070 Import west virginia course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#27077 Import Maine course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#27091 Import Nevada course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#27099 Import Texas Course Offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#27100 Import New Jersey Course Offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#27144 Import Tennessee course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#27145 Import New Hampshire course codes.
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#27146 Import Vermont course offerings.
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#27147 Import DC course offerings.
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#27148 Import Hawaii course offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#27150 Scholarship Info: use ScholarshipInfo table
  bin/oneoff/backfill_data/scholarship_info
  dashboard/app/controllers/api/v1/pd/applications_controller.rb
  dashboard/app/models/pd/application/teacher_application_base.rb
  dashboard/test/controllers/api/v1/pd/applications_controller_test.rb
  dashboard/test/models/pd/application/teacher1920_application_test.rb
Labels: professional-learning

#27203 Teacher Application: Scholarship question changes
  apps/src/code-studio/pd/application/teacher1920/Section4ProfessionalLearningProgramRequirements.jsx
  dashboard/app/models/pd/application/teacher1920_application.rb
  dashboard/test/controllers/api/v1/pd/applications_controller_test.rb
  dashboard/test/factories/pd_factories.rb
  dashboard/test/models/pd/application/teacher1920_application_test.rb
  lib/cdo/shared_constants/pd/teacher_common_application_constants.rb
Labels: professional-learning

#27244 Teacher Application: Remove page six
  apps/src/code-studio/pd/application/teacher1920/PrivacyDialog.jsx
  apps/src/code-studio/pd/application/teacher1920/Section1AboutYou.jsx
  apps/src/code-studio/pd/application/teacher1920/Section5AdditionalDemographicInformation.jsx
  apps/src/code-studio/pd/application/teacher1920/Section6Submission.jsx
  apps/src/code-studio/pd/application/teacher1920/Teacher1920Application.jsx
  dashboard/test/ui/features/pd/teacher_application.feature
  lib/cdo/shared_constants/pd/teacher1920_application_constants.rb
Labels: professional-learning

#27226 Import Delaware Course Offerings
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#27273 Teacher Application: Fixup old applications with new "Pay fee" question changes
  bin/oneoff/backfill_data/teacher1920_application_pay_fee_changes
  dashboard/app/models/pd/application/teacher1920_application.rb
  dashboard/test/models/pd/application/teacher1920_application_test.rb
Labels: professional-learning
