Repository code-dot-org/code-dot-org, pull requests merged in 2019-05, with the labels that each got.

#28286 Update curriculum guide links in emails
  dashboard/app/views/pd/workshop_mailer/_csd_pre_course_reading.html.haml
  dashboard/app/views/pd/workshop_mailer/_csp_pre_course_reading.html.haml
Labels: professional-learning

#28289 Fix alignment of checkboxes in Levelbuilder
  apps/style/code-studio/levelbuilder.scss
Labels: levelbuilder-improvements

#28338 Tests: Stub File.write in levelbuilder mode script test
  dashboard/test/controllers/scripts_controller_test.rb
Labels: testing

#28325 External levels can be displayed as Unplugged
  apps/src/templates/progress/progressHelpers.js
  apps/test/unit/code-studio/progressReduxTest.js
  apps/test/unit/templates/sectionProgress/sectionProgressReduxTest.js
  dashboard/app/dsl/content_dsl.rb
  dashboard/app/models/script_level.rb
  dashboard/config/locales/scripts.en.yml
  dashboard/config/scripts/allthethings.script
  dashboard/config/scripts/allthethings_external_displayed_as_unplugged.external
  dashboard/config/scripts/allthethings_external_not_displayed_as_unplugged.external
Labels: levelbuilder-improvements

#28369 Tests: Make tests in apps/test/unit/templates/progress Enzyme-3-ready
  apps/test/unit/templates/progress/ProgressLessonTest.js
  apps/test/unit/templates/progress/ProgressTableTest.jsx
  apps/test/unit/templates/progress/SummaryProgressRowTest.js
Labels: testing

#28368 Tests: Make ScriptOverviewHeaderTest.js Enzyme-3-ready
  apps/test/unit/code-studio/components/progress/ScriptOverviewHeaderTest.js
Labels: testing

#28365 Tests: Make tests in apps/test/unit/templates/teacherDashboard Enzyme-3-ready
  apps/test/unit/templates/teacherDashboard/OwnedSectionsTest.js
  apps/test/unit/templates/teacherDashboard/SectionActionDropdownTest.js
Labels: testing

#28367 Tests: Make tests in apps/test/unit/templates/sectionAssessments Enzyme-3-ready
  apps/test/unit/templates/sectionAssessments/SubmissionStatusAssessmentsTableTest.js
Labels: testing

#28398 Optionally use large video player in external levels
  dashboard/app/dsl/content_dsl.rb
  dashboard/app/views/levels/_external.html.haml
  dashboard/app/views/levels/show.html.haml
Labels: levelbuilder-improvements

#28417 Fix broken link to home on /lesson_plans
  pegasus/sites.v3/code.org/public/lesson_plans.haml
Labels: bug-fix

#28478 Jotform: Add a reachability check to api.jotform.com
  apps/src/sites/studio/pages/jotformLoader.js
Labels: professional-learning

#28450 Increase test coverage for user menu
  dashboard/test/integration/user_menu_test.rb
Labels: testing

#28553 Move continue button below video in external levels
  dashboard/app/assets/stylesheets/application.scss
  dashboard/app/views/levels/_external.html.haml
Labels: levelbuilder-improvements

#28296 Scholarship info course validations
  dashboard/app/models/pd/scholarship_info.rb
  dashboard/db/migrate/20190430234600_scholarship_info_course_cannot_be_null.rb
  dashboard/db/migrate/20190504203007_change_scholarship_info_unique_constraints.rb
  dashboard/db/schema.rb
  dashboard/test/models/pd/scholarship_info_test.rb
Labels: professional-learning

#28534 remove puzzles completed columns
  apps/src/code-studio/pd/workshop_dashboard/attendance/session_attendance.jsx
  apps/src/code-studio/pd/workshop_dashboard/attendance/session_attendance_row.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/attendance/session_attendance_row_test.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/attendance/session_attendance_test.jsx
  dashboard/app/serializers/api/v1/pd/session_attendance_serializer.rb
Labels: professional-learning

#28503 Csf enrollment scholarship
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_enrollment.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_enrollment_school_info.jsx
  apps/src/code-studio/pd/workshop_dashboard/workshop.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/components/workshop_enrollment_school_infoTest.js
  dashboard/app/models/pd/enrollment.rb
  dashboard/app/models/pd/scholarship_info.rb
  dashboard/app/models/pd/workshop.rb
  dashboard/app/serializers/api/v1/pd/workshop_serializer.rb
  dashboard/test/models/pd/enrollment_test.rb
  dashboard/test/models/pd/scholarship_info_test.rb
Labels: professional-learning

#28537 remove code studio account column from ws db
  apps/src/code-studio/pd/workshop_dashboard/attendance/session_attendance.jsx
  apps/src/code-studio/pd/workshop_dashboard/attendance/session_attendance_row.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_enrollment_school_info.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/attendance/session_attendance_row_test.jsx
Labels: professional-learning

#28611 Levelbuilder: fix disappearing videos on external levels
  dashboard/app/dsl/content_dsl.rb
  dashboard/app/views/levels/editors/_all.html.haml
Labels: bug-fix, levelbuilder-improvements
