Repository code-dot-org/code-dot-org, pull requests merged in 2019-06, with the labels that each got.

#28900 Language-specific profanity filtering
  lib/cdo/profanity_filter.rb
  lib/cdo/share_filtering.rb
  lib/test/cdo/test_share_filtering.rb
Labels: learning-platform

#28762 CS Fundamentals PD uses our standard certificates
  apps/src/code-studio/pd/professional_learning_landing/EnrolledWorkshops.jsx
  apps/src/utils.js
  apps/test/unit/code-studio/pd/professional_learning_landing/EnrolledWorkshopsTest.jsx
  dashboard/app/assets/images/pd_workshop_certificate_csf.png
  dashboard/app/controllers/pd/csf_certificate_controller.rb
  dashboard/app/controllers/pd/workshop_certificate_controller.rb
  dashboard/app/mailers/pd/workshop_mailer.rb
  dashboard/app/models/pd/workshop.rb
  dashboard/app/models/pd/workshop_constants.rb
  dashboard/lib/pd/certificate_renderer.rb
  dashboard/test/controllers/pd/csf_certificate_controller_test.rb
  dashboard/test/controllers/pd/workshop_certificate_controller_test.rb
  dashboard/test/lib/pd/payment/payment_calculator_base_test.rb
  dashboard/test/models/pd/workshop_test.rb
Labels: professional-learning

#29125 Tests: Make SectionProjectsListTest Enzyme-3-ready
  apps/test/unit/templates/projects/SectionProjectsListTest.js
Labels: testing

#29154 Testing: Make StageDescriptionsTest enzyme 3 ready
  apps/test/unit/lib/script-editor/StageDescriptionsTest.js
Labels: testing

#29157 Tests: Make PopUpMenuTest enzyme 3 ready
  apps/test/unit/lib/ui/PopUpMenuTest.js
Labels: testing

#29156 Tests: Make BubbleChoiceTest enzyme 3 ready
  apps/test/unit/code-studio/components/BubbleChoiceTest.js
Labels: testing

#29138 Testing: Make VersionHistoryTest Enzyme 3 ready
  apps/test/unit/templates/VersionHistoryTest.jsx
Labels: testing

#29155 Tests: Make ImageWithStatusTest enzyme 3 ready
  apps/test/unit/templates/ImageWithStatusTest.js
Labels: testing

#29151 Tests: Make CertificateTest enzyme 3 ready and fix minecraft certificate bug
  apps/src/templates/Certificate.jsx
  apps/src/templates/Congrats.jsx
  apps/test/unit/templates/CertificateTest.js
Labels: testing

#29183 Tests: Make FormControllerTest enzyme 3 ready
  apps/test/unit/code-studio/pd/form_components/FormControllerTest.js
Labels: testing

#29184 Tests: Make workshop dashboard tests ready for enzyme 3
  apps/test/unit/code-studio/pd/workshop_dashboard/attendance/session_attendance_test.jsx
  apps/test/unit/code-studio/pd/workshop_dashboard/components/local_summer_workshop_survey_resultsTest.js
Labels: testing

#29241 Tests: PeerReviewSubmissionsTest is ready for enzyme 3
  apps/test/unit/code-studio/peer_reviews/PeerReviewSubmissionsTest.jsx
Labels: testing

#29225 Testing: filterGroupContainerTest.jsx uses reconfiguredChai
  apps/test/unit/tutorialExplorer/filterGroupContainerTest.jsx
Labels: testing

#29227 Testing: ImageTest is ready for enzyme 3
  apps/test/unit/tutorialExplorer/imageTest.jsx
Labels: testing

#29221 Testing: Make instructionsComponentsTest.js ready for Enzyme 3
  apps/test/unit/instructionsComponentsTest.js
Labels: testing

#29246 Tests: SchoolInfoConfirmationDialogTest is ready for enzyme 3
  apps/test/unit/lib/ui/SchoolInfoConfirmationDialogTest.js
Labels: testing

#29247 Tests: Use reconfiguredChai in more places
  apps/test/unit/lib/script-editor/ScriptAnnouncementsEditorTests.js
  apps/test/unit/lib/ui/SchoolInfoInterstitialTest.jsx
  apps/test/unit/lib/ui/SettingsCogTest.js
  apps/test/unit/lib/ui/SyncOmniAuthSectionControlTest.jsx
  apps/test/unit/lib/ui/ValidationStepTest.js
  apps/test/unit/lib/ui/WireframeButtonsTest.jsx
  apps/test/unit/lib/util/audioApiTest.js
  apps/test/unit/lib/util/timeoutApiTest.js
  apps/test/unit/lib/util/timeoutListTest.js
  apps/test/unit/lib/util/urlHelpersTest.js
  apps/test/unit/redux/feedbackTest.js
  apps/test/unit/redux/layoutTest.js
  apps/test/unit/redux/scriptSelectionReduxTest.js
  apps/test/unit/redux/sectionDataReduxTest.js
  apps/test/unit/redux/watchedExpressionsTest.js
  apps/test/unit/sites/studio/pages/levelbuilder_edit_script.js
  apps/test/unit/sites/studio/pages/signupTest.js
  apps/test/unit/storage/FirebaseStorageTest.js
  apps/test/unit/storage/MockFirebaseTest.js
  apps/test/unit/storage/dataUtilsTest.js
  apps/test/unit/storage/firebaseMetadataTest.js
  apps/test/unit/storage/firebaseUtilsTest.js
  apps/test/unit/tutorialExplorer/backButtonTest.jsx
  apps/test/unit/tutorialExplorer/filterChoiceTest.jsx
  apps/test/unit/tutorialExplorer/filterGroupHeaderSelectionTest.jsx
  apps/test/unit/tutorialExplorer/filterGroupOrgNamesTest.jsx
  apps/test/unit/tutorialExplorer/filterGroupSortByTest.jsx
  apps/test/unit/tutorialExplorer/filterGroupTest.jsx
  apps/test/unit/tutorialExplorer/filterHeaderTest.jsx
  apps/test/unit/tutorialExplorer/filterSetTest.jsx
  apps/test/unit/tutorialExplorer/roboticsButtonTest.jsx
  apps/test/unit/tutorialExplorer/toggleAllTutorialsButtonTest.jsx
  apps/test/unit/tutorialExplorer/tutorialSetTest.jsx
  apps/test/unit/tutorialExplorer/tutorialTest.jsx
  apps/test/unit/util/getScriptDataTest.js
  apps/test/unit/util/imageUtilsTest.js
  apps/test/unit/util/thumbnailTest.js
  apps/test/util/netsimTestUtils.js
Labels: code-hygiene, testing

#29233 Remove FacilitatorProgramRegistrationController
  apps/Gruntfile.js
  apps/src/code-studio/pd/facilitator_program_registration/DateConfirm.jsx
  apps/src/code-studio/pd/facilitator_program_registration/Demographics.jsx
  apps/src/code-studio/pd/facilitator_program_registration/FacilitatorProgramRegistration.jsx
  apps/src/code-studio/pd/facilitator_program_registration/TravelInformation.jsx
  apps/src/sites/studio/pages/pd/facilitator_program_registration/new.js
  apps/test/unit/facilitatorProgramRegistrationTest.js
  dashboard/app/controllers/api/v1/pd/facilitator_program_registrations_controller.rb
  dashboard/app/controllers/pd/facilitator_program_registration_controller.rb
  dashboard/app/models/pd/facilitator_program_registration.rb
  dashboard/app/views/pd/facilitator_program_registration/new.html.haml
  dashboard/app/views/pd/facilitator_program_registration/not_attending.html.haml
  dashboard/app/views/pd/facilitator_program_registration/submitted.html.haml
  dashboard/app/views/pd/facilitator_program_registration/unauthorized.html.haml
  dashboard/config/routes.rb
  dashboard/test/controllers/api/v1/pd/facilitator_program_registrations_controller_test.rb
  dashboard/test/controllers/pd/facilitator_program_registration_controller_test.rb
Labels: code-hygiene, professional-learning

#29235 Remove RegionalPartnerProgramRegistrationController
  apps/Gruntfile.js
  apps/src/code-studio/pd/program_registration/LiabilityWaiver.jsx
  apps/src/code-studio/pd/program_registration/PhotoRelease.jsx
  apps/src/code-studio/pd/regional_partner_program_registration/DateConfirm.jsx
  apps/src/code-studio/pd/regional_partner_program_registration/RegionalPartnerProgramRegistration.jsx
  apps/src/code-studio/pd/regional_partner_program_registration/TravelInformation.jsx
  apps/src/sites/studio/pages/pd/regional_partner_program_registration/new.js
  dashboard/app/controllers/api/v1/pd/regional_partner_program_registrations_controller.rb
  dashboard/app/controllers/pd/regional_partner_program_registration_controller.rb
  dashboard/app/models/pd/regional_partner_program_registration.rb
  dashboard/app/views/pd/regional_partner_program_registration/new.html.haml
  dashboard/config/routes.rb
Labels: code-hygiene, professional-learning

#29259 Prevent this/other sprite from crashing project when used outside scope
  dashboard/config/libraries/GameLabJr.interpreted.js
  dashboard/config/libraries/NativeSpriteLab.interpreted.js
  dashboard/config/libraries/SpriteLab2Beta.interpreted.js
Labels: star-labs

#29268 Sprite Lab event tests
  apps/test/unit/gamelab/spritelab/spriteUtilsTest.js
Labels: star-labs

#29257 I18n sync In & Up 06/20
  dashboard/config/locales/blocks.en.yml
  dashboard/config/locales/dsls.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/gamelab.json
  i18n/locales/source/course_content/2017/csd2-2017.json
  i18n/locales/source/course_content/2017/csd3-2017.json
  i18n/locales/source/course_content/2018/csd3-2018.json
  i18n/locales/source/course_content/2018/csd6-2018.json
  i18n/locales/source/course_content/2019/coursee-2019.json
  i18n/locales/source/course_content/2019/coursef-2019.json
  i18n/locales/source/course_content/2019/csd3-2019.json
  i18n/locales/source/course_content/2019/csd6-2019.json
  i18n/locales/source/course_content/2019/express-2019.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/dsls.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#29301 Mailer: Change Anthonette to Liz on application emails
  dashboard/app/mailers/pd/application/teacher1920_application_mailer.rb
  dashboard/app/views/pd/application/teacher1920_application_mailer/_partner_signature.html.haml
  dashboard/app/views/pd/application/teacher1920_application_mailer/confirmation.html.haml
  dashboard/app/views/pd/application/teacher1920_application_mailer/principal_approval_completed_partner.html.haml
Labels: professional-learning

#29284 Add firehose logging for duplicate and delete events in applab design mode
  apps/src/applab/designMode.js
Labels: star-labs

#29315 Clear text display for preview
  apps/src/gamelab/GameLab.js
Labels: star-labs

#29320 I18n sync In & Up 06/24
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2019/coursec-2019.json
  i18n/locales/source/course_content/2019/csd3-2019.json
  i18n/locales/source/course_content/2019/express-2019.json
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#29266 Upgrade Enzyme to version 3
  apps/Gruntfile.js
  apps/package.json
  apps/src/lib/tools/jsdebugger/JsDebugger.jsx
  apps/src/templates/instructions/TopInstructions.jsx
  apps/test/storybook/renderStoriesTest.js
  apps/test/unit-tests.js
  apps/test/unit/code-studio/components/header/EditableProjectNameTest.js
  apps/test/unit/lib/tools/jsdebugger/DebugConsoleTest.js
  apps/test/unit/lib/tools/jsdebugger/JsDebuggerTest.js
  apps/test/unit/lib/ui/VisualizationResizeBarTest.jsx
  apps/yarn.lock
Labels: star-labs

#29209 Updated VisualizationResizeBarTest to be compatible with Enzyme 3
  apps/test/unit/lib/ui/VisualizationResizeBarTest.jsx
Labels: star-labs

#28402 Applab themes experiment now only hides UI to switch themes, add unit tests
  apps/src/applab/commands.js
  apps/src/applab/designElements/button.jsx
  apps/src/applab/designElements/dropdown.jsx
  apps/src/applab/designElements/elementUtils.js
  apps/src/applab/designElements/label.jsx
  apps/src/applab/designElements/library.js
  apps/src/applab/designElements/screen.jsx
  apps/src/applab/designElements/textInput.jsx
  apps/src/applab/designElements/textarea.jsx
  apps/src/applab/designMode.js
  apps/src/applab/gridUtils.js
  apps/src/applab/themeColor.js
  apps/test/integration/levelSolutions/applab/ec_screens.js
  apps/test/unit/applab/designElements/elementThemesTest.js
  apps/test/unit/applab/designModeTest.js
  apps/test/unit/applab/designModeThemesTest.js
  apps/test/util/testUtils.js
Labels: star-labs

#29308 Email: Send Poste activity metrics to New Relic
  bin/cron/deliver_poste_messages
Labels: professional-learning

#29312 Added tests for sprite lab text console react component
  apps/test/unit/gamelab/reducersTest.js
  apps/test/unit/gamelab/spritelab/TextConsoleTest.js
Labels: star-labs

#29280 Cleanup: Add isSpritelab property to Gamelab
  apps/src/gamelab/GameLab.js
Labels: star-labs

#29339 Add new backgrounds to animation library
  apps/src/gamelab/animationLibrary.json
Labels: star-labs

#29343 Use VerifiedResourcesNotification in ScriptOverviewHeader
  apps/src/code-studio/components/progress/ScriptOverviewHeader.jsx
  apps/test/unit/code-studio/components/progress/ScriptOverviewHeaderTest.js
Labels: code-hygiene

#29300 Use the same worker base class and context object
  apps/src/code-studio/pd/workshop_dashboard/reports/local_summer_workshop_daily_survey/results_loader.jsx
  dashboard/app/controllers/api/v1/pd/workshop_survey_report_controller.rb
  dashboard/lib/pd/survey_pipeline/daily_survey_decorator.rb
  dashboard/lib/pd/survey_pipeline/daily_survey_joiner.rb
  dashboard/lib/pd/survey_pipeline/daily_survey_parser.rb
  dashboard/lib/pd/survey_pipeline/daily_survey_retriever.rb
  dashboard/lib/pd/survey_pipeline/decorator.rb
  dashboard/lib/pd/survey_pipeline/mapper.rb
  dashboard/lib/pd/survey_pipeline/retriever.rb
  dashboard/lib/pd/survey_pipeline/survey_pipeline_worker.rb
  dashboard/lib/pd/survey_pipeline/transformer.rb
  dashboard/test/lib/pd/survey_pipeline/daily_survey_decorator_test.rb
  dashboard/test/lib/pd/survey_pipeline/daily_survey_joiner_test.rb
  dashboard/test/lib/pd/survey_pipeline/daily_survey_parser_test.rb
  dashboard/test/lib/pd/survey_pipeline/daily_survey_retriever_test.rb
  dashboard/test/lib/pd/survey_pipeline/mapper_test.rb
  dashboard/test/lib/pd/survey_pipeline/survey_pipeline_worker_test.rb
Labels: survey-pipeline

#29310 Applab: Design Mode Apply Theme button (on an element)
  apps/src/applab/DesignModeBox.jsx
  apps/src/applab/DesignWorkspace.jsx
  apps/src/applab/designElements/RestoreThemeDefaultsButton.jsx
  apps/src/applab/designElements/button.jsx
  apps/src/applab/designElements/screen.jsx
  apps/src/applab/designMode.js
  apps/src/applab/designProperties.jsx
  apps/test/unit/applab/designModeThemesTest.js
Labels: star-labs

#29381 Revert library prototype
  apps/src/applab/applab.js
  apps/src/blockTooltips/DropletFunctionTooltip.html.ejs
  apps/src/blockTooltips/DropletFunctionTooltip.js
  apps/src/code-studio/assets/show.js
  apps/src/code-studio/components/AdvancedShareOptions.jsx
  apps/src/code-studio/components/LibraryPicker.jsx
  apps/src/code-studio/components/PublishLibraryDialog.jsx
  apps/src/code-studio/components/ShareAllowedDialog.jsx
  apps/src/code-studio/components/ShareAllowedDialog.story.jsx
  apps/src/code-studio/components/applabLibraryRedux.jsx
  apps/src/code-studio/components/libraryShareDialogRedux.js
  apps/src/code-studio/headerShare.js
  apps/src/code-studio/initApp/loadApp.js
  apps/src/code-studio/initApp/project.js
  apps/src/code-studio/redux.js
  apps/src/code-studio/sampleApplabLibrary.json
  apps/src/lib/tools/jsinterpreter/JSInterpreter.js
  apps/src/lib/ui/SettingsCog.jsx
  apps/test/unit/code-studio/initApp/projectTest.js
  config.yml.erb
  cookbooks/cdo-varnish/libraries/http_cache.rb
  dashboard/app/models/levels/applab.rb
  dashboard/app/views/levels/editors/_applab.html.haml
  shared/middleware/files_api.rb
  shared/middleware/helpers/librarypilot_bucket.rb
Labels: star-labs

#29374 Check condition before adding event
  apps/src/gamelab/spritelab/eventCommands.js
Labels: star-labs

#29364 Remove preview options from level edit page
  dashboard/app/views/levels/editors/_gamelab.html.haml
Labels: star-labs

#29366 Always show preview in spritelab
  apps/src/gamelab/GameLab.js
Labels: star-labs

#29389 Detect Maker Type Refactor
  apps/src/lib/kits/maker/CircuitPlaygroundBoard.js
  apps/src/lib/kits/maker/toolkit.js
  apps/src/lib/kits/maker/util/SetupChecker.js
  apps/test/unit/lib/kits/maker/CircuitPlaygroundBoardTest.js
Labels: star-labs

#29379 Revert dataset prototype
  apps/i18n/common/en_us.json
  apps/src/applab/api.js
  apps/src/applab/commands.js
  apps/src/applab/dropletConfig.js
  apps/src/applab/getListDropdown.js
  apps/src/code-studio/assets/show.js
  apps/src/code-studio/components/DatasetListEntry.jsx
  apps/src/code-studio/components/DatasetPicker.jsx
  apps/src/code-studio/datasetLibrary.json
  apps/src/storage/firebaseStorage.js
  apps/test/unit/applab/getListDropdownTest.js
  apps/test/unit/code-studio/components/DatasetPickerTest.js
  apps/test/unit/storage/FirebaseStorageTest.js
  cookbooks/cdo-varnish/libraries/http_cache.rb
  dashboard/config/application.rb
  shared/middleware/dataset_library_api.rb
Labels: star-labs

#29358 Preload Sprite Lab background images
  apps/src/gamelab/GameLab.js
  apps/src/gamelab/GameLabP5.js
  apps/src/gamelab/spritelab/backgrounds.json
  apps/src/gamelab/spritelab/worldCommands.js
Labels: star-labs

#29406 Disallow mailto redirect
  apps/i18n/common/en_us.json
  apps/src/applab/ExternalRedirectDialog.jsx
  apps/src/applab/ExternalRedirectDialog.story.jsx
  apps/src/applab/commands.js
  apps/src/applab/redux/applab.js
  apps/test/unit/applab/redux/applabTest.js
Labels: star-labs

#29407 Close the redirect dialog after you follow the redirect
  apps/src/applab/ExternalRedirectDialog.jsx
Labels: star-labs

#29395 JS errors from malformed project html no longer disable the Start Over button.
  apps/src/applab/designElements/library.js
  apps/src/applab/designMode.js
Labels: star-labs

#29421 Updated BorderProperties to use prop-types package
  apps/src/applab/designElements/BorderProperties.jsx
Labels: star-labs
