Repository code-dot-org/code-dot-org, pull requests merged in 2019-08, with the labels that each got.

#30049 School Info Completeness: Change from nces school type to non-nces school type
  apps/src/lib/ui/SchoolInfoInterstitial.jsx
  apps/test/unit/lib/ui/SchoolInfoInterstitialTest.jsx
Labels: bug-fix

#30083 Peer Reviews: Instructor feedback is visually differentiated
  dashboard/app/assets/stylesheets/application.scss
  dashboard/app/models/peer_review.rb
  dashboard/app/views/peer_reviews/_viewer.html.haml
  dashboard/app/views/peer_reviews/show.html.haml
Labels: professional-learning

#30059 Peer Review Dashboard: Require instructors to select a status before submit
  apps/src/sites/studio/pages/peer_reviews/show.js
  dashboard/app/controllers/peer_reviews_controller.rb
  dashboard/app/models/peer_review.rb
  dashboard/app/views/peer_reviews/show.html.haml
  dashboard/test/controllers/peer_reviews_controller_test.rb
Labels: professional-learning

#30038 Applab export: remove extractCSSFromHTML
  apps/src/applab/Exporter.js
  apps/test/unit/applab/ExporterTest.js
Labels: star-labs

#30061 [Widget Mode] Create extra-width mode that levelbuilders can use to create widgets
  apps/src/applab/ApplabVisualizationColumn.jsx
  apps/src/applab/ApplabVisualizationColumn.story.jsx
  apps/src/applab/PhoneFrame.jsx
  apps/src/applab/Visualization.jsx
  apps/src/applab/applab.js
  apps/src/applab/constants.js
  apps/src/applab/designElements/screen.jsx
  apps/src/lib/ui/VisualizationResizeBar.jsx
  apps/src/redux/pageConstants.js
  apps/src/templates/VisualizationOverlay.jsx
  apps/src/templates/instructions/TopInstructions.jsx
  apps/style/applab/style.scss
  apps/test/integration/levelSolutions/applab/cspunit3.js
  apps/test/unit/applab/ExporterTest.js
  dashboard/app/models/levels/applab.rb
  dashboard/app/views/levels/editors/_applab.html.haml
Labels: star-labs

#30096 Peer reviews: Include first and last submission dates in CSV
  dashboard/app/controllers/api/v1/peer_review_submissions_controller.rb
  dashboard/test/controllers/api/v1/peer_review_submissions_controller_test.rb
  dashboard/test/factories/plc_factories.rb
  dashboard/test/models/peer_review_test.rb
Labels: professional-learning

#30108 Tests: Remove unused UI test steps
  dashboard/test/ui/features/step_definitions/pd.rb
Labels: UI Testing, code-hygiene, professional-learning, testing

#30086 Export: Use official snack-sdk package and new snack-build package
  apps/package.json
  apps/src/applab/Exporter.js
  apps/src/p5lab/gamelab/Exporter.js
  apps/src/util/exporter.js
  apps/yarn.lock
Labels: star-labs

#29839 [Netsim] Always show wire state in simplex mode
  apps/src/netsim/NetSimLocalClientNode.js
  apps/src/netsim/NetSimVisualization.js
  apps/src/netsim/NetSimVizWire.js
  apps/test/unit/netsim/NetSimRouterNode.js
Labels: star-labs

#30106 Testing: Isolate workshop factories
  dashboard/test/controllers/api/v1/pd/applications_controller_test.rb
  dashboard/test/controllers/api/v1/pd/regional_partner_workshops_controller_test.rb
  dashboard/test/controllers/api/v1/pd/teacher_attendance_report_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshop_attendance_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshop_enrollments_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshop_summary_report_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshop_survey_report_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshops_controller_test.rb
  dashboard/test/controllers/pd/pre_workshop_survey_controller_test.rb
  dashboard/test/controllers/pd/professional_learning_landing_controller_test.rb
  dashboard/test/controllers/pd/session_attendance_controller_test.rb
  dashboard/test/controllers/pd/workshop_certificate_controller_test.rb
  dashboard/test/controllers/pd/workshop_daily_survey_controller_test.rb
  dashboard/test/controllers/pd/workshop_enrollment_controller_test.rb
  dashboard/test/factories/factories.rb
  dashboard/test/factories/pd_factories.rb
  dashboard/test/factories/workshops.rb
  dashboard/test/helpers/pd/application/pd_workshop_helper_test.rb
  dashboard/test/helpers/pd/find_related_workshops_helper_test.rb
  dashboard/test/helpers/pd/workshop_survey_results_helper_test.rb
  dashboard/test/lib/api/v1/pd/workshop_score_summarizer_test.rb
  dashboard/test/lib/pd/application/regional_partner_teachercon_mapping_test.rb
  dashboard/test/lib/pd/payment/payment_calculator_test.rb
  dashboard/test/lib/pd/survey_pipeline/daily_survey_decorator_test.rb
  dashboard/test/lib/pd/survey_pipeline/daily_survey_parser_test.rb
  dashboard/test/lib/pd/survey_pipeline/daily_survey_retriever_test.rb
  dashboard/test/mailers/pd/workshop_mailer_test.rb
  dashboard/test/mailers/previews/pd_fit_weekend_registration_mailer_preview.rb
  dashboard/test/mailers/previews/pd_teacher1920_application_mailer_preview.rb
  dashboard/test/mailers/previews/pd_workshop_mailer_preview.rb
  dashboard/test/models/circuit_playground_discount_application_test.rb
  dashboard/test/models/pd/application/facilitator1819_application_test.rb
  dashboard/test/models/pd/application/facilitator1920_application_test.rb
  dashboard/test/models/pd/application/teacher1819_application_test.rb
  dashboard/test/models/pd/application/teacher1920_application_test.rb
  dashboard/test/models/pd/attendance_test.rb
  dashboard/test/models/pd/enrollment_test.rb
  dashboard/test/models/pd/payment_term_test.rb
  dashboard/test/models/pd/regional_partner_program_manager_test.rb
  dashboard/test/models/pd/session_test.rb
  dashboard/test/models/pd/teachercon_survey_test.rb
  dashboard/test/models/pd/workshop_daily_survey_test.rb
  dashboard/test/models/pd/workshop_facilitator_daily_survey_test.rb
  dashboard/test/models/pd/workshop_survey_test.rb
  dashboard/test/models/pd/workshop_test.rb
  dashboard/test/models/regional_partner_test.rb
  dashboard/test/serializers/api/v1/pd/enrollment_flat_attendance_serializer_test.rb
  dashboard/test/serializers/api/v1/pd/session_attendance_serializer_test.rb
  dashboard/test/serializers/api/v1/pd/workshop_enrollment_serializer_test.rb
  dashboard/test/ui/features/step_definitions/pd.rb
Labels: testing

#30112 Make peer review feedback colors WCAG2.0-compliant
  dashboard/app/assets/stylesheets/application.scss
Labels: professional-learning, ui-style

#30120 I18n sync In & Up 08/05
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2017/coursea-2017.json
  i18n/locales/source/course_content/2017/courseb-2017.json
  i18n/locales/source/course_content/2017/coursec-2017.json
  i18n/locales/source/course_content/2017/coursed-2017.json
  i18n/locales/source/course_content/2017/coursee-2017.json
  i18n/locales/source/course_content/2017/coursef-2017.json
  i18n/locales/source/course_content/2017/express-2017.json
  i18n/locales/source/course_content/2017/pre-express-2017.json
  i18n/locales/source/course_content/2018/coursea-2018.json
  i18n/locales/source/course_content/2018/courseb-2018.json
  i18n/locales/source/course_content/2018/coursec-2018.json
  i18n/locales/source/course_content/2018/coursed-2018.json
  i18n/locales/source/course_content/2018/coursee-2018.json
  i18n/locales/source/course_content/2018/coursef-2018.json
  i18n/locales/source/course_content/2018/express-2018.json
  i18n/locales/source/course_content/2018/pre-express-2018.json
  i18n/locales/source/course_content/2019/coursea-2019.json
  i18n/locales/source/course_content/2019/courseb-2019.json
  i18n/locales/source/course_content/2019/coursec-2019.json
  i18n/locales/source/course_content/2019/coursed-2019.json
  i18n/locales/source/course_content/2019/coursee-2019.json
  i18n/locales/source/course_content/2019/coursef-2019.json
  i18n/locales/source/course_content/2019/express-2019.json
  i18n/locales/source/course_content/2019/pre-express-2019.json
  i18n/locales/source/course_content/Hour of Code/dance.json
  i18n/locales/source/course_content/Hour of Code/hero.json
  i18n/locales/source/course_content/Hour of Code/minecraft.json
  i18n/locales/source/course_content/other/K5-OnlinePD.json
  i18n/locales/source/course_content/other/course1.json
  i18n/locales/source/course_content/other/course2.json
  i18n/locales/source/course_content/other/course3.json
  i18n/locales/source/course_content/other/course4.json
  i18n/locales/source/course_content/other/k1hoc2017.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#29906 Preload and persist Sprite Images
  apps/src/p5lab/P5Lab.js
  apps/src/p5lab/gamelab/GameLabP5.js
Labels: star-labs

#30160 De-flaked eyes test by moving functionality to UI test
  dashboard/test/ui/features/applab/eyes1.feature
  dashboard/test/ui/features/projects/project_sharing.feature
Labels: star-labs

#30127 [Widget Mode] Disabled code workspace and code/design/data mode on widget levels
  apps/src/applab/applab.js
  dashboard/app/helpers/levels_helper.rb
  dashboard/app/views/levels/editors/_applab.html.haml
Labels: star-labs

#30138 [Widget Mode] Updated widget mode to auto-run on page load.
  apps/src/StudioApp.js
  apps/src/applab/PhoneFrame.jsx
  apps/src/applab/applab.js
Labels: star-labs

#30044 Separate gamelab, spritelab, and shared constants
  apps/src/code-studio/components/ShareAllowedDialog.jsx
  apps/src/p5lab/AnimationPicker/AnimationPickerBody.jsx
  apps/src/p5lab/AnimationPicker/animationPickerModule.js
  apps/src/p5lab/GameLabView.jsx
  apps/src/p5lab/GameLabVisualizationColumn.jsx
  apps/src/p5lab/GameLabVisualizationHeader.jsx
  apps/src/p5lab/P5Lab.js
  apps/src/p5lab/actions.js
  apps/src/p5lab/constants.js
  apps/src/p5lab/gamelab/Exporter.js
  apps/src/p5lab/gamelab/MobileControls.js
  apps/src/p5lab/gamelab/constants.js
  apps/src/p5lab/reducers.js
  apps/src/p5lab/spritelab/blocks.js
  apps/src/p5lab/spritelab/constants.js
  apps/src/p5lab/spritelab/locationPickerModule.js
  apps/test/unit/p5lab/reducersTest.js
Labels: star-labs

#30176 [Widget Mode] Refactor phone frame logic
  apps/src/applab/ApplabVisualizationColumn.jsx
  apps/src/applab/PhoneFrame.jsx
  apps/src/applab/applab.js
  apps/src/templates/GameButtons.jsx
Labels: star-labs

#30115 Export dialog: add iOS to UI flow
  apps/src/code-studio/components/ExportDialog/Dialog.jsx
  apps/src/code-studio/components/ExportDialog/GeneratingPage.jsx
  apps/src/code-studio/components/ExportDialog/PlatformPage.jsx
  apps/src/code-studio/components/ExportDialog/PublishAndroidPage.jsx
  apps/src/code-studio/components/ExportDialog/PublishIOSPage.jsx
  apps/src/util/exporter.js
Labels: star-labs

#30229 Prevent invalid urls from causing 500 errors in safe browsing API
  lib/cdo/safe_browsing.rb
Labels: star-labs

#30221 [Cleanup] Remove unused parameter to getDatabase()
  apps/src/applab/applab.js
Labels: star-labs

#30198 [Widget Mode] Add unit and eyes tests
  apps/src/applab/ApplabVisualizationColumn.jsx
  apps/src/applab/Visualization.jsx
  apps/test/unit/applab/ApplabVisualizationColumnTest.js
  apps/test/unit/applab/VisualizationTest.js
  dashboard/config/scripts/allthethings.script
  dashboard/config/scripts/levels/Applab allthethings Widget Mode.level
  dashboard/test/ui/features/applab/eyes2.feature
Labels: star-labs

#30217 Tests: Add :in_progress and :ended traits to workshop factory
  dashboard/test/controllers/api/v1/pd/teacher_attendance_report_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshop_summary_report_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshops_controller_test.rb
  dashboard/test/controllers/pd/professional_learning_landing_controller_test.rb
  dashboard/test/controllers/pd/workshop_daily_survey_controller_test.rb
  dashboard/test/factories/workshops.rb
  dashboard/test/helpers/pd/find_related_workshops_helper_test.rb
  dashboard/test/lib/pd/payment/payment_calculator_base_test.rb
  dashboard/test/lib/pd/payment/payment_calculator_counselor_admin_test.rb
  dashboard/test/lib/pd/payment/payment_calculator_csf_test.rb
  dashboard/test/lib/pd/payment/payment_calculator_district_test.rb
  dashboard/test/lib/pd/payment/payment_calculator_standard_test.rb
  dashboard/test/lib/pd/payment/payment_calculator_test.rb
  dashboard/test/lib/pd/payment/payment_calculator_unpaid_test.rb
  dashboard/test/lib/pd/payment/payment_factory_test.rb
  dashboard/test/lib/pd/payment/workshop_summary_test.rb
  dashboard/test/mailers/pd/workshop_mailer_test.rb
  dashboard/test/models/pd/enrollment_test.rb
  dashboard/test/models/pd/session_test.rb
  dashboard/test/models/pd/workshop_test.rb
  dashboard/test/models/regional_partner_test.rb
  dashboard/test/ui/features/step_definitions/pd.rb
Labels: professional-learning, testing

#30240 Tests: Re-enable tests in professional_learning_landing_controller_test
  dashboard/test/controllers/pd/professional_learning_landing_controller_test.rb
Labels: testing

#30184 Show error when table doesn't exist
  apps/src/applab/commands.js
  apps/src/storage/firebaseStorage.js
  apps/test/unit/storage/FirebaseStorageTest.js
  dashboard/config/scripts/levels/Applab allthethings onRecordEvent.level
Labels: star-labs

#30251 Peer Review: Search by submitter name
  apps/src/code-studio/peer_reviews/PeerReviewSubmissions.jsx
  apps/test/unit/code-studio/peer_reviews/PeerReviewSubmissionsTest.jsx
  dashboard/app/controllers/api/v1/peer_review_submissions_controller.rb
  dashboard/test/controllers/api/v1/peer_review_submissions_controller_test.rb
Labels: professional-learning

#30233 Spritelab Fix: toolbox displays on top of block layout when switching out of the costume tab
  apps/src/p5lab/GameLabVisualizationHeader.jsx
  apps/src/p5lab/actions.js
Labels: star-labs

#30255 I18n sync In & Up 08/13
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/gamelab.json
  i18n/locales/source/blockly-mooc/spritelab.json
  i18n/locales/source/course_content/2019/coursea-2019.json
  i18n/locales/source/course_content/2019/courseb-2019.json
  i18n/locales/source/course_content/2019/coursec-2019.json
  i18n/locales/source/course_content/2019/pre-express-2019.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#30277 Sprite Lab: Fix audio in video downloads
  dashboard/config/videos.csv
Labels: bug-fix

#30050 School Info Interstitial: country dropdown bug
  apps/src/templates/CountryAutocompleteDropdown.jsx
  apps/src/templates/SchoolInfoInputs.jsx
Labels: bug-fix

#30281 Realistic workshop factories
  dashboard/test/controllers/api/v1/pd/workshop_survey_report_controller_test.rb
  dashboard/test/controllers/pd/workshop_certificate_controller_test.rb
  dashboard/test/controllers/pd/workshop_daily_survey_controller_test.rb
  dashboard/test/factories/workshops.rb
  dashboard/test/helpers/pd/workshop_survey_results_helper_test.rb
  dashboard/test/lib/pd/payment/payment_calculator_base_test.rb
  dashboard/test/lib/pd/payment/payment_calculator_test.rb
  dashboard/test/lib/pd/payment/payment_factory_test.rb
  dashboard/test/lib/pd/survey_pipeline/daily_survey_decorator_test.rb
  dashboard/test/lib/pd/survey_pipeline/daily_survey_parser_test.rb
  dashboard/test/lib/pd/survey_pipeline/daily_survey_retriever_test.rb
  dashboard/test/mailers/pd/workshop_mailer_test.rb
  dashboard/test/models/pd/enrollment_test.rb
  dashboard/test/models/pd/workshop_daily_survey_test.rb
  dashboard/test/models/pd/workshop_facilitator_daily_survey_test.rb
  dashboard/test/models/pd/workshop_survey_test.rb
  dashboard/test/models/pd/workshop_test.rb
Labels: professional-learning, testing

#30296 More realistic workshop factories
  dashboard/test/controllers/api/v1/pd/applications_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshop_enrollments_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshop_survey_report_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshops_controller_test.rb
  dashboard/test/controllers/pd/workshop_daily_survey_controller_test.rb
  dashboard/test/controllers/pd/workshop_enrollment_controller_test.rb
  dashboard/test/factories/factories.rb
  dashboard/test/factories/workshops.rb
  dashboard/test/helpers/pd/workshop_survey_results_helper_test.rb
  dashboard/test/lib/pd/payment/payment_calculator_base_test.rb
  dashboard/test/lib/pd/survey_pipeline/daily_survey_decorator_test.rb
  dashboard/test/models/circuit_playground_discount_application_test.rb
  dashboard/test/models/pd/application/teacher1920_application_test.rb
  dashboard/test/models/pd/enrollment_test.rb
  dashboard/test/models/pd/workshop_daily_survey_test.rb
  dashboard/test/models/pd/workshop_facilitator_daily_survey_test.rb
  dashboard/test/models/pd/workshop_test.rb
  dashboard/test/serializers/api/v1/pd/workshop_enrollment_serializer_test.rb
  dashboard/test/ui/features/step_definitions/pd.rb
Labels: professional-learning, testing

#30301 Even more realistic workshop factories
  dashboard/test/controllers/api/v1/pd/applications_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshops_controller_test.rb
  dashboard/test/controllers/pd/professional_learning_landing_controller_test.rb
  dashboard/test/factories/workshops.rb
  dashboard/test/lib/pd/payment/payment_calculator_counselor_admin_test.rb
  dashboard/test/lib/pd/payment/payment_factory_test.rb
  dashboard/test/models/pd/application/facilitator1819_application_test.rb
  dashboard/test/models/pd/application/facilitator1920_application_test.rb
  dashboard/test/models/pd/enrollment_test.rb
  dashboard/test/models/pd/workshop_test.rb
Labels: professional-learning, testing

#30312 I18n sync In & Up 08/19
  i18n/locales/source/course_content/2019/coursea-2019.json
  i18n/locales/source/course_content/2019/pre-express-2019.json
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#30337 Zendesk 246444: Added developers.zomato.com to allowlist
  dashboard/app/controllers/xhr_proxy_controller.rb
Labels: star-labs

#30342 Update location before selecting on mobile devices in SpriteLab
  apps/src/p5lab/GameLabVisualizationColumn.jsx
Labels: star-labs

#30289 [Applab Datasets] Add applabDatasets experiment and show "current tables" in data tab
  apps/src/applab/applab.js
  apps/src/storage/firebaseCounters.js
  apps/src/storage/firebaseMetadata.js
  apps/src/storage/firebaseStorage.js
  apps/src/storage/firebaseUtils.js
  apps/src/storage/redux/data.js
  apps/src/util/experiments.js
  apps/test/integration/util/runLevelTest.js
  apps/test/unit/storage/FirebaseStorageTest.js
  apps/test/unit/storage/MockFirebaseTest.js
  apps/test/unit/storage/firebaseMetadataTest.js
Labels: star-labs

#30360 Enabled mp3 recording of audio
  apps/i18n/common/en_us.json
  apps/package.json
  apps/src/code-studio/components/AddAssetButtonRow.jsx
  apps/src/code-studio/components/AudioRecorder.jsx
  apps/webpack.js
  apps/yarn.lock
  shared/middleware/shared_resources.rb
  shared/wasm/vmsg.wasm
Labels: star-labs

#30348 [Applab Datasets] Implement Data Browser Tab UI
  apps/i18n/common/en_us.json
  apps/src/storage/dataBrowser/DataBrowser.jsx
  apps/src/storage/dataBrowser/DataOverview.jsx
Labels: star-labs

#30316 use fullWidth for small screens
  apps/i18n/common/en_us.json
  apps/src/applab/ExternalRedirectDialog.jsx
  apps/src/constants.js
  apps/src/templates/BaseDialog.jsx
Labels: star-labs

#30357 [Applab Datasets] Implement Key Value Tab
  apps/src/storage/dataBrowser/DataBrowser.jsx
  apps/src/storage/dataBrowser/DataOverview.jsx
Labels: star-labs

#30402 Reintroduce mp3 audio recording with fixed UI test
  apps/i18n/common/en_us.json
  apps/package.json
  apps/src/code-studio/components/AddAssetButtonRow.jsx
  apps/src/code-studio/components/AudioRecorder.jsx
  apps/webpack.js
  apps/yarn.lock
  dashboard/test/ui/features/manage_assets.feature
  shared/middleware/shared_resources.rb
  shared/wasm/vmsg.wasm
Labels: star-labs

#30503 Fix pd-workshop-survey contact_id reference
  pegasus/sites.v3/code.org/public/pd-workshop-survey/splat.haml
Labels: professional-learning

#30456 Fixed checkbox clone issue.
  apps/src/applab/designMode.js
Labels: star-labs

#30452 [Applab Datasets] Library tree-view
  apps/src/storage/dataBrowser/DataCategory.jsx
  apps/src/storage/dataBrowser/DataLibraryPane.jsx
Labels: star-labs

#30540 Fixed messaging around widget mode
  dashboard/app/views/levels/editors/_applab.html.haml
Labels: star-labs

#30506 [Sprite Lab][Cleanup] Rename spriteUtils and move commands to spritelab/commands
  apps/src/p5lab/spritelab/SpriteLab.js
  apps/src/p5lab/spritelab/commands.js
  apps/src/p5lab/spritelab/commands/actionCommands.js
  apps/src/p5lab/spritelab/commands/behaviorCommands.js
  apps/src/p5lab/spritelab/commands/eventCommands.js
  apps/src/p5lab/spritelab/commands/locationCommands.js
  apps/src/p5lab/spritelab/commands/spriteCommands.js
  apps/src/p5lab/spritelab/commands/validationCommands.js
  apps/src/p5lab/spritelab/commands/worldCommands.js
  apps/src/p5lab/spritelab/coreLibrary.js
  apps/src/p5lab/spritelab/validationCommands.js
  apps/test/unit/spritelab/actionCommandsTest.js
  apps/test/unit/spritelab/coreLibraryTest.js
  apps/test/unit/spritelab/locationCommandsTest.js
  apps/test/unit/spritelab/spriteCommandsTest.js
Labels: star-labs

#30511 [Cleanup] Rename p5 wrapper files and p5lab react components
  apps/src/p5lab/AnimationTab/AnimationTab.jsx
  apps/src/p5lab/P5GroupWrapper.js
  apps/src/p5lab/P5Lab.js
  apps/src/p5lab/P5LabView.jsx
  apps/src/p5lab/P5LabVisualizationColumn.jsx
  apps/src/p5lab/P5LabVisualizationHeader.jsx
  apps/src/p5lab/P5SpriteWrapper.js
  apps/src/p5lab/P5Wrapper.js
  apps/src/p5lab/gamelab/debugger/replay.js
  apps/src/p5lab/spritelab/SpriteLab.js
  apps/test/unit/gamelab/GameLabTest.js
  apps/test/unit/p5lab/GameLabGroupTest.js
  apps/test/unit/p5lab/GameLabP5Test.js
  apps/test/unit/p5lab/GameLabSpriteTest.js
  apps/test/unit/spritelab/SpritelabTest.js
  apps/test/unit/spritelab/actionCommandsTest.js
  apps/test/unit/spritelab/coreLibraryTest.js
  apps/test/unit/spritelab/locationCommandsTest.js
  apps/test/unit/spritelab/spriteCommandsTest.js
  apps/test/util/gamelab/TestableP5Wrapper.js
Labels: star-labs

#30468 [Applab Datasets] Finish tree structure for Library Pane
  apps/i18n/common/en_us.json
  apps/src/storage/dataBrowser/DataLibraryPane.jsx
  apps/src/storage/dataBrowser/LibraryCategory.jsx
  apps/src/storage/dataBrowser/LibraryTable.jsx
  apps/src/storage/dataBrowser/datasetManifest.json
Labels: star-labs
