Repository code-dot-org/code-dot-org, pull requests merged in 2020-01, with the labels that each got.

#32417 InstructionsWithWorkspace owns the resizer
  apps/src/templates/instructions/HeightResizer.jsx
  apps/src/templates/instructions/InstructionsWithWorkspace.jsx
  apps/src/templates/instructions/TopInstructions.jsx
  apps/test/unit/templates/instructions/InstructionsWithWorkspaceTest.jsx
Labels: code-hygiene, refactor

#32518 SoundsTest passes in ChromeHeadless
  apps/test/unit/SoundsTest.js
Labels: testing

#32519 ProjectHeaderTest passes in ChromeHeadless
  apps/test/unit/templates/projects/ProjectHeaderTest.js
Labels: testing

#32520 ProjectRemixTest passes on ChromeHeadless
  apps/src/code-studio/components/header/ProjectRemix.jsx
  apps/test/unit/code-studio/components/header/ProjectRemixTest.js
Labels: testing

#32522 loadAppTest passes on ChromeHeadless
  apps/test/unit/code-studio/initApp/loadAppTest.js
Labels: testing

#32492 Removed unused shared functions checkbox from dance edit page on levelbuilder
  dashboard/app/views/levels/editors/_dance.html.haml
Labels: star-labs

#32524 imageUtilsTest passes on ChromeHeadless
  apps/test/unit/util/expected-chrome.png
  apps/test/unit/util/expected-phantom.png
  apps/test/unit/util/imageUtilsTest.js
Labels: testing

#32502 Mb temp sensor
  apps/src/lib/kits/maker/MicroBitBoard.js
  apps/src/lib/kits/maker/MicroBitComponents.js
  apps/src/lib/kits/maker/MicroBitConstants.js
  apps/src/lib/kits/maker/PlaygroundComponents.js
  apps/src/lib/kits/maker/Thermometer.js
  apps/src/lib/kits/maker/toolkit.js
Labels: star-labs

#32550 Updated firmata client to handle the uppercase vendorId on Windows devices
  apps/src/third-party/maker/MBFirmataClient.js
Labels: star-labs

#32556 [Data Viz] Fix dropdown display bug
  apps/i18n/common/en_us.json
  apps/src/storage/dataBrowser/dataVisualizer/DropdownField.jsx
  apps/src/storage/dataBrowser/dataVisualizer/VisualizerModal.jsx
Labels: star-labs

#32561 [Datasets] Remove search bar
  apps/src/storage/dataBrowser/DataLibraryPane.jsx
Labels: star-labs

#32575 Update the name of the flag we use for specificity
  apps/src/lib/kits/maker/toolkit.js
  apps/src/util/experiments.js
Labels: star-labs

#32579 Stopped assuming that vendorId always exists when connecting to microbit
  apps/src/third-party/maker/MBFirmataClient.js
Labels: star-labs

#32570 Check for elements lower on the page in courses eyes test
  apps/src/templates/studioHomepages/CourseBlocksTools.jsx
  dashboard/test/ui/features/courses_eyes.feature
Labels: UI Testing

#32480 MicroBit Accelerometer
  apps/src/lib/kits/maker/Accelerometer.js
  apps/src/lib/kits/maker/MicroBitComponents.js
  apps/src/lib/kits/maker/MicroBitConstants.js
  apps/src/lib/kits/maker/toolkit.js
Labels: star-labs

#32106 Use flexbox instead of float:left for tutorial boxes.
  apps/src/templates/studioHomepages/CourseBlocks.jsx
  shared/css/course-blocks.scss
Labels: ui-style

#32384 Update weather script
  apps/src/storage/dataBrowser/datasetManifest.json
  bin/cron/applab_datasets/daily_weather
Labels: star-labs

#32533 Remove 'Create a Behavior/Function' buttons from the toolbox WYSIWYG levelbuilder page
  apps/i18n/common/en_us.json
  apps/src/StudioApp.js
  apps/src/constants.js
  apps/src/dance/blocks.js
  apps/src/p5lab/P5Lab.js
  apps/src/p5lab/spritelab/blocks.js
Labels: star-labs

#32599 [student-libraries] Allow renaming a library when creating/publishing it
  apps/i18n/common/en_us.json
  apps/src/code-studio/components/libraries/LibraryCreationDialog.jsx
  apps/src/code-studio/components/libraries/libraryParser.js
  apps/test/unit/code-studio/components/libraries/LibraryCreationDialogTest.js
  apps/test/unit/code-studio/components/libraries/libraryParserTest.js
Labels: star-labs

#32652 If tableRecords is an object, convert it to an array before parsing
  apps/src/storage/dataBrowser/dataVisualizer/VisualizerModal.jsx
Labels: star-labs

#32642 MicroBit button test
  apps/test/unit/lib/kits/maker/ButtonTest.js
  apps/test/unit/lib/kits/maker/LedTest.js
  apps/test/unit/lib/kits/maker/makeStubBoard.js
Labels: star-labs

#32644 [Applab Datasets] Spotify upload script
  apps/src/storage/dataBrowser/datasetManifest.json
  bin/cron/applab_datasets/spotify
Labels: star-labs

#32646 MicroBit led matrix test
  apps/test/unit/lib/kits/maker/LedMatrixTest.js
  apps/test/unit/lib/kits/maker/makeStubBoard.js
Labels: star-labs

#32663 display null, undefined, "" in Applab Data Table
  apps/src/storage/dataBrowser/dataUtils.js
Labels: star-labs

#32645 Application Dashboard: Show total application count
  apps/src/code-studio/pd/application_dashboard/summary_table.jsx
  apps/test/unit/code-studio/pd/application_dashboard/summary_table_test.jsx
Labels: feature

#32685 Add /api/v1/animation-library/(spritelab|gamelab)/<version_id>/<filename>
  shared/middleware/animation_library_api.rb
  shared/test/fixtures/vcr/animationlibrary/animation_not_found.yml
  shared/test/test_animation_library_api.rb
Labels: star-labs

#32688 Fix error handling on library export
  apps/src/code-studio/components/libraries/LibraryCreationDialog.jsx
  apps/test/unit/code-studio/components/libraries/LibraryCreationDialogTest.js
Labels: star-labs

#32689 Rename voilin to violin in GameLab Animation Library
  apps/src/p5lab/gamelab/animationLibrary.json
  tools/scripts/rebuildAnimationLibraryManifest.rb
Labels: star-labs

#32681 [Applab Datasets] Add missing id column, capitalize table names
  apps/src/storage/dataBrowser/datasetManifest.json
  bin/cron/applab_datasets/spotify
  bin/oneoff/applab_datasets/upload_csv_to_firebase
Labels: star-labs

#32679 Mb Temp Sensor Test
  apps/test/unit/lib/kits/maker/ThermometerTest.js
  apps/test/unit/lib/kits/maker/makeStubBoard.js
Labels: star-labs

#32710 [Sprite Lab] Fix syntax error with location generated code
  apps/src/p5lab/spritelab/blocks.js
Labels: star-labs

#32723 [Star Wars] Change callout text
  apps/i18n/studio/en_us.json
  apps/src/studio/levels.js
Labels: star-labs

#32713 Mb Accelerometer test
  apps/src/lib/kits/maker/Accelerometer.js
  apps/test/unit/lib/kits/maker/AccelerometerTest.js
Labels: star-labs

#32754 Teacher Application Export: Squash Honeybadger error
  bin/cron/teacher_applications_to_gdrive
Labels: bug-fix

#32745 MicroBit board test
  apps/test/unit/lib/kits/maker/MicroBitBoardTest.js
  apps/test/unit/lib/kits/maker/makeStubBoard.js
Labels: star-labs

#32741 Allow .jfif uploads in labs
  apps/src/code-studio/components/ImagePicker.jsx
  shared/middleware/files_api.rb
  shared/test/fixtures/vcr/files/upload_files.yml
  shared/test/test_files.rb
Labels: star-labs

#32759 PLC--Standardize location of ActiveRecord callback functions
  dashboard/app/models/pd/application/application_base.rb
  dashboard/app/models/pd/application/facilitator1819_application.rb
  dashboard/app/models/pd/application/facilitator1920_application.rb
  dashboard/app/models/pd/application/facilitator_application_base.rb
  dashboard/app/models/pd/application/principal_approval1819_application.rb
  dashboard/app/models/pd/application/principal_approval1920_application.rb
  dashboard/app/models/pd/application/principal_approval2021_application.rb
  dashboard/app/models/pd/application/teacher1819_application.rb
  dashboard/app/models/pd/application/teacher1920_application.rb
  dashboard/app/models/pd/application/teacher2021_application.rb
  dashboard/app/models/pd/application/teacher_application_base.rb
  dashboard/app/models/pd/attendance.rb
  dashboard/app/models/pd/course_facilitator.rb
  dashboard/app/models/pd/district_payment_term.rb
  dashboard/app/models/pd/enrollment.rb
  dashboard/app/models/pd/facilitator_program_registration.rb
  dashboard/app/models/pd/facilitator_teachercon_attendance.rb
  dashboard/app/models/pd/fit_weekend1819_registration.rb
  dashboard/app/models/pd/fit_weekend_registration_base.rb
  dashboard/app/models/pd/post_course_survey.rb
  dashboard/app/models/pd/pre_workshop_survey.rb
  dashboard/app/models/pd/regional_partner_cohort.rb
  dashboard/app/models/pd/teachercon1819_registration.rb
  dashboard/app/models/pd/teachercon_survey.rb
  dashboard/app/models/pd/workshop.rb
  dashboard/app/models/pd/workshop_daily_survey.rb
  dashboard/app/models/pd/workshop_facilitator_daily_survey.rb
  dashboard/app/models/pd/workshop_survey.rb
  dashboard/app/models/plc/enrollment_unit_assignment.rb
  dashboard/app/models/plc/learning_module.rb
  dashboard/app/models/plc/task.rb
Labels: code-hygiene

#32551 Fix minimum requirement logic in teacher application
  dashboard/app/models/pd/application/principal_approval2021_application.rb
  dashboard/app/models/pd/application/teacher2021_application.rb
  dashboard/test/models/pd/application/teacher2021_application_test.rb
Labels: bug-fix

#32777 Account Purger: Make Net::ReadTimeout a reason to retry a QueuedAccountPurge
  dashboard/app/models/queued_account_purge.rb
  dashboard/test/models/queued_account_purge_test.rb
Labels: feature

#32693 [Data Viz] Populate filter dropdowns
  apps/src/storage/dataBrowser/dataVisualizer/VisualizerModal.jsx
  apps/test/unit/storage/dataBrowser/dataVisualizer/VisualizerModalTest.js
Labels: star-labs

#32792 [student-libraries] Refactor the library creation dialog in preparation for adding 'unpublish' functionality
  apps/i18n/common/en_us.json
  apps/src/code-studio/components/ShareAllowedDialog.jsx
  apps/src/code-studio/components/libraries/LibraryCreationDialog.jsx
  apps/src/code-studio/components/libraries/LibraryPublisher.jsx
  apps/src/code-studio/components/libraries/libraryLoader.js
  apps/test/unit/code-studio/components/libraries/LibraryCreationDialogTest.js
  apps/test/unit/code-studio/components/libraries/LibraryPublisherTest.js
  apps/test/unit/code-studio/components/libraries/libraryLoaderTest.js
Labels: star-labs

#32824 Display spinner/error on library import failure
  apps/i18n/common/en_us.json
  apps/src/code-studio/components/libraries/LibraryManagerDialog.jsx
  apps/test/unit/code-studio/components/libraries/libraryManagerDialogTest.js
Labels: star-labs

#32818 [DataViz] Implement exact-match filter
  apps/src/storage/dataBrowser/dataVisualizer/VisualizerModal.jsx
  apps/test/unit/storage/dataBrowser/dataVisualizer/VisualizerModalTest.js
Labels: star-labs

#32716 [student-libraries] Add ability for students to unpublish a library they have shared
  apps/i18n/common/en_us.json
  apps/src/code-studio/components/ShareAllowedDialog.jsx
  apps/src/code-studio/components/libraries/LibraryClientApi.js
  apps/src/code-studio/components/libraries/LibraryCreationDialog.jsx
  apps/src/code-studio/components/libraries/LibraryListItem.jsx
  apps/src/code-studio/components/libraries/LibraryPublisher.jsx
  apps/src/code-studio/components/libraries/PublishSuccessDisplay.jsx
  apps/src/code-studio/components/libraries/libraryLoader.js
  apps/src/code-studio/initApp/clientApi.js
  apps/src/code-studio/initApp/project.js
  apps/test/unit/code-studio/components/libraries/LibraryCreationDialogTest.js
  apps/test/unit/code-studio/components/libraries/LibraryPublisherTest.js
  apps/test/unit/code-studio/components/libraries/PublishSuccessDisplayTest.js
  apps/test/unit/code-studio/components/libraries/libraryLoaderTest.js
Labels: star-labs

#32860 I18n sync In & Up 01/24
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/fish.json
  i18n/locales/source/blockly-mooc/studio.json
  i18n/locales/source/course_content/2017/coursec-2017.json
  i18n/locales/source/course_content/2017/coursed-2017.json
  i18n/locales/source/course_content/2017/coursee-2017.json
  i18n/locales/source/course_content/2017/coursef-2017.json
  i18n/locales/source/course_content/2017/csd1-2017.json
  i18n/locales/source/course_content/2017/csd2-2017.json
  i18n/locales/source/course_content/2017/csd3-2017.json
  i18n/locales/source/course_content/2017/csd4-2017.json
  i18n/locales/source/course_content/2017/csd5-2017.json
  i18n/locales/source/course_content/2017/csd6-2017.json
  i18n/locales/source/course_content/2017/express-2017.json
  i18n/locales/source/course_content/2017/pre-express-2017.json
  i18n/locales/source/course_content/2018/coursec-2018.json
  i18n/locales/source/course_content/2018/coursed-2018.json
  i18n/locales/source/course_content/2018/coursee-2018.json
  i18n/locales/source/course_content/2018/coursef-2018.json
  i18n/locales/source/course_content/2018/csd1-2018.json
  i18n/locales/source/course_content/2018/csd2-2018.json
  i18n/locales/source/course_content/2018/csd3-2018.json
  i18n/locales/source/course_content/2018/csd4-2018.json
  i18n/locales/source/course_content/2018/csd5-2018.json
  i18n/locales/source/course_content/2018/csd6-2018.json
  i18n/locales/source/course_content/2018/express-2018.json
  i18n/locales/source/course_content/2019/coursec-2019.json
  i18n/locales/source/course_content/2019/coursed-2019.json
  i18n/locales/source/course_content/2019/coursee-2019.json
  i18n/locales/source/course_content/2019/coursef-2019.json
  i18n/locales/source/course_content/2019/csd1-2019.json
  i18n/locales/source/course_content/2019/csd2-2019.json
  i18n/locales/source/course_content/2019/csd3-2019.json
  i18n/locales/source/course_content/2019/csd4-2019.json
  i18n/locales/source/course_content/2019/csd5-2019.json
  i18n/locales/source/course_content/2019/csd6-2019.json
  i18n/locales/source/course_content/2019/express-2019.json
  i18n/locales/source/course_content/Hour of Code/flappy.json
  i18n/locales/source/course_content/Hour of Code/hoc-encryption.json
  i18n/locales/source/course_content/Hour of Code/hourofcode.json
  i18n/locales/source/course_content/other/K5-OnlinePD.json
  i18n/locales/source/course_content/other/applab-2hour.json
  i18n/locales/source/course_content/other/course1.json
  i18n/locales/source/course_content/other/course2.json
  i18n/locales/source/course_content/other/course3.json
  i18n/locales/source/course_content/other/csd-post-survey-2018.json
  i18n/locales/source/course_content/other/csd-post-survey.json
  i18n/locales/source/course_content/other/fesbinary.json
  i18n/locales/source/course_content/other/netsim.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/hourofcode/how-to/2019.md
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#32804 Mb maker board test
  apps/src/lib/kits/maker/MicroBitBoard.js
  apps/test/unit/lib/kits/maker/CircuitPlaygroundBoardTest.js
  apps/test/unit/lib/kits/maker/FakeBoardTest.js
  apps/test/unit/lib/kits/maker/MakerBoardTest.js
  apps/test/unit/lib/kits/maker/MicroBitBoardTest.js
Labels: star-labs

#32884 I18n sync In & Up 01/27
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2017/csd3-2017.json
  i18n/locales/source/course_content/2017/csd6-2017.json
  i18n/locales/source/course_content/2018/csd3-2018.json
  i18n/locales/source/course_content/2018/csd6-2018.json
  i18n/locales/source/course_content/2019/csd3-2019.json
  i18n/locales/source/course_content/2019/csd6-2019.json
  i18n/locales/source/course_content/other/course3.json
Labels: i18n

#32899 BugFix STAR-959: Libraries are duplicated for each section by /api/v1/section_libraries
  dashboard/app/controllers/api/v1/section_libraries_controller.rb
Labels: star-labs

#32842 [Applab Datasets] Render links in table description
  apps/i18n/common/en_us.json
  apps/src/storage/dataBrowser/LibraryTable.jsx
  apps/src/storage/dataBrowser/datasetManifest.json
Labels: star-labs

#32889 [student-libraries] Migrated library 'View Code' modal to droplet view rather than basic <pre> view
  apps/src/code-studio/components/libraries/LibraryViewCode.jsx
  apps/style/common.scss
Labels: star-labs

#32891 Allow import data urls
  apps/src/applab/constants.js
  apps/src/applab/designMode.js
  apps/src/applab/import.js
  apps/src/assetManagement/assetPrefix.js
Labels: star-labs
