Repository code-dot-org/code-dot-org, pull requests merged in 2020-03, with the labels that each got.

#33382 I18n sync In & Up 03/02
  i18n/locales/source/course_content/2017/coursea-2017.json
  i18n/locales/source/course_content/2017/courseb-2017.json
  i18n/locales/source/course_content/2017/csd2-2017.json
  i18n/locales/source/course_content/2017/csd3-2017.json
  i18n/locales/source/course_content/2017/csd4-2017.json
  i18n/locales/source/course_content/2017/csd5-2017.json
  i18n/locales/source/course_content/2017/csd6-2017.json
  i18n/locales/source/course_content/2017/pre-express-2017.json
  i18n/locales/source/course_content/2018/coursea-2018.json
  i18n/locales/source/course_content/2018/csd1-2018.json
  i18n/locales/source/course_content/2018/csd2-2018.json
  i18n/locales/source/course_content/2018/csd3-2018.json
  i18n/locales/source/course_content/2018/csd4-2018.json
  i18n/locales/source/course_content/2018/csd5-2018.json
  i18n/locales/source/course_content/2018/csd6-2018.json
  i18n/locales/source/course_content/2018/pre-express-2018.json
  i18n/locales/source/course_content/2019/coursea-2019.json
  i18n/locales/source/course_content/2019/courseb-2019.json
  i18n/locales/source/course_content/2019/coursec-2019.json
  i18n/locales/source/course_content/2019/coursee-2019.json
  i18n/locales/source/course_content/2019/coursef-2019.json
  i18n/locales/source/course_content/2019/csd1-2019.json
  i18n/locales/source/course_content/2019/csd2-2019.json
  i18n/locales/source/course_content/2019/csd3-2019.json
  i18n/locales/source/course_content/2019/csd4-2019.json
  i18n/locales/source/course_content/2019/csd5-2019.json
  i18n/locales/source/course_content/2019/csd6-2019.json
  i18n/locales/source/course_content/2019/express-2019.json
  i18n/locales/source/course_content/2019/pre-express-2019.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#33391 Fixed order of operations bug in libraries controller
  dashboard/lib/projects_list.rb
Labels: star-labs

#33337 [Applab Design Mode] Fix hex code auto-complete bug
  apps/src/applab/designElements/ColorPickerPropertyRow.jsx
Labels: star-labs

#33406 [student-libraries] Get hidden libraries when querying a class list
  dashboard/lib/projects_list.rb
Labels: star-labs

#33357 [Applab Datasets] Add new dataset link on levelbuilder page
  apps/src/storage/levelbuilder/DatasetList.jsx
Labels: star-labs

#33440 Deflake disable_toolbox_maze UI test
  dashboard/test/ui/features/star_labs/disable_toolbox_maze.feature
Labels: star-labs

#33402 Remove Litmus tracking
  lib/cdo/poste.rb
  lib/test/fixtures/deliverer/expected/hoc_signup_2014_receipt/header.yaml
  lib/test/fixtures/deliverer/expected/hoc_signup_2015_receipt/header.yaml
  lib/test/fixtures/deliverer/expected/hoc_signup_2017_receipt_en/header.yaml
  lib/test/fixtures/deliverer/expected/hoc_signup_2018_receipt_en/header.yaml
  lib/test/fixtures/deliverer/expected/hoc_signup_2018_receipt_es/header.yaml
  lib/test/fixtures/deliverer/expected/hoc_signup_2018_receipt_pt/header.yaml
  lib/test/fixtures/deliverer/expected/hoc_signup_2019_receipt_en/header.yaml
  lib/test/fixtures/deliverer/expected/hoc_signup_2019_receipt_es/header.yaml
  lib/test/fixtures/deliverer/expected/hoc_signup_2019_receipt_pt/header.yaml
  lib/test/fixtures/deliverer/expected/petition_receipt/header.yaml
  pegasus/emails/hoc_signup_2014_receipt.md
  pegasus/emails/hoc_signup_2015_receipt.md
  pegasus/emails/hoc_signup_2017_receipt_en.md
  pegasus/emails/hoc_signup_2018_receipt_en.md
  pegasus/emails/hoc_signup_2018_receipt_es.md
  pegasus/emails/hoc_signup_2018_receipt_pt.md
  pegasus/emails/hoc_signup_2019_receipt_en.md
  pegasus/emails/hoc_signup_2019_receipt_es.md
  pegasus/emails/hoc_signup_2019_receipt_pt.md
  pegasus/emails/petition_receipt.md
Labels: code-hygiene

#33381 Google OAuth Maker Decrypt and Authenticate
  dashboard/app/controllers/maker_controller.rb
  dashboard/app/controllers/omniauth_callbacks_controller.rb
  dashboard/app/controllers/sessions_controller.rb
  dashboard/app/views/maker/login_code.html.haml
  dashboard/config/locales/en.yml
  dashboard/config/routes.rb
  dashboard/lib/encryption.rb
  dashboard/test/controllers/omniauth_callbacks_controller_test.rb
Labels: star-labs

#33329 "My Libraries" tab - server changes
  apps/src/sites/studio/pages/projects/index.js
  dashboard/app/controllers/projects_controller.rb
  dashboard/app/views/layouts/_header.html.haml
  dashboard/app/views/projects/index.html.haml
  dashboard/config/routes.rb
  dashboard/lib/projects_list.rb
  dashboard/test/controllers/projects_controller_test.rb
  dashboard/test/lib/projects_list_test.rb
  shared/middleware/channels_api.rb
  shared/test/test_channels.rb
Labels: star-labs

#33455 [student-libraries] Fixed library creation code so libraries that end in comments don't break things.
  apps/src/code-studio/components/libraries/libraryParser.js
  apps/test/unit/code-studio/components/libraries/libraryParserTest.js
Labels: star-labs

#33407 [student-libraries] Add test for hidden library
  dashboard/test/lib/projects_list_test.rb
Labels: star-labs

#33447 [Applab Data] Restrict record data types entered through API
  apps/i18n/common/en_us.json
  apps/src/lib/util/javascriptMode.js
Labels: star-labs

#33330 "My Libraries" tab - client changes
  apps/i18n/common/en_us.json
  apps/src/code-studio/components/libraries/LibraryPublisher.jsx
  apps/src/code-studio/initApp/project.js
  apps/src/templates/projects/LibraryTable.jsx
  apps/src/templates/projects/LibraryTable.story.jsx
  apps/src/templates/projects/PersonalProjectsTable.jsx
  apps/src/templates/projects/ProjectsGallery.jsx
  apps/src/templates/projects/ProjectsGallery.story.jsx
  apps/src/templates/projects/projectConstants.js
  apps/src/templates/projects/projectsRedux.js
  apps/test/unit/code-studio/initApp/projectTest.js
  apps/test/unit/templates/projects/projectsReduxTest.js
Labels: star-labs

#33374 "My Libraries" tab - unpublish libraries
  apps/src/code-studio/components/libraries/LibraryClientApi.js
  apps/src/code-studio/components/libraries/LibraryPublisher.jsx
  apps/src/templates/projects/LibraryTable.jsx
  apps/src/templates/projects/LibraryTable.story.jsx
  apps/src/templates/projects/projectsRedux.js
  apps/test/unit/code-studio/components/libraries/LibraryClientApiTest.js
  apps/test/unit/code-studio/components/libraries/LibraryPublisherTest.js
  apps/test/unit/templates/projects/projectsReduxTest.js
  shared/middleware/channels_api.rb
Labels: star-labs

#33505 I18n sync In & Up 03/09
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2019/coursee-2019.json
  i18n/locales/source/course_content/2019/coursef-2019.json
  i18n/locales/source/course_content/2019/express-2019.json
  i18n/locales/source/course_content/projects.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#33534 Create contact rollups raw
  dashboard/app/models/contact_rollups_raw.rb
  dashboard/db/migrate/20200310000601_create_contact_rollups_raw.rb
  dashboard/db/schema.rb
Labels: contact-rollups

#33530 Disable exporting functions with duplicate names
  apps/i18n/common/en_us.json
  apps/src/code-studio/components/libraries/LibraryPublisher.jsx
  apps/test/unit/code-studio/components/libraries/LibraryPublisherTest.js
Labels: star-labs

#33539 Add migration to create contact_rollups_processed table
  dashboard/db/migrate/20200309213913_create_contact_rollups_processed.rb
  dashboard/db/schema.rb
Labels: contact-rollups

#33529 Put create/updateRecord API change behind experiment flag
  apps/src/lib/util/javascriptMode.js
Labels: star-labs

#33553 [Cleanup][Applab Data] Coerce Firebase response to consistent type
  apps/src/storage/dataBrowser/DataBrowser.jsx
  apps/src/storage/dataBrowser/DataTable.jsx
  apps/src/storage/dataBrowser/DataTableView.jsx
  apps/src/storage/dataBrowser/KVPairs.jsx
  apps/src/storage/dataBrowser/dataVisualizer/VisualizerModal.jsx
  apps/src/storage/levelbuilder/Dataset.jsx
  apps/src/storage/redux/data.js
Labels: star-labs

#33582 Add error param to callbacks that use fetchLatestLibrary
  apps/src/code-studio/components/libraries/LibraryManagerDialog.jsx
  apps/test/unit/code-studio/components/libraries/libraryManagerDialogTest.js
Labels: star-labs

#33519 Star wars skin
  dashboard/app/models/levels/blockly.rb
  dashboard/app/views/levels/editors/_blockly.html.haml
  dashboard/config/scripts/levels/New Star Wars Blocks Project.level
  dashboard/config/scripts/levels/New Star Wars Expanded Blocks Project.level
  dashboard/config/scripts/levels/New Star Wars Project.level
  dashboard/config/scripts/levels/aaron star wars game 1.level
  dashboard/config/scripts/levels/course_e_explore_3.level
Labels: star-labs

#33557 Extract email preferences into contact_rollups_raw
  bin/cron/build_contact_rollups_v2
  dashboard/app/models/contact_rollups_raw.rb
  dashboard/test/factories/factories.rb
  dashboard/test/models/contact_rollups_raw_test.rb
  lib/cdo/contact_rollups_v2.rb
Labels: contact-rollups

#33576 Revert "Revert "[Cleanup][Applab Data] Coerce Firebase response to consistent type""
  apps/src/storage/dataBrowser/DataBrowser.jsx
  apps/src/storage/dataBrowser/DataTable.jsx
  apps/src/storage/dataBrowser/DataTableView.jsx
  apps/src/storage/dataBrowser/KVPairs.jsx
  apps/src/storage/dataBrowser/dataVisualizer/VisualizerModal.jsx
  apps/src/storage/levelbuilder/Dataset.jsx
  apps/src/storage/redux/data.js
  apps/test/unit/storage/dataBrowser/DataTableViewTest.js
Labels: star-labs

#33533 [Applab Data] Restrict data entry types entered through UI
  apps/i18n/common/en_us.json
  apps/src/storage/dataBrowser/AddKeyRow.jsx
  apps/src/storage/dataBrowser/AddTableRow.jsx
  apps/src/storage/dataBrowser/DataEntryError.jsx
  apps/src/storage/dataBrowser/DataTable.jsx
  apps/src/storage/dataBrowser/EditKeyRow.jsx
  apps/src/storage/dataBrowser/EditTableRow.jsx
  apps/src/storage/dataBrowser/KVPairs.jsx
  apps/src/storage/dataBrowser/dataUtils.js
  apps/src/storage/firebaseStorage.js
  apps/test/unit/storage/dataUtilsTest.js
Labels: star-labs

#33552 Add latestLibraryVersion field to projects db
  apps/src/code-studio/components/libraries/LibraryPublisher.jsx
  apps/src/code-studio/initApp/project.js
  apps/test/unit/code-studio/components/libraries/LibraryPublisherTest.js
  apps/test/unit/code-studio/initApp/projectTest.js
Labels: star-labs

#33479 [student-libraries] Refactor MoveStudents.jsx into MoveStudents.jsx and SortedTableSelect.jsx
  apps/src/code-studio/components/SortedTableSelect.jsx
  apps/src/templates/manageStudents/MoveStudents.jsx
  apps/test/unit/code-studio/components/SortedTableSelectTest.js
  apps/test/unit/templates/manageStudents/MoveStudentsTest.js
Labels: star-labs

#33541 Process opt_in attribute
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/test/factories/factories.rb
  dashboard/test/models/contact_rollups_processed_test.rb
  lib/cdo/contact_rollups/v2/contact_rollups.rb
Labels: contact-rollups

#33518 Manage libraries modal re-design
  apps/Gruntfile.js
  apps/i18n/common/en_us.json
  apps/src/code-studio/components/libraries/LibraryListItem.jsx
  apps/src/code-studio/components/libraries/LibraryManagerDialog.jsx
  apps/src/templates/Tooltip.jsx
  apps/test/unit/code-studio/components/libraries/libraryListItemTest.js
Labels: star-labs

#33620 Add theunitedstates.io for startWebRequest
  dashboard/app/controllers/xhr_proxy_controller.rb
Labels: star-labs

#33625 [Eval] Fix booleans
  apps/src/sharedFunctionalBlocks.js
Labels: star-labs

#33637 Add author name for project libraries from classmates
  apps/src/code-studio/components/libraries/LibraryManagerDialog.jsx
  apps/test/unit/code-studio/components/libraries/libraryManagerDialogTest.js
Labels: star-labs

#33641 I18n sync In & Up 03/16
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#33690 Update SerialPort.List
  apps/src/lib/kits/maker/portScanning.js
Labels: star-labs

#33677 Create migrations for data comparison step
  dashboard/db/migrate/20200317042200_create_contact_rollups_final.rb
  dashboard/db/migrate/20200317042242_create_contact_rollups_comparison.rb
  dashboard/db/schema.rb
Labels: contact-rollups

#33709 Add permissions to display_code
  dashboard/app/controllers/maker_controller.rb
Labels: star-labs

#33674 Compare new and existing processed data
  bin/cron/build_contact_rollups_v2
  dashboard/app/models/contact_rollups_comparison.rb
  dashboard/app/models/contact_rollups_final.rb
  dashboard/test/factories/factories.rb
  dashboard/test/models/contact_rollups_comparison_test.rb
  lib/cdo/contact_rollups/v2/contact_rollups.rb
  lib/cdo/contact_rollups_v2.rb
Labels: contact-rollups

#33686 [DataViz] Snapshot Modal
  apps/i18n/common/en_us.json
  apps/src/storage/dataBrowser/dataVisualizer/Snapshot.jsx
  apps/src/storage/dataBrowser/dataVisualizer/VisualizerModal.jsx
  apps/test/unit/storage/dataBrowser/dataVisualizer/VisualizerModalTest.js
Labels: star-labs

#33666 Create contact_rollups_pardot_memory table
  dashboard/app/models/contact_rollups_pardot_memory.rb
  dashboard/db/migrate/20200316201644_create_contact_rollups_pardot_memory.rb
  dashboard/db/schema.rb
Labels: contact-rollups

#33703 [DataViz] Snapshot works for GoogleCharts
  apps/src/imageUtils.js
  apps/src/storage/dataBrowser/dataVisualizer/GoogleChartWrapper.jsx
  apps/src/storage/dataBrowser/dataVisualizer/Snapshot.jsx
  apps/src/storage/dataBrowser/dataVisualizer/VisualizerModal.jsx
  apps/src/storage/dataBrowser/dataVisualizer/constants.js
  apps/src/third-party/canvg/svg_todataurl.js
Labels: star-labs

#33750 GET /libraries/get_updates
  dashboard/app/controllers/libraries_controller.rb
  dashboard/config/routes.rb
  dashboard/lib/projects_list.rb
  dashboard/test/lib/projects_list_test.rb
Labels: star-labs

#33708 [DataViz] Snapshot for Cross Tab
  apps/src/storage/dataBrowser/dataVisualizer/CrossTabChart.jsx
  apps/src/storage/dataBrowser/dataVisualizer/Snapshot.jsx
  apps/src/storage/dataBrowser/dataVisualizer/constants.js
Labels: star-labs

#33770 Manage Students: pass studioUrlPrefix to LoginCard
  apps/src/templates/teacherDashboard/SectionLoginInfo.jsx
Labels: bug-fix

#33657 Library Manager: Internationalized strings and updated variable names
  apps/i18n/common/en_us.json
  apps/src/code-studio/components/libraries/LibraryManagerDialog.jsx
  apps/src/code-studio/components/libraries/LibraryViewCode.jsx
  apps/test/unit/code-studio/components/libraries/libraryManagerDialogTest.js
Labels: star-labs

#33780 Remove string parameter in test
  apps/test/unit/lib/kits/maker/CircuitPlaygroundBoardTest.js
  apps/test/unit/lib/kits/maker/FakeBoardTest.js
  apps/test/unit/lib/kits/maker/MakerBoardTest.js
  apps/test/unit/lib/kits/maker/MicroBitBoardTest.js
Labels: star-labs

#33775 I18n sync In & Up 03/23
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2018/coursee-2018.json
  i18n/locales/source/course_content/2018/coursef-2018.json
  i18n/locales/source/course_content/2018/express-2018.json
  i18n/locales/source/course_content/2019/coursee-2019.json
  i18n/locales/source/course_content/2019/coursef-2019.json
  i18n/locales/source/course_content/2019/express-2019.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#33862 Jobs page: Add COVID-19 note
  pegasus/sites.v3/code.org/public/about/jobs.md.erb
Labels: content-change

#33702 Contact rollups pardot memory logic
  dashboard/app/models/contact_rollups_pardot_memory.rb
  dashboard/test/factories/factories.rb
  dashboard/test/models/contact_rollups_pardot_memory_test.rb
  lib/cdo/contact_rollups/v2/contact_rollups.rb
  lib/cdo/contact_rollups/v2/pardot.rb
  lib/cdo/contact_rollups/v2/pardot_helpers.rb
  lib/test/cdo/contact_rollups/test_pardot_helpers.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#33910 I18n sync In & Up 03/30
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/markdown/public/athome.md
  i18n/locales/source/markdown/public/athome/csf.md
  i18n/locales/source/markdown/public/break.md
  i18n/locales/source/markdown/public/csforgood.md
  i18n/locales/source/markdown/public/educate/curriculum/csf-transition-guide.md
  i18n/locales/source/markdown/public/international/about.md
Labels: i18n

#33912 Pin Mode with Test
  apps/src/lib/kits/maker/MicroBitBoard.js
  apps/test/unit/lib/kits/maker/MicroBitBoardTest.js
  apps/test/unit/lib/kits/maker/makeStubBoard.js
Labels: star-labs

#33893 [Datasets] Fix update manifest route
  apps/src/storage/levelbuilder/ManifestEditor.jsx
  dashboard/app/controllers/datasets_controller.rb
Labels: star-labs

#33919 Tests: Deflake progress_standards_view.feature
  dashboard/test/ui/features/step_definitions/steps.rb
Labels: UI Testing, testing

#33920 Fixed droplet tooltips so they no longer cover blocks
  apps/src/blockTooltips/DropletBlockTooltipManager.js
Labels: star-labs

#33944 Tests: Deflake progress_standards_view.feature
  dashboard/test/ui/features/step_definitions/steps.rb
Labels: testing

#33941 Disable deleting levelbuilder-specified libraries
  apps/i18n/common/en_us.json
  apps/src/code-studio/components/libraries/LibraryListItem.jsx
Labels: star-labs

#33933 [Applab Datasets] Add doc link to table description
  apps/src/storage/dataBrowser/LibraryTable.jsx
  apps/src/storage/dataBrowser/PreviewModal.jsx
Labels: star-labs

#33931 DigitalWrite with tests
  apps/src/lib/kits/maker/MicroBitBoard.js
  apps/src/third-party/maker/MBFirmataClient.js
  apps/test/unit/lib/kits/maker/MicroBitBoardTest.js
  apps/test/unit/lib/kits/maker/makeStubBoard.js
Labels: star-labs
