Repository code-dot-org/code-dot-org, pull requests merged in 2020-12, with the labels that each got.

#38034 I18n sync In & Up 11/30
  i18n/locales/source/animations/spritelab_animation_library.json
  i18n/locales/source/course_content/other/outbreak.json
  i18n/locales/source/dashboard/progressions.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#37942 Store logged-out progress if we are on an auto-success level
  apps/src/code-studio/levels/postOnLoad.js
  dashboard/test/ui/features/learning_platform/level_navigation.feature
Labels: progress-leak

#38063 Explicitly specify class name for generic association
  dashboard/app/models/pd/application/tag.rb
Labels: Rails 6

#38146 I18n sync In & Up 12/07
  i18n/locales/source/animations/spritelab_animation_library.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/spritelab.json
  i18n/locales/source/course_content/other/outbreak.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#38241 Update to CanCanCan 3.0
  Gemfile
  Gemfile.lock
Labels: Rails 6

#38168 proactively silence a few deprecation warnings added in Rails 6.0
  dashboard/config/initializers/backtrace_silencers.rb
Labels: Rails 6
