Repository code-dot-org/code-dot-org, pull requests merged in 2020-07, with the labels that each got.

#35554 Dataset Library Search
  apps/i18n/common/en_us.json
  apps/src/storage/dataBrowser/DataLibraryPane.jsx
  apps/src/storage/dataBrowser/LibraryCategory.jsx
  apps/src/templates/SearchBar.jsx
  dashboard/test/ui/features/star_labs/applab/eyes3.feature
Labels: star-labs

#35579 Move gamelab animation library to s3
  apps/src/p5lab/P5LabView.jsx
  apps/src/p5lab/gamelab/animationLibrary.json
  apps/src/p5lab/spritelab/spriteCostumeLibrary.json
  apps/test/unit/code-studio/searchAssetsTest.js
  apps/test/unit/p5lab/AnimationPicker/AnimationPickerBodyTest.js
  apps/test/unit/p5lab/testAnimationLibrary.json
  shared/middleware/animation_library_api.rb
Labels: star-labs

#35602 added empty json check for voice request
  dashboard/app/helpers/levels_helper.rb
Labels: star-labs

#35596 CRv2: Report results to Slack and S3
  dashboard/lib/contact_rollups_v2.rb
Labels: contact-rollups

#35594 Guard against user trying to access sprite with invalid spriteIndex
  apps/src/studio/studio.js
Labels: star-labs

#35642 CRv2: Report failures to process contacts
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/test/models/contact_rollups_processed_test.rb
Labels: contact-rollups

#35571 Text to speech block profanity filtering, character limit, and caching
  apps/i18n/common/en_us.json
  apps/src/Sound.js
  apps/src/Sounds.js
  apps/src/code-studio/components/libraries/util.js
  apps/src/constants.js
  apps/src/lib/util/audioApi.js
  apps/src/lib/util/speech.js
  dashboard/app/controllers/profanity_controller.rb
  dashboard/app/helpers/levels_helper.rb
Labels: star-labs

#35626 Bump blockly to 3.5.26
  apps/package.json
  apps/yarn.lock
Labels: star-labs

#35612 Track which sprite is chosen from animation library
  apps/src/p5lab/AnimationPicker/animationPickerModule.js
Labels: star-labs

#35647 I18n sync In & Up 07/06
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2020/coursea-2020.json
  i18n/locales/source/course_content/2020/courseb-2020.json
  i18n/locales/source/course_content/2020/coursec-2020.json
  i18n/locales/source/course_content/2020/coursed-2020.json
  i18n/locales/source/course_content/2020/coursee-2020.json
  i18n/locales/source/course_content/2020/coursef-2020.json
  i18n/locales/source/course_content/2020/express-2020.json
  i18n/locales/source/course_content/2020/pre-express-2020.json
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#35638 [Applab Datasets] Show max tables error for imported libraries
  apps/src/storage/dataBrowser/DataLibraryPane.jsx
Labels: star-labs

#35632 [Playlab] Fix validation for lose condition
  apps/src/code-studio/reporting.js
  dashboard/config/scripts/levels/courseD_playLab_cond5_2018.level
Labels: star-labs

#35664 added null check in Google Chart options for drawChart in app lab
  apps/src/applab/GoogleChart.js
Labels: star-labs

#35649 New App Lab themes
  apps/src/applab/constants.js
  apps/src/applab/designElements/label.jsx
  apps/src/applab/themeValues.js
  apps/static/applab/theme_dropdown/berry_patch.png
  apps/static/applab/theme_dropdown/blue_and_gold.png
  apps/static/applab/theme_dropdown/blue_steel.png
  apps/static/applab/theme_dropdown/cherry_vanilla.png
  apps/static/applab/theme_dropdown/coral_reef.png
  apps/static/applab/theme_dropdown/crushed_velvet.png
  apps/static/applab/theme_dropdown/cucumber.png
  apps/static/applab/theme_dropdown/darkscheme.png
  apps/static/applab/theme_dropdown/lavender.png
  apps/static/applab/theme_dropdown/mint_chip.png
  apps/static/applab/theme_dropdown/pastel.png
  apps/static/applab/theme_dropdown/peachy.png
  apps/static/applab/theme_dropdown/playtime.png
  apps/static/applab/theme_dropdown/two_tone.png
  apps/static/applab/theme_dropdown/under_the_sea.png
Labels: star-labs

#35691 Studio App displayPlayspaceAlert refactor
  apps/src/StudioApp.js
  apps/src/applab/designMode.js
  apps/src/constants.js
  apps/test/unit/applab/designModeThemesTest.js
Labels: star-labs

#35710 Census: State CS offerings July batch
  dashboard/app/models/census/state_cs_offering.rb
  dashboard/config/state_cs_offerings/DE/2019-2020.2.csv
  dashboard/config/state_cs_offerings/IA/2019-2020.csv
  dashboard/config/state_cs_offerings/IN/2019-2020.2.csv
  dashboard/config/state_cs_offerings/KS/2019-2020.csv
  dashboard/config/state_cs_offerings/KY/2019-2020.csv
  dashboard/config/state_cs_offerings/ME/2018-2019.csv
  dashboard/config/state_cs_offerings/ME/2019-2020.csv
  dashboard/config/state_cs_offerings/NH/2019-2020.csv
  dashboard/config/state_cs_offerings/NV/2019-2020.csv
  dashboard/config/state_cs_offerings/NY/2018-2019.csv
  dashboard/config/state_cs_offerings/PA/2018-2019.csv
  dashboard/config/state_cs_offerings/RI/2019-2020.csv
  dashboard/config/state_cs_offerings/TX/2018-2019.csv
  dashboard/config/state_cs_offerings/VT/2019-2020.csv
  dashboard/config/state_cs_offerings/WV/2019-2020.csv
  dashboard/config/state_cs_offerings/WY/2018-2019.csv
Labels: access report

#35673 Consolidated touchscreen and mobile sections
  pegasus/sites.v3/code.org/public/educate/it.md
Labels: star-labs

#35337 Libraries UI tests
  apps/src/code-studio/components/SortedTableSelect.jsx
  apps/src/code-studio/components/libraries/LibraryListItem.jsx
  apps/src/code-studio/components/libraries/LibraryManagerDialog.jsx
  apps/src/code-studio/components/libraries/LibraryPublisher.jsx
  apps/src/templates/projects/LibraryTable.jsx
  aws/cloudformation/s3_buckets.yml
  dashboard/test/ui/features/star_labs/applab/libraries.feature
  dashboard/test/ui/features/step_definitions/applab.rb
  dashboard/test/ui/features/step_definitions/steps.rb
  docker/ui_tests.sh
Labels: star-labs

#35413 Updated Applab and Gamelab engine to unify support with Droplet
  apps/lib/droplet/droplet-full.js
  apps/lib/droplet/droplet-full.min.js
  apps/lib/droplet/droplet-full.min.js.map
  apps/src/JavaScriptModeErrorHandler.js
  apps/src/applab/applab.js
  apps/src/p5lab/P5Lab.js
  apps/src/templates/ShowCodeToggle.js
  apps/src/util/dropletCommon.js
  apps/test/unit/templates/ShowCodeToggleTest.js
  apps/test/unit/util/dropletCommonTest.js
Labels: star-labs

#35738 Allow teachers to share libraries with their classmates
  dashboard/lib/projects_list.rb
  dashboard/test/lib/projects_list_test.rb
Labels: star-labs

#35747 Census: Remove Maine 2018-2019 reference
  dashboard/app/models/census/state_cs_offering.rb
Labels: access report

#35789 I18n sync In & Up 07/13
  i18n/locales/source/animations/spritelab_animation_library.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/other/k5-onlinepd-2019.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#35888 Redirect /educate/district/agreement to /dpa
  pegasus/sites.v3/code.org/public/educate/district/agreement.md
  pegasus/sites.v3/code.org/public/educate/district/agreement.moved
Labels: content-change

#35897 Fix ForbiddenAttributesError in registrations#new
  dashboard/app/controllers/registrations_controller.rb
  dashboard/test/integration/registration/new_test.rb
Labels: bug-fix

#35898 Add 59 new URLs to the broken link checker ignore list
  tools/scripts/brokenLinkChecker/brokenLinkChecker.json
Labels: testing

#35886 I18n sync In & Up 07/20
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/animations/spritelab_animation_library.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2020/express-2020.json
  i18n/locales/source/course_content/2020/pre-express-2020.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#35864 MicroBit Capacitive Touch
  apps/src/lib/kits/maker/api.js
  apps/src/lib/kits/maker/boards/microBit/CapacitiveTouchSensor.js
  apps/src/lib/kits/maker/boards/microBit/MicroBitBoard.js
  apps/src/lib/kits/maker/boards/microBit/MicroBitComponents.js
  apps/src/lib/kits/maker/commands.js
  apps/src/lib/kits/maker/dropletConfig.js
  apps/test/unit/lib/kits/maker/boards/MakerBoardTest.js
  apps/test/unit/lib/kits/maker/boards/makeStubBoard.js
  apps/test/unit/lib/kits/maker/boards/microBit/CapacitiveTouchSensorTest.js
  apps/test/unit/lib/kits/maker/boards/microBit/MicroBitBoardTest.js
  apps/test/unit/lib/kits/maker/boards/microBit/MicroBitComponentsTest.js
  lib/cdo/shared_constants.rb
Labels: star-labs

#35875 RailsAuthenticityToken is test-aware
  apps/src/lib/util/RailsAuthenticityToken.jsx
  apps/src/templates/teacherDashboard/RosterDialog.story.jsx
  apps/test/unit/lib/util/RailsAuthenticityTokenTest.jsx
  apps/test/util/stubRailsAuthenticityToken.js
Labels: testing

#35877 ManageLinkedAccounts uses RailsAuthenticityToken
  apps/src/lib/ui/accounts/ManageLinkedAccounts.jsx
  apps/src/lib/ui/accounts/ManageLinkedAccounts.story.jsx
  apps/src/lib/ui/accounts/ManageLinkedAccountsController.js
  apps/src/lib/ui/accounts/manageLinkedAccountsRedux.js
  apps/src/sites/studio/pages/devise/registrations/edit.js
  apps/test/unit/lib/ui/accounts/ManageLinkedAccountsTest.jsx
  dashboard/app/views/devise/registrations/edit.html.haml
Labels: code-hygiene

#35880 NewScriptForm uses RailsAuthenticityToken
  apps/src/lib/script-editor/NewScriptForm.jsx
  apps/src/sites/studio/pages/scripts/new.js
  dashboard/app/views/scripts/new.html.haml
Labels: code-hygiene

#35879 ReportAbuseForm uses RailsAuthenticityToken
  apps/Gruntfile.js
  apps/src/code-studio/components/ReportAbuseForm.jsx
  apps/src/sites/studio/pages/code-studio.js
  apps/src/sites/studio/pages/report_abuse/report_abuse_form.js
  dashboard/app/controllers/report_abuse_controller.rb
  dashboard/app/views/report_abuse/report_abuse_form.html.haml
Labels: code-hygiene

#36048 I18n sync In & Up 07/29
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/course_content/2019/coursee-2019.json
  i18n/locales/source/course_content/2019/coursef-2019.json
  i18n/locales/source/course_content/2019/express-2019.json
  i18n/locales/source/course_content/2020/coursee-2020.json
  i18n/locales/source/course_content/2020/coursef-2020.json
  i18n/locales/source/course_content/2020/express-2020.json
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/how-to/parents-new.md
Labels: i18n
