Repository code-dot-org/code-dot-org, pull requests merged in 2020-11, with the labels that each got.

#37580 Revert "Revert "Remove deprecated :text option to render""
  dashboard/app/controllers/admin_reports_controller.rb
  dashboard/app/controllers/dynamic_config_controller.rb
  dashboard/app/controllers/home_controller.rb
  dashboard/app/controllers/lessons_controller.rb
  dashboard/app/controllers/levels_controller.rb
  dashboard/app/controllers/script_levels_controller.rb
  dashboard/app/controllers/videos_controller.rb
  dashboard/config/initializers/backtrace_silencers.rb
  dashboard/test/controllers/admin_reports_controller_test.rb
  dashboard/test/controllers/script_levels_controller_test.rb
Labels: Rails 6

#37582 Prevent nil params in controller tests
  dashboard/test/controllers/pd/workshop_admins_controller_test.rb
  dashboard/test/controllers/pd/workshop_user_management_controller_test.rb
  dashboard/test/controllers/regional_partners_controller_test.rb
  dashboard/test/test_helper.rb
Labels: Rails 6

#37465 Rails 5.1
  Gemfile
  Gemfile.lock
  dashboard/config/initializers/backtrace_silencers.rb
  dashboard/config/initializers/schema_cache_dedup.rb
  dashboard/db/schema.rb
  dashboard/test/controllers/home_controller_test.rb
  dashboard/test/controllers/media_proxy_controller_test.rb
  pegasus/test/test_hoc_routes.rb
Labels: Rails 6

#37681 Use generic - rather than region-specific - regional partner in test
  dashboard/test/models/regional_partner_test.rb
Labels: Rails 6

#37489 Update the use of `changed?` in after callbacks
  dashboard/app/models/levels/level.rb
  dashboard/app/models/pd/enrollment.rb
  dashboard/app/models/peer_review.rb
  dashboard/app/models/user.rb
  dashboard/app/models/user_level.rb
  dashboard/app/models/user_permission.rb
Labels: Rails 6

#37704 Created experiment for time-spent feature
  apps/src/util/experiments.js
Labels: time-spent

#37708 Enabled time-spent logging on oceans levels
  apps/src/fish/Fish.js
Labels: time-spent

#37602 I18n sync In & Up 11/02
  i18n/locales/source/blockly-mooc/ailab.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/promote/resources.md
Labels: i18n

#37756 Explicitly cast session id to a string in milestone log
  dashboard/app/controllers/activities_controller.rb
Labels: Rails 6

#37741 Update the logic which detects if caching is disabled
  dashboard/test/test_helper.rb
Labels: Rails 6

#37749 Update 'no-transform' header logic
  dashboard/config/initializers/no_transform_paths.rb
  dashboard/test/integration/no_transform_paths_test.rb
Labels: Rails 6

#37748 Stop validating email match on oauth upgrade
  dashboard/app/models/user.rb
Labels: Rails 6

#37788 Construct valid regional partner for test
  dashboard/test/controllers/regional_partners_controller_test.rb
Labels: Rails 6

#37804 Update CanCanCan to 2.2.0
  Gemfile
  Gemfile.lock
Labels: Rails 6

#37850 Explicitly cast session.id to a string everywhere we directly use it
  dashboard/app/helpers/levels_helper.rb
  dashboard/lib/pd/payment/payment_calculator_base.rb
  dashboard/test/controllers/api/v1/pd/workshops_controller_test.rb
Labels: Rails 6

#37832 Remove 'escaped cookies' test
  shared/test/test_cookie_whitelist.rb
Labels: Rails 6

#37098 Rails 5.2
  Gemfile
  Gemfile.lock
  dashboard/config/initializers/backtrace_silencers.rb
  dashboard/db/schema.rb
  dashboard/test/test_helper.rb
  lib/cdo/rack/request.rb
Labels: Rails 6

#37875 Don't deduplicate the 'table_name' attribute on columns
  dashboard/config/initializers/schema_cache_dedup.rb
Labels: Rails 6

#37864 I18n sync In & Up 11/16
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/animations/spritelab_animation_library.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/spritelab.json
  i18n/locales/source/course_content/2019/csd3-2019.json
  i18n/locales/source/course_content/other/outbreak.json
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/progressions.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/markdown/public/athome.md
  i18n/locales/source/markdown/public/csforgood.md
  i18n/locales/source/markdown/public/hourofcode/artist.md
  i18n/locales/source/markdown/public/hourofcode/flappy.md
  i18n/locales/source/markdown/public/hourofcode/frozen.md
  i18n/locales/source/markdown/public/hourofcode/hourofcode.md
  i18n/locales/source/markdown/public/hourofcode/infinity.md
  i18n/locales/source/markdown/public/hourofcode/mc.md
  i18n/locales/source/markdown/public/hourofcode/playlab.md
  i18n/locales/source/markdown/public/hourofcode/starwars.md
  i18n/locales/source/markdown/public/hourofcode/unplugged-conditionals-with-cards.md
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n
