Repository code-dot-org/code-dot-org, pull requests merged in 2020-08, with the labels that each got.

#36126 I18n sync In & Up 08/03
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/base.yml
Labels: i18n

#36082 Created migration to add 'time_spent' to 'user_levels' table
  dashboard/app/models/user_level.rb
  dashboard/db/migrate/20200730194330_add_time_spent_to_user_levels.rb
  dashboard/db/schema.rb
Labels: time-spent

#36097 Remove unused validated_user_levels table
  dashboard/app/models/validated_user_level.rb
  dashboard/db/migrate/20200730231738_drop_validated_user_levels.rb
  dashboard/db/schema.rb
  dashboard/test/factories/factories.rb
  dashboard/test/models/validated_user_level_test.rb
Labels: time-spent

#36158 compute all descendant levels of a script
  dashboard/app/models/levels/bubble_choice.rb
  dashboard/app/models/levels/level.rb
  dashboard/app/models/levels/level_group.rb
  dashboard/app/models/script.rb
  dashboard/test/models/level_test.rb
  dashboard/test/models/levels/bubble_choice_test.rb
  dashboard/test/models/script_test.rb
Labels: hackathon

#36214 omit self from descendant levels
  dashboard/app/models/levels/level.rb
  dashboard/test/models/level_test.rb
Labels: hackathon

#36304 I18n sync In & Up 08/17
  i18n/locales/source/animations/spritelab_animation_library.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/how-to/parents.md
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#36121 Pass time spent from StudioApp to user_level
  apps/src/StudioApp.js
  apps/src/code-studio/reporting.js
  apps/test/unit/StudioAppTest.js
  dashboard/app/controllers/activities_controller.rb
  dashboard/app/models/user.rb
  dashboard/app/models/user_level.rb
  dashboard/test/controllers/activities_controller_test.rb
  dashboard/test/models/user_level_test.rb
Labels: time-spent

#36351 Pass recorded time_spent to the teacher section progress redux store
  apps/src/templates/sectionProgress/sectionProgressLoader.js
  apps/src/templates/sectionProgress/sectionProgressRedux.js
  apps/test/unit/templates/sectionProgress/sectionProgressLoaderTest.js
  dashboard/app/helpers/users_helper.rb
Labels: time-spent

#36516 I18n sync In & Up 08/31
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/hourofcode/how-to/companies-old.md
  i18n/locales/source/hourofcode/how-to/companies.md
  i18n/locales/source/hourofcode/how-to/index.md
  i18n/locales/source/hourofcode/how-to/virtual.md
Labels: i18n
