Repository code-dot-org/code-dot-org, pull requests merged in 2020-02, with the labels that each got.

#32952 [student libraries] Disabled cloud front caching and some browser caching for library GET requests.
  apps/src/code-studio/components/libraries/LibraryClientApi.js
  shared/middleware/files_api.rb
Labels: star-labs

#32956 Update sprite manifests to use new api endpoint
  apps/src/p5lab/gamelab/animationLibrary.json
  apps/src/p5lab/spritelab/defaultSprites.json
  apps/src/p5lab/spritelab/spriteCostumeLibrary.json
  tools/scripts/constants.rb
  tools/scripts/rebuildAnimationLibraryManifest.rb
Labels: star-labs

#32925 Enable access to shared firebase environment
  apps/src/applab/applab.js
  apps/src/code-studio/appOptions.js
  apps/src/storage/firebaseUtils.js
  apps/test/integration/util/runLevelTest.js
  apps/test/unit/storage/FirebaseStorageTest.js
  apps/test/unit/storage/MockFirebaseTest.js
  config.yml.erb
  config/development.yml.erb
  config/test.yml.erb
  dashboard/app/helpers/levels_helper.rb
  shared/middleware/helpers/firebase_helper.rb
Labels: star-labs

#32920 Revert "Revert "Don't show tts button until audio is playable" again"
  apps/src/templates/instructions/InlineAudio.jsx
  apps/src/templates/instructions/InstructionsCSF.story.jsx
  apps/src/templates/instructions/TopInstructions.story.jsx
  apps/test/storybook/renderStoriesTest.js
  apps/test/unit/templates/instructions/InlineAudioTest.js
  dashboard/test/ui/features/text_to_speech.feature
Labels: star-labs

#32961 I18n sync In & Up 02/03
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2019/csd3-2019.json
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/international-partners.md
Labels: i18n

#32971 script to generate defaultSprites
  apps/src/sites/studio/pages/levels/editors/_gamelab.js
  tools/scripts/constants.rb
  tools/scripts/rebuildDefaultSprites.rb
Labels: star-labs

#32973 [Applab Datasets] Pull manifest from firebase
  apps/src/applab/applab.js
  apps/src/sites/studio/pages/levels/editors/_applab.js
  apps/src/storage/dataBrowser/DataLibraryPane.jsx
  apps/src/storage/dataBrowser/LibraryTable.jsx
  apps/src/storage/dataBrowser/PreviewModal.jsx
  apps/src/storage/dataBrowser/dataUtils.js
  apps/src/storage/dataBrowser/datasetManifest.json
  apps/src/storage/firebaseStorage.js
  apps/src/storage/redux/data.js
  apps/src/util/experiments.js
  dashboard/app/controllers/levels_controller.rb
  dashboard/app/views/levels/editors/_applab.html.haml
  dashboard/test/controllers/levels_controller_test.rb
  shared/middleware/helpers/firebase_helper.rb
Labels: star-labs

#32999 Bump blockly to 3.5.6
  apps/package.json
  apps/yarn.lock
  dashboard/test/ui/features/angle_helper.feature
  dashboard/test/ui/features/step_definitions/angleHelper.rb
Labels: star-labs

#33058 [Applab Datasets] Fix experiment check
  apps/src/storage/dataBrowser/LibraryTable.jsx
Labels: star-labs

#33053 Updated api allowlist for applab
  dashboard/app/controllers/xhr_proxy_controller.rb
  dashboard/test/controllers/xhr_proxy_controller_test.rb
Labels: star-labs

#33061 [Applab Datasets] Levelbuilder manifest edit page
  apps/Gruntfile.js
  apps/src/sites/studio/pages/datasets/show_manifest.js
  apps/src/storage/levelbuilder/ManifestEditor.jsx
  dashboard/app/controllers/datasets_controller.rb
  dashboard/app/models/ability.rb
  dashboard/app/views/datasets/show_manifest.html.haml
  dashboard/config/routes.rb
Labels: star-labs

#33066 [Applab Datasets] Show library preview on manifest edit page
  apps/src/sites/studio/pages/datasets/show_manifest.js
  apps/src/storage/levelbuilder/ManifestEditor.jsx
Labels: star-labs

#33073 I18n sync In & Up 02/11
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2019/coursec-2019.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#33118 Move storage strings to common
  apps/i18n/common/en_us.json
  apps/src/storage/dataBrowser/ConfirmImportButton.jsx
  apps/src/storage/dataBrowser/TableControls.jsx
Labels: star-labs

#32986 Updated Applab and Gamelab debugger to work with libraries
  apps/i18n/common/en_us.json
  apps/package.json
  apps/src/JavaScriptModeErrorHandler.js
  apps/src/StudioApp.js
  apps/src/applab/applab.js
  apps/src/lib/tools/jsinterpreter/JSInterpreter.js
  apps/src/p5lab/P5Lab.js
  apps/test/unit/StudioAppTest.js
  apps/yarn.lock
Labels: star-labs

#33068 [Applab Datasets] Implement submit button to change firebase manifest
  apps/src/storage/levelbuilder/ManifestEditor.jsx
  dashboard/app/controllers/datasets_controller.rb
  dashboard/app/models/ability.rb
  dashboard/config/routes.rb
  shared/middleware/helpers/firebase_helper.rb
Labels: star-labs

#33011 Set up controller and backend components for teachers to share libraries with their students.
  apps/src/code-studio/components/libraries/LibraryListItem.jsx
  apps/src/code-studio/initApp/project.js
  apps/test/unit/code-studio/initApp/projectTest.js
  dashboard/lib/projects_list.rb
  dashboard/test/lib/projects_list_test.rb
Labels: star-labs

#32919 Add subtitle and 'functions' section descriptions
  apps/i18n/common/en_us.json
  apps/src/code-studio/components/libraries/LibraryCreationDialog.jsx
  apps/src/code-studio/components/libraries/LibraryPublisher.jsx
Labels: star-labs

#33103 Simplify blocks edit page
  apps/src/code-studio/initializeCodeMirror.js
  apps/src/sites/studio/pages/blocks/edit.js
  apps/src/sites/studio/pages/levels/editors/_gamelab.js
Labels: star-labs

#33162 I18n sync In & Up 02/17
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#33185 Fix error thrown on load for the block edit page.
  apps/src/p5lab/spritelab/blocks.js
Labels: star-labs

#33173 [DataViz] Change modal title
  apps/i18n/common/en_us.json
Labels: star-labs

#33139 Scaffold for new pages
  apps/Gruntfile.js
  apps/src/sites/studio/pages/datasets/edit_manifest.js
  apps/src/sites/studio/pages/datasets/index.js
  apps/src/sites/studio/pages/datasets/show.js
  apps/src/storage/levelbuilder/Dataset.jsx
  apps/src/storage/levelbuilder/DatasetList.jsx
  dashboard/app/controllers/datasets_controller.rb
  dashboard/app/models/ability.rb
  dashboard/app/views/datasets/edit_manifest.html.haml
  dashboard/app/views/datasets/index.html.haml
  dashboard/app/views/datasets/show.html.haml
  dashboard/config/routes.rb
Labels: star-labs

#33188 HAML page for inputting secret login code
  dashboard/app/controllers/maker_controller.rb
  dashboard/app/views/maker/login_code.html.haml
  dashboard/config/routes.rb
Labels: star-labs

#33193 Add unit test for datasets_controller
  apps/src/storage/levelbuilder/ManifestEditor.jsx
  dashboard/app/controllers/datasets_controller.rb
  dashboard/test/controllers/datasets_controller_test.rb
Labels: star-labs

#33140 Add Datasets index page to Levelbuilder
  apps/src/sites/studio/pages/datasets/index.js
  apps/src/storage/levelbuilder/DatasetList.jsx
  dashboard/app/controllers/datasets_controller.rb
  dashboard/app/views/datasets/index.html.haml
  shared/middleware/helpers/firebase_helper.rb
Labels: star-labs

#33143 Fixed instance of weblab empty manifest issue from error in project creation.
  apps/i18n/weblab/en_us.json
  apps/src/clientApi.js
  apps/src/code-studio/assets.js
  apps/src/code-studio/assets/show.js
  apps/src/weblab/WebLab.js
  apps/src/weblab/WebLabView.jsx
  apps/src/weblab/actions.js
  apps/src/weblab/brambleHost.js
  apps/src/weblab/reducers.js
Labels: star-labs

#33172 Add Datasets show page to Levelbuilder
  apps/src/sites/studio/pages/datasets/show.js
  apps/src/storage/levelbuilder/Dataset.jsx
  dashboard/app/controllers/datasets_controller.rb
  dashboard/app/views/datasets/show.html.haml
  shared/middleware/helpers/firebase_helper.rb
Labels: star-labs

#33241 [Applab Datasets] Scroll data library pane
  apps/src/storage/dataBrowser/DataLibraryPane.jsx
  apps/src/storage/dataBrowser/LibraryTable.jsx
Labels: star-labs

#33253 [Maze] Don't allow action sounds to overlap
  apps/src/Sounds.js
  apps/src/StudioApp.js
  apps/src/lib/util/audioApi.js
  apps/src/maze/maze.js
  apps/test/unit/StudioAppTest.js
  apps/test/unit/code-studio/components/SoundListEntryTest.js
Labels: star-labs

#33240 [Applab Datasets] Add last updated time to library pane
  apps/src/storage/dataBrowser/LibraryTable.jsx
  bin/cron/applab_datasets/daily_weather
  bin/cron/applab_datasets/spotify
  shared/middleware/helpers/firebase_helper.rb
Labels: star-labs

#33270 I18n sync In & Up 02/24
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/weblab.json
  i18n/locales/source/course_content/2019/csd2-2019.json
  i18n/locales/source/course_content/2019/csd3-2019.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#33293 Change notification email for unmatched RP contact
  dashboard/app/models/pd/regional_partner_mini_contact.rb
  dashboard/test/models/pd/regional_partner_mini_contact_test.rb
Labels: professional-learning

#33313 Add back thingspeak api
  dashboard/app/controllers/xhr_proxy_controller.rb
Labels: star-labs

#33176 Implement dataset upload on levelbuilder page
  apps/src/storage/levelbuilder/Dataset.jsx
  bin/oneoff/applab_datasets/cats.csv
  bin/oneoff/applab_datasets/dogs.csv
  bin/oneoff/applab_datasets/states.csv
  bin/oneoff/applab_datasets/upload_csv_to_firebase
  bin/oneoff/applab_datasets/words.csv
  dashboard/app/controllers/datasets_controller.rb
  shared/middleware/helpers/firebase_helper.rb
  shared/test/middleware/helpers/test_firebase_helper.rb
Labels: star-labs

#33321 Add pastebin to allowlist
  dashboard/app/controllers/xhr_proxy_controller.rb
Labels: star-labs

#33312 [Applab] Fix error mesages for get/set key value with empty string
  apps/src/JavaScriptModeErrorHandler.js
  apps/src/storage/firebaseStorage.js
Labels: star-labs

#33250 Google Maker OAuth Display Code
  dashboard/app/controllers/maker_controller.rb
  dashboard/app/views/maker/display_code.html.haml
  dashboard/app/views/maker/login_code.html.haml
  dashboard/config/locales/en.yml
  dashboard/config/routes.rb
  dashboard/lib/encryption.rb
Labels: star-labs
