Repository code-dot-org/code-dot-org, pull requests merged in 2020-06, with the labels that each got.

#35066 I18n sync In & Up 06/01
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2017/coursec-2017.json
  i18n/locales/source/course_content/2017/coursed-2017.json
  i18n/locales/source/course_content/2017/coursee-2017.json
  i18n/locales/source/course_content/2017/coursef-2017.json
  i18n/locales/source/course_content/2017/express-2017.json
  i18n/locales/source/course_content/2018/coursec-2018.json
  i18n/locales/source/course_content/2018/coursed-2018.json
  i18n/locales/source/course_content/2018/coursee-2018.json
  i18n/locales/source/course_content/2018/coursef-2018.json
  i18n/locales/source/course_content/2018/express-2018.json
  i18n/locales/source/course_content/2019/coursec-2019.json
  i18n/locales/source/course_content/2019/coursed-2019.json
  i18n/locales/source/course_content/2019/coursee-2019.json
  i18n/locales/source/course_content/2019/coursef-2019.json
  i18n/locales/source/course_content/2019/csd2-2019.json
  i18n/locales/source/course_content/2019/csd3-2019.json
  i18n/locales/source/course_content/2019/csd4-2019.json
  i18n/locales/source/course_content/2019/csd5-2019.json
  i18n/locales/source/course_content/2019/csd6-2019.json
  i18n/locales/source/course_content/2019/express-2019.json
  i18n/locales/source/course_content/other/course2.json
  i18n/locales/source/course_content/other/course4.json
  i18n/locales/source/course_content/other/fesbinary.json
  i18n/locales/source/course_content/projects.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/markdown/public/break.md
Labels: i18n

#34975 [Sprite Lab] Set up shadowing for mini toolbox blocks
  apps/package.json
  apps/src/block_utils.js
  apps/yarn.lock
Labels: star-labs

#34751 App lab camera integration with photo chooser design element
  apps/i18n/applab/en_us.json
  apps/src/applab/DesignToolbox.jsx
  apps/src/applab/designElements/library.js
  apps/src/applab/designElements/photoSelect.jsx
  apps/src/applab/dropletConfig.js
  apps/src/applab/sanitizeHtml.js
  apps/src/applab/themeValues.js
  apps/static/applab/design_toolbox/camera.png
  apps/test/unit/applab/designElements/photoSelectTest.js
Labels: star-labs

#35081 Census: Move real CS offerings data to config folder
  dashboard/app/models/census/state_cs_offering.rb
  dashboard/config/state_cs_offerings/AK/2018-2019.csv
  dashboard/config/state_cs_offerings/AR/2018-2019.csv
  dashboard/config/state_cs_offerings/CA/2017-2018.csv
  dashboard/config/state_cs_offerings/CO/2018-2019.csv
  dashboard/config/state_cs_offerings/CT/2018-2019.csv
  dashboard/config/state_cs_offerings/DC/2018-2019.2.csv
  dashboard/config/state_cs_offerings/DE/2018-2019.2.csv
  dashboard/config/state_cs_offerings/FL/2018-2019.csv
  dashboard/config/state_cs_offerings/GA/2018-2019.csv
  dashboard/config/state_cs_offerings/HI/2017-2018.csv
  dashboard/config/state_cs_offerings/IA/2018-2019.csv
  dashboard/config/state_cs_offerings/ID/2018-2019.csv
  dashboard/config/state_cs_offerings/IL/2018-2019.csv
  dashboard/config/state_cs_offerings/IN/2018-2019.csv
  dashboard/config/state_cs_offerings/LA/2018-2019.csv
  dashboard/config/state_cs_offerings/MA/2018-2019.csv
  dashboard/config/state_cs_offerings/MD/2018-2019.csv
  dashboard/config/state_cs_offerings/ME/2018-2019.csv
  dashboard/config/state_cs_offerings/MN/2018-2019.csv
  dashboard/config/state_cs_offerings/MO/2018-2019.csv
  dashboard/config/state_cs_offerings/MS/2018-2019.csv
  dashboard/config/state_cs_offerings/MT/2018-2019.csv
  dashboard/config/state_cs_offerings/ND/2018-2019.csv
  dashboard/config/state_cs_offerings/NE/2018-2019.csv
  dashboard/config/state_cs_offerings/NH/2018-2019.2.csv
  dashboard/config/state_cs_offerings/NJ/2018-2019.2.csv
  dashboard/config/state_cs_offerings/NM/2018-2019.csv
  dashboard/config/state_cs_offerings/NY/2018-2019.csv
  dashboard/config/state_cs_offerings/OH/2018-2019.csv
  dashboard/config/state_cs_offerings/OR/2018-2019.csv
  dashboard/config/state_cs_offerings/PA/2018-2019.csv
  dashboard/config/state_cs_offerings/RI/2017-2018.2.csv
  dashboard/config/state_cs_offerings/RI/2018-2019.csv
  dashboard/config/state_cs_offerings/SC/2018-2019.csv
  dashboard/config/state_cs_offerings/SD/2018-2019.csv
  dashboard/config/state_cs_offerings/TX/2018-2019.csv
  dashboard/config/state_cs_offerings/UT/2018-2019.csv
  dashboard/config/state_cs_offerings/VA/2018-2019.csv
  dashboard/config/state_cs_offerings/VT/2018-2019.2.csv
  dashboard/config/state_cs_offerings/WI/2018-2019.csv
  dashboard/config/state_cs_offerings/WV/2018-2019.csv
  dashboard/config/state_cs_offerings/WY/2018-2019.csv
Labels: access report

#35027 Census: Support re-importing CS offering data
  dashboard/app/models/census/state_cs_offering.rb
  dashboard/config/state_cs_offerings/IL/2017-2018.csv
  dashboard/config/state_cs_offerings/MA/2017-2018.csv
  dashboard/config/state_cs_offerings/MD/2017-2018.csv
  dashboard/config/state_cs_offerings/NE/2017-2018.csv
  dashboard/config/state_cs_offerings/NJ/2017-2018.2.csv
  dashboard/config/state_cs_offerings/NY/2017-2018.csv
  dashboard/config/state_cs_offerings/OR/2017-2018.csv
  dashboard/config/state_cs_offerings/PA/2017-2018.csv
  dashboard/config/state_cs_offerings/VA/2017-2018.csv
Labels: access report

#34822 Add swipe prompt overlay to visualization area
  apps/src/StudioApp.js
  apps/src/bounce/BounceVisualizationColumn.jsx
  apps/src/bounce/bounce.js
  apps/src/code-studio/redux.js
  apps/src/craft/agent/CraftVisualizationColumn.jsx
  apps/src/craft/agent/craft.js
  apps/src/craft/designer/CraftVisualizationColumn.jsx
  apps/src/craft/designer/craft.js
  apps/src/craft/utils.js
  apps/src/dance/Dance.js
  apps/src/p5lab/gamelab/MobileControls.js
  apps/src/studio/StudioVisualizationColumn.jsx
  apps/src/studio/studio.js
  apps/src/templates/ArrowButtons.jsx
  apps/src/templates/SwipePrompt.jsx
  apps/src/templates/arrowDisplayRedux.js
  apps/src/templates/export/gamelabIndex.html.ejs
  apps/static/common_images/swipe-directions.png
  apps/static/common_images/touch-icon.png
  apps/style/common.scss
  apps/test/integration/levelTests.js
  apps/test/unit/templates/SwipePromptTest.js
Labels: star-labs

#35071 Updating blockly to enable truncating the non-category toolbox.
  apps/package.json
  apps/yarn.lock
Labels: star-labs

#35095 Census: Add 2016-2019 state CS offering files
  dashboard/app/models/census/state_cs_offering.rb
  dashboard/config/state_cs_offerings/CA/2018-2019.csv
  dashboard/config/state_cs_offerings/CO/2018-2019.csv
  dashboard/config/state_cs_offerings/CT/2018-2019.csv
  dashboard/config/state_cs_offerings/IL/2018-2019.csv
  dashboard/config/state_cs_offerings/MA/2016-2017.csv
  dashboard/config/state_cs_offerings/MA/2018-2019.csv
  dashboard/config/state_cs_offerings/MD/2018-2019.csv
  dashboard/config/state_cs_offerings/MN/2018-2019.csv
  dashboard/config/state_cs_offerings/NE/2018-2019.csv
  dashboard/config/state_cs_offerings/NJ/2017-2018.csv
  dashboard/config/state_cs_offerings/NJ/2018-2019.csv
  dashboard/config/state_cs_offerings/OH/2018-2019.csv
  dashboard/config/state_cs_offerings/OR/2018-2019.csv
  dashboard/config/state_cs_offerings/VA/2018-2019.csv
  dashboard/config/state_cs_offerings/WA/2018-2019.csv
Labels: access report

#35039 [SpriteLab] Add setup to reserved words
  apps/src/p5lab/spritelab/constants.js
Labels: star-labs

#35130 App lab camera integration fix
  apps/src/applab/commands.js
  apps/src/applab/designElements/photoSelect.jsx
Labels: star-labs

#35024 Constrain AnimationPicker dialog width
  apps/src/p5lab/AnimationPicker/AnimationPicker.jsx
  apps/src/p5lab/AnimationPicker/styles.js
Labels: star-labs

#35028 Fix cursor styles in LibraryManagerDialog
  apps/src/code-studio/components/libraries/LibraryListItem.jsx
  apps/src/code-studio/components/libraries/LibraryManagerDialog.jsx
Labels: star-labs

#34919 Text to speech block in app lab and game lab
  .drone.yml
  apps/i18n/common/en_us.json
  apps/package.json
  apps/src/Sound.js
  apps/src/Sounds.js
  apps/src/applab/dropletConfig.js
  apps/src/lib/util/audioApi.js
  apps/src/lib/util/audioApiDropletConfig.js
  apps/src/p5lab/gamelab/dropletConfig.js
  apps/src/util/experiments.js
  apps/test/unit/lib/util/audioApiTest.js
  apps/yarn.lock
  config.yml.erb
  config/development.yml.erb
  config/levelbuilder.yml.erb
  config/production.yml.erb
  config/staging.yml.erb
  config/test.yml.erb
  dashboard/app/controllers/projects_controller.rb
  dashboard/app/helpers/levels_helper.rb
  dashboard/app/helpers/view_options_helper.rb
  dashboard/app/models/game.rb
Labels: star-labs

#35047 [Applab Datasets] Modal Pickers for getColumn block
  apps/i18n/common/en_us.json
  apps/src/applab/dropletConfig.js
  apps/src/storage/GetColumnParamPicker.jsx
  apps/src/storage/dataBrowser/DataLibraryPane.jsx
  apps/src/storage/firebaseMetadata.js
  apps/src/storage/firebaseStorage.js
  apps/src/storage/getColumnDropdown.js
  apps/test/integration/levelSolutions/applab1/ec_data_blocks.js
  apps/test/unit/storage/firebaseMetadataTest.js
  lib/cdo/shared_constants.rb
Labels: star-labs

#35134 CRv2: Ignore contacts marked for deletion
  dashboard/app/models/contact_rollups_pardot_memory.rb
Labels: contact-rollups

#35183 CRv2: Re-enable creating new prospects in Pardot
  bin/cron/build_contact_rollups_v2
Labels: contact-rollups

#35119 CRv2: Use Sequel to avoid ActiveRecord timeout issue
  dashboard/app/models/contact_rollups_final.rb
  dashboard/app/models/contact_rollups_raw.rb
  dashboard/lib/contact_rollups_v2.rb
Labels: contact-rollups

#35195 I18n sync In & Up 06/08
  i18n/locales/source/blockly-mooc/applab.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/dance.json
  i18n/locales/source/course_content/2019/coursed-2019.json
  i18n/locales/source/course_content/2019/express-2019.json
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/markdown/public/athome.md
  i18n/locales/source/markdown/public/break.md
Labels: i18n

#35199 Census: Add 29 2019-2020 state CS files
  dashboard/config/state_cs_offerings/AL/2019-2020.csv
  dashboard/config/state_cs_offerings/AR/2019-2020.csv
  dashboard/config/state_cs_offerings/AZ/2019-2020.csv
  dashboard/config/state_cs_offerings/DC/2019-2020.csv
  dashboard/config/state_cs_offerings/DE/2019-2020.csv
  dashboard/config/state_cs_offerings/FL/2019-2020.csv
  dashboard/config/state_cs_offerings/GA/2019-2020.csv
  dashboard/config/state_cs_offerings/HI/2019-2020.csv
  dashboard/config/state_cs_offerings/ID/2019-2020.csv
  dashboard/config/state_cs_offerings/IN/2019-2020.csv
  dashboard/config/state_cs_offerings/LA/2019-2020.csv
  dashboard/config/state_cs_offerings/ME/2019-2020.csv
  dashboard/config/state_cs_offerings/MI/2019-2020.csv
  dashboard/config/state_cs_offerings/MO/2019-2020.csv
  dashboard/config/state_cs_offerings/MS/2019-2020.csv
  dashboard/config/state_cs_offerings/MT/2019-2020.csv
  dashboard/config/state_cs_offerings/NC/2019-2020.csv
  dashboard/config/state_cs_offerings/ND/2019-2020.csv
  dashboard/config/state_cs_offerings/NH/2019-2020.csv
  dashboard/config/state_cs_offerings/NM/2019-2020.csv
  dashboard/config/state_cs_offerings/OK/2019-2020.csv
  dashboard/config/state_cs_offerings/SD/2019-2020.csv
  dashboard/config/state_cs_offerings/TN/2019-2020.csv
  dashboard/config/state_cs_offerings/UT/2019-2020.csv
  dashboard/config/state_cs_offerings/VT/2019-2020.csv
  dashboard/config/state_cs_offerings/WA/2019-2020.csv
  dashboard/config/state_cs_offerings/WI/2019-2020.csv
  dashboard/config/state_cs_offerings/WV/2019-2020.csv
  dashboard/config/state_cs_offerings/WY/2019-2020.csv
Labels: access report

#35216 SafeNames does not abbreviate first names
  lib/cdo/safe_names.rb
  lib/test/cdo/test_safe_names.rb
Labels: bug-fix

#34984 Add Blob support to assertVisualMatch
  apps/src/imageUtils.js
  apps/test/unit/util/imageUtilsTest.js
Labels: testing

#34989 Micro:Bit Light Sensor Component
  apps/src/lib/kits/maker/boards/microBit/LightSensor.js
  apps/src/lib/kits/maker/boards/microBit/MBFirmataWrapper.js
  apps/src/lib/kits/maker/boards/microBit/MicroBitBoard.js
  apps/src/lib/kits/maker/boards/microBit/MicroBitComponents.js
  apps/src/lib/kits/maker/boards/microBit/MicroBitConstants.js
  apps/test/unit/lib/kits/maker/boards/makeStubBoard.js
  apps/test/unit/lib/kits/maker/boards/microBit/LightSensorTest.js
  apps/test/unit/lib/kits/maker/boards/microBit/MicroBitBoardTest.js
  apps/test/unit/lib/kits/maker/boards/microBit/MicroBitComponentsTest.js
Labels: star-labs

#35131 Pixelation widget now saves the width and height and bits per pixel
  dashboard/public/pixelation/pixelation.js
Labels: star-labs

#35215 [Sprite Lab]Set Up Mini Toolbox Pointer Blocks
  apps/i18n/spritelab/en_us.json
  apps/package.json
  apps/src/block_utils.js
  apps/src/p5lab/spritelab/blocks.js
  apps/yarn.lock
Labels: star-labs

#35157 Unpublish failure modal
  apps/i18n/common/en_us.json
  apps/src/templates/projects/LibraryTable.jsx
  apps/src/templates/projects/generateFakeProjects.js
  apps/test/unit/templates/projects/LibraryTableTest.js
Labels: star-labs

#35270 fixed showElement, hideElement, setProperty fix for photo select
  apps/src/applab/setPropertyDropdown.js
  apps/test/unit/applab/setPropertyDropdownTest.js
Labels: star-labs

#35234 CRv2: Add CloudWatch metrics
  bin/cron/build_contact_rollups_v2
  dashboard/app/models/contact_rollups_pardot_memory.rb
  dashboard/lib/contact_rollups_v2.rb
  lib/cdo/log_collector.rb
Labels: contact-rollups

#35226 [Spritelab] Use spaces in aliases
  apps/src/p5lab/spritelab/spriteCostumeLibrary.json
  tools/scripts/updateAnimationAliases.rb
Labels: star-labs

#35274 Updated cursor for short instructions to use a pointer
  dashboard/public/pixelation/pixelation.css
Labels: star-labs

#35248 CRv2: Use Sequel connection to find new and updated contacts
  dashboard/app/models/contact_rollups_pardot_memory.rb
  dashboard/lib/contact_rollups_v2.rb
Labels: contact-rollups

#35285 CRv2: Remove ContactRollupsRaw unique constraint
  dashboard/app/models/contact_rollups_raw.rb
  dashboard/db/migrate/20200611222103_remove_contact_rollups_raw_index.rb
  dashboard/db/schema.rb
Labels: contact-rollups

#35256 Darker workspace background in blockly labs when code is running
  apps/src/StudioApp.js
  shared/css/color.scss
Labels: star-labs

#35295 CRv2: Extract data from 5 tables
  dashboard/app/models/contact_rollups_raw.rb
Labels: contact-rollups

#35309 Add api.fungenerators.com
  dashboard/app/controllers/xhr_proxy_controller.rb
Labels: star-labs

#35305 Updated css to valid value. Correctly aligns minecraft buttons.
  apps/style/craft/style.scss
Labels: star-labs

#35289 Split out minecraft tests to address flakiness
  dashboard/test/ui/features/star_labs/can_see_finish.feature
  dashboard/test/ui/features/star_labs/craft/can_see_finish.feature
  dashboard/test/ui/features/star_labs/craft/hero.feature
  dashboard/test/ui/features/star_labs/craft/hero_logged_in.feature
  dashboard/test/ui/features/star_labs/craft/hero_logged_out.feature
Labels: star-labs

#35293 5 new Contact Rollups extraction steps
  dashboard/app/models/contact_rollups_raw.rb
Labels: contact-rollups

#35268 [Applab Datasets][Cleanup] Category description is not required
  apps/src/storage/dataBrowser/LibraryCategory.jsx
Labels: star-labs

#35313 CRv2: Extract data form 2 more tables
  dashboard/app/models/contact_rollups_raw.rb
Labels: contact-rollups

#35338 CRv2: Simplify extraction functions
  dashboard/app/models/contact_rollups_raw.rb
  dashboard/test/models/contact_rollups_raw_test.rb
Labels: contact-rollups

#35349 CRv2: Fix unit test failure
  dashboard/test/models/contact_rollups_raw_test.rb
Labels: contact-rollups

#35303 Updated spritelab migration to skip user-created animations and to run only when spritelab is loaded.
  apps/src/p5lab/P5Lab.js
  apps/src/p5lab/animationListModule.js
Labels: star-labs

#35328 Text to speech block backend
  dashboard/app/controllers/projects_controller.rb
  dashboard/app/helpers/levels_helper.rb
  dashboard/app/helpers/view_options_helper.rb
  dashboard/app/models/game.rb
  dashboard/test/controllers/projects_controller_test.rb
Labels: star-labs

#35342 [Maker] Add micro:bit category to Droplet toolbox
  apps/src/lib/kits/maker/boards/circuitPlayground/PlaygroundConstants.js
  apps/src/lib/kits/maker/boards/microBit/MicroBitConstants.js
  apps/src/lib/kits/maker/dropletConfig.js
  apps/src/lib/kits/maker/toolkit.js
  apps/src/util/experiments.js
  apps/test/unit/lib/kits/maker/dropletConfigTest.js
  lib/cdo/shared_constants.rb
Labels: star-labs

#35377 [Applab Datasets] Add covid19 live dataset script
  Gemfile
  Gemfile.lock
  bin/cron/applab_datasets/covid19
  cookbooks/cdo-apps/templates/default/crontab.erb
  dashboard/app/controllers/datasets_controller.rb
Labels: star-labs

#35370 Fix playlab js errors
  apps/src/studio/studio.js
  dashboard/config/scripts/levels/courseC_PlayLab_events5.level
  dashboard/config/scripts/levels/courseC_PlayLab_events5_2018.level
  dashboard/config/scripts/levels/courseC_PlayLab_events5_2019.level
Labels: star-labs

#35367 Remove unneeded PLC course un-slug logic
  dashboard/app/controllers/courses_controller.rb
  dashboard/test/controllers/courses_controller_integration_test.rb
  dashboard/test/controllers/courses_controller_test.rb
Labels: code-hygiene

#35394 [Applab Datasets] Downsample, don't aggregate covid-19 world data
  bin/cron/applab_datasets/covid19
Labels: star-labs

#35395 Correct Firmata Sketch Link for CPE
  apps/src/lib/kits/maker/ui/SetupChecklist.jsx
Labels: star-labs

#35347 CRv2: Enable all data extraction
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/app/models/contact_rollups_raw.rb
  dashboard/lib/contact_rollups_v2.rb
  dashboard/test/lib/contact_rollups_v2_test.rb
  dashboard/test/models/contact_rollups_processed_test.rb
  lib/cdo/log_collector.rb
  lib/test/cdo/test_log_collector.rb
Labels: contact-rollups

#35416 Revert "Darker workspace background in blockly labs when code is running"
  apps/src/StudioApp.js
Labels: star-labs

#35391 Bump Blockly to pull in Mini Toolbox changes
  apps/package.json
  apps/src/p5lab/spritelab/blocks.js
  apps/yarn.lock
  dashboard/config/blocks/GamelabJr/gamelab_clickedSpritePointer.json
  dashboard/config/blocks/GamelabJr/gamelab_objectSpritePointer.json
  dashboard/config/blocks/GamelabJr/gamelab_subjectSpritePointer.json
Labels: star-labs

#35396 [Spritelab] Add levelbuilder option to enable mini toolbox
  apps/src/block_utils.js
  dashboard/app/models/levels/gamelab_jr.rb
  dashboard/app/views/levels/editors/fields/_blockly.html.haml
  dashboard/app/views/levels/new.html.haml
Labels: star-labs

#35412 CRv2: Break processing time metric to collect and process metrics.
  dashboard/lib/contact_rollups_v2.rb
Labels: contact-rollups

#35402 CRv2: Allow setting number of rows to be extracted
  dashboard/app/models/contact_rollups_raw.rb
  dashboard/lib/contact_rollups_v2.rb
Labels: contact-rollups

#35410 CRv2: Update attribute processing methods
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/test/models/contact_rollups_processed_test.rb
Labels: contact-rollups

#35414 CRv2: Process user_id
  dashboard/app/models/contact_rollups_processed.rb
  lib/cdo/contact_rollups/v2/pardot.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#35423 I18n sync In & Up 06/22
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/other/k5-onlinepd-2019.json
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/markdown/public/athome.md
  i18n/locales/source/markdown/public/break.md
Labels: i18n

#35419 Darker background in blockly on run with update for modal editors
  apps/src/StudioApp.js
Labels: star-labs

#35448 CRv2: Process profession_learning_enrolled attribute
  dashboard/app/models/contact_rollups_pardot_memory.rb
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/test/models/contact_rollups_processed_test.rb
  dashboard/test/models/contact_rollups_raw_test.rb
  lib/cdo/contact_rollups/v2/pardot.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#35455 [Spritelab MiniToolbox] Shadow values on minitoolbox blocks when the minitoolbox opens.
  apps/package.json
  apps/src/block_utils.js
  apps/yarn.lock
Labels: star-labs

#35463 Open documentation in new tab
  apps/src/storage/dataBrowser/LibraryTable.jsx
Labels: star-labs

#35475 CRv2: Fix cronjob script
  bin/cron/build_contact_rollups_v2
Labels: contact-rollups

#35457 CRv2: Process professional_learning_attended attribute
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/lib/contact_rollups_v2.rb
  dashboard/test/models/contact_rollups_pardot_memory_test.rb
  dashboard/test/models/contact_rollups_processed_test.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#35443 Feedback dialog metrics
  apps/src/feedback.js
  apps/src/util/experiments.js
Labels: star-labs

#35472 CRv2: Fix download multi-value fields
  lib/cdo/contact_rollups/v2/pardot.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#35447 Updated tech requirements page to include Mobile and Intro to App Lab
  pegasus/sites.v3/code.org/public/educate/it.md
Labels: star-labs

#35466 [Spritelab] Distinguish between subject and clicked sprite in generated code
  apps/src/p5lab/spritelab/blocks.js
  apps/src/p5lab/spritelab/commands/spriteCommands.js
  apps/src/p5lab/spritelab/coreLibrary.js
  apps/test/unit/spritelab/coreLibraryTest.js
Labels: star-labs

#35515 Bump blockly to 3.5.24
  apps/package.json
  apps/yarn.lock
Labels: star-labs

#35518 added timeout error handling for azure token request
  dashboard/app/helpers/levels_helper.rb
Labels: star-labs

#35484 CRv2: Re-download Pardot prospects
  dashboard/app/models/contact_rollups_pardot_memory.rb
Labels: contact-rollups

#35490 CRv2: Process hoc_organizer_years attribute
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/test/models/contact_rollups_pardot_memory_test.rb
  dashboard/test/models/contact_rollups_processed_test.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#35351 Display informational warning when code is edited while its running
  apps/i18n/common/en_us.json
  apps/src/StudioApp.js
  apps/src/code-studio/components/WorkspaceAlert.jsx
  apps/src/templates/alert.jsx
  apps/test/unit/StudioAppTest.js
  apps/test/unit/code-studio/components/WorkspaceAlertTest.js
Labels: star-labs

#35429 Text to Speech Block Frontend
  apps/i18n/common/en_us.json
  apps/package.json
  apps/src/Sound.js
  apps/src/Sounds.js
  apps/src/applab/dropletConfig.js
  apps/src/lib/util/audioApi.js
  apps/src/lib/util/audioApiDropletConfig.js
  apps/src/lib/util/speech.js
  apps/src/p5lab/gamelab/dropletConfig.js
  apps/src/util/experiments.js
  apps/test/unit/lib/util/audioApiTest.js
  apps/webpack.js
  apps/yarn.lock
Labels: star-labs

#35505 CRv2: Process forms_submitted attribute
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/test/models/contact_rollups_pardot_memory_test.rb
  dashboard/test/models/contact_rollups_processed_test.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#35523 Fixes for LB page and readonly blockspace
  apps/package.json
  apps/src/block_utils.js
  apps/src/p5lab/spritelab/blocks.js
  apps/yarn.lock
Labels: star-labs

#35502 CRv2: Process form_roles attribute
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/test/models/contact_rollups_pardot_memory_test.rb
  dashboard/test/models/contact_rollups_processed_test.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#35442 [Applab Data] Allow periods in keys and table names
  apps/src/applab/applab.js
  apps/src/storage/firebaseCounters.js
  apps/src/storage/firebaseMetadata.js
  apps/src/storage/firebaseStorage.js
  apps/src/storage/firebaseUtils.js
  apps/test/unit/storage/FirebaseStorageTest.js
  apps/test/unit/storage/firebaseUtilsTest.js
  dashboard/config/routes.rb
  shared/middleware/helpers/firebase_helper.rb
Labels: star-labs

#35508 CRv2: Process roles attribute
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/app/models/contact_rollups_raw.rb
  dashboard/test/lib/contact_rollups_v2_test.rb
  dashboard/test/models/contact_rollups_pardot_memory_test.rb
  dashboard/test/models/contact_rollups_processed_test.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#35567 [Spritelab] Remove miniToolbox experiment
  apps/src/block_utils.js
  apps/src/util/experiments.js
Labels: star-labs

#35517 CRv2: Process state attribute
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/test/models/contact_rollups_pardot_memory_test.rb
  dashboard/test/models/contact_rollups_processed_test.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#35537 CRv2: Process city attribute
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/test/models/contact_rollups_pardot_memory_test.rb
  dashboard/test/models/contact_rollups_processed_test.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#35534 CRv2: Process country attribute
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/test/models/contact_rollups_pardot_memory_test.rb
  dashboard/test/models/contact_rollups_processed_test.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#35538 CRv2: Process postal_code attribute
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/test/models/contact_rollups_pardot_memory_test.rb
  dashboard/test/models/contact_rollups_processed_test.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups
