Repository code-dot-org/code-dot-org, pull requests merged in 2020-05, with the labels that each got.

#34525 Remove ContactRollupsComparison
  dashboard/app/models/contact_rollups_comparison.rb
  dashboard/lib/contact_rollups_v2.rb
  dashboard/test/models/contact_rollups_comparison_test.rb
Labels: contact-rollups

#34522 JS unit tests pass on ChromeHeadless
  apps/test/unit/promiseChainTest.js
  apps/test/unit/storage/dataUtilsTest.js
  apps/test/unit/templates/SchoolAutocompleteDropdownTest.js
Labels: testing

#34502 Fixed the android overflow bug.
  apps/src/templates/instructions/InstructionsWithWorkspace.jsx
  apps/test/unit/templates/instructions/InstructionsWithWorkspaceTest.jsx
Labels: star-labs

#34506 Hack Day Item #47-Pivot: Debug command metrics
  apps/src/lib/tools/jsdebugger/DebugButtons.jsx
  apps/src/lib/tools/jsdebugger/JsDebugger.jsx
Labels: star-labs

#34526 Migration to drop contact_rollups_comparison
  dashboard/db/migrate/20200429234529_drop_contact_rollups_comparison.rb
  dashboard/db/schema.rb
Labels: contact-rollups

#34540 Cross-browser visual match assertions in unit tests
  apps/package.json
  apps/src/imageUtils.js
  apps/src/studio/collisionMaskWalls.js
  apps/src/util/thumbnail.js
  apps/test/unit/util/imageUtilsTest.js
  apps/test/unit/util/squarePlayspaceThumbnail.png
  apps/test/unit/util/tallPlayspaceThumbnail.png
  apps/test/unit/util/thumbnailTest.js
  apps/test/util/assertVisualMatch.js
  apps/webpack.js
  apps/yarn.lock
Labels: testing

#34571 Fix Firefox bug where opacity filter breaks dropdown design elements
  apps/style/applab/skins/modern.scss
Labels: star-labs

#34587 I18n sync In & Up 05/04
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/other/k5-onlinepd-2019.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/activity-guidelines.md
  i18n/locales/source/markdown/public/athome.md
  i18n/locales/source/markdown/public/break.md
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#34591 I18n sync Down & Out 05/04
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/other/k5-onlinepd-2019.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/activity-guidelines.md
  i18n/locales/source/markdown/public/athome.md
  i18n/locales/source/markdown/public/break.md
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#34580 Handle multi-value fields when downloading Pardot prospects
  dashboard/app/models/contact_rollups_pardot_memory.rb
  lib/cdo/contact_rollups/v2/pardot.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#34550 Fix Zoom Helper: help touch users zoom back out again
  apps/i18n/common/en_us.json
  apps/src/templates/FixZoomHelper.jsx
  apps/src/templates/StudioAppWrapper.jsx
  apps/test/unit/templates/instructions/FixZoomHelperTest.jsx
Labels: star-labs

#34541 Add parent email to new contact rollups process
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/app/models/contact_rollups_raw.rb
  dashboard/lib/contact_rollups_v2.rb
  dashboard/test/models/contact_rollups_processed_test.rb
  dashboard/test/models/contact_rollups_raw_test.rb
Labels: contact-rollups

#34412 Add 'select all functions' checkbox to library export modal
  apps/i18n/common/en_us.json
  apps/src/code-studio/components/libraries/LibraryPublisher.jsx
  apps/test/unit/code-studio/components/libraries/LibraryPublisherTest.js
Labels: star-labs

#34590 Add google maps for startWebRequest
  dashboard/app/controllers/xhr_proxy_controller.rb
Labels: star-labs

#34594 [MicroBit] Rename ledMatrix -> ledScreen
  apps/src/lib/kits/maker/boards/microBit/LedScreen.js
  apps/src/lib/kits/maker/boards/microBit/MicroBitComponents.js
  apps/test/unit/lib/kits/maker/boards/MakerBoardTest.js
  apps/test/unit/lib/kits/maker/boards/microBit/LedScreenTest.js
  apps/test/unit/lib/kits/maker/boards/microBit/MicroBitBoardTest.js
  apps/test/unit/lib/kits/maker/boards/microBit/MicroBitComponentsTest.js
Labels: star-labs

#34611 Update the arrow buttons so they always display on one line. Especially on mobile.
  apps/src/templates/ArrowButtons.jsx
  apps/style/common.scss
  apps/style/craft/style.scss
Labels: star-labs

#34623 [Sprite Lab|Artist|Maze] Don't disable toolboxes while running
  apps/src/maze/maze.js
  apps/src/p5lab/P5Lab.js
  apps/src/turtle/artist.js
  dashboard/test/ui/features/star_labs/disable_toolbox_artist.feature
  dashboard/test/ui/features/star_labs/disable_toolbox_maze.feature
Labels: star-labs

#34631 [Artist] Delete limitedAutoRun option
  apps/src/turtle/artist.js
  dashboard/app/views/levels/editors/_artist.html.haml
  dashboard/config/scripts/levels/courseD_autorun_binary2_2019.level
  dashboard/config/scripts/levels/courseD_autorun_binary3_2019.level
  dashboard/config/scripts/levels/courseD_autorun_binary4_2019.level
  lib/cdo/shared_constants.rb
Labels: star-labs

#34639 Revert "Revert "Add parent email to new contact rollups process""
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/app/models/contact_rollups_raw.rb
  dashboard/test/models/contact_rollups_raw_test.rb
Labels: contact-rollups

#34614 Run first half of contact rollups daily at 5PM PST
  cookbooks/cdo-apps/templates/default/crontab.erb
Labels: contact-rollups

#34463 Implement infinite scroll for animation picker
  apps/src/p5lab/AnimationPicker/AnimationPickerBody.jsx
  apps/src/p5lab/AnimationTab/ScrollableList.jsx
  apps/test/unit/p5lab/AnimationPicker/AnimationPickerBodyTest.js
Labels: star-labs

#34701 Minecraft: Fix scroll-to-top on iPhone
  apps/src/craft/agent/craft.js
  apps/src/craft/aquatic/craft.js
  apps/src/craft/designer/craft.js
  apps/src/craft/simple/craft.js
Labels: star-labs

#34684 Set theme to default if handleChange event === null
  apps/src/applab/designElements/ThemeDropdown.jsx
  apps/test/unit/applab/designElements/ThemeDropdownTest.js
Labels: star-labs

#34633 [Student Libraries] Add error messaging when class libraries fail to load
  apps/i18n/common/en_us.json
  apps/src/code-studio/components/libraries/LibraryManagerDialog.jsx
  apps/test/unit/code-studio/components/libraries/libraryManagerDialogTest.js
Labels: star-labs

#34755 Alert contact rollups on account deletion
  dashboard/test/helpers/delete_accounts_helper_test.rb
  lib/cdo/delete_accounts_helper.rb
Labels: contact-rollups

#34732 Allow seeding of deleted contacts from Pardot
  dashboard/app/models/contact_rollups_pardot_memory.rb
  dashboard/test/models/contact_rollups_pardot_memory_test.rb
  lib/cdo/contact_rollups/v2/pardot.rb
  lib/cdo/contact_rollups/v2/pardot_helpers.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#34242 Part 2, delete prospects from Pardot: delete using Pardot API
  dashboard/app/models/contact_rollups_pardot_memory.rb
  dashboard/test/models/contact_rollups_pardot_memory_test.rb
  lib/cdo/contact_rollups/v2/pardot.rb
  lib/cdo/contact_rollups/v2/pardot_helpers.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#34516 Refactor MicroBit Tests
  apps/test/unit/lib/kits/maker/boards/FakeBoardTest.js
  apps/test/unit/lib/kits/maker/boards/MakerBoardTest.js
  apps/test/unit/lib/kits/maker/boards/circuitPlayground/CircuitPlaygroundBoardTest.js
  apps/test/unit/lib/kits/maker/boards/microBit/MicroBitBoardTest.js
Labels: star-labs

#34742 [Applab Datasets] Filter out empty records
  apps/src/storage/redux/data.js
Labels: star-labs

#34536 Add new Artist brushes
  apps/src/turtle/linePatterns.js
  apps/src/turtle/skins.js
  apps/static/common_images/brick-menuicon.png
  apps/static/common_images/brick.png
  apps/static/common_images/candycane-menuicon.png
  apps/static/common_images/candycane.png
  apps/static/common_images/dashline-menuicon.png
  apps/static/common_images/dashline.png
  apps/static/common_images/diamond-menuicon.png
  apps/static/common_images/diamond.png
  apps/static/common_images/dotline-menuicon.png
  apps/static/common_images/dotline.png
  apps/static/common_images/flower-pink-menuicon.png
  apps/static/common_images/flower-pink.png
  apps/static/common_images/flower-purple-menuicon.png
  apps/static/common_images/flower-purple.png
  apps/static/common_images/flower-yellow-menuicon.png
  apps/static/common_images/flower-yellow.png
  apps/static/common_images/heart-pink-menuicon.png
  apps/static/common_images/heart-pink.png
  apps/static/common_images/lightning-menuicon.png
  apps/static/common_images/lightning.png
  apps/static/common_images/pawprint-menuicon.png
  apps/static/common_images/pawprint.png
  apps/static/common_images/smiley-menuicon.png
  apps/static/common_images/smiley.png
  apps/static/common_images/smoke-menuicon.png
  apps/static/common_images/smoke.png
  apps/static/common_images/smoke2-menuicon.png
  apps/static/common_images/smoke2.png
  apps/static/common_images/spiky-menuicon.png
  apps/static/common_images/spiky.png
  apps/static/common_images/swirlyline2-menuicon.png
  apps/static/common_images/swirlyline2.png
  apps/static/common_images/tiretrack-menuicon.png
  apps/static/common_images/tiretrack.png
  apps/static/common_images/traintrack-menuicon.png
  apps/static/common_images/traintrack.png
  apps/static/common_images/water-menuicon.png
  apps/static/common_images/water.png
Labels: star-labs

#34657 Add parent email to full contact rollups run
  dashboard/lib/contact_rollups_v2.rb
  dashboard/test/lib/contact_rollups_v2_test.rb
Labels: contact-rollups

#34772 Assignment Metrics: set pageType correctly on script overview
  apps/src/code-studio/progress.js
Labels: bug-fix

#34794 More limited override of prospect information
  lib/cdo/contact_rollups/v2/pardot.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#34722 MicroBit Shake Event
  apps/src/lib/kits/maker/boards/microBit/Accelerometer.js
  apps/src/lib/kits/maker/boards/microBit/MBFirmataWrapper.js
  apps/src/lib/kits/maker/commands.js
  apps/test/unit/lib/kits/maker/boards/microBit/AccelerometerTest.js
Labels: star-labs

#34843 Updated pre-work link in faciltator workshop reminder
  dashboard/app/views/pd/workshop_mailer/_teacher_enrollment_details_facilitator.html.haml
Labels: content-change

#34839 Add api for covidtracking
  dashboard/app/controllers/xhr_proxy_controller.rb
Labels: star-labs

#34813 MicroBit Compass
  apps/src/lib/kits/maker/boards/microBit/Compass.js
  apps/src/lib/kits/maker/boards/microBit/MicroBitComponents.js
  apps/src/lib/kits/maker/boards/microBit/MicroBitConstants.js
  apps/test/unit/lib/kits/maker/boards/microBit/CompassTest.js
  apps/test/unit/lib/kits/maker/boards/microBit/MicroBitBoardTest.js
  apps/test/unit/lib/kits/maker/boards/microBit/MicroBitComponentsTest.js
Labels: star-labs

#34847 I18n sync In & Up 05/18
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2017/coursea-2017.json
  i18n/locales/source/course_content/2017/courseb-2017.json
  i18n/locales/source/course_content/2017/coursec-2017.json
  i18n/locales/source/course_content/2017/coursed-2017.json
  i18n/locales/source/course_content/2017/coursee-2017.json
  i18n/locales/source/course_content/2017/coursef-2017.json
  i18n/locales/source/course_content/2017/express-2017.json
  i18n/locales/source/course_content/2017/pre-express-2017.json
  i18n/locales/source/course_content/2018/courseb-2018.json
  i18n/locales/source/course_content/2018/coursec-2018.json
  i18n/locales/source/course_content/2018/coursed-2018.json
  i18n/locales/source/course_content/2018/coursee-2018.json
  i18n/locales/source/course_content/2018/coursef-2018.json
  i18n/locales/source/course_content/2018/express-2018.json
  i18n/locales/source/course_content/2018/pre-express-2018.json
  i18n/locales/source/course_content/2019/courseb-2019.json
  i18n/locales/source/course_content/2019/coursec-2019.json
  i18n/locales/source/course_content/2019/coursed-2019.json
  i18n/locales/source/course_content/2019/coursee-2019.json
  i18n/locales/source/course_content/2019/coursef-2019.json
  i18n/locales/source/course_content/2019/express-2019.json
  i18n/locales/source/course_content/2019/pre-express-2019.json
  i18n/locales/source/course_content/Hour of Code/artist.json
  i18n/locales/source/course_content/Hour of Code/hero.json
  i18n/locales/source/course_content/other/K5-OnlinePD.json
  i18n/locales/source/course_content/other/course1.json
  i18n/locales/source/course_content/other/course2.json
  i18n/locales/source/course_content/other/course3.json
  i18n/locales/source/course_content/other/course4.json
  i18n/locales/source/course_content/other/fesbinary.json
  i18n/locales/source/course_content/other/k5-onlinepd-2019.json
  i18n/locales/source/course_content/projects.json
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/markdown/public/break.md
Labels: i18n

#34829 Add maps.googleapis.com to startWebRequest()
  dashboard/app/controllers/xhr_proxy_controller.rb
Labels: star-labs

#34833 Use channelId as element key instead of name
  apps/src/code-studio/components/libraries/LibraryManagerDialog.jsx
  apps/test/unit/code-studio/components/libraries/libraryManagerDialogTest.js
Labels: star-labs

#34675 Show library code in function tooltip
  apps/src/blockTooltips/DropletBlockTooltipManager.js
  apps/src/blockTooltips/DropletFunctionTooltip.html.ejs
  apps/src/blockTooltips/DropletFunctionTooltip.js
  apps/style/common.scss
Labels: star-labs

#34858 Make 'select all functions' bold
  apps/src/code-studio/components/libraries/LibraryPublisher.jsx
Labels: star-labs

#34879 Contact rollups dry run
  bin/cron/build_contact_rollups_v2
  dashboard/app/models/contact_rollups_pardot_memory.rb
  dashboard/lib/contact_rollups_v2.rb
  dashboard/test/lib/contact_rollups_v2_test.rb
  dashboard/test/models/contact_rollups_pardot_memory_test.rb
  lib/cdo/contact_rollups/v2/pardot.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: contact-rollups

#34920 [Applab] Gracefully handle when there's no callback
  apps/src/lib/util/timeoutApi.js
Labels: star-labs

#34916 Add crypto currency tracker to hostnames
  dashboard/app/controllers/xhr_proxy_controller.rb
Labels: star-labs

#34907 Remove library by channelId instead of name
  apps/src/code-studio/components/libraries/LibraryListItem.jsx
  apps/src/code-studio/components/libraries/LibraryManagerDialog.jsx
  apps/test/unit/code-studio/components/libraries/libraryManagerDialogTest.js
Labels: star-labs

#34937 Revert Revert "Show library code in function tooltip"
  apps/src/blockTooltips/DropletBlockTooltipManager.js
  apps/src/blockTooltips/DropletFunctionTooltip.html.ejs
  apps/src/blockTooltips/DropletFunctionTooltip.js
  apps/style/common.scss
Labels: star-labs

#34925 Census: seed state CS offerings collected in 2020
  dashboard/app/models/census/state_cs_offering.rb
  lib/cdo/aws/s3.rb
Labels: access report

#34880 [Student Libraries] Enable filtering class libraries by section
  apps/i18n/common/en_us.json
  apps/src/code-studio/components/libraries/LibraryManagerDialog.jsx
  apps/test/unit/code-studio/components/libraries/libraryManagerDialogTest.js
  dashboard/lib/projects_list.rb
  dashboard/test/lib/projects_list_test.rb
Labels: star-labs

#34887 Add rollback and retry logic
  bin/cron/build_contact_rollups_v2
  dashboard/app/models/contact_rollups_final.rb
  dashboard/app/models/contact_rollups_pardot_memory.rb
  dashboard/app/models/contact_rollups_processed.rb
  dashboard/app/models/contact_rollups_raw.rb
  dashboard/lib/contact_rollups_v2.rb
  dashboard/test/lib/contact_rollups_v2_test.rb
  lib/cdo/contact_rollups/v2/pardot.rb
  lib/cdo/contact_rollups/v2/pardot_helpers.rb
  lib/cdo/log_collector.rb
  lib/test/cdo/contact_rollups/test_pardot_helpers.rb
Labels: contact-rollups

#34969 Temporarily disable parent email extraction
  dashboard/lib/contact_rollups_v2.rb
  dashboard/test/lib/contact_rollups_v2_test.rb
Labels: contact-rollups

#34977 Address an old TODO
  apps/test/integration/levelSolutions/applab1/ec_design.js
Labels: testing

#34965 Remove applabDatasets experiment
  apps/src/applab/applab.js
  apps/src/applab/dropletConfig.js
  apps/src/lib/util/javascriptMode.js
  apps/src/storage/dataBrowser/AddKeyRow.jsx
  apps/src/storage/dataBrowser/AddTableRow.jsx
  apps/src/storage/dataBrowser/DataOverview.jsx
  apps/src/storage/dataBrowser/DataTableView.jsx
  apps/src/storage/dataBrowser/DataWorkspace.jsx
  apps/src/storage/dataBrowser/EditKeyRow.jsx
  apps/src/storage/dataBrowser/EditTableRow.jsx
  apps/src/storage/dataBrowser/KVPairs.jsx
  apps/src/storage/dataBrowser/TableControls.jsx
  apps/src/storage/dataBrowser/dataUtils.js
  apps/src/util/experiments.js
  apps/test/integration/levelSolutions/applab1/ec_data_browser.js
  apps/test/unit/storage/dataUtilsTest.js
  dashboard/test/ui/features/star_labs/applab/eyes3.feature
  dashboard/test/ui/features/star_labs/applab/level_options.feature
Labels: star-labs

#34955 Census: Empty state exclusion list
  dashboard/app/models/census/state_cs_offering.rb
  dashboard/test/models/census/census_summary_test.rb
Labels: access report

#34967 Remove student-libraries experiment
  apps/src/code-studio/components/AdvancedShareOptions.jsx
  apps/src/lib/ui/SettingsCog.jsx
  apps/src/templates/projects/ProjectsGallery.jsx
  apps/src/util/experiments.js
  dashboard/config/scripts/levels/New App Lab Project.level
Labels: star-labs

#35013 CRv2: Enable the full pipeline
  bin/cron/build_contact_rollups_v2
Labels: contact-rollups

#34954 Census: seed 2019-2020 AP CS offerings
  dashboard/app/models/census/ap_cs_offering.rb
  dashboard/app/models/census/ap_school_code.rb
Labels: access report

#35040 CRv2: Disable adding new prospects to Pardot
  bin/cron/build_contact_rollups_v2
  dashboard/lib/contact_rollups_v2.rb
  dashboard/test/lib/contact_rollups_v2_test.rb
Labels: contact-rollups
