Repository code-dot-org/code-dot-org, pull requests merged in 2020-10, with the labels that each got.

#36957 Check for code changes when the user finishes a level
  apps/src/StudioApp.js
  apps/src/applab/applab.js
  apps/src/code-studio/initApp/project.js
  apps/src/constants.js
  apps/src/p5lab/P5Lab.js
  apps/test/unit/StudioAppTest.js
  apps/test/unit/code-studio/initApp/projectTest.js
Labels: auto-validation

#36938 upgrade rails-controller-testing gem to 1.0.5
  Gemfile
  Gemfile.lock
Labels: Rails 6

#36861 Update Responders gem to 3.0
  Gemfile
  Gemfile.lock
Labels: Rails 6

#37063 Add an "unfinished" state to the finish dialog for lab levels
  apps/i18n/common/en_us.json
  apps/src/StudioApp.js
  apps/src/feedback.js
  apps/src/p5lab/P5Lab.js
  apps/src/templates/instructions/TopInstructions.jsx
  apps/src/templates/instructions/utils.js
Labels: auto-validation

#37091 update paranoia gem to 2.4.2
  Gemfile
  Gemfile.lock
Labels: Rails 6

#36981 Auto-validation checkbox in level builder
  apps/Gruntfile.js
  apps/src/applab/applab.js
  apps/src/p5lab/P5Lab.js
  apps/src/redux/pageConstants.js
  apps/src/sites/studio/pages/levels/editors/fields/_validation_code.js
  apps/src/turtle/artist.js
  apps/src/weblab/WebLab.js
  apps/style/code-studio/levelbuilder.scss
  dashboard/app/models/levels/applab.rb
  dashboard/app/models/levels/artist.rb
  dashboard/app/models/levels/gamelab.rb
  dashboard/app/models/levels/weblab.rb
  dashboard/app/views/levels/editors/fields/_auto_validation_checkbox.html.haml
  dashboard/app/views/levels/editors/fields/_code_area.html.haml
  dashboard/app/views/levels/editors/fields/_special_level_types.html.haml
  dashboard/app/views/levels/editors/fields/_validation_code.html.haml
Labels: auto-validation

#36976 Upgrade annotate gem to 3.1.1
  Gemfile
  Gemfile.lock
  dashboard/app/models/assessment_activity.rb
  dashboard/app/models/authored_hint_view_request.rb
  dashboard/app/models/lesson.rb
  dashboard/app/models/level_source_image.rb
  dashboard/app/models/levels_script_level.rb
  dashboard/app/models/paired_user_level.rb
  dashboard/app/models/pd/misc_survey.rb
  dashboard/app/models/pd/post_course_survey.rb
  dashboard/app/models/pd/survey_question.rb
  dashboard/app/models/pd/workshop_daily_survey.rb
  dashboard/app/models/pd/workshop_facilitator_daily_survey.rb
  dashboard/app/models/peer_review.rb
  dashboard/app/models/script_level.rb
  dashboard/app/models/teacher_score.rb
  dashboard/app/models/user_level.rb
Labels: Rails 6

#37094 Use our custom fork of sassc-rails
  Gemfile
  Gemfile.lock
Labels: Rails 6

#36936 Optionally view workshop map with Mapbox
  apps/src/sites/code.org/pages/views/workshop_search.js
  dashboard/app/controllers/api/v1/pd/workshops_controller.rb
  pegasus/sites.v3/code.org/views/workshop_search.haml
Labels: mapbox

#37153 Remove Google Maps code in favor of Mapbox
  apps/src/sites/code.org/pages/views/workshop_search.js
  pegasus/sites.v3/code.org/views/workshop_search.haml
Labels: mapbox

#37124 Enable auto validation on a small set of levels
  apps/src/feedback.js
  apps/src/sites/studio/pages/levels/editors/fields/_validation_code.js
  dashboard/app/models/levels/applab.rb
  dashboard/app/models/levels/artist.rb
  dashboard/app/models/levels/gamelab.rb
  dashboard/app/models/levels/weblab.rb
  dashboard/config/scripts/levels/CSD games sidescroll background.level
  dashboard/config/scripts/levels/CourseE_Project_SpriteLab_2020.level
  dashboard/config/scripts/levels/U5 L03 Lists Practice 1.level
  dashboard/config/scripts/levels/courseE_aboutme_3_2020.level
Labels: auto-validation

#37271 Switch back to mainline seamless_database_pool
  Gemfile
  Gemfile.lock
Labels: Rails 6

#37273 replace string conditionals with lambdas
  dashboard/app/models/user.rb
Labels: Rails 6

#37274 Stringify all uses of class_name
  dashboard/app/models/follower.rb
  dashboard/app/models/regional_partner.rb
  dashboard/app/models/user.rb
Labels: Rails 6

#37347 Gracefully handle null startBlocks in auto-validation
  apps/src/code-studio/initApp/project.js
  apps/test/unit/code-studio/initApp/projectTest.js
Labels: auto-validation

#37305 Enable auto-validation in Web Lab
  apps/src/StudioApp.js
  apps/src/feedback.js
  apps/src/redux/pageConstants.js
  apps/src/weblab/WebLab.js
  apps/src/weblab/brambleHost.js
  apps/test/integration/feedbackTests.js
  apps/test/unit/weblab/weblabTest.js
  dashboard/config/scripts/levels/CSDU2 - Type Anything_2020.level
Labels: auto-validation

#37340 Enabled time_spent logging on Web Lab.
  apps/src/StudioApp.js
  apps/src/weblab/WebLab.js
Labels: time-spent

#37360 Enabled validation on all relevant Web Lab levels in csd 2020
  dashboard/config/scripts/levels/CSD U2 CSS explore CSS_2020.level
  dashboard/config/scripts/levels/CSD U2 CSS_2020.level
  dashboard/config/scripts/levels/CSD U2 HTML Adding Paragraphs pt 2_2020.level
  dashboard/config/scripts/levels/CSD U2 HTML Adding Paragraphs_2020.level
  dashboard/config/scripts/levels/CSD U2 HTML Debug Paragraphs_2020.level
  dashboard/config/scripts/levels/CSD U2 Heading Demo_2020.level
  dashboard/config/scripts/levels/CSD U2 Heading Sizes_2020.level
  dashboard/config/scripts/levels/CSD U2 Heading Test_2020.level
  dashboard/config/scripts/levels/CSD U2 Heading debug_2020.level
  dashboard/config/scripts/levels/CSD U2 Image Credit_2020.level
  dashboard/config/scripts/levels/CSD U2 Image Tag 1_2020.level
  dashboard/config/scripts/levels/CSD U2 Image Tag 2_2020.level
  dashboard/config/scripts/levels/CSD U2 Image Tag Debug_2020.level
  dashboard/config/scripts/levels/CSD U2 Image assessment_2020.level
  dashboard/config/scripts/levels/CSD U2 Image choose name_2020.level
  dashboard/config/scripts/levels/CSD U2 Inspector Warm Up_2020.level
  dashboard/config/scripts/levels/CSD U2 add content_2020.level
  dashboard/config/scripts/levels/CSD U2 add file_2020.level
  dashboard/config/scripts/levels/CSD U2 add style_2020.level
  dashboard/config/scripts/levels/CSD U2 adding pages_2020.level
  dashboard/config/scripts/levels/CSD U2 classes haikus.level
  dashboard/config/scripts/levels/CSD U2 classes humors.level
  dashboard/config/scripts/levels/CSD U2 classes waterfalls.level
  dashboard/config/scripts/levels/CSD U2 layout style bgcolor_2020.level
  dashboard/config/scripts/levels/CSD U2 layout style body_2020.level
  dashboard/config/scripts/levels/CSD U2 layout style float_2020.level
  dashboard/config/scripts/levels/CSD U2 layout style sample_2020.level
  dashboard/config/scripts/levels/CSD U2 layout style width_2020.level
  dashboard/config/scripts/levels/CSD U2 link demo_2020.level
  dashboard/config/scripts/levels/CSD U2 making links_2020.level
  dashboard/config/scripts/levels/CSD U2 naming links_2020.level
  dashboard/config/scripts/levels/CSD U2 naming pages_2020.level
  dashboard/config/scripts/levels/CSD U2 nav bar_2020.level
  dashboard/config/scripts/levels/CSD U2 project review_2020.level
  dashboard/config/scripts/levels/CSD U2 project share_2020.level
  dashboard/config/scripts/levels/CSD U2 text style h1_2020.level
  dashboard/config/scripts/levels/CSD U2 text style h3_2020.level
  dashboard/config/scripts/levels/CSD U2 text style size_2020.level
  dashboard/config/scripts/levels/CSD U2 upload images_2020.level
  dashboard/config/scripts/levels/CSD Web CSS Assessment_2020.level
  dashboard/config/scripts/levels/CSD Web incorporate feedback_2020.level
  dashboard/config/scripts/levels/CSD web CSS project CSS.level
  dashboard/config/scripts/levels/CSD web CSS project HTML.level
  dashboard/config/scripts/levels/CSD web CSS project check.level
  dashboard/config/scripts/levels/CSD web HTML project HTML.level
  dashboard/config/scripts/levels/CSD web HTML project check.level
  dashboard/config/scripts/levels/CSD web add CSS_2020.level
  dashboard/config/scripts/levels/CSD web add html_2020.level
  dashboard/config/scripts/levels/CSD web check_2020.level
  dashboard/config/scripts/levels/CSD web create pages project.level
  dashboard/config/scripts/levels/CSD web share CSS_2020.level
  dashboard/config/scripts/levels/CSD web share html_2020.level
  dashboard/config/scripts/levels/CSD web upload images multi_2020.level
Labels: auto-validation

#37376 Removed duplicate reference to 'total lines of code' from the cookie
  apps/src/code-studio/clientState.js
  apps/src/code-studio/header.js
  apps/src/code-studio/initApp/loadApp.js
  apps/src/code-studio/progressRedux.js
  apps/src/feedback.js
  apps/src/templates/feedback/CodeWritten.jsx
  apps/test/unit/code-studio/clientStateTest.js
  apps/test/unit/code-studio/progressReduxTest.js
  dashboard/app/controllers/activities_controller.rb
  dashboard/app/helpers/users_helper.rb
  dashboard/lib/client_state.rb
  dashboard/test/controllers/activities_controller_test.rb
  dashboard/test/controllers/api_controller_test.rb
  dashboard/test/helpers/application_helper_test.rb
Labels: progress-leak

#37461 Pass IDs rather than objects to `.destroy`
  dashboard/lib/services/script_seed.rb
Labels: Rails 6

#37471 Hook up Share to Google button in send lesson dialog
  apps/i18n/common/en_us.json
  apps/src/code-studio/progress.js
  apps/src/templates/progress/SendLessonDialog.jsx
  apps/src/templates/progress/SendLessonDialog.story.jsx
  apps/test/unit/templates/progress/SendLessonDialogTest.js
Labels: learning-platform

#37470 I18n sync In & Up 10/26
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/applab.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/spritelab.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/hourofcode/international-partners.md
  i18n/locales/source/hourofcode/promote/stats.md
  i18n/locales/source/markdown/public/athome.md
Labels: i18n

#37487 Update capture_queries cache detection logic
  dashboard/test/testing/capture_queries.rb
Labels: Rails 6

#37533 Changed 'retry' button from 'try again' to 'keep working'
  apps/i18n/common/en_us.json
  apps/src/feedback.js
Labels: auto-validation

#37531 Updated the auto-validation dialog to use new strings.
  apps/i18n/common/en_us.json
Labels: auto-validation
