Repository code-dot-org/code-dot-org, pull requests merged in 2021-12, with the labels that each got.

#43763 Only show inline answers to instructors of course
  dashboard/app/controllers/lessons_controller.rb
  dashboard/app/helpers/levels_helper.rb
  dashboard/app/models/script_level.rb
  dashboard/app/views/levels/_free_response.html.haml
  dashboard/app/views/levels/_level_group.haml
  dashboard/app/views/levels/_match_answer.html.haml
  dashboard/app/views/levels/_multi_answer.html.haml
  dashboard/app/views/levels/_single_multi.html.haml
  dashboard/app/views/levels/_teacher_markdown.html.haml
  dashboard/app/views/levels/show.html.haml
  dashboard/lib/policies/inline_answer.rb
  dashboard/test/controllers/script_levels_controller_test.rb
  dashboard/test/factories/factories.rb
  dashboard/test/fixtures/test-serialize-seeding-json.script_json
  dashboard/test/integration/db_query_test.rb
  dashboard/test/lib/policies/inline_answer_test.rb
  dashboard/test/models/concerns/curriculum/course_types_test.rb
  dashboard/test/models/script_level_test.rb
Labels: self-paced-pl

#43843 Make sure instructor and participant audiences are not equal
  dashboard/app/models/concerns/curriculum/course_types.rb
  dashboard/test/models/concerns/curriculum/course_types_test.rb
Labels: self-paced-pl

#43522 Show teacher panel on cached pages
  apps/src/code-studio/components/progress/teacherPanel/TeacherPanel.jsx
  apps/src/code-studio/initApp/loadApp.js
  apps/src/sites/studio/pages/levels/_teacher_panel.js
  apps/test/unit/code-studio/components/progress/teacherPanel/TeacherPanelTest.jsx
  apps/test/unit/code-studio/initApp/loadAppTest.js
  dashboard/app/controllers/api_controller.rb
  dashboard/app/controllers/script_levels_controller.rb
  dashboard/app/helpers/levels_helper.rb
  dashboard/app/views/levels/show.html.haml
  dashboard/app/views/scripts/lesson_extras.html.haml
  dashboard/test/controllers/script_levels_controller_test.rb
  dashboard/test/helpers/levels_helper_test.rb
Labels: cached level teacher view

#43825 I18n sync In 11/29
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/javalab.json
  i18n/locales/source/blockly-mooc/poetry.json
  i18n/locales/source/course_content/2017/coursee-2017.json
  i18n/locales/source/course_content/2017/coursef-2017.json
  i18n/locales/source/course_content/2017/express-2017.json
  i18n/locales/source/course_content/2019/coursec-2019.json
  i18n/locales/source/course_content/2019/coursee-2019.json
  i18n/locales/source/course_content/2019/coursef-2019.json
  i18n/locales/source/course_content/2019/express-2019.json
  i18n/locales/source/course_content/2020/coursec-2020.json
  i18n/locales/source/course_content/2020/coursee-2020.json
  i18n/locales/source/course_content/2020/coursef-2020.json
  i18n/locales/source/course_content/2020/express-2020.json
  i18n/locales/source/course_content/2021/coursec-2021.json
  i18n/locales/source/course_content/2021/coursee-2021.json
  i18n/locales/source/course_content/2021/coursef-2021.json
  i18n/locales/source/course_content/2021/express-2021.json
  i18n/locales/source/course_content/Hour of Code/hello-world-animals-2021.json
  i18n/locales/source/course_content/Hour of Code/hello-world-emoji-2021.json
  i18n/locales/source/course_content/Hour of Code/hello-world-food-2021.json
  i18n/locales/source/course_content/Hour of Code/hello-world-retro-2021.json
  i18n/locales/source/course_content/Hour of Code/poem-art-2021.json
  i18n/locales/source/course_content/other/course3.json
  i18n/locales/source/course_content/other/course4.json
  i18n/locales/source/course_content/other/hello-world-animals.json
  i18n/locales/source/course_content/other/hello-world-emoji.json
  i18n/locales/source/course_content/other/hello-world-food.json
  i18n/locales/source/course_content/other/hello-world-retro.json
  i18n/locales/source/course_content/other/outbreak.json
  i18n/locales/source/course_content/other/poem-art.json
  i18n/locales/source/course_content/other/poetry-hoc3.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/progressions.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/dashboard/slides.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/hourofcode/promote/resources.md
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#43886 Fix translations for HoC markdown pages
  pegasus/sites.v3/code.org/i18n/public/educate/csc.ar-SA.md.partial
  pegasus/sites.v3/code.org/i18n/public/educate/csc.cs-CZ.md.partial
  pegasus/sites.v3/code.org/i18n/public/educate/csc.de-DE.md.partial
  pegasus/sites.v3/code.org/i18n/public/educate/csc.hi-IN.md.partial
  pegasus/sites.v3/code.org/i18n/public/educate/csc.ja-JP.md.partial
  pegasus/sites.v3/code.org/i18n/public/educate/csc.ms-MY.md.partial
  pegasus/sites.v3/code.org/i18n/public/helloworld.id-ID.md.partial
Labels: i18n

#43990 Make everything used verified_teacher instead of authorized_teacher
  dashboard/app/controllers/activities_controller.rb
  dashboard/app/controllers/api/v1/assessments_controller.rb
  dashboard/app/helpers/levels_helper.rb
  dashboard/app/helpers/users_helper.rb
  dashboard/app/models/lesson.rb
  dashboard/app/models/plc/user_course_enrollment.rb
  dashboard/app/models/script_level.rb
  dashboard/app/models/teacher_feedback.rb
  dashboard/app/models/user.rb
  dashboard/app/models/user_permission.rb
  dashboard/app/views/courses/show.html.haml
  dashboard/app/views/scripts/show.html.haml
  dashboard/test/models/concerns/user_permission_grantee_test.rb
  dashboard/test/models/user_test.rb
Labels: self-paced-pl

#43991 Remove page constant which can be retrieved from redux store
  apps/src/StudioApp.js
  apps/src/code-studio/appOptions.js
  apps/src/redux/pageConstants.js
  apps/src/templates/instructions/teacherFeedback/EditableTeacherFeedback.jsx
  dashboard/app/helpers/levels_helper.rb
Labels: self-paced-pl

#43994 Update testing data to set new course type fields
  dashboard/test/fixtures/script.yml
  dashboard/test/fixtures/unit_groups.yml
  dashboard/test/ui/config/scripts_json/ui-test-script-in-course-2017.script_json
  dashboard/test/ui/config/scripts_json/ui-test-script-in-course-2019.script_json
  dashboard/test/ui/config/scripts_json/ui-test-versioned-script-2017.script_json
  dashboard/test/ui/config/scripts_json/ui-test-versioned-script-2019.script_json
Labels: self-paced-pl

#43999 On LevelGroup in Readonly Mode do not show Teacher Only Box
  dashboard/app/controllers/activities_controller.rb
  dashboard/app/views/levels/_teacher_markdown.html.haml
  dashboard/config/locales/scripts.en.yml
  dashboard/config/scripts/allthethings_example_csp_assessment.level_group
  dashboard/config/scripts_json/allthethings.script_json
  dashboard/test/ui/features/learning_platform/lesson_lock.feature
  dashboard/test/ui/features/step_definitions/lesson_management_steps.rb
Labels: self-paced-pl

#43993 Update assignable_for_user? to check instructor instead of teacher
  dashboard/app/models/concerns/curriculum/course_types.rb
  dashboard/app/models/script.rb
  dashboard/app/models/unit_group.rb
  dashboard/test/models/script_test.rb
  dashboard/test/models/unit_group_test.rb
Labels: self-paced-pl

#43997 Update front end variables and props from isVerifiedTeacher to isVerifiedInstructor
  apps/src/code-studio/components/progress/UnitOverviewHeader.jsx
  apps/src/code-studio/progress.js
  apps/src/code-studio/progressRedux.js
  apps/src/sites/studio/pages/lessons/show.js
  apps/src/templates/courseOverview/CourseOverview.js
  apps/src/templates/lessonOverview/LessonOverview.jsx
  apps/test/unit/code-studio/components/progress/UnitOverviewHeaderTest.js
  apps/test/unit/code-studio/components/progress/UnitOverviewTest.js
  apps/test/unit/code-studio/progressReduxTest.js
  apps/test/unit/templates/courseOverview/CourseOverviewTest.js
  apps/test/unit/templates/lessonOverview/LessonOverviewTest.js
  dashboard/app/helpers/users_helper.rb
  dashboard/app/models/lesson.rb
Labels: self-paced-pl

#44037 I18n sync In & Up 12/13
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/javalab.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#44008 Always treat instructors as instructors
  dashboard/app/models/concerns/curriculum/course_types.rb
  dashboard/test/models/concerns/curriculum/course_types_test.rb
Labels: self-paced-pl

#44028 Allow editing of instructor in training field on PL courses
  dashboard/app/models/activity_section.rb
  dashboard/app/models/script.rb
Labels: self-paced-pl

#44029 Create helper method for determining if viewing as instructor in trai…
  dashboard/app/models/script_level.rb
  dashboard/test/models/script_level_test.rb
Labels: self-paced-pl

#44063 Rename verifiedTeacherRedux to verifiedInstructorRedux
  apps/src/code-studio/components/TeacherContentToggle.js
  apps/src/code-studio/components/progress/UnitOverviewHeader.jsx
  apps/src/code-studio/header.js
  apps/src/code-studio/progress.js
  apps/src/code-studio/progressRedux.js
  apps/src/code-studio/redux.js
  apps/src/code-studio/verifiedInstructorRedux.js
  apps/src/sites/studio/pages/courses/show.js
  apps/src/sites/studio/pages/lessons/show.js
  apps/src/sites/studio/pages/scripts/show.js
  apps/src/templates/courseOverview/CourseOverview.js
  apps/src/templates/instructions/teacherFeedback/EditableTeacherFeedback.jsx
  apps/src/templates/lessonOverview/LessonOverview.jsx
  apps/test/unit/code-studio/TeacherContentToggleTest.js
  apps/test/unit/code-studio/progressReduxTest.js
  apps/test/unit/code-studio/verifiedInstructorReduxTest.js
Labels: self-paced-pl

#44064 Create participant_type column on section and have it default to student
  dashboard/app/models/sections/clever_section.rb
  dashboard/app/models/sections/email_section.rb
  dashboard/app/models/sections/google_classroom_section.rb
  dashboard/app/models/sections/omni_auth_section.rb
  dashboard/app/models/sections/picture_section.rb
  dashboard/app/models/sections/section.rb
  dashboard/app/models/sections/word_section.rb
  dashboard/db/migrate/20211215025455_add_participant_type_to_section.rb
  dashboard/db/schema.rb
Labels: self-paced-pl

#43779 Show example solutions and teacher markdown for instructors in training
  apps/src/StudioApp.js
  apps/src/lib/levelbuilder/shapes.jsx
  apps/src/redux/pageConstants.js
  apps/src/templates/instructions/TopInstructions.jsx
  apps/src/templates/instructions/TopInstructionsHeader.jsx
  apps/src/templates/lessonOverview/lessonPlanShapes.jsx
  apps/test/unit/templates/instructions/TopInstructionsHeaderTest.jsx
  apps/test/unit/templates/instructions/TopInstructionsTest.jsx
  dashboard/app/assets/stylesheets/application.scss
  dashboard/app/controllers/test_controller.rb
  dashboard/app/helpers/levels_helper.rb
  dashboard/app/views/levels/show.html.haml
  dashboard/config/locales/scripts.en.yml
  dashboard/config/scripts/levels/self-paced-example-level-applab.level
  dashboard/config/scripts/levels/self-paced-example-level-dance.level
  dashboard/config/scripts/levels/self-paced-example-level-free-response.level
  dashboard/config/scripts/self_paced_example_level_bubble_choice.bubble_choice
  dashboard/config/scripts/self_paced_example_level_external.external
  dashboard/config/scripts/self_paced_example_level_match.match
  dashboard/config/scripts/self_paced_example_level_multi.multi
  dashboard/config/scripts/self_paced_pl_example_levelgroup_1.level_group
  dashboard/config/scripts_json/alltheselfpacedplthings.script_json
  dashboard/lib/policies/inline_answer.rb
  dashboard/lib/tasks/seed.rake
  dashboard/test/lib/policies/inline_answer_test.rb
  dashboard/test/ui/features/ed_programs/instructor_in_training.feature
  dashboard/test/ui/features/step_definitions/account_steps.rb
Labels: self-paced-pl

#44096 Update plc course ui test to have a facilitator participant
  dashboard/test/ui/features/ed_programs/plc_course_unit_navigation.feature
  dashboard/test/ui/features/step_definitions/pd.rb
Labels: self-paced-pl

#44101 Signed out users can only participate in student courses
  dashboard/app/models/concerns/curriculum/course_types.rb
  dashboard/test/models/concerns/curriculum/course_types_test.rb
Labels: self-paced-pl

#43981 Move to using verified instructor instead of verified teacher
  apps/src/code-studio/components/progress/UnitOverviewHeader.jsx
  apps/src/code-studio/components/progress/teacherPanel/types.js
  apps/src/code-studio/header.js
  apps/src/code-studio/progress.js
  apps/src/code-studio/progressRedux.js
  apps/src/lib/levelbuilder/course-editor/CourseEditor.js
  apps/src/lib/levelbuilder/unit-editor/UnitEditor.jsx
  apps/src/sites/studio/pages/courses/show.js
  apps/src/sites/studio/pages/lessons/show.js
  apps/src/sites/studio/pages/scripts/show.js
  apps/src/templates/courseOverview/CourseOverview.js
  apps/src/templates/instructions/teacherFeedback/EditableTeacherFeedback.jsx
  apps/src/templates/lessonOverview/LessonOverview.jsx
  apps/src/templates/progress/ProgressLessonTeacherInfo.story.jsx
  apps/test/unit/code-studio/components/progress/UnitOverviewHeaderTest.js
  apps/test/unit/code-studio/components/progress/UnitOverviewTest.js
  apps/test/unit/code-studio/progressReduxTest.js
  apps/test/unit/templates/courseOverview/CourseOverviewTest.js
  apps/test/unit/templates/instructions/teacherFeedback/EditableTeacherFeedbackTest.jsx
  apps/test/unit/templates/lessonOverview/LessonOverviewTest.js
  dashboard/app/controllers/activities_controller.rb
  dashboard/app/controllers/api/v1/assessments_controller.rb
  dashboard/app/controllers/api/v1/users_controller.rb
  dashboard/app/helpers/users_helper.rb
  dashboard/app/models/lesson.rb
  dashboard/app/models/script.rb
  dashboard/app/models/script_level.rb
  dashboard/app/models/teacher_feedback.rb
  dashboard/app/models/user.rb
  dashboard/app/models/user_permission.rb
  dashboard/app/views/courses/show.html.haml
  dashboard/app/views/scripts/show.html.haml
  dashboard/test/controllers/api/v1/users_controller_test.rb
  dashboard/test/models/script_test.rb
  dashboard/test/models/user_test.rb
Labels: self-paced-pl

#44110 Update CourseOverview props from isTeacher to isInstructor
  apps/src/templates/courseOverview/CourseOverview.js
  apps/src/templates/courseOverview/CourseOverviewTopRow.js
  apps/test/unit/templates/courseOverview/CourseOverviewTest.js
  apps/test/unit/templates/courseOverview/CourseOverviewTopRowTest.js
Labels: self-paced-pl
