Repository code-dot-org/code-dot-org, pull requests merged in 2021-08, with the labels that each got.

#41818 [React Upgrade] upgrade a handful of tests to use reconfiguredChai
  apps/test/unit/code-studio/pd/form_components/FormControllerTest.js
  apps/test/unit/templates/TooltipOverlayTest.js
  apps/test/unit/templates/VisualizationOverlayTest.js
  apps/test/unit/turtle/turtleTest.js
Labels: react-16.13-upgrade

#41853 I18n sync In & Up 08/02
  i18n/locales/source/blockly-mooc/javalab.json
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#41834 Remove redux details from ProgressDetailToggle storybook
  apps/src/templates/progress/ProgressDetailToggle.jsx
  apps/src/templates/progress/ProgressDetailToggle.story.jsx
Labels: react-16.13-upgrade

#41835 Upgrade react-dom-confetti package
  apps/package.json
  apps/yarn.lock
Labels: react-16.13-upgrade

#41839 Update progress dropdown UI test step
  dashboard/test/ui/features/step_definitions/progress.rb
Labels: react-16.13-upgrade

#41840 Upgrade eslint-plugin-prettier
  apps/package.json
  apps/yarn.lock
Labels: react-16.13-upgrade

#41831 Pre-React upgrade apps/ updates
  apps/src/applab/designElements/PropertyRow.jsx
  apps/src/applab/designElements/library.js
  apps/src/blockTooltips/DropletFunctionTooltip.html.ejs
  apps/src/blockTooltips/DropletParameterTooltip.html.ejs
  apps/src/code-studio/components/ShareAllowedDialog.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_table_loader.jsx
  apps/src/code-studio/pd/workshop_dashboard/reports/foorm/section_results.jsx
  apps/src/lib/ui/SchoolInfoConfirmationDialog.jsx
  apps/src/templates/Button.jsx
  apps/src/templates/CrosshairOverlay.jsx
  apps/src/templates/PaneHeader.jsx
  apps/src/templates/ProtectedStatefulDiv.jsx
  apps/src/templates/TooltipOverlay.jsx
  apps/src/templates/instructions/InstructionsDialogWrapper.jsx
  apps/src/templates/tables/wrapped_sortable.js
  apps/src/templates/teacherDashboard/LoginTypeCard.jsx
  apps/test/unit/applab/designElements/dropdownTest.js
  apps/test/unit/applab/designElements/labelTest.js
  apps/test/unit/lib/tools/jsinterpreter/JSInterpreterTest.js
  apps/test/unit/lib/ui/SchoolInfoConfirmationDialogTest.js
  apps/test/unit/templates/CrosshairOverlayTest.js
  apps/test/unit/templates/instructions/InstructionsDialogWrapperTest.jsx
Labels: react-16.13-upgrade

#41842 Upgrade react-router
  apps/package.json
  apps/yarn.lock
Labels: react-16.13-upgrade

#41819 [React upgrade] allow console warnings in anticipation of React upgrade
  apps/src/code-studio/components/progress/ResourcesDropdown.story.jsx
  apps/src/code-studio/pd/application_dashboard/workshop_assignment_select.story.jsx
  apps/src/lib/levelbuilder/lesson-editor/ActivitiesEditor.story.jsx
  apps/src/lib/tools/jsdebugger/JsDebugger.story.jsx
  apps/src/templates/NavigationBar.story.jsx
  apps/src/templates/sectionProgress/progressTables/ProgressTableView.story.jsx
  apps/src/templates/watchers/AutocompleteSelector.story.jsx
  apps/test/unit/code-studio/pd/application_dashboard/detail_view_contentsTest.js
  apps/test/unit/code-studio/pd/foorm/FoormEntityEditorFormModeTest.js
  apps/test/unit/javalab/JavalabEditorTest.js
  apps/test/unit/lib/levelbuilder/course-editor/CourseEditorTest.js
  apps/test/unit/lib/levelbuilder/lesson-editor/ActivitySectionCardTest.jsx
  apps/test/unit/lib/levelbuilder/lesson-editor/AddVocabularyDialogTest.jsx
  apps/test/unit/lib/levelbuilder/lesson-editor/LessonEditorTest.js
  apps/test/unit/lib/levelbuilder/lesson-editor/ObjectivesEditorTest.js
  apps/test/unit/lib/tools/jsdebugger/JsDebuggerTest.js
  apps/test/unit/sites/studio/pages/levelbuilder_edit_script.js
  apps/test/unit/templates/SchoolAutocompleteDropdownTest.js
  apps/test/unit/templates/manageStudents/ManageStudentsTableTest.js
  apps/test/unit/templates/manageStudents/SharingControlActionsHeaderCellTest.js
  apps/test/unit/templates/projects/PersonalProjectsTableTest.js
  apps/test/unit/templates/sectionProgress/progressTables/ProgressTableContentViewTest.jsx
  apps/test/unit/tutorialExplorer/filterHeaderTest.jsx
  apps/test/unit/watchers/AutocompleteSelectorTest.js
Labels: react-16.13-upgrade

#41924 Add alt text to a few LP components
  apps/i18n/common/en_us.json
  apps/src/templates/VerticalImageResourceCard.jsx
  apps/src/templates/projects/NewProjectButtons.jsx
  apps/src/templates/projects/ProjectCard.jsx
  apps/src/templates/sectionProgress/standards/StandardsReportHeader.jsx
  apps/src/templates/studioHomepages/CourseBlocks.jsx
  apps/src/templates/studioHomepages/CourseCard.jsx
  apps/src/templates/studioHomepages/TopCourse.jsx
  apps/src/templates/studioHomepages/TwoColumnActionBlock.jsx
  apps/src/templates/teacherDashboard/SectionLoginInfo.jsx
Labels: accessibility

#41941 I18n sync In & Up 08/09
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/javalab.json
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#41704 Migration for user_scripts table for reset progress
  dashboard/app/models/user_script.rb
  dashboard/db/migrate/20210809205147_add_deleted_at_to_user_scripts.rb
  dashboard/db/schema.rb
Labels: reset progress

#41841 Upgrade react-bootstrap
  apps/package.json
  apps/test/unit/applab/applabTest.js
  apps/test/unit/lib/tools/jsdebugger/JsDebuggerTest.js
  apps/test/unit/templates/ShowCodeToggleTest.js
  apps/test/unit/templates/convertXmlToBlockly.js
  apps/test/unit/templates/instructions/InstructionsCSFTest.jsx
  apps/yarn.lock
Labels: react-16.13-upgrade

#41843 Upgrade react-tooltip
  apps/package.json
  apps/yarn.lock
  dashboard/test/ui/features/learning_platform/level_types/level_group_multi_page_dots.feature
Labels: react-16.13-upgrade

#42095 Update <g> to <svg> to fix test
  apps/src/templates/TooltipOverlay.jsx
Labels: react-16.14-upgrade

#42109 I18n sync In & Up 08/18
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/javalab.json
  i18n/locales/source/course_content/2021/coursee-2021.json
  i18n/locales/source/course_content/2021/coursef-2021.json
  i18n/locales/source/course_content/2021/express-2021.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#42153 Webpack: Always use eval devtool in CI
  apps/webpack.js
Labels: react-16.14-upgrade

#42184 Upgrade redux & react-redux
  apps/package.json
  apps/src/lib/tools/jsdebugger/DebugConsole.jsx
  apps/src/lib/tools/jsdebugger/JsDebugger.jsx
  apps/src/templates/CodeWorkspaceContainer.jsx
  apps/src/templates/instructions/InstructionsCSF.jsx
  apps/src/templates/instructions/InstructionsCsfLeftCol.jsx
  apps/src/templates/instructions/InstructionsCsfMiddleCol.jsx
  apps/src/templates/instructions/InstructionsCsfRightCol.jsx
  apps/src/templates/instructions/InstructionsWithWorkspace.jsx
  apps/src/templates/instructions/TopInstructions.jsx
  apps/src/templates/watchers/Watchers.jsx
  apps/test/storybook/renderStoriesTest.js
  apps/test/unit-tests.js
  apps/test/unit/templates/instructions/InstructionsWithWorkspaceTest.jsx
  apps/yarn.lock
Labels: react-16.14-upgrade

#42220 Run rename-unsafe-lifecycles codemod
  apps/Gruntfile.js
  apps/src/applab/designElements/ColorPickerPropertyRow.jsx
  apps/src/applab/designElements/PropertyRow.jsx
  apps/src/code-studio/components/Attachments.jsx
  apps/src/code-studio/components/SoundLibrary.jsx
  apps/src/code-studio/components/SoundListEntry.jsx
  apps/src/code-studio/components/pairing/Pairing.jsx
  apps/src/code-studio/components/progress/LessonLockDialog.jsx
  apps/src/code-studio/components/progress/teacherPanel/TeacherPanel.jsx
  apps/src/code-studio/pd/application/teacher/TeacherApplication.jsx
  apps/src/code-studio/pd/application_dashboard/application_dashboard.jsx
  apps/src/code-studio/pd/application_dashboard/application_loader.jsx
  apps/src/code-studio/pd/application_dashboard/cohort_view.jsx
  apps/src/code-studio/pd/application_dashboard/cohort_view_table.jsx
  apps/src/code-studio/pd/application_dashboard/detail_view_contents.jsx
  apps/src/code-studio/pd/application_dashboard/quick_view.jsx
  apps/src/code-studio/pd/application_dashboard/summary.jsx
  apps/src/code-studio/pd/application_dashboard/workshop_assignment_loader.jsx
  apps/src/code-studio/pd/components/regional_partner_dropdown.jsx
  apps/src/code-studio/pd/form_components/FormController.jsx
  apps/src/code-studio/pd/workshop_dashboard/attendance/session_attendance.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/organizer_form_part.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_form.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_table.jsx
  apps/src/code-studio/pd/workshop_dashboard/components/workshop_table_loader.jsx
  apps/src/code-studio/pd/workshop_dashboard/reports/teacher_attendance_report.jsx
  apps/src/code-studio/pd/workshop_dashboard/reports/workshop_summary_report.jsx
  apps/src/code-studio/pd/workshop_survey/VariableFormGroup.jsx
  apps/src/lib/tools/jsdebugger/JsDebugger.jsx
  apps/src/p5lab/AnimationPicker/AnimationPickerBody.jsx
  apps/src/p5lab/AnimationPicker/AnimationPreview.jsx
  apps/src/p5lab/AnimationTab/AnimationListItem.jsx
  apps/src/p5lab/AnimationTab/PiskelEditor.jsx
  apps/src/p5lab/P5LabVisualizationColumn.jsx
  apps/src/storage/dataBrowser/ColumnHeader.jsx
  apps/src/storage/dataBrowser/DataTable.jsx
  apps/src/storage/dataBrowser/DataTableView.jsx
  apps/src/storage/dataBrowser/LibraryCategory.jsx
  apps/src/templates/HintDisplayLightbulb.jsx
  apps/src/templates/ImageWithStatus.jsx
  apps/src/templates/ShowCodeToggle.js
  apps/src/templates/VersionHistory.jsx
  apps/src/templates/VisualizationOverlay.jsx
  apps/src/templates/census2017/CensusMapReplacement.jsx
  apps/src/templates/feedback/StudentFeedbackNotification.jsx
  apps/src/templates/instructions/InlineAudio.jsx
  apps/src/templates/instructions/InstructionsCSF.jsx
  apps/src/templates/instructions/InstructionsDialogWrapper.jsx
  apps/src/templates/instructions/TopInstructions.jsx
  apps/src/templates/progress/ProgressLesson.jsx
  apps/src/templates/projects/ProjectAppTypeArea.jsx
  apps/src/templates/projects/ProjectCardGrid.jsx
  apps/src/templates/projects/ProjectWidgetWithData.jsx
  apps/src/templates/projects/SectionProjectsList.jsx
  apps/src/templates/sectionAssessments/SectionAssessments.jsx
  apps/test/storybook/renderStoriesTest.js
  apps/test/unit-tests.js
Labels: react-16.14-upgrade
