Repository code-dot-org/code-dot-org, pull requests merged in 2022-03, with the labels that each got.

#45129 I18n sync In & Up 03/02
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/spritelab.json
  i18n/locales/source/course_content/2019/coursef-2019.json
  i18n/locales/source/course_content/2020/coursee-2020.json
  i18n/locales/source/course_content/2021/coursee-2021.json
  i18n/locales/source/course_content/2021/csd6-2021.json
  i18n/locales/source/course_content/other/csd3-2021.json
  i18n/locales/source/course_content/other/csd7-2021.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/dashboard/unplugged.yml
  i18n/locales/source/markdown/public/educate/csc.md
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#45166 Refactor AssignmentVersionMenuItem
  apps/src/templates/teacherDashboard/AssignmentVersionMenuItem.jsx
Labels: self-paced-pl

#45168 Make valid grades shared constant
  apps/script/generateSharedConstants.rb
  apps/src/sites/studio/pages/home/_homepage.js
  apps/src/sites/studio/pages/teacher_dashboard/show.js
  apps/src/templates/teacherDashboard/EditSectionForm.jsx
  apps/src/templates/teacherDashboard/EditSectionForm.story.jsx
  apps/src/templates/teacherDashboard/OwnedSectionsTable.jsx
  apps/src/templates/teacherDashboard/OwnedSectionsTable.story.jsx
  apps/src/templates/teacherDashboard/teacherSectionsRedux.js
  apps/test/unit/templates/teacherDashboard/EditSectionFormTest.js
  apps/test/unit/templates/teacherDashboard/OwnedSectionsTableTest.js
  apps/test/unit/templates/teacherDashboard/teacherSectionsReduxTest.js
  dashboard/app/controllers/home_controller.rb
  dashboard/app/controllers/teacher_dashboard_controller.rb
  dashboard/app/models/sections/section.rb
  dashboard/app/views/teacher_dashboard/show.html.haml
  dashboard/test/models/sections/section_test.rb
  lib/cdo/shared_constants.rb
Labels: self-paced-pl

#45190 I18n sync In & Up 03/08
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/markdown/public/coldplay.md
Labels: i18n

#44285 Create summaries of course offerings for assignment dropdown
  dashboard/app/models/concerns/curriculum/assignable_course.rb
  dashboard/app/models/course_offering.rb
  dashboard/app/models/course_version.rb
  dashboard/app/models/script.rb
  dashboard/app/models/unit_group.rb
  dashboard/test/models/concerns/curriculum/assignable_course_test.rb
  dashboard/test/models/course_offering_test.rb
  dashboard/test/models/course_version_test.rb
Labels: self-paced-pl

#45289 I18n sync In & Up 03/14
  i18n/locales/source/blockly-mooc/javalab.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#45271 Pass course offering summaries to front end
  apps/src/code-studio/components/progress/UnitOverviewHeader.jsx
  apps/src/code-studio/progress.js
  apps/src/code-studio/progressRedux.js
  apps/src/sites/studio/pages/teacher_dashboard/show.js
  apps/src/templates/teacherDashboard/AssignmentSelector.jsx
  apps/src/templates/teacherDashboard/EditSectionForm.jsx
  apps/src/templates/teacherDashboard/EditSectionForm.story.jsx
  apps/src/templates/teacherDashboard/OwnedSectionsTable.story.jsx
  apps/src/templates/teacherDashboard/shapes.jsx
  apps/src/templates/teacherDashboard/teacherDashboardTestHelpers.js
  apps/src/templates/teacherDashboard/teacherSectionsRedux.js
  apps/test/unit/code-studio/components/progress/UnitOverviewHeaderTest.js
  apps/test/unit/templates/teacherDashboard/AssignmentSelectorTest.js
  apps/test/unit/templates/teacherDashboard/EditSectionFormTest.js
  apps/test/unit/templates/teacherDashboard/teacherSectionsReduxTest.js
  dashboard/app/controllers/api/v1/sections_controller.rb
  dashboard/app/views/teacher_dashboard/show.html.haml
  dashboard/config/routes.rb
Labels: self-paced-pl

#45305 Remove opening of section edit when navigate to homepage with course and script id params
  apps/src/sites/studio/pages/home/_homepage.js
  apps/src/templates/studioHomepages/SetUpSections.jsx
  apps/src/templates/studioHomepages/SetUpSections.story.jsx
  apps/src/templates/teacherDashboard/OwnedSections.jsx
  apps/src/templates/teacherDashboard/teacherSectionsRedux.js
  apps/test/unit/templates/studioHomepages/SetUpSectionsTest.jsx
  apps/test/unit/templates/teacherDashboard/OwnedSectionsTest.js
  apps/test/unit/templates/teacherDashboard/teacherSectionsReduxTest.js
Labels: self-paced-pl

#45315 Pass down more information we will use when updating assignment dropdown
  apps/src/code-studio/components/progress/UnitOverview.jsx
  apps/src/code-studio/components/progress/UnitOverviewTopRow.jsx
  apps/src/sites/studio/pages/courses/show.js
  apps/src/sites/studio/pages/scripts/show.js
  apps/src/templates/AssignButton.jsx
  apps/src/templates/courseOverview/CourseOverview.js
  apps/src/templates/courseOverview/CourseOverviewTopRow.js
  apps/src/templates/courseOverview/CourseScript.js
  apps/src/templates/teacherDashboard/SectionAssigner.jsx
  apps/src/templates/teacherDashboard/shapes.jsx
  apps/src/templates/teacherDashboard/teacherSectionsRedux.js
  apps/test/unit/templates/teacherDashboard/teacherSectionsReduxTest.js
  dashboard/app/models/script.rb
  dashboard/app/models/sections/section.rb
  dashboard/app/models/unit_group.rb
  dashboard/test/fixtures/script.yml
  dashboard/test/models/sections/section_test.rb
  dashboard/test/models/unit_group_test.rb
Labels: self-paced-pl

#45364 Make some testing improvements ahead of assignment dropdown updates
  dashboard/lib/tasks/seed.rake
  dashboard/test/controllers/api/v1/sections_controller_test.rb
  dashboard/test/factories/factories.rb
  dashboard/test/models/unit_group_test.rb
  dashboard/test/ui/config/course_offerings/ui-test-course.json
  dashboard/test/ui/config/course_offerings/ui-test-csa-family-script.json
  dashboard/test/ui/config/course_offerings/ui-test-versioned-script.json
  dashboard/test/ui/config/courses/ui-test-course-2017.course
  dashboard/test/ui/config/courses/ui-test-course-2019.course
  dashboard/test/ui/features/learning_platform/teacher_homepage.feature
Labels: self-paced-pl

#45405 I18n sync In & Up 03/21
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#44863 Silence some new deprecation warnings added in Rails 6
  dashboard/config/initializers/backtrace_silencers.rb
Labels: Rails 6

#45235 Use DynamoDB for DCDO & Gatekeeper in test web application server
  lib/dynamic_config/dcdo.rb
  lib/dynamic_config/environment_aware_dynamic_config_helper.rb
  lib/dynamic_config/gatekeeper.rb
  lib/test/dynamic_config/test_environment_aware_dynamic_config_helper.rb
Labels: Rails 6

#45489 UI Testing Updates to Prep for Assignment Dropdown
  dashboard/app/controllers/test_controller.rb
  dashboard/test/ui/features/learning_platform/course_versions.feature
  dashboard/test/ui/features/learning_platform/teacher_homepage.feature
  dashboard/test/ui/features/step_definitions/steps.rb
Labels: self-paced-pl

#45488 Courses settings fix
  dashboard/config/courses/allthethingscourse.course
  dashboard/config/courses/andrea-test-dlp.course
  dashboard/config/courses/csa-pilot.course
  dashboard/config/courses/csd-2017.course
  dashboard/config/courses/csd-2018.course
  dashboard/config/courses/csd-2019.course
  dashboard/config/courses/csd-2020.course
  dashboard/config/courses/csd-2021.course
  dashboard/config/courses/csp-2017.course
  dashboard/config/courses/csp-2018.course
  dashboard/config/courses/csp-2019.course
  dashboard/config/courses/csp-2020.course
  dashboard/config/courses/fit2019-apprentice.course
  dashboard/config/courses/mike-test.course
  dashboard/config/courses/time4cs-control.course
  dashboard/config/courses/time4cs-experiment.course
Labels: self-paced-pl

#45487 Update verified_teacher? to verified_instructor?
  dashboard/app/helpers/users_helper.rb
Labels: self-paced-pl

#45490 Update playlab course offering to be in hoc category
  dashboard/config/course_offerings/playlab.json
Labels: self-paced-pl

#45505 Update the course offering summaries based pl assignment set up
  dashboard/app/models/course_offering.rb
  dashboard/test/models/course_offering_test.rb
Labels: self-paced-pl

#45492 Just use default lessonExtras unless explicitly set
  apps/src/templates/teacherDashboard/teacherSectionsRedux.js
  apps/test/unit/templates/teacherDashboard/teacherSectionsReduxTest.js
Labels: self-paced-pl

#45580 Update helper data for teacher dashboard assignment tests
  apps/src/templates/teacherDashboard/teacherDashboardTestHelpers.js
Labels: self-paced-pl
