Repository code-dot-org/code-dot-org, pull requests merged in 2022-10, with the labels that each got.

#48397 Update `devise_invitable` to >= 2.0.2
  Gemfile
  Gemfile.lock
Labels: Ruby 2.7

#48424 relax index on course_versions table to allow both script and unit
  dashboard/app/models/course_version.rb
  dashboard/db/migrate/20221003141047_update_course_version_index.rb
  dashboard/db/schema.rb
Labels: rename-script-to-unit

#48486 Fix Violations of and Reenable `Style/RedundantFileExtensionInRequire`
  .rubocop_todo.yml
  bin/content-push
  bin/create-release
  bin/cron/sync_dropbox
  bin/cron/update_project_count
  bin/cronjob
  bin/geocode
  bin/i18n/translation_monitor/crowdin_validator.rb
  bin/k5-professional-development-survey-results
  bin/oneoff/generate_legacy_survey_summaries.rb
  bin/oneoff/upload_non_en_videos.rb
  bin/start-build
  bin/terminate_build
  bin/watch-and-test-levelbuilder
  dashboard/app/controllers/api/v1/pd/workshop_survey_report_controller.rb
  dashboard/db/migrate/20200602014720_revert_add_foreign_key_for_script_to_section.rb
  dashboard/legacy/middleware/helpers/profanity_privacy_helper.rb
  dashboard/lib/pd/survey_pipeline/generic_mapper.rb
  dashboard/lib/pd/survey_pipeline/helper.rb
  dashboard/test/lib/datastore_cache_test.rb
  dashboard/test/lib/pd/survey_pipeline/daily_survey_decorator_test.rb
  dashboard/test/lib/pd/survey_pipeline/daily_survey_joiner_test.rb
  dashboard/test/lib/pd/survey_pipeline/daily_survey_parser_test.rb
  dashboard/test/lib/pd/survey_pipeline/daily_survey_retriever_test.rb
  dashboard/test/lib/pd/survey_pipeline/mapper_test.rb
  dashboard/test/lib/pd/survey_pipeline/reducer_test.rb
  i18n/Rakefile
  lib/cdo/crowdin/project.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
  pegasus/helpers.rb
  shared/test/test_country_codes.rb
  shared/test/test_state_abbr.rb
  tools/hooks/lint.rb
  tools/hooks/restrict_large_files.rb
  tools/hooks/restrict_levelbuilder_changes.rb
  tools/hooks/restrict_staging_changes.rb
Labels: code-hygiene

#48323 Fix Violations of and Reenable `Performance/StringInclude`
  .rubocop_todo.yml
  dashboard/legacy/middleware/helpers/bucket_helper.rb
  dashboard/test/controllers/media_proxy_controller_test.rb
  dashboard/test/controllers/registrations_controller_test.rb
  dashboard/test/integration/registration/upgrade_test.rb
  dashboard/test/models/user_test.rb
  lib/cdo/poste.rb
  lib/cdo/user_agent_parser.rb
  shared/test/test_cookie_whitelist.rb
  tools/hooks/lint.rb
Labels: code-hygiene

#48203 cleanup dead js code from congrats page launch
  apps/src/sites/studio/pages/congrats/index.js
  apps/src/templates/certificates/Certificate.jsx
  apps/src/templates/certificates/Congrats.jsx
  apps/src/templates/teacherDashboard/PrintCertificates.jsx
  apps/src/templates/teacherDashboard/SectionActionDropdown.jsx
  apps/src/util/experiments.js
  apps/test/unit/templates/certificates/CertificateTest.js
  apps/test/unit/templates/teacherDashboard/PrintCertificatesTest.js
  apps/test/unit/templates/teacherDashboard/SectionActionDropdownTest.js
  dashboard/test/ui/features/hour_of_code/hour_of_code_finish.feature
Labels: move-congrats-to-dashboard

#48457 move properties.rb and analyze_hoc_activity_helper.rb to pegasus/helpers/
  bin/cron/analyze_hoc_activity
  bin/cron/geocode_hoc_activity
  bin/cron/hoc_signup_counts
  bin/cron/hoc_student_name_cleanup
  bin/cron/update_census_mapbox
  bin/cron/update_hoc_map
  bin/cron/update_project_count
  bin/oneoff/import_concept_difficulty_tags.rb
  bin/oneoff/rank_tutorials.rb
  pegasus/helpers/analyze_hoc_activity_helper.rb
  pegasus/helpers/properties.rb
  pegasus/router.rb
  pegasus/src/database.rb
  pegasus/test/test_analyze_hoc_activity_helper.rb
  pegasus/test/test_properties.rb
Labels: separating-pegasus

#47961 Update to Ruby 2.7.5
  .drone.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  SETUP.md
  cookbooks/.ruby-version
  cookbooks/Gemfile
  cookbooks/Gemfile.lock
  cookbooks/cdo-apps/spec/default_spec.rb
  cookbooks/cdo-ruby/attributes/default.rb
  cookbooks/cdo-ruby/test/integration/default/serverspec/ruby_spec.rb
  docker/dockerfiles/Dockerfile
  docker/setup-compose.yml
  docker/site-compose.yml
  docker/ui-tests-compose.yml
  docker/unit-tests-compose.yml
Labels: Ruby 2.7

#48547 Fix `whitelist/allow_authorized` Deprecation Warning
  dashboard/config/initializers/mini_profiler.rb
Labels: Ruby 2.7

#48558 Restore "cleanup dead js code from congrats page launch"
  apps/src/sites/studio/pages/congrats/index.js
  apps/src/templates/certificates/Certificate.jsx
  apps/src/templates/certificates/Congrats.jsx
  apps/src/templates/teacherDashboard/PrintCertificates.jsx
  apps/src/templates/teacherDashboard/SectionActionDropdown.jsx
  apps/src/util/experiments.js
  apps/test/unit/templates/certificates/CertificateTest.js
  apps/test/unit/templates/teacherDashboard/PrintCertificatesTest.js
  apps/test/unit/templates/teacherDashboard/SectionActionDropdownTest.js
  dashboard/test/ui/features/hour_of_code/hour_of_code_finish.feature
Labels: move-congrats-to-dashboard

#48565 Fix "passing a block without an image argument" Deprecation warning
  lib/cdo/pegasus/graphics.rb
Labels: Ruby 2.7

#48556 Stop Using Deprecated `URI.escape` (again)
  dashboard/app/helpers/levels_helper.rb
  dashboard/legacy/middleware/helpers/firebase_helper.rb
  dashboard/legacy/test/middleware/test_files.rb
  lib/cdo/contact_rollups/v2/pardot.rb
  lib/cdo/slack.rb
  lib/test/cdo/contact_rollups/test_pardot_v2.rb
Labels: Ruby 2.7

#48586 Update `ffi` sub-dependency to 1.15.5
  Gemfile.lock
Labels: Ruby 2.7

#48496 Update Rubocp Config for Ruby 2.7
  .rubocop.yml
  .rubocop_todo.yml
  bin/cron/zendesk_slack_report
  bin/oneoff/backfill_data/backfill_script_level_ids_teacher_feedbacks_3.rb
  bin/oneoff/backfill_data/backfill_section_start.rb
  bin/oneoff/census/ap-data/map-ap-school-data.rb
  bin/remove_script_remnants
  dashboard/app/controllers/api/v1/pd/teacher_attendance_report_controller.rb
  dashboard/app/controllers/api/v1/pd/workshop_summary_report_controller.rb
  dashboard/app/controllers/api/v1/pd/workshops_controller.rb
  dashboard/app/controllers/api_controller.rb
  dashboard/app/controllers/application_controller.rb
  dashboard/app/controllers/code_reviews_controller.rb
  dashboard/app/controllers/level_starter_assets_controller.rb
  dashboard/app/helpers/users_helper.rb
  dashboard/app/models/course_version.rb
  dashboard/app/models/foorm/submission.rb
  dashboard/app/models/lesson.rb
  dashboard/app/models/levels/blockly.rb
  dashboard/app/models/levels/level_group.rb
  dashboard/app/models/pd/workshop_daily_survey.rb
  dashboard/app/models/plc/enrollment_unit_assignment.rb
  dashboard/app/models/school.rb
  dashboard/app/models/user.rb
  dashboard/legacy/middleware/helpers/projects.rb
  dashboard/lib/autocomplete_helper.rb
  dashboard/lib/level_loader.rb
  dashboard/lib/mega_section.rb
  dashboard/lib/pd/foorm/submission_analytics_parser.rb
  dashboard/lib/pd/jot_form/form_questions.rb
  dashboard/lib/pd/payment/payment_calculator_base.rb
  dashboard/lib/projects_list.rb
  dashboard/lib/sample_data.rb
  dashboard/lib/services/curriculum_pdfs/resources.rb
  dashboard/lib/tasks/seed.rake
  dashboard/test/models/pd/payment_term_test.rb
  dashboard/test/ui/runner.rb
  lib/cdo/aws/cloud_formation.rb
  lib/cdo/aws/s3_packaging.rb
  lib/cdo/lesson_import_helper.rb
  lib/cdo/test_flakiness.rb
  pegasus/helper_modules/hoc_event_review.rb
  pegasus/helpers/hourofcode_survey_helpers.rb
Labels: Ruby 2.7

#48608 eliminate unqualified use of CourseVersion.all
  dashboard/app/models/course_version.rb
Labels: rename-script-to-unit

#48606 Add `.irb_history` to `.gitignore`
  .gitignore
Labels: Ruby 2.7

#48611 Fix Violation of and Reenable `Lint/SelfAssignment`
  .rubocop_todo.yml
  dashboard/app/controllers/foorm/forms_controller.rb
Labels: code-hygiene

#48614 HoC 2022 - i18n strings batch #2
  apps/i18n/common/en_us.json
  pegasus/sites.v3/hourofcode.com/i18n/en.yml
Labels: hoc

#48211 replace pegasus congrats pages with server-side redirects
  apps/Gruntfile.js
  apps/src/sites/code.org/pages/public/certificates.js
  apps/src/sites/code.org/pages/public/certificates/blank.js
  apps/src/sites/code.org/pages/public/congrats.js
  apps/src/sites/code.org/pages/public/sharecertificate.js
  apps/src/sites/code.org/pages/views/csf_congrats.js
  dashboard/test/ui/features/hour_of_code/hour_of_code_finish.feature
  pegasus/sites.v3/code.org/public/certificates.haml
  pegasus/sites.v3/code.org/public/certificates.moved
  pegasus/sites.v3/code.org/public/certificates/blank.haml
  pegasus/sites.v3/code.org/public/certificates/blank.moved
  pegasus/sites.v3/code.org/public/congrats.haml
  pegasus/sites.v3/code.org/public/congrats.moved
  pegasus/sites.v3/code.org/public/congrats/splat.haml
  pegasus/sites.v3/code.org/public/sharecertificate.haml
  pegasus/sites.v3/code.org/public/sharecertificate.moved
  pegasus/sites.v3/code.org/views/csf_congrats.haml
  pegasus/test/test_congrats_routes.rb
  pegasus/test/test_hoc_routes.rb
Labels: move-congrats-to-dashboard

#48673 I18n sync In & Up 10/17
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/animations/spritelab_animation_library.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2022/coursed-2022.json
  i18n/locales/source/course_content/2022/express-2022.json
  i18n/locales/source/course_content/Hour of Code/hello-world-soccer-2022.json
  i18n/locales/source/course_content/Hour of Code/hello-world-space-2022.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#48684 fix certificate links in k5-onlinepd levels
  dashboard/config/scripts/csp5_virtual_ending.external
  dashboard/config/scripts/opd_k5_connect_copy_2021.external
  dashboard/config/scripts/opd_k5_connect_copy_2022.external
Labels: move-congrats-to-dashboard

#48618 preflight script constants
  lib/cdo/script_constants.rb
  lib/test/test_script_constants.rb
  pegasus/helpers/hoc_helpers.rb
  pegasus/sites.v3/code.org/public/congrats/splat.haml
  pegasus/test/test_congrats_routes.rb
Labels: separating-pegasus, move-congrats-to-dashboard

#48711 I18n sync In & Up 10/18
  apps/i18n/common/es_mx.json
  apps/i18n/common/pl_pl.json
  bin/i18n/crowdin/codeorg-restricted_etags.json
  bin/i18n/crowdin/codeorg_etags.json
  bin/i18n/crowdin/hour-of-code_etags.json
  dashboard/config/locales/activity_sections.es-ES.json
  dashboard/config/locales/activity_sections.fa-IR.json
  dashboard/config/locales/authored_hints.es-ES.json
  dashboard/config/locales/authored_hints.fr-FR.json
  dashboard/config/locales/authored_hints.pl-PL.json
  dashboard/config/locales/blocks.fr-FR.yml
  dashboard/config/locales/callouts.pl-PL.json
  dashboard/config/locales/es-MX.yml
  dashboard/config/locales/frameworks.es-ES.json
  dashboard/config/locales/frameworks.fr-FR.json
  dashboard/config/locales/frameworks.ro-RO.json
  dashboard/config/locales/lesson_activities.fa-IR.json
  dashboard/config/locales/lessons.fa-IR.json
  dashboard/config/locales/lessons.fr-FR.json
  dashboard/config/locales/long_instructions.es-ES.json
  dashboard/config/locales/long_instructions.fr-FR.json
  dashboard/config/locales/long_instructions.pl-PL.json
  dashboard/config/locales/objectives.fa-IR.json
  dashboard/config/locales/pl-PL.yml
  dashboard/config/locales/reference_guides.pl-PL.json
  dashboard/config/locales/resources.fa-IR.json
  dashboard/config/locales/resources.fr-FR.json
  dashboard/config/locales/scripts.es-MX.yml
  dashboard/config/locales/standard_categories.es-ES.json
  dashboard/config/locales/standard_categories.fr-FR.json
  dashboard/config/locales/standard_categories.ro-RO.json
  dashboard/config/locales/standards.es-ES.json
  dashboard/config/locales/standards.fr-FR.json
  dashboard/config/locales/standards.ro-RO.json
  dashboard/config/locales/teacher_markdown.es-ES.json
  i18n/locales/es-MX/blockly-mooc/common.json
  i18n/locales/es-MX/dashboard/base.yml
  i18n/locales/es-MX/dashboard/scripts.yml
  i18n/locales/es-MX/pegasus/mobile.yml
  i18n/locales/fr-FR/dashboard/blocks.yml
  i18n/locales/pl-PL/animations/spritelab_animation_library.json
  i18n/locales/pl-PL/blockly-mooc/common.json
  i18n/locales/pl-PL/dashboard/base.yml
  i18n/locales/pl-PL/pegasus/mobile.yml
  i18n/locales/source/blockly-mooc/applab.json
  pegasus/cache/i18n/es-MX.yml
  pegasus/cache/i18n/pl-PL.yml
Labels: i18n

#48712 fix certificate images for mee minecraft courses
  dashboard/app/controllers/certificate_images_controller.rb
  dashboard/legacy/certificate_image.rb
  dashboard/legacy/test/test_certificate_image.rb
  dashboard/test/controllers/certificate_images_controller_test.rb
Labels: move-congrats-to-dashboard

#48705 move script constants to dashboard
  dashboard/app/controllers/maker_controller.rb
  dashboard/app/controllers/script_levels_controller.rb
  dashboard/app/models/levels/dsl_defined.rb
  dashboard/app/models/unit.rb
  dashboard/app/models/unit_group.rb
  dashboard/config/application.rb
  dashboard/legacy/certificate_image.rb
  dashboard/legacy/script_constants.rb
  dashboard/legacy/test/test_script_constants.rb
  lib/cdo/script_config.rb
Labels: separating-pegasus, move-congrats-to-dashboard

#48713 Batch certificates links update
  dashboard/config/scripts_json/aquatic.script_json
  dashboard/config/scripts_json/artist.script_json
  dashboard/config/scripts_json/basketball.script_json
  dashboard/config/scripts_json/dance-extras-2019.script_json
  dashboard/config/scripts_json/dance-unplugged.script_json
  dashboard/config/scripts_json/hero.script_json
  dashboard/config/scripts_json/mc.script_json
  dashboard/config/scripts_json/minecraft.script_json
  dashboard/config/scripts_json/oceans.script_json
  dashboard/config/scripts_json/outbreak.script_json
  dashboard/config/scripts_json/soccer.script_json
  dashboard/config/scripts_json/sports.script_json
  dashboard/test/fixtures/lesson.yml
  pegasus/sites.v3/hourofcode.com/public/how-to/virtual.md.partial
Labels: move-congrats-to-dashboard

#48734 Decorative Images with Blank Alt Text
  pegasus/sites.v3/code.org/public/help.md
  pegasus/sites.v3/code.org/views/stats_advocate_locally.haml
Labels: accessibility

#48739 Customize hoc congrats certificate
  apps/src/sites/studio/pages/congrats/index.js
  apps/src/templates/certificates/Certificate.jsx
  dashboard/test/ui/features/hour_of_code/hour_of_code_finish.feature
Labels: move-congrats-to-dashboard

#47848 Add localization to data table views
  apps/i18n/common/en_us.json
  apps/src/storage/dataBrowser/AddKeyRow.jsx
  apps/src/storage/dataBrowser/AddTableListRow.jsx
  apps/src/storage/dataBrowser/AddTableRow.jsx
  apps/src/storage/dataBrowser/ColumnMenu.jsx
  apps/src/storage/dataBrowser/ConfirmDeleteButton.jsx
  apps/src/storage/dataBrowser/ConfirmImportButton.jsx
  apps/src/storage/dataBrowser/DataTable.jsx
  apps/src/storage/dataBrowser/DataTableView.jsx
  apps/src/storage/dataBrowser/EditKeyRow.jsx
  apps/src/storage/dataBrowser/EditTableListRow.jsx
  apps/src/storage/dataBrowser/EditTableRow.jsx
  apps/src/storage/dataBrowser/KVPairs.jsx
  apps/src/storage/dataBrowser/TableControls.jsx
  apps/src/storage/dataBrowser/data-library-pane.module.scss
  apps/src/storage/dataBrowser/data-table-view.module.scss
  apps/src/storage/dataBrowser/dataVisualizer/VisualizerModal.jsx
  apps/src/storage/dataBrowser/table-controls.module.scss
  apps/test/unit/storage/dataBrowser/AddKeyRowTest.jsx
  apps/test/unit/storage/dataBrowser/AddTableListRowTest.jsx
  apps/test/unit/storage/dataBrowser/AddTableRowTest.jsx
  apps/test/unit/storage/dataBrowser/ColumnMenuTest.jsx
  apps/test/unit/storage/dataBrowser/ConfirmDeleteButtonTest.jsx
  apps/test/unit/storage/dataBrowser/ConfirmImportButtonTest.jsx
  apps/test/unit/storage/dataBrowser/DataTableTest.jsx
  apps/test/unit/storage/dataBrowser/DataTableViewTest.js
  apps/test/unit/storage/dataBrowser/DataTableViewTest.jsx
  apps/test/unit/storage/dataBrowser/EditKeyRowTest.jsx
  apps/test/unit/storage/dataBrowser/EditTableListRowTest.jsx
  apps/test/unit/storage/dataBrowser/EditTableRowTest.jsx
  apps/test/unit/storage/dataBrowser/KVPairsTest.jsx
  apps/test/unit/storage/dataBrowser/TableControlsTest.jsx
  apps/test/unit/storage/dataBrowser/dataVisualizer/VisualizerModalTest.js
Labels: translate-csd

#48826 I18n sync In & Up 10/25
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/weblab.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/how-to/virtual.md
Labels: i18n

#48797 remove references to pegasus tutorials table from congrats pages
  dashboard/app/controllers/certificate_images_controller.rb
  dashboard/lib/certificate_image.rb
  dashboard/test/controllers/certificate_images_controller_test.rb
  dashboard/test/lib/certificate_image_test.rb
Labels: separating-pegasus, move-congrats-to-dashboard

#48756 Make empty string default for altText prop
  apps/src/templates/VerticalImageResourceCard.jsx
  apps/src/templates/studioHomepages/CourseCard.jsx
  apps/src/templates/studioHomepages/ImageResourceCard.jsx
Labels: accessibility

#48868 Updating the course page button labels for accessibility
  apps/i18n/common/en_us.json
  apps/src/sites/code.org/pages/public/student/MiddleHighResourceCards.jsx
  apps/src/templates/studioHomepages/CourseBlocksTools.jsx
Labels: accessibility

#48876 Localize remaining block variables
  dashboard/app/models/levels/blockly.rb
  dashboard/test/models/blockly_test.rb
Labels: translate-csd

#48742 Fix Violations of and Reenable `Style/SingleArgumentDig`
  .rubocop_todo.yml
  dashboard/app/models/pd/enrollment.rb
  dashboard/lib/pd/survey_pipeline/helper.rb
  dashboard/test/controllers/pd/application/teacher_application_controller_test.rb
Labels: code-hygiene

#48900 Fix Violations of and Reenable `Lint/ErbNewArguments`
  .rubocop_todo.yml
  lib/cdo/cloud_formation/stack_template.rb
  lib/cdo/erb.rb
Labels: code-hygiene

#48925 drop pegasus tutorials table
  pegasus/migrations/140_drop_tutorials.rb
Labels: separating-pegasus

#48760 Update `json` Gem to 2.6.2
  cookbooks/Gemfile.lock
Labels: Ruby 2.7

#48759 Update `chef_client_updater` Gem to 3.12.3
  cookbooks/Berksfile
  cookbooks/Berksfile.lock
  cookbooks/cdo-apps/Berksfile
Labels: Chef 17

#48344 Fnd 2075 i18n maker toolkit setup
  apps/i18n/applab/en_us.json
  apps/src/lib/kits/maker/ui/SetupGuide.jsx
  apps/src/lib/kits/maker/ui/SetupInstructions.jsx
  apps/src/sites/studio/pages/maker/setup.js
  apps/test/unit/lib/kits/maker/ui/SetupGuideTest.js
  dashboard/app/views/maker/setup.html.haml
Labels: translate-csd
