Repository code-dot-org/code-dot-org, pull requests merged in 2022-07, with the labels that each got.

#46990 Misc. proofreader work
  bin/i18n/translation_monitor/configs/crowdin_validator_config.json
  bin/i18n/translation_monitor/data_io_helper.rb
Labels: proofreader

#46989 Temporarily disable language validation
  bin/i18n/translation_monitor/configs/crowdin_validator_config.json
  bin/i18n/translation_monitor/crowdin_validator.rb
  bin/i18n/translation_monitor/data_io_helper.rb
Labels: proofreader

#46945 Fix and Reenable some `BelongsTo` Rubocop Rules
  .rubocop_todo.yml
  dashboard/db/migrate/20170428002439_create_courses.rb
Labels: code-hygiene

#47095 Update `rmagick` Gem to 3.2.0
  Gemfile
  Gemfile.lock
Labels: Ruby 2.7

#47083 Update `MiniRacer` gem to 0.4.0
  Gemfile.lock
Labels: Ruby 2.7

#47096 Fix `Lint/UselessMethodDefinition` Rubocop Violations
  .rubocop_todo.yml
  bin/i18n/translation_status/translation_status_service.rb
  dashboard/app/controllers/application_controller.rb
  dashboard/app/models/pd/fit_weekend_registration_base.rb
Labels: code-hygiene

#46988 Support multiple Crowdin accounts for the same vendor
  bin/i18n/translation_monitor/config_helper.rb
  bin/i18n/translation_monitor/configs/crowdin_validator_config.json
  bin/i18n/translation_monitor/crowdin_validator.rb
  bin/i18n/translation_monitor/data_io_helper.rb
  lib/cdo/crowdin/client_extentions.rb
  lib/test/cdo/crowdin/test_client_extensions.rb
Labels: proofreader

#47117 Fix Violation of `Lint/RedundantCopDisableDirective` and Reenable
  .rubocop_todo.yml
  lib/cdo/app_server_metrics.rb
Labels: code-hygiene

#47091 Update `rmagick` gem to 4.2.5
  Gemfile
  Gemfile.lock
Labels: Ruby 2.7

#47175 Fix and Reenable `Security/YAMLLoad` Violations
  .rubocop_todo.yml
  dashboard/test/ui/features/step_definitions/steps.rb
  lib/cdo/aws/cloud_formation.rb
  lib/cdo/yaml.rb
  lib/dynamic_config/loaders/dcdo_loader.rb
  lib/dynamic_config/loaders/gatekeeper_loader.rb
  pegasus/data/csv.rb
  pegasus/router.rb
  pegasus/src/text_render.rb
  pegasus/test/fixtures/fake_dashboard.rb
  pegasus/test/test_pegasus_documents.rb
Labels: code-hygiene

#47173 Fix and Reenable `Security/JSONLoad` Violations
  .rubocop_todo.yml
  bin/cron/analyze_hoc_activity
  bin/cron/process_forms
  bin/i18n/redact_restore_utils.rb
  bin/i18n/sync-in.rb
  bin/i18n/sync-out.rb
  bin/i18n/translation_status/translation_service.rb
  bin/oneoff/backfill_pegasus_forms_sans_solr.rb
  dashboard/app/controllers/dynamic_config_controller.rb
  dashboard/test/ui/features/support/connect.rb
  lib/cdo/form.rb
  lib/cdo/properties.rb
  lib/dynamic_config/adapters/json_file_adapter.rb
  lib/dynamic_config/gatekeeper.rb
  pegasus/forms/pd_program_registration.rb
  pegasus/forms/pd_workshop_survey.rb
  pegasus/forms/pd_workshop_survey_counselor_admin.rb
  pegasus/routes/form_routes.rb
  pegasus/routes/v2_forms_routes.rb
  shared/middleware/files_api.rb
  shared/middleware/helpers/file_bucket.rb
Labels: code-hygiene

#46937 Disable `unknown_asset_fallback` Configuration
  dashboard/config/application.rb
Labels: Rails 6

#47283 Fix `Performance/Casecmp` Violations and Reenable
  .rubocop_todo.yml
  bin/content-push
  bin/kill-tests
  bin/oneoff/behavior_migration.rb
  bin/oneoff/diff_email_previews
  bin/update-contact-email
  dashboard/app/controllers/levels_controller.rb
  dashboard/app/helpers/race_interstitial_helper.rb
  dashboard/app/models/pd/international_opt_in.rb
  dashboard/app/models/user.rb
  lib/cdo/rack/request.rb
  pegasus/Rakefile
  shared/middleware/channels_api.rb
  shared/middleware/helpers/file_bucket.rb
  shared/middleware/net_sim_api.rb
Labels: code-hygiene

#47307 Remove an Invalid `asset_path` Call
  dashboard/app/views/teacher_dashboard/parent_letter.html.haml
Labels: Rails 6

#47311 Revert "Revert "Disable `unknown_asset_fallback` Configuration""
  dashboard/config/application.rb
Labels: Rails 6

#47192 Load Default Configuration Values for Rails 5.1
  dashboard/config/application.rb
Labels: Rails 6

#47219 Add `.ruby-version` To Version Control
  .drone.yml
  .gitignore
  .ruby-version
  SETUP.md
  cookbooks/Gemfile.lock
  cookbooks/cdo-ruby/attributes/default.rb
  docker/dockerfiles/Dockerfile
  docker/setup-compose.yml
  docker/site-compose.yml
  docker/ui-tests-compose.yml
  docker/unit-tests-compose.yml
Labels: Ruby 2.7

#47251 I18n sync In & Up 07/15
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/javalab.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/markdown/public/ai.md
  i18n/locales/source/markdown/public/curriculum/unplugged.md
  i18n/locales/source/markdown/public/educate/csc.md
  i18n/locales/source/markdown/public/educate/it.md
Labels: i18n

#47329 Unsilence 'asset not present' Deprecation Warning
  dashboard/config/initializers/backtrace_silencers.rb
Labels: Rails 6

#47328 Unsilence `update_attributes!?` Deprecation Warning
  dashboard/config/initializers/backtrace_silencers.rb
Labels: Rails 6

#47322 Update `font-awesome-rails` Gem to 4.7.0.8
  Gemfile
  Gemfile.lock
Labels: Rails 6

#47324 Update `paranoia` gem to 2.5.3
  Gemfile
  Gemfile.lock
Labels: Rails 6

#47321 Update `active_model_serializers` Gem to 0.10.13
  Gemfile
  Gemfile.lock
Labels: Rails 6

#46479 Load Default Configuration Values for Rails 6.0
  dashboard/config/application.rb
Labels: Rails 6

#47384 Fix Violations of `Security/IoMethods` and Reenable
  .rubocop_todo.yml
  aws/ci_build
  bin/cron/analyze_hoc_activity
  bin/cron/mysql-metrics
  cookbooks/cdo-apps/metadata.rb
  cookbooks/cdo-authorized-keys/metadata.rb
  cookbooks/cdo-awscli/metadata.rb
  cookbooks/cdo-cloudwatch-agent/metadata.rb
  cookbooks/cdo-github-access/metadata.rb
  cookbooks/cdo-home-ubuntu/metadata.rb
  cookbooks/cdo-java-7/metadata.rb
  cookbooks/cdo-jemalloc/metadata.rb
  cookbooks/cdo-mysql/metadata.rb
  cookbooks/cdo-nginx/metadata.rb
  cookbooks/cdo-nginx/test/cookbooks/nginx_test/metadata.rb
  cookbooks/cdo-nodejs/metadata.rb
  cookbooks/cdo-postfix/metadata.rb
  cookbooks/cdo-redis/metadata.rb
  cookbooks/cdo-repository/metadata.rb
  cookbooks/cdo-ruby/metadata.rb
  cookbooks/cdo-secrets/metadata.rb
  cookbooks/cdo-syslog/metadata.rb
  cookbooks/cdo-tippecanoe/metadata.rb
  cookbooks/cdo-users/metadata.rb
  cookbooks/cdo-varnish/metadata.rb
  cookbooks/cdo-varnish/test/cookbooks/varnish_test/metadata.rb
  dashboard/config/initializers/trusted_proxies.rb
  dashboard/lib/announcements.rb
  lib/cdo/analytics/milestone_parser.rb
  lib/cdo/aws/s3_packaging.rb
  lib/cdo/erb.rb
  lib/cdo/poste.rb
  lib/cdo/rack/request.rb
  lib/pdf/collate.rb
  pegasus/data/csv.rb
  pegasus/helpers/hourofcode_helpers.rb
  pegasus/helpers/page_helpers.rb
  pegasus/router.rb
  pegasus/routes/form_routes.rb
  pegasus/src/curriculum_router.rb
  pegasus/src/homepage.rb
  pegasus/src/text_render.rb
  shared/middleware/shared_resources.rb
  shared/test/test_milestone_parser.rb
  shared/test/test_s3_packaging.rb
  shared/test/test_sources.rb
Labels: code-hygiene

#47381 Add Explicit `case_sensitivity` Option to Uniqueness Validations
  dashboard/app/models/authentication_option.rb
  dashboard/app/models/concerns/multi_file_seeded.rb
  dashboard/app/models/email_preference.rb
  dashboard/app/models/experiments/pilot.rb
  dashboard/app/models/foorm/library_question.rb
  dashboard/app/models/lesson.rb
  dashboard/app/models/lesson_group.rb
  dashboard/app/models/levels/level.rb
  dashboard/app/models/pd/course_facilitator.rb
  dashboard/app/models/pd/enrollment.rb
  dashboard/app/models/reference_guide.rb
  dashboard/app/models/video.rb
  dashboard/config/initializers/backtrace_silencers.rb
Labels: Rails 6
