Repository code-dot-org/code-dot-org, pull requests merged in 2022-09, with the labels that each got.

#47865 Update `globalid` and `zeitwerk` Gems
  Gemfile.lock
Labels: Rails 6

#47703 Update `activerecord-import` Gem
  Gemfile
  Gemfile.lock
Labels: Rails 6

#47857 Remove Unnecessary `lock_thread` Argument
  dashboard/test/testing/transactional_test_case.rb
Labels: Rails 6

#47981 I18n sync In & Up 09/07
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2022/coursea-2022.json
  i18n/locales/source/course_content/2022/courseb-2022.json
  i18n/locales/source/course_content/2022/coursec-2022.json
  i18n/locales/source/course_content/2022/coursed-2022.json
  i18n/locales/source/course_content/2022/coursee-2022.json
  i18n/locales/source/course_content/2022/coursef-2022.json
  i18n/locales/source/course_content/2022/csd1-2022.json
  i18n/locales/source/course_content/2022/csd2-2022.json
  i18n/locales/source/course_content/2022/csd3-2022.json
  i18n/locales/source/course_content/2022/csd4-2022.json
  i18n/locales/source/course_content/2022/csd5-2022.json
  i18n/locales/source/course_content/2022/csd7-2022.json
  i18n/locales/source/course_content/2022/express-2022.json
  i18n/locales/source/course_content/2022/pre-express-2022.json
  i18n/locales/source/course_content/other/csd6-2022.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/block_categories.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/progressions.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/dashboard/variable_names.yml
  i18n/locales/source/hourofcode/activity-guidelines.md
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/hourofcode/partners.md
Labels: i18n

#48015 Fix Violations of and Reenable `Rails/Blank`
  .rubocop_todo.yml
  dashboard/app/controllers/concerns/azure_text_to_speech.rb
  dashboard/app/controllers/foorm/simple_survey_forms_controller.rb
  dashboard/app/controllers/omniauth_callbacks_controller.rb
  dashboard/app/controllers/pd/application/teacher_application_controller.rb
  dashboard/app/controllers/pd/international_opt_in_controller.rb
  dashboard/app/controllers/pd/misc_survey_controller.rb
  dashboard/app/controllers/pd/workshop_enrollment_controller.rb
  dashboard/app/controllers/regional_partners_controller.rb
  dashboard/app/controllers/registrations_controller.rb
  dashboard/app/controllers/transfers_controller.rb
  dashboard/app/helpers/certificates_helper.rb
  dashboard/app/helpers/levels_helper.rb
  dashboard/app/helpers/users_helper.rb
  dashboard/app/models/authentication_option.rb
  dashboard/app/models/concerns/pd/jot_form_backed_form.rb
  dashboard/app/models/lesson.rb
  dashboard/app/models/levels/standalone_video.rb
  dashboard/app/models/pd/application/application_base.rb
  dashboard/app/models/script.rb
  dashboard/app/models/sections/section.rb
  dashboard/app/models/unit_group.rb
  dashboard/app/models/user.rb
  dashboard/lib/pd/survey_pipeline/generic_mapper.rb
  dashboard/lib/services/curriculum_pdfs.rb
  dashboard/lib/services/curriculum_pdfs/lesson_plans.rb
  dashboard/lib/services/curriculum_pdfs/resources.rb
  dashboard/lib/services/curriculum_pdfs/script_overview.rb
  dashboard/lib/services/globally_unique_identifiers.rb
  dashboard/lib/services/i18n/curriculum_sync_utils/sync_in.rb
  dashboard/lib/services/i18n/curriculum_sync_utils/sync_out.rb
  dashboard/lib/services/markdown_preprocessor.rb
  dashboard/lib/tasks/seed.rake
  dashboard/test/test_helper.rb
Labels: code-hygiene

#48166 I18n sync In & Up 09/19
  i18n/locales/source/animations/spritelab_animation_library.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#47866 Revert "Revert "Drop Support for Ruby 2.5""
  Gemfile
  cookbooks/cdo-ruby/attributes/default.rb
Labels: Ruby 2.7

#48014 Fix Violations of and Reenable `Performance/Sum`
  .rubocop_todo.yml
  dashboard/app/helpers/pd/workshop_survey_results_helper.rb
  dashboard/app/models/pd/application/application_base.rb
  dashboard/app/models/pd/application/facilitator1920_application.rb
  dashboard/app/models/pd/application/principal_approval_application.rb
  dashboard/app/models/pd/workshop.rb
  dashboard/app/models/school_stats_by_year.rb
  dashboard/app/serializers/api/v1/pd/application_serializer.rb
  dashboard/legacy/middleware/helpers/bucket_helper.rb
  dashboard/lib/pd/payment/workshop_payment.rb
  dashboard/lib/pd/payment/workshop_summary.rb
  dashboard/scripts/archive/chicago_stats
  dashboard/scripts/archive/kipp_teachers
  dashboard/scripts/archive/sf_teachers
  dashboard/test/models/census/census_summary_test.rb
  lib/cdo/analytics/milestone_parser.rb
  lib/cdo/app_server_metrics.rb
Labels: code-hygiene

#46673 Update `rack` and related gems
  Gemfile.lock
Labels: Ruby 2.7

#47974 Revert "Revert "Update `activerecord-import` Gem""
  Gemfile
  Gemfile.lock
Labels: Rails 6

#48333 Fix Violations of and Reenable `Rails/Present`
  .rubocop_todo.yml
  dashboard/app/controllers/foorm/simple_survey_forms_controller.rb
  dashboard/app/controllers/omniauth_callbacks_controller.rb
  dashboard/app/controllers/report_abuse_controller.rb
  dashboard/app/controllers/sms_controller.rb
  dashboard/app/models/concerns/text_to_speech.rb
  dashboard/app/models/lesson.rb
  dashboard/app/models/levels/blockly.rb
  dashboard/app/models/levels/level.rb
  dashboard/app/models/pd/application/facilitator_application_base.rb
  dashboard/app/models/programming_class.rb
  dashboard/app/models/programming_method.rb
  dashboard/app/models/school_info.rb
  dashboard/app/models/script.rb
  dashboard/app/models/user.rb
  dashboard/db/migrate/20160824002113_create_school_infos.rb
  dashboard/test/ui/runner.rb
Labels: code-hygiene

#47889 Update RubyGems to 3.3.21
  cookbooks/cdo-apps/spec/default_spec.rb
  cookbooks/cdo-ruby/attributes/default.rb
  cookbooks/cdo-ruby/test/integration/default/serverspec/ruby_spec.rb
Labels: Ruby 2.7

#48337 Fix Violations of and Reenable `Performance/InefficientHashSearch`
  .rubocop_todo.yml
  dashboard/app/models/sections/section.rb
  dashboard/lib/projects_list.rb
  dashboard/test/controllers/api/v1/pd/application/principal_approval_applications_controller_test.rb
  dashboard/test/models/course_offering_test.rb
Labels: code-hygiene

#48386 I18n sync In & Up 09/30
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/animations/spritelab_animation_library.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/javalab.json
  i18n/locales/source/course_content/2022/coursee-2022.json
  i18n/locales/source/course_content/2022/coursef-2022.json
  i18n/locales/source/course_content/2022/csd2-2022.json
  i18n/locales/source/course_content/2022/csd3-2022.json
  i18n/locales/source/course_content/2022/express-2022.json
  i18n/locales/source/course_content/Hour of Code/aquatic.json
  i18n/locales/source/course_content/other/csd6-2022.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/hourofcode/how-to/companies.md
  i18n/locales/source/hourofcode/how-to/index.md
  i18n/locales/source/hourofcode/how-to/parents.md
  i18n/locales/source/hourofcode/how-to/volunteers.md
  i18n/locales/source/markdown/public/educate/csc.md
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#48403 Update `raindrops` to 0.20.0
  Gemfile.lock
Labels: Ruby 2.7
