Repository code-dot-org/code-dot-org, pull requests merged in 2022-12, with the labels that each got.

#49342 I18n sync In & Up 12/02
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#49255 Fix Violations of and Reenable `Rails/DeprecatedActiveModelErrorsMethods`
  .rubocop_todo.yml
  dashboard/app/models/foorm/form.rb
  dashboard/app/models/pd/regional_partner_mapping.rb
  dashboard/app/models/pd/workshop_daily_survey.rb
  dashboard/app/models/pd/workshop_facilitator_daily_survey.rb
  dashboard/app/models/pd/workshop_survey_foorm_submission.rb
  dashboard/lib/no_utf8mb4_validator.rb
  dashboard/lib/us_zip_code_validator.rb
Labels: code-hygiene

#49140 replace URI.encode with non-deprecated alternatives
  dashboard/app/helpers/javalab_files_helper.rb
  dashboard/app/views/dynamic_config/gatekeeper_show.html.haml
  dashboard/app/views/layouts/_small_footer.html.haml
  dashboard/legacy/middleware/files_api.rb
  dashboard/legacy/middleware/helpers/asset_bucket.rb
  dashboard/legacy/middleware/helpers/bucket_helper.rb
  dashboard/legacy/test/middleware/test_assets.rb
Labels: code-hygiene

#49446 Update and translate incubator banner
  apps/i18n/common/en_us.json
  apps/src/templates/studioHomepages/IncubatorBanner.jsx
Labels: accessibility

#49441 Convert JoinSection clickable div to button
  apps/src/templates/studioHomepages/JoinSection.jsx
  dashboard/test/ui/features/teacher_tools/pl_sections.feature
  dashboard/test/ui/features/teacher_tools/teacher_dashboard/teacher_dashboard.feature
Labels: accessibility

#49451 A11Y-4: Assign tall course blocks an empty alt tag
  dashboard/app/views/shared/_course_tall_block.haml
Labels: accessibility

#49454 Fixed Download CSV buttons for Feedback and Assessments
  apps/src/templates/sectionAssessments/FeedbackDownload.jsx
  apps/src/templates/sectionAssessments/SubmissionStatusAssessmentsContainer.jsx
Labels: accessibility

#49472 AccHack - Increase footer background and text contrast
  dashboard/app/assets/stylesheets/application.scss
  pegasus/sites.v3/code.org/public/css/mobile-footer.css
  pegasus/sites.v3/code.org/public/css/theme.css
  pegasus/sites.v3/code.org/styles_min/050-theme.css
  shared/css/color.scss
Labels: accessibility

#49191 Remove AWS CLI Cloudwatch Logs Python Package
  cookbooks/cdo-awscli/attributes/default.rb
  cookbooks/cdo-awscli/recipes/default.rb
  cookbooks/cdo-awscli/templates/default/config.erb
  cookbooks/cdo-awscli/test/integration/default/inspec/test_spec.rb
Labels: Chef 17

#49474 Removing clickable divs on three components
  apps/src/templates/sectionAssessments/FreeResponseDetailsDialog.jsx
  apps/src/templates/sectionAssessments/MatchDetailsDialog.jsx
  apps/src/templates/sectionAssessments/MultipleChoiceDetailsDialog.jsx
Labels: accessibility

#49395 P20-12 i18n docummentation content
  bin/i18n/sync-in.rb
  bin/i18n/sync-out.rb
  dashboard/app/models/programming_expression.rb
  dashboard/test/integration/curriculum_docs_test.rb
Labels: translate-csd

#49482 Add empty alt text to avatars on leadership page
  pegasus/sites.v3/code.org/views/about_headshots.haml
Labels: accessibility

#49488 AccHack - Add alt text to Microsoft logo on /ai page
  pegasus/sites.v3/code.org/views/ai_microsoft_block.erb
Labels: accessibility

#49467 Add labels for social media links in footer
  pegasus/sites.v3/code.org/views/footer.haml
  pegasus/sites.v3/code.org/views/mobile_footer_responsive.haml
  pegasus/sites.v3/hourofcode.com/i18n/en.yml
Labels: accessibility

#49498 Remove _useDeprecatedTag from StartNewProject Component
  apps/src/templates/projects/StartNewProject.jsx
Labels: accessibility

#49471 Add a label to the Javalab file explorer button
  apps/i18n/common/en_us.json
  apps/src/javalab/JavalabFileExplorer.jsx
Labels: accessibility

#49513 A11Y-7: Add alt text to careers page images
  pegasus/sites.v3/code.org/public/about/careers.md.erb
  pegasus/sites.v3/hourofcode.com/i18n/en.yml
Labels: accessibility

#49458 Make level buttons accessible
  dashboard/app/views/levels/_curriculum_reference.haml
  dashboard/app/views/levels/_dialog.html.haml
  dashboard/app/views/levels/_external.html.haml
  dashboard/app/views/levels/_single_match.html.haml
Labels: accessibility

#49525 Removing useDeprecated to make buttons instead of clickable divs
  apps/src/templates/courseOverview/ConfirmHiddenAssignment.js
  apps/src/templates/manageStudents/PasswordReset.jsx
Labels: accessibility

#49517 Adds alt text for data snapshots and challenge dialog
  apps/i18n/common/en_us.json
  apps/src/storage/dataBrowser/dataVisualizer/Snapshot.jsx
  apps/src/storage/dataBrowser/dataVisualizer/VisualizerModal.jsx
  apps/src/templates/ChallengeDialog.jsx
Labels: accessibility

#49526 Updating semantics of census buttons
  apps/src/templates/census2017/CensusForm.jsx
  apps/src/templates/census2017/CensusInaccuracyReviewDetails.jsx
  apps/src/templates/census2017/CensusInaccuracyReviewTable.jsx
Labels: accessibility

#49519 A11Y-6: Full team photo and headshot link alt text
  pegasus/sites.v3/code.org/public/about/team.md.erb
  pegasus/sites.v3/code.org/views/about_headshots.haml
  pegasus/sites.v3/hourofcode.com/i18n/en.yml
Labels: accessibility

#49443 A11Y-2: Add label to language dropdown
  dashboard/app/views/layouts/_footer.html.haml
  dashboard/config/locales/en.yml
Labels: accessibility

#49461 I18n sync In & Up 12/13
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/spritelab.json
  i18n/locales/source/course_content/2017/csd2-2017.json
  i18n/locales/source/course_content/2017/csd4-2017.json
  i18n/locales/source/course_content/2017/csd6-2017.json
  i18n/locales/source/course_content/2018/csd2-2018.json
  i18n/locales/source/course_content/2018/csd4-2018.json
  i18n/locales/source/course_content/2018/csd5-2018.json
  i18n/locales/source/course_content/2018/csd6-2018.json
  i18n/locales/source/course_content/2019/csd2-2019.json
  i18n/locales/source/course_content/2019/csd4-2019.json
  i18n/locales/source/course_content/2019/csd5-2019.json
  i18n/locales/source/course_content/2019/csd6-2019.json
  i18n/locales/source/course_content/2021/csd6-2021.json
  i18n/locales/source/course_content/2022/csd1-2022.json
  i18n/locales/source/course_content/2022/csd2-2022.json
  i18n/locales/source/course_content/2022/csd4-2022.json
  i18n/locales/source/course_content/2022/csd5-2022.json
  i18n/locales/source/course_content/2022/csd7-2022.json
  i18n/locales/source/course_content/Hour of Code/applab-intro.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/course_content/other/applab-1hour.json
  i18n/locales/source/course_content/other/applab-2hour.json
  i18n/locales/source/course_content/other/csd1-2021.json
  i18n/locales/source/course_content/other/csd2-2021.json
  i18n/locales/source/course_content/other/csd4-2021.json
  i18n/locales/source/course_content/other/csd5-2021.json
  i18n/locales/source/course_content/other/csd6-2022.json
  i18n/locales/source/course_content/other/csd7-2021.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#49516 Add aria-label to Java Lab preview show/hide button
  apps/i18n/common/en_us.json
  apps/src/javalab/PreviewPaneHeader.jsx
  apps/src/templates/PaneHeader.jsx
Labels: accessibility

#49543 Add empty alt text to run/reset buttons
  apps/src/templates/GameButtons.jsx
Labels: accessibility

#49532 Tab navigable javalab settings
  apps/src/javalab/JavalabSettings.jsx
  apps/src/javalab/javalab-settings.module.scss
Labels: accessibility

#49496 Make header "more/less" button accessible
  apps/src/code-studio/components/header/HeaderPopup.jsx
  apps/src/code-studio/components/header/header-popup.module.scss
Labels: accessibility

#49529 Add ariaLabel prop to PaneButton for icon-only buttons
  apps/i18n/weblab/en_us.json
  apps/src/templates/PaneHeader.jsx
  apps/src/weblab/WebLabView.jsx
Labels: accessibility

#49552 Asset buttons and retry project save dialog buttons should not be clickable divs
  apps/src/code-studio/components/AddAssetButtonRow.jsx
  apps/src/code-studio/components/AssetUploader.jsx
  apps/src/code-studio/components/header/RetryProjectSaveDialog.jsx
Labels: accessibility

#49550 Make input marker in debug console a <label>
  apps/src/lib/tools/jsdebugger/DebugConsole.jsx
Labels: accessibility

#49570 Remove _useDeprecated tag from PersonalProjectsPublishedCell
  apps/src/templates/projects/PersonalProjectsPublishedCell.jsx
Labels: accessibility

#49572 <button> instead of <div> in hoc /learn filters
  apps/src/tutorialExplorer/filterGroupHeaderSelection.jsx
Labels: accessibility

#49563 Make the immersive reader button tabbable
  apps/src/templates/instructions/ImmersiveReaderButton.jsx
Labels: accessibility

#49559 Updating and restyling buttons on unit overview page
  apps/src/templates/progress/HiddenForSectionToggle.jsx
  apps/src/templates/progress/LessonLock.jsx
  apps/src/templates/progress/ProgressLessonTeacherInfo.jsx
  apps/src/templates/progress/SendLesson.jsx
  apps/test/unit/templates/progress/HiddenForSectionToggleTest.jsx
Labels: accessibility

#49589 A11y 9 hoc overview alt text
  dashboard/app/helpers/course_block_helper.rb
  dashboard/app/views/shared/_course_tall_block.haml
  dashboard/config/locales/en.yml
Labels: accessibility

#49494 ARIA labels for chevrons in applab
  apps/i18n/common/en_us.json
  apps/src/lib/tools/jsdebugger/JsDebugger.jsx
  apps/src/templates/CodeWorkspace.jsx
Labels: accessibility
