Repository code-dot-org/code-dot-org, pull requests merged in 2022-01, with the labels that each got.

#41927 Update level_sources gh-ost migration
  bin/oneoff/gh-ost_migrations/level_sources.sh
Labels: no-reminders

#42885 Support `localhost-studio.code.org` in the Rails 6 `hosts` configuration
  dashboard/config/environments/development.rb
Labels: Rails 6

#43964 Stop `create`ing invalid test data
  dashboard/test/models/regional_partner_test.rb
Labels: Rails 6

#44183 Create edit page for programming environments
  apps/Gruntfile.js
  apps/src/lib/levelbuilder/code-docs-editor/ProgrammingEnvironmentEditor.jsx
  apps/src/sites/studio/pages/programming_environments/edit.js
  apps/test/unit/lib/levelbuilder/code-docs-editor/ProgrammingEnvironmentEditorTest.jsx
  dashboard/app/controllers/programming_environments_controller.rb
  dashboard/app/models/ability.rb
  dashboard/app/models/programming_environment.rb
  dashboard/app/views/programming_environments/edit.html.haml
  dashboard/config/routes.rb
  dashboard/test/controllers/programming_environments_controller_test.rb
Labels: code-docs-part-2

#44187 I18n sync In & Up 01/04
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/javalab.json
  i18n/locales/source/course_content/2021/coursef-2021.json
  i18n/locales/source/course_content/other/K5-OnlinePD.json
  i18n/locales/source/course_content/other/k5-onlinepd-2019.json
  i18n/locales/source/course_content/other/outbreak.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/assistive-technology.md
  i18n/locales/source/hourofcode/promote/resources.md
  i18n/locales/source/hourofcode/promote/stats.md
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#44321 Use a custom renderer instead of overriding PathObject directly
  apps/src/blockly/addons/cdoRenderer.js
  apps/src/blockly/googleBlocklyWrapper.js
Labels: google blockly

#44062 Validation that courses in family share course type
  dashboard/app/models/concerns/curriculum/course_types.rb
  dashboard/test/controllers/scripts_controller_test.rb
  dashboard/test/factories/factories.rb
  dashboard/test/fixtures/test-serialize-seeding-json.script_json
  dashboard/test/lib/services/script_seed_test.rb
  dashboard/test/models/concerns/curriculum/course_types_test.rb
Labels: self-paced-pl

#44295 Only go forward in published states and do not change participant audience once launched
  apps/src/lib/levelbuilder/CourseVersionPublishingEditor.jsx
  apps/src/lib/levelbuilder/course-editor/CourseEditor.js
  apps/src/lib/levelbuilder/course-editor/CourseTypeEditor.jsx
  apps/src/lib/levelbuilder/unit-editor/UnitEditor.jsx
  apps/test/unit/lib/levelbuilder/CourseVersionPublishingEditorTest.jsx
  apps/test/unit/lib/levelbuilder/course-editor/CourseTypeEditorTest.jsx
Labels: self-paced-pl

#44318 Move ignore child logic into required blocks utils
  apps/src/blockly/addons/cdoXml.js
  apps/src/required_block_utils.js
  apps/test/integration/blockUtilTests.js
Labels: google blockly

#44419 Fix can read for UnitGroup
  dashboard/app/controllers/courses_controller.rb
  dashboard/app/models/ability.rb
  dashboard/test/models/ability_test.rb
Labels: self-paced-pl

#44478 When generating PLC course set all course type and published state information
  dashboard/app/models/script.rb
  dashboard/test/fixtures/test-plc.script_json
  dashboard/test/models/script_test.rb
Labels: self-paced-pl

#44271 Validation for section with participant type
  dashboard/app/controllers/followers_controller.rb
  dashboard/app/controllers/transfers_controller.rb
  dashboard/app/models/sections/section.rb
  dashboard/config/locales/en.yml
  dashboard/test/controllers/followers_controller_test.rb
  dashboard/test/controllers/transfers_controller_test.rb
  dashboard/test/factories/factories.rb
  dashboard/test/models/sections/section_test.rb
Labels: self-paced-pl

#44555 Implement 'use_reader_connection' block in MultipleDatabasesTransitionHelper
  dashboard/app/controllers/admin_hoc_controller.rb
  dashboard/app/controllers/admin_reports_controller.rb
  dashboard/app/helpers/multiple_databases_transition_helper.rb
Labels: Rails 6

#44552 Update MysqlCheckIndexUsed for Rails 6
  dashboard/config/initializers/mysql_check_index_used.rb
Labels: Rails 6

#44585 When removing units from unit group make sure to reset course types
  dashboard/app/models/unit_group.rb
  dashboard/test/models/unit_group_test.rb
Labels: self-paced-pl

#44479 Update settings for UnitGroups for PLC Courses
  dashboard/db/migrate/20220123171920_set_course_type_on_pl_unit_groups.rb
  dashboard/db/schema.rb
Labels: self-paced-pl

#44586 Add category and is_featured to course offerings
  dashboard/app/models/course_offering.rb
  dashboard/db/migrate/20220128193930_add_category_and_is_featured_to_course_offering.rb
  dashboard/db/schema.rb
Labels: self-paced-pl
