Repository code-dot-org/code-dot-org, pull requests merged in 2023-03, with the labels that each got.

#49864 Install Ruby with `ruby-build` in Chef
  cookbooks/cdo-ruby/README.md
  cookbooks/cdo-ruby/attributes/default.rb
  cookbooks/cdo-ruby/recipes/brightbox.rb
  cookbooks/cdo-ruby/recipes/bundler.rb
  cookbooks/cdo-ruby/recipes/default.rb
  cookbooks/cdo-ruby/recipes/rake.rb
  cookbooks/cdo-ruby/recipes/ruby-build.rb
  cookbooks/cdo-ruby/recipes/rubygems.rb
Labels: Ruby Update

#50576 Assign and unassign section buttons a11y, realigning hidden and visible
  apps/src/code-studio/components/progress/bulk-lesson-visibility-toggle.module.scss
  apps/src/templates/AssignButton.jsx
  apps/src/templates/UnassignSectionButton.jsx
Labels: accessibility

#50626 Adding comment for context around __useDeprecatedTag
  apps/src/templates/Button.jsx
Labels: accessibility

#50287 Fix Violations of and Reenable `Naming/MemoizedInstanceVariableName`
  .rubocop_todo.yml
  dashboard/db/migrate/20170929102458_add_details_to_regional_partner.rb
  dashboard/test/testing/capture_queries.rb
  lib/cdo/app_server_metrics.rb
  lib/cdo/circle_utils.rb
  lib/cdo/cloud_formation/cdo_app.rb
  lib/cdo/secrets.rb
  shared/middleware/helpers/shared_auth_helpers.rb
  shared/middleware/helpers/storage_id.rb
  shared/test/capture_queries.rb
  shared/test/test_cookie_whitelist.rb
  shared/test/test_html_parser.rb
Labels: code-hygiene

#50693 Update `cancancan` Gem to 3.2
  Gemfile
  Gemfile.lock
  dashboard/app/models/ability.rb
Labels: Rails 6

#50727 I18n sync In & Up 03/13
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/applab.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/poetry.json
  i18n/locales/source/course_content/2022/coursef-2022.json
  i18n/locales/source/course_content/2022/express-2022.json
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#50666 adding dashboard/config/courses/*.course to sync-in
  bin/i18n/sync-in.rb
  bin/i18n/sync-out.rb
Labels: translate-csd

#50910 Update `where.not` Calls with Multiple Predicates
  dashboard/app/controllers/script_levels_controller.rb
  dashboard/app/models/peer_review.rb
  dashboard/test/controllers/script_levels_controller_test.rb
Labels: Rails 6

#50829 Simplify `Cache-Control` Header
  dashboard/app/controllers/application_controller.rb
  dashboard/test/test_helper.rb
Labels: Rails 6

#50886 Add a Temporary DCDO Flag for Unicorn-Specific Middleware
  dashboard/config.ru
Labels: Ruby Update

#50908 Update `rake` Gem to v12
  Gemfile.lock
Labels: Rails 6
