Repository code-dot-org/code-dot-org, pull requests merged in 2023-07, with the labels that each got.

#50743 Update Ruby to 3.0.5
  .drone.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  SETUP.md
  cookbooks/.ruby-version
  cookbooks/Gemfile
  cookbooks/Gemfile.lock
  cookbooks/cdo-ruby/attributes/default.rb
  dashboard/lib/tasks/seed.rake
  docker/dockerfiles/Dockerfile
  docker/setup-compose.yml
  docker/site-compose.yml
  docker/ui-tests-compose.yml
  docker/unit-tests-compose.yml
  lib/cdo/cloud_formation/cdo_app.rb
Labels: Ruby Update

#52481 P20-273: Prepare i18n sync-in script for unit testing
  bin/Rakefile
  bin/i18n/Rakefile
  bin/i18n/sync-in.rb
  bin/test/i18n/test_sync-in.rb
  bin/test/i18n/translation_monitor/test_core_validator.rb
  bin/test/i18n/translation_status/test_translation_service.rb
  bin/test/test_helper.rb
  deployment.rb
  lib/cdo/test_run_utils.rb
  lib/rake/test.rake
Labels: testing

#52619 Run Tests Without `Dir.chdir`
  lib/rake/test.rake
Labels: Ruby Update

#52628 Fix Violations of and Reenable `Rails/Pick`
  .rubocop_todo.yml
  dashboard/app/controllers/admin_reports_controller.rb
  dashboard/test/controllers/api/v1/pd/workshop_survey_foorm_report_controller_test.rb
  dashboard/test/lib/pd/foorm/rollup_creator_test.rb
Labels: code-hygiene

#52600 Use `assert_includes` and `refute_includes` Wherever Possible
  dashboard/test/controllers/api/v1/pd/applications_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshops_controller_test.rb
  dashboard/test/controllers/api/v1/regional_partners_controller_test.rb
  dashboard/test/controllers/authentication_options_controller_test.rb
  dashboard/test/controllers/courses_controller_test.rb
  dashboard/test/controllers/followers_controller_test.rb
  dashboard/test/controllers/home_controller_test.rb
  dashboard/test/controllers/javabuilder_sessions_controller_test.rb
  dashboard/test/controllers/lessons_controller_test.rb
  dashboard/test/controllers/media_proxy_controller_test.rb
  dashboard/test/controllers/passwords_controller_test.rb
  dashboard/test/controllers/policy_compliance_controller_test.rb
  dashboard/test/controllers/programming_classes_controller_test.rb
  dashboard/test/controllers/programming_environments_controller_test.rb
  dashboard/test/controllers/programming_expressions_controller_test.rb
  dashboard/test/controllers/projects_controller_test.rb
  dashboard/test/controllers/registrations_controller_test.rb
  dashboard/test/controllers/resources_controller_test.rb
  dashboard/test/controllers/script_levels_controller_test.rb
  dashboard/test/controllers/scripts_controller_test.rb
  dashboard/test/controllers/vocabularies_controller_test.rb
  dashboard/test/integration/registration/upgrade_test.rb
  dashboard/test/lib/page_mode_test.rb
  dashboard/test/lib/pd/payment/payment_calculator_test.rb
  dashboard/test/lib/pd/payment/workshop_summary_test.rb
  dashboard/test/lib/programming_expression_autocomplete_test.rb
  dashboard/test/lib/queries/script_activity_test.rb
  dashboard/test/lib/services/complete_application_reminder_test.rb
  dashboard/test/lib/services/curriculum_pdfs_test.rb
  dashboard/test/models/callout_test.rb
  dashboard/test/models/concerns/pd/jot_form_backed_form_test.rb
  dashboard/test/models/course_offering_test.rb
  dashboard/test/models/level_test.rb
  dashboard/test/models/levels/bubble_choice_test.rb
  dashboard/test/models/pd/application/teacher_application_test.rb
  dashboard/test/models/pd/enrollment_test.rb
  dashboard/test/models/pd/payment_term_test.rb
  dashboard/test/models/pd/regional_partner_program_manager_test.rb
  dashboard/test/models/pd/workshop_test.rb
  dashboard/test/models/peer_review_test.rb
  dashboard/test/models/survey_result_test.rb
  dashboard/test/models/unit_test.rb
  dashboard/test/models/user_test.rb
  dashboard/test/models/video_test.rb
Labels: code-hygiene

#52654 I18n sync In & Up 07/06
  i18n/locales/source/blockly-mooc/applab.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/lab2.json
  i18n/locales/source/blockly-mooc/music.json
  i18n/locales/source/blockly-mooc/poetry.json
  i18n/locales/source/blockly-mooc/spritelab.json
  i18n/locales/source/blockly-mooc/standaloneVideo.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#52668 Revert "Revert "Run Tests Without `Dir.chdir`""
  lib/rake/test.rake
Labels: Ruby Update

#52617 Revert "Revert "Update Ruby to 3.0.5""
  .drone.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  SETUP.md
  cookbooks/.ruby-version
  cookbooks/Gemfile.lock
  cookbooks/cdo-ruby/attributes/default.rb
  dashboard/lib/tasks/seed.rake
  docker/dockerfiles/Dockerfile
  docker/setup-compose.yml
  docker/site-compose.yml
  docker/ui-tests-compose.yml
  docker/unit-tests-compose.yml
  lib/cdo/cloud_formation/cdo_app.rb
Labels: Ruby Update

#52665 More Explicit `runner.rb` Filepaths
  dashboard/test/ui/features/support/connect.rb
  dashboard/test/ui/runner.rb
  dashboard/test/ui/test_status.haml
Labels: code-hygiene

#52641 P20-287: Create unit tests for course offerings i18n sync-in
  bin/i18n/resources/dashboard/course_offerings.rb
  bin/i18n/sync-in.rb
  bin/test/i18n/resources/dashboard/test_course_offerings.rb
  bin/test/i18n/test_sync-in.rb
Labels: testing

#52621 P20-281: Create unit tests for animations i18n sync-in
  bin/i18n/resources/apps/animations.rb
  bin/i18n/resources/dashboard/course_offerings.rb
  bin/i18n/sync-in.rb
  bin/test/animation_assets/test_manifest_builder.rb
  bin/test/i18n/resources/apps/test_animations.rb
  bin/test/i18n/test_sync-in.rb
  shared/test/fixtures/vcr/animations/manifest_spritelab_strings.yml
Labels: testing

#51589 Enable Some Rails 7.0 Configuration Defaults
  dashboard/config/initializers/new_framework_defaults_7_0.rb
Labels: Rails Upgrade

#52412 Set `Rails/Date` `EnforcedStyle` to "strict"
  .rubocop.yml
  dashboard/test/factories/factories.rb
  dashboard/test/factories/pd_factories.rb
  dashboard/test/factories/workshop_factories.rb
  dashboard/test/helpers/teacher_application_helper_test.rb
  dashboard/test/models/pd/application/application_base_test.rb
  dashboard/test/models/pd/application/teacher_application_test.rb
  dashboard/test/models/pd/enrollment_test.rb
  dashboard/test/models/pd/workshop_test.rb
  dashboard/test/models/regional_partner_test.rb
  dashboard/test/serializers/api/v1/pd/enrollment_flat_attendance_serializer_test.rb
Labels: code-hygiene

#52623 P20-285: Create unit tests for shared functions i18n sync-in
  bin/i18n/resources/dashboard/shared_functions.rb
  bin/i18n/sync-in.rb
  bin/test/i18n/resources/dashboard/test_shared_functions.rb
  bin/test/i18n/test_sync-in.rb
Labels: testing

#52706 P20-288: Create unit tests for standards i18n sync-in
  bin/i18n/resources/dashboard/standards.rb
  bin/i18n/sync-in.rb
  bin/test/i18n/resources/dashboard/test_standards.rb
  bin/test/i18n/test_sync-in.rb
Labels: testing

#52731 P20-289: Create unit tests for docs i18n sync-in
  bin/i18n/resources/dashboard/docs.rb
  bin/i18n/sync-in.rb
  bin/test/i18n/resources/dashboard/test_docs.rb
  bin/test/i18n/test_sync-in.rb
Labels: testing

#52622 P20-282: Create unit tests for blocks i18n sync-in
  bin/i18n-codeorg/in.sh
  bin/i18n/redact_restore_utils.rb
  bin/i18n/resources/dashboard/blocks.rb
  bin/i18n/sync-in.rb
  bin/test/fixtures/dashboard_config_block.json
  bin/test/fixtures/i18n_locales_source_dashboard_blocks.yml
  bin/test/fixtures/i18n_locales_source_dashboard_docs.json
  bin/test/i18n/resources/dashboard/test_blocks.rb
  bin/test/i18n/test_i18n_script_utils.rb
  bin/test/i18n/test_redact_restore_utils.rb
  bin/test/i18n/test_sync-in.rb
Labels: testing

#52792 Remove SQLite Dependency
  .drone.yml
  Gemfile
  Gemfile.lock
  SETUP.md
  cookbooks/cdo-apps/recipes/default.rb
  dashboard/fake_dashboard_for_tests.db
  docker/dockerfiles/Dockerfile
  docker/setup-compose.yml
  docker/site-compose.yml
  docker/ui-tests-compose.yml
  docker/unit-tests-compose.yml
Labels: code-hygiene

#52888 Add focus state to carousel pagination
  pegasus/sites.v3/code.org/public/css/design-system-pegasus.scss
Labels: accessibility

#52883 Fix Violations of and Reenable `Lint/OrAssignmentToConstant`
  .rubocop_todo.yml
  lib/cdo.rb
  lib/cdo/rack/deflater.rb
Labels: code-hygiene

#52915 I18n sync In & Up 07/20
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/markdown/public/curriculum/unplugged.md
Labels: i18n

#52931 Fix Violations of and Reenable `Rails/AssertNot`
  .rubocop.yml
  .rubocop_todo.yml
  dashboard/test/controllers/api/v1/users_controller_test.rb
  dashboard/test/controllers/code_reviews_controller_test.rb
  dashboard/test/helpers/application_helper_test.rb
  dashboard/test/lib/certificate_image_test.rb
  dashboard/test/models/user_test.rb
Labels: code-hygiene

#53004 I18n sync In & Up 07/25
  i18n/locales/source/blockly-mooc/aichat.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#52294 Update Chef Client to 18.0.185
  aws/chef-bootstrap.sh
  cookbooks/Gemfile
  cookbooks/Gemfile.lock
  cookbooks/cdo-analytics/.kitchen.yml
  cookbooks/cdo-apps/.kitchen.yml
  cookbooks/cdo-apps/attributes/default.rb
  cookbooks/cdo-awscli/.kitchen.yml
  cookbooks/cdo-cloudwatch-agent/.kitchen.yml
  cookbooks/cdo-i18n/.kitchen.yml
  cookbooks/cdo-jemalloc/.kitchen.yml
  cookbooks/cdo-mysql/.kitchen.yml
  cookbooks/cdo-nginx/.kitchen.yml
  cookbooks/cdo-nodejs/.kitchen.yml
  cookbooks/cdo-postfix/.kitchen.yml
  cookbooks/cdo-redis/.kitchen.yml
  cookbooks/cdo-repository/.kitchen.yml
  cookbooks/cdo-ruby/.kitchen.yml
  cookbooks/cdo-syslog/.kitchen.yml
  cookbooks/cdo-tippecanoe/.kitchen.yml
  cookbooks/cdo-users/.kitchen.yml
  lib/cdo/cloud_formation/cdo_app.rb
Labels: Chef Upgrade

#53096 I18n sync In & Up 07/31
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n
