Repository code-dot-org/code-dot-org, pull requests merged in 2023-12, with the labels that each got.

#55292 Update the download button on video lightboxes
  pegasus/sites.v3/code.org/views/index_video_reveal.haml
  pegasus/sites.v3/hourofcode.com/i18n/en.yml
Labels: accessibility

#55298 Update Several Minitest stubs to Mocha stubs
  dashboard/legacy/test/middleware/helpers/test_animation_bucket.rb
  dashboard/legacy/test/middleware/helpers/test_asset_bucket.rb
  dashboard/legacy/test/middleware/helpers/test_file_bucket.rb
  dashboard/legacy/test/middleware/helpers/test_library_bucket.rb
  dashboard/legacy/test/middleware/helpers/test_source_bucket.rb
  dashboard/legacy/test/middleware/test_assets.rb
  dashboard/legacy/test/middleware/test_sound_library_api.rb
  dashboard/legacy/test/middleware/test_tables.rb
  lib/test/cdo/test_circle_utils.rb
  shared/test/common_test_helper.rb
  shared/test/middleware/helpers/test_storage_id.rb
  shared/test/test_s3_packaging.rb
Labels: code-hygiene

#55162 Accessibility - set alt text to empty string for blockly tracking pixel
  apps/src/bounce/BounceVisualizationColumn.jsx
  apps/src/eval/EvalVisualizationColumn.jsx
  apps/src/flappy/FlappyVisualizationColumn.jsx
  apps/src/lib/tools/jsdebugger/DebugButtons.jsx
  apps/src/maze/SpellingControls.jsx
  apps/src/maze/StepButton.jsx
  apps/src/studio/StudioVisualizationColumn.jsx
  apps/src/templates/ArrowButtons.jsx
  apps/src/templates/CompletionButton.jsx
  apps/src/templates/GameButtons.jsx
  apps/src/templates/instructions/CollapserButton.jsx
  apps/src/templates/instructions/ScrollButtons.jsx
  apps/src/turtle/ArtistVisualizationColumn.jsx
  apps/test/integration/levelSolutions/applab1/ec_design.js
  apps/test/integration/levelSolutions/applab2/ec_setprop.js
Labels: accessibility

#55371 Add aria-labels to previous and next buttons on code.org/promote stats carousel
  pegasus/sites.v3/code.org/views/stats_carousel.haml
Labels: accessibility

#55372 Enable `jsx-a11y/aria-role`
  apps/.eslintrc.js
  apps/test/unit/code-studio/pd/application_dashboard/cohort_calculatorTest.js
Labels: code-hygiene, hackathon, accessibility

#55368 Fix Violations of and Reenable `jsx-a11y/anchor-has-content`
  apps/.eslintrc.js
  apps/src/templates/DropdownButton.js
  apps/src/templates/InlineDropdownMenu.jsx
Labels: code-hygiene, hackathon, accessibility

#55429 [AccHack] Fix tab navigation for the Project Gallery tabs
  apps/src/templates/projects/ProjectsGallery.jsx
Labels: accessibility

#55405 Replace button tags nested in a tags with a.link-buttons on high traffic legacy pages on code.org
  pegasus/sites.v3/advocacy.code.org/public/css/advocacy-home.css
  pegasus/sites.v3/advocacy.code.org/public/index.haml
  pegasus/sites.v3/advocacy.code.org/views/forum_banner.haml
  pegasus/sites.v3/advocacy.code.org/views/header.haml
  pegasus/sites.v3/code.org/public/css/tools.css
  pegasus/sites.v3/code.org/public/css/tutorial-promo.css
  pegasus/sites.v3/code.org/public/educate/applab.haml
  pegasus/sites.v3/code.org/public/educate/gamelab.haml
  pegasus/sites.v3/code.org/public/educate/spritelab.haml
  pegasus/sites.v3/code.org/public/oceans.haml
  pegasus/sites.v3/code.org/styles_min/040-page.css
  pegasus/sites.v3/code.org/views/dance_tutorial_section_higher_power.haml
  pegasus/sites.v3/code.org/views/homepage_hero.haml
  pegasus/sites.v3/code.org/views/homepage_supporters.haml
  pegasus/sites.v3/code.org/views/interactive_map.haml
  pegasus/sites.v3/code.org/views/resource_boxes.haml
  pegasus/sites.v3/code.org/views/top_hoc_tutorial_applab.haml
  pegasus/sites.v3/code.org/views/tutorial_promo.haml
Labels: accessibility

#55397 Refactor share_buttons view to remove screen reader duplication
  pegasus/sites.v3/code.org/public/css/common.css
  pegasus/sites.v3/code.org/views/share_buttons.haml
  pegasus/sites.v3/code.org/views/stats_carousel.haml
  pegasus/sites.v3/code.org/views/stats_mobile.haml
Labels: accessibility

#55465 [AccHack] add labels or aria-labels for a few more input fields
  apps/i18n/common/en_us.json
  apps/src/storage/levelbuilder/ManifestEditor.jsx
  apps/src/templates/RegionalPartnerSearch.jsx
  apps/src/templates/certificates/CertificateBatch.jsx
  apps/src/templates/manageStudents/AddMultipleStudents.jsx
  apps/src/templates/sectionProgress/standards/CreateStandardsReportStep2.jsx
Labels: accessibility

#55417 Lint dashboard and pegasus db access
  .rubocop.yml
  dashboard/db/migrate/20150423215834_create_channel_tokens.rb
  dashboard/db/migrate/20170509100000_add_program_registration_id_to_pd_teacher_application.rb
  dashboard/db/migrate/20210908195236_update_backpack_storage_apps_value.rb
  dashboard/lib/account_purger.rb
  dashboard/test/helpers/delete_accounts_helper_test.rb
  lib/cdo/app_server_hooks.rb
  lib/cdo/db.rb
  lib/cdo/delete_accounts_helper.rb
  lib/cdo/poste.rb
  pegasus/forms/hoc_signup_2017.rb
  pegasus/helper_modules/dashboard.rb
  pegasus/migrations/117_fix_pd_program_registration_form_data_and_remove_dupes.rb
  pegasus/migrations/117_nop.rb
  pegasus/test/test_pegasus_documents.rb
  shared/middleware/helpers/shared_auth_helpers.rb
  shared/middleware/helpers/storage_id.rb
  shared/test/common_test_helper.rb
  shared/test/test_poste.rb
  tools/customLinters/rubocop_dashboard_db_usage.rb
  tools/customLinters/rubocop_pegasus_db_usage.rb
Labels: separating-pegasus

#55486 I18n sync In & Up 12/15
  i18n/locales/source/animations/spritelab_animation_library.json
  i18n/locales/source/blockly-mooc/applab.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/standaloneVideo.json
  i18n/locales/source/course_content/2023/csc-adaptations-2023.json
  i18n/locales/source/course_content/2023/csd3-2023.json
  i18n/locales/source/course_content/2023/csd6a-2023.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/marketing_announcements.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/dashboard/slides.yml
  i18n/locales/source/dashboard/unplugged.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/hourofcode/promote/resources.md
  i18n/locales/source/markdown/public/educate/it.md
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#55485 [AccHack] alt text for a few images across the site
  apps/i18n/applab/en_us.json
  apps/i18n/common/en_us.json
  apps/i18n/dance/en_us.json
  apps/src/applab/designElements/ThemeDropdown.jsx
  apps/src/code-studio/components/ShareAllowedDialog.jsx
  apps/src/dance/DanceVisualizationColumn.jsx
  apps/src/lib/ui/ParentLetter.jsx
  apps/src/templates/census2017/CensusMapReplacement.jsx
Labels: accessibility
