Repository code-dot-org/code-dot-org, pull requests merged in 2023-06, with the labels that each got.

#52165 Update callout section text link color for better accessibility
  pegasus/sites.v3/code.org/public/css/design-system-pegasus.scss
Labels: accessibility

#51271 Update Remaining Instances of "last argument as parameters" For Ruby 3.0
  apps/script/generateSharedConstants.rb
  dashboard/app/models/concerns/seeded.rb
  dashboard/app/models/framework.rb
  dashboard/app/models/standard.rb
  dashboard/app/models/standard_category.rb
Labels: Ruby Update

#52279 Remove `build-essential` Cookbook
  cookbooks/Berksfile
  cookbooks/Berksfile.lock
  cookbooks/cdo-apps/metadata.rb
  cookbooks/cdo-java-7/metadata.rb
  cookbooks/cdo-java-7/recipes/default.rb
Labels: Chef Upgrade

#52313 Puma with SystemD
  Gemfile
  Gemfile.lock
  bin/oneoff/migrate_db
  bin/restart-dashboard-and-pegasus-hoc2016
  bin/restart-dashboard-hoc2016
  bin/restart-pegasus-hoc2016
  bin/restart_host
  config.yml.erb
  cookbooks/cdo-apps/libraries/cdo_apps.rb
  cookbooks/cdo-apps/templates/default/puma.service.erb
  cookbooks/cdo-apps/templates/default/puma.sh.erb
  dashboard/config/puma.rb
  docs/build-assets-on-adhoc.md
  docs/logging.md
  docs/update-levelbuilder.md
  lib/cdo/app_server_hooks.rb
  lib/cdo/rake_utils.rb
  lib/rake/build.rake
  pegasus/config/puma.rb
Labels: Ruby Update

#52280 Remove `yarn` Cookbook
  cookbooks/Berksfile.lock
  cookbooks/cdo-apps/metadata.rb
  cookbooks/cdo-apps/recipes/generate_pdf.rb
Labels: Chef Upgrade

#52370 I18n sync In & Up 06/20
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2022/coursee-2022.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#50760 Fix Violations of and Reenable `Rails/Date`
  .rubocop_todo.yml
  dashboard/app/controllers/api/v1/pd/workshops_controller.rb
  dashboard/app/controllers/api/v1/users_controller.rb
  dashboard/app/controllers/concerns/pd/workshop_filters.rb
  dashboard/app/models/pd/workshop.rb
  dashboard/app/models/regional_partner.rb
  dashboard/app/models/user.rb
  dashboard/lib/services/complete_application_reminder.rb
  dashboard/scripts/update_under_13_students.rb
  dashboard/test/controllers/api/v1/pd/teacher_attendance_report_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshop_summary_report_controller_test.rb
  dashboard/test/controllers/concerns/pd/workshop_filters_test.rb
  dashboard/test/controllers/followers_controller_test.rb
  dashboard/test/controllers/omniauth_callbacks_controller_test.rb
  dashboard/test/controllers/pd/professional_learning_landing_controller_test.rb
  dashboard/test/controllers/pd/workshop_daily_survey_controller_test.rb
  dashboard/test/controllers/registrations_controller_test.rb
  dashboard/test/integration/omniauth/utils.rb
  dashboard/test/integration/registration/new_account_tracking_test.rb
  dashboard/test/integration/registration/update_test.rb
  dashboard/test/models/concerns/pd/jot_form_backed_form_test.rb
  dashboard/test/models/pd/application/teacher_application_test.rb
  dashboard/test/models/pd/payment_term_test.rb
  dashboard/test/models/pd/workshop_test.rb
  dashboard/test/models/regional_partner_test.rb
  dashboard/test/models/user_test.rb
Labels: code-hygiene

#52368 Reapply "Puma with SystemD"
  Gemfile
  Gemfile.lock
  bin/oneoff/migrate_db
  bin/restart-dashboard-and-pegasus-hoc2016
  bin/restart-dashboard-hoc2016
  bin/restart-pegasus-hoc2016
  bin/restart_host
  config.yml.erb
  cookbooks/cdo-apps/libraries/cdo_apps.rb
  cookbooks/cdo-apps/templates/default/puma.service.erb
  cookbooks/cdo-apps/templates/default/puma.sh.erb
  dashboard/config/puma.rb
  docs/build-assets-on-adhoc.md
  docs/logging.md
  docs/update-levelbuilder.md
  lib/cdo/app_server_hooks.rb
  lib/cdo/rake_utils.rb
  lib/rake/build.rake
  pegasus/config/puma.rb
Labels: Ruby Update

#52333 Update Puma to 5.6.5
  Gemfile
  Gemfile.lock
  cookbooks/cdo-apps/templates/default/puma.service.erb
Labels: Ruby Update

#52271 Fix Violations of and Reenable `Style/SoleNestedConditional`
  .rubocop_todo.yml
  bin/cron/deploy_to_test
  bin/cron/detect_restricted_videos
  bin/oneoff/backfill_data/user_proficiencies
  bin/oneoff/rescore_taught_in_past
  dashboard/app/controllers/api/v1/pd/applications_controller.rb
  dashboard/app/controllers/application_controller.rb
  dashboard/app/controllers/foorm/simple_survey_forms_controller.rb
  dashboard/app/controllers/pd/misc_survey_controller.rb
  dashboard/app/controllers/videos_controller.rb
  dashboard/app/models/concerns/pd/facilitator_specific_form.rb
  dashboard/app/models/concerns/pd/jot_form_backed_form.rb
  dashboard/app/models/foorm/form.rb
  dashboard/app/models/level_source_image.rb
  dashboard/app/models/parent_levels_child_level.rb
  dashboard/app/models/pd/teachercon_survey.rb
  dashboard/app/models/pd/workshop_survey.rb
  dashboard/app/models/school_info.rb
  dashboard/app/models/sections/section.rb
  dashboard/config/initializers/trackable.rb
  dashboard/lib/pd/survey_pipeline/daily_survey_decorator.rb
  lib/cdo/create_header.rb
  lib/cdo/url_converter.rb
  lib/rake/build.rake
  pegasus/routes/hoc_routes.rb
  pegasus/src/curriculum_router.rb
Labels: code-hygiene

#52453 I18n sync In & Up 06/26
  i18n/locales/source/blockly-mooc/applab.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#50661 Install ruby to `/usr/local`
  cookbooks/cdo-ruby/recipes/ruby-build.rb
  cookbooks/cdo-ruby/recipes/rubygems.rb
  cookbooks/cdo-ruby/test/integration/default/serverspec/ruby_spec.rb
Labels: Ruby Update

#52543 Fix Violations of and Reenable `Style/CollectionCompact`
  .rubocop_todo.yml
  dashboard/app/models/levels/ailab.rb
  dashboard/app/models/levels/blockly.rb
  dashboard/app/models/levels/fish.rb
  dashboard/app/models/levels/javalab.rb
  dashboard/app/models/levels/level.rb
  dashboard/app/models/levels/weblab.rb
Labels: code-hygiene
