Repository code-dot-org/code-dot-org, pull requests merged in 2023-05, with the labels that each got.

#51587 Update `annotate` Gem to 3.2.0
  Gemfile
  Gemfile.lock
  dashboard/config/application.rb
Labels: Rails Upgrade

#50511 Rails 6.1.4.7
  Gemfile
  Gemfile.lock
  dashboard/app/controllers/levels_controller.rb
  dashboard/app/models/concerns/pd/form.rb
  dashboard/config/initializers/no_transform_paths.rb
  dashboard/config/storage.yml
  dashboard/db/schema.rb
  dashboard/lib/pd/jot_form/matrix_question.rb
  dashboard/lib/services/i18n/curriculum_sync_utils/serializers.rb
  dashboard/lib/services/i18n/curriculum_sync_utils/sync_in.rb
  dashboard/test/controllers/api/v1/assessments_controller_test.rb
  dashboard/test/controllers/api_controller_test.rb
  dashboard/test/integration/db_query_test.rb
  dashboard/test/integration/no_transform_paths_test.rb
  pegasus/test/fixtures/fake_dashboard.rb
Labels: Rails Upgrade

#51713 Fix `env.colorize` Call After Rails 6.1 Update
  dashboard/.irbrc
Labels: Rails Upgrade

#51688 Make display_video_thumbnail partial more accessible
  pegasus/sites.v3/code.org/views/display_video_thumbnail.haml
  pegasus/sites.v3/code.org/views/index_video_reveal.haml
  shared/images/play-button.png
Labels: accessibility

#51751 I18n sync In & Up 05/07
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/javalab.json
  i18n/locales/source/blockly-mooc/music.json
  i18n/locales/source/blockly-mooc/poetry.json
  i18n/locales/source/blockly-mooc/spritelab.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#51660 Fix Violations of and Reenable `Style/NegatedIfElseCondition`
  .rubocop_todo.yml
  bin/i18n-codeorg/lib/merge-all-locales.rb
  bin/oneoff/backfill_data/storage_apps_project_type_and_standalone
  bin/oneoff/upload_non_en_videos.rb
  dashboard/app/controllers/regional_partners_controller.rb
  dashboard/app/models/concerns/sti_factory.rb
  dashboard/app/models/lesson_group.rb
  dashboard/app/models/user.rb
  dashboard/legacy/middleware/channels_api.rb
  dashboard/legacy/middleware/helpers/animation_bucket.rb
  dashboard/lib/level_loader.rb
  lib/cdo.rb
  lib/cdo/cloud_formation/adhoc.rb
  lib/cdo/parse_email_address_string.rb
  lib/cdo/poste.rb
  pegasus/helpers/page_helpers.rb
  pegasus/routes/state_sheets.rb
  pegasus/src/curriculum_course.rb
Labels: code-hygiene

#51665 Fix Violations of and Reenable `Rails/SquishedSQLHeredocs`
  .rubocop_todo.yml
  dashboard/app/models/contact_rollups_final.rb
  dashboard/app/models/contact_rollups_raw.rb
  dashboard/db/migrate/20130812211107_create_concepts.rb
  dashboard/db/migrate/20150206185854_denormalize_secret_words.rb
  dashboard/db/migrate/20160118192602_add_published_column_to_levels.rb
  dashboard/db/migrate/20160205205103_ensure_cohorts_id_column_is_first.rb
  dashboard/db/migrate/20220701192307_rename_versions_to_commits.rb
  dashboard/db/migrate/20220713165055_drop_project_versions_view.rb
  dashboard/db/migrate/20220920231241_rename_code_review_notes_to_comments.rb
  dashboard/db/migrate/20220927170718_drop_code_review_notes_view.rb
  dashboard/lib/services/registration_reminder.rb
  dashboard/test/helpers/delete_accounts_helper_test.rb
  dashboard/test/models/contact_rollups_raw_test.rb
Labels: code-hygiene

#51588 Load Rails 6.1 Configuration Defaults
  dashboard/config/application.rb
  dashboard/config/initializers/new_framework_defaults_6_1.rb
  dashboard/config/initializers/new_framework_defaults_7_0.rb
Labels: Rails Upgrade

#51890 I18n sync In & Up 05/15
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/other/csd6-2022.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#51635 Update `selenium-webdriver` gem to 4.2.0
  Gemfile
  Gemfile.lock
  dashboard/test/ui/browsers.json
  dashboard/test/ui/features/step_definitions/dropdown.rb
  dashboard/test/ui/features/step_definitions/minecraft.rb
  dashboard/test/ui/features/step_definitions/steps.rb
  dashboard/test/ui/features/support/connect.rb
  dashboard/test/ui/features/support/hooks.rb
  dashboard/test/ui/utils/selenium_browser.rb
Labels: Ruby Update

#51929 Update `puma` Gem to 5.6.5
  Gemfile
  Gemfile.lock
  dashboard/config/puma.rb
  pegasus/config/puma.rb
Labels: Ruby Update

#51960 Revert "Revert "Update `selenium-webdriver` gem to 4.2.0""
  Gemfile
  Gemfile.lock
  dashboard/test/ui/browsers.json
  dashboard/test/ui/features/step_definitions/dropdown.rb
  dashboard/test/ui/features/step_definitions/minecraft.rb
  dashboard/test/ui/features/step_definitions/steps.rb
  dashboard/test/ui/features/support/connect.rb
  dashboard/test/ui/features/support/hooks.rb
  dashboard/test/ui/utils/selenium_browser.rb
Labels: Ruby Update

#51590 Remove `gctools` Gem
  Gemfile
  Gemfile.lock
  dashboard/config/puma.rb
  pegasus/config/puma.rb
Labels: Ruby Update

#51930 Update Rails to 6.1.7.3
  Gemfile
  Gemfile.lock
Labels: Rails Upgrade

#52162 I18n sync In & Up 05/31
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/javalab.json
  i18n/locales/source/blockly-mooc/music.json
  i18n/locales/source/blockly-mooc/spritelab.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/course_content/other/csd6-2022.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/activity-guidelines.md
  i18n/locales/source/hourofcode/en.yml
Labels: i18n
