Repository code-dot-org/code-dot-org, pull requests merged in 2023-08, with the labels that each got.

#52938 Fix Violations of and Reenable `Style/ClassEqualityComparison`
  .rubocop_todo.yml
  bin/aws_access
  dashboard/app/models/foorm/form.rb
  dashboard/app/models/plc/course_unit.rb
  dashboard/legacy/middleware/channels_api.rb
  dashboard/legacy/middleware/files_api.rb
  dashboard/lib/pd/foorm/foorm_parser.rb
  lib/forms/pegasus_form_errors.rb
  lib/forms/pegasus_form_validation.rb
  pegasus/forms/petition.rb
Labels: code-hygiene

#52978 Extract `.level` File Logic
  bin/oneoff/import_concept_difficulty_tags.rb
  dashboard/app/helpers/levels_helper.rb
  dashboard/app/models/concerns/text_to_speech.rb
  dashboard/app/models/levels/level.rb
  dashboard/lib/level_loader.rb
  dashboard/lib/policies/level_files.rb
  dashboard/lib/services/level_files.rb
  dashboard/scripts/archive/extra_level_files_for_dsl_defined_levels
  dashboard/test/controllers/levels_controller_test.rb
  dashboard/test/lib/level_loader_test.rb
  dashboard/test/lib/policies/level_files_test.rb
  dashboard/test/lib/services/level_files_test.rb
  dashboard/test/models/concerns/text_to_speech_test.rb
  dashboard/test/models/level_test.rb
  dashboard/test/models/levels/blockly_test.rb
Labels: code-hygiene

#53193 I18n sync In & Up 08/07
  i18n/locales/source/blockly-mooc/aichat.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#53216 Explicitly Disable `Performance/Detect`
  .rubocop.yml
  .rubocop_todo.yml
Labels: code-hygiene

#53066 Write New `.level` Files to Subdirectories
  dashboard/lib/policies/level_files.rb
  dashboard/lib/services/level_files.rb
  dashboard/scripts/archive/extra_level_files_for_dsl_defined_levels
  dashboard/test/controllers/levels_controller_test.rb
  dashboard/test/lib/policies/level_files_test.rb
  dashboard/test/lib/services/level_files_test.rb
Labels: code-hygiene

#53282 I18n sync In & Up 08/14
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2017/coursee-2017.json
  i18n/locales/source/course_content/2019/coursec-2019.json
  i18n/locales/source/course_content/2020/coursec-2020.json
  i18n/locales/source/course_content/2021/coursec-2021.json
  i18n/locales/source/course_content/2022/coursec-2022.json
  i18n/locales/source/course_content/Hour of Code/minecraft.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/course_content/other/course4.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/activity-guidelines.md
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#53280 Rebrand - Pegasus - Container updates
  pegasus/sites.v3/code.org/layouts/default.haml
  pegasus/sites.v3/code.org/public/css/brstrap.css
Labels: accessibility

#53283 Call `FileUtils.rm` More Explicitly in Error Handler
  dashboard/lib/tasks/seed.rake
Labels: Ruby Update

#53167 Rebrand - Pegasus - Update text and button colors
  pegasus/sites.v3/code.org/public/athome.md.partial
  pegasus/sites.v3/code.org/public/careers-with-cs/index.md.partial
  pegasus/sites.v3/code.org/public/careers-with-cs/k5.md
  pegasus/sites.v3/code.org/public/csjourneys/csadventures.md.partial
  pegasus/sites.v3/code.org/public/csjourneys/index.md.partial
  pegasus/sites.v3/code.org/public/css/advocate-locally.css
  pegasus/sites.v3/code.org/public/css/common.css
  pegasus/sites.v3/code.org/public/css/cookies.css
  pegasus/sites.v3/code.org/public/css/design-system-pegasus.scss
  pegasus/sites.v3/code.org/public/css/donors.css
  pegasus/sites.v3/code.org/public/css/hoc2022-landing-page.scss
  pegasus/sites.v3/code.org/public/css/homepage.css
  pegasus/sites.v3/code.org/public/css/interactive-map.css
  pegasus/sites.v3/code.org/public/educate/applab.haml
  pegasus/sites.v3/code.org/styles_min/040-page.css
  pegasus/sites.v3/code.org/styles_min/050-theme.css
  pegasus/sites.v3/code.org/views/ai_and_ethics_tile.erb
  pegasus/sites.v3/code.org/views/ai_and_ethics_tile50.erb
  pegasus/sites.v3/code.org/views/ai_for_oceans_tile.erb
  pegasus/sites.v3/code.org/views/ai_for_oceans_tile50.erb
  pegasus/sites.v3/code.org/views/ai_module_tile50.erb
  pegasus/sites.v3/code.org/views/featured_tutorial.html
  pegasus/sites.v3/code.org/views/how_ai_works_tile.erb
  pegasus/sites.v3/code.org/views/how_ai_works_tile50.erb
  pegasus/sites.v3/code.org/views/minecraft_content.haml
  pegasus/sites.v3/code.org/views/testimonials.haml
  pegasus/sites.v3/code.org/views/top_hoc_tutorial_applab.haml
Labels: accessibility

#53139 Fix Violations of and Reenable `Style/Encoding`
  .rubocop_todo.yml
  bin/oneoff/move_census_data.rb
  dashboard/legacy/test/middleware/test_assets.rb
  lib/country_codes.rb
  lib/rake/test.rake
  shared/test/test_email_validator.rb
  shared/test/test_rake_utils.rb
Labels: code-hygiene

#53379 I18n sync In & Up 08/21
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/aichat.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/activity-guidelines.md
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/markdown/public/athome.md
Labels: i18n

#53388 Adding a11y labels to both dropdowns in teacher panel
  apps/src/code-studio/components/progress/SectionSelector.jsx
  apps/src/templates/SortByNameDropdown.jsx
Labels: accessibility

#53422 I18n sync In & Up 08/23
  i18n/locales/source/course_content/other/allthethings.json
Labels: i18n

#53412 Call `reorganize_level_file_into_subdirectory` on Save
  dashboard/lib/services/level_files.rb
Labels: code-hygiene

#53305 Install MySQL 5.7 Even on Ubuntu 20
  cookbooks/cdo-mysql/recipes/client.rb
  cookbooks/cdo-mysql/recipes/repo.rb
  cookbooks/cdo-mysql/recipes/server.rb
  docker/dockerfiles/Dockerfile
Labels: Ubuntu Update

#53513 I18n sync In & Up 08/29
  i18n/locales/source/blockly-mooc/aichat.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#53484 Fix Violations of and Reenable `Lint/AmbiguousBlockAssociation`
  .rubocop_todo.yml
  aws/cloudformation/test/test_fast_snapshot_restore.rb
  bin/k5-professional-development-survey-results
  cookbooks/cdo-apps/libraries/cdo_apps.rb
  dashboard/lib/level_loader.rb
  dashboard/test/controllers/api/v1/pd/applications_controller_test.rb
  dashboard/test/controllers/api/v1/pd/course_facilitators_controller_test.rb
  dashboard/test/controllers/api/v1/pd/teacher_attendance_report_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshop_organizers_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshop_survey_foorm_report_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshops_controller_test.rb
  dashboard/test/controllers/api/v1/peer_review_submissions_controller_test.rb
  dashboard/test/controllers/courses_controller_test.rb
  dashboard/test/controllers/pd/professional_learning_landing_controller_test.rb
  dashboard/test/controllers/project_commits_controller_test.rb
  dashboard/test/controllers/scripts_controller_test.rb
  dashboard/test/helpers/delete_accounts_helper_test.rb
  dashboard/test/helpers/levels_helper_test.rb
  dashboard/test/integration/omniauth/utils.rb
  dashboard/test/lib/api/v1/school_autocomplete_test.rb
  dashboard/test/lib/api/v1/school_district_autocomplete_test.rb
  dashboard/test/lib/vocabulary_autocomplete_test.rb
  dashboard/test/models/block_test.rb
  dashboard/test/models/lesson_test.rb
  dashboard/test/models/pd/session_test.rb
  dashboard/test/models/pd/workshop_test.rb
  dashboard/test/models/programming_class_test.rb
  dashboard/test/models/unit_group_test.rb
  dashboard/test/models/unit_test.rb
  dashboard/test/models/user_test.rb
  lib/cdo/hamburger.rb
  lib/pdf/collate.rb
  lib/test/cdo/test_i18n_string_url_tracker.rb
  lib/test/test_hamburger.rb
  lib/test/test_help_header.rb
  pegasus/data/static_models.rb
  pegasus/test/test_form_routes.rb
Labels: code-hygiene
