Repository code-dot-org/code-dot-org, pull requests merged in 2023-02, with the labels that each got.

#49990 Deprecate teacher conference registration model
  apps/script/generateSharedConstants.rb
  dashboard/app/models/pd/teachercon1819_registration.rb
  dashboard/test/factories/pd_factories.rb
  dashboard/test/helpers/delete_accounts_helper_test.rb
  dashboard/test/models/pd/teachercon1819_registration_test.rb
  lib/cdo/delete_accounts_helper.rb
  lib/cdo/shared_constants/pd/teachercon1819_registration_constants.rb
Labels: remove-facilitator-apps

#50032 Removing clickable div from LessonGroupInfoDialog
  apps/src/templates/progress/LessonGroupInfoDialog.jsx
Labels: accessibility

#49763 A11y 48 remove duplicate help site button link
  pegasus/sites.v3/code.org/public/css/common.css
  pegasus/sites.v3/code.org/public/help.md
Labels: accessibility

#50075 Remove more facilitator code
  apps/Gruntfile.js
  apps/src/code-studio/pd/application_dashboard/detail_view_contents.jsx
  apps/src/code-studio/pd/application_dashboard/detail_view_response.jsx
  apps/src/code-studio/pd/application_dashboard/detail_view_response.story.jsx
  apps/src/code-studio/pd/fit_weekend_registration/FitWeekendRegistration.jsx
  apps/src/code-studio/pd/fit_weekend_registration/Joining.jsx
  apps/src/code-studio/pd/fit_weekend_registration/Releases.jsx
  apps/src/code-studio/pd/fit_weekend_registration/TravelPlans.jsx
  apps/src/code-studio/pd/form_components/FormComponent.jsx
  apps/src/code-studio/pd/form_components/FormController.jsx
  apps/src/sites/studio/pages/pd/fit_weekend_registration/new.js
  apps/test/unit/code-studio/pd/application_dashboard/detail_view_contentsTest.js
Labels: remove-facilitator-apps

#50111 Fix Violations of and Reenable `Lint/RedundantSafeNavigation`
  .rubocop_todo.yml
  dashboard/app/controllers/api/v1/user_school_infos_controller.rb
  dashboard/app/controllers/levels_controller.rb
  dashboard/app/models/ability.rb
  dashboard/app/models/levels/blockly.rb
  dashboard/lib/pd/payment/payment_factory.rb
Labels: code-hygiene

#49836 Revert "Revert "Revert "Revert "Update Chef Infra Client to 17.6.18""""
  aws/chef-bootstrap.sh
  cookbooks/.rubocop.yml
  cookbooks/Gemfile
  cookbooks/Gemfile.lock
  cookbooks/cdo-analytics/.kitchen.yml
  cookbooks/cdo-apps/.kitchen.yml
  cookbooks/cdo-apps/attributes/default.rb
  cookbooks/cdo-awscli/.kitchen.yml
  cookbooks/cdo-cloudwatch-agent/.kitchen.yml
  cookbooks/cdo-i18n/.kitchen.yml
  cookbooks/cdo-jemalloc/.kitchen.yml
  cookbooks/cdo-mysql/.kitchen.yml
  cookbooks/cdo-nginx/.kitchen.yml
  cookbooks/cdo-nodejs/.kitchen.yml
  cookbooks/cdo-postfix/.kitchen.yml
  cookbooks/cdo-redis/.kitchen.yml
  cookbooks/cdo-repository/.kitchen.yml
  cookbooks/cdo-ruby/.kitchen.yml
  cookbooks/cdo-syslog/.kitchen.yml
  cookbooks/cdo-tippecanoe/.kitchen.yml
  cookbooks/cdo-users/.kitchen.yml
  cookbooks/cdo-varnish/.kitchen.yml
  lib/cdo/cloud_formation/cdo_app.rb
Labels: Chef 17

#50054 Fix Violations of and Reenable `Style/CaseLikeIf`
  .rubocop_todo.yml
  bin/i18n/sync-in.rb
  bin/oneoff/backfill_data/backfill_scholarship_course
  bin/oneoff/backfill_data/principalapproval1920_application_pay_fee_changes.rb
  bin/oneoff/backfill_data/teacher1920_application_pay_fee_changes
  bin/oneoff/data_fix/fix_bad_school_info_in_users
  dashboard/app/controllers/api/v1/regional_partners_controller.rb
  dashboard/app/controllers/api/v1/sections_controller.rb
  dashboard/app/controllers/registrations_controller.rb
  dashboard/app/controllers/sms_controller.rb
  dashboard/app/models/concerns/curriculum/course_types.rb
  dashboard/app/models/levels/blockly.rb
  dashboard/app/models/pd/application/application_base.rb
  dashboard/app/models/pd/application/teacher_application.rb
  dashboard/app/models/pd/international_opt_in.rb
  dashboard/app/models/school_info.rb
  dashboard/app/models/script_level.rb
  dashboard/app/models/user_proficiency.rb
  dashboard/db/migrate/20140624203113_convert_stringified_boolean_properties.rb
  dashboard/legacy/middleware/animation_library_api.rb
  dashboard/lib/certificate_image.rb
  dashboard/lib/pd/jot_form/translation.rb
  dashboard/scripts/ideal_level_sources_to_test_json.rb
  dashboard/test/ui/features/step_definitions/dropdown.rb
  dashboard/test/ui/features/step_definitions/progress.rb
  dashboard/test/ui/utils/selenium_browser.rb
  lib/cdo/hamburger.rb
  lib/cdo/i18n_backend.rb
  lib/cdo/lesson_import_helper.rb
  pegasus/src/social_metadata.rb
Labels: code-hygiene

#50051 Fix Violations of and Reenable `Rails/WhereEquals`
  .rubocop_todo.yml
  dashboard/app/controllers/levels_controller.rb
  dashboard/app/models/census/census_submission.rb
  dashboard/app/models/levels/level.rb
  dashboard/db/migrate/20131029225428_create_level_sources.rb
  dashboard/db/migrate/20170308012502_add_contact_regional_partner_to_workshops.rb
  dashboard/db/migrate/20170426010410_populate_pd_workshop_on_map_and_funded.rb
  dashboard/db/migrate/20170427221156_remove_pd_workshop_type.rb
  dashboard/db/migrate/20210907200327_convert_application_classes.rb
  dashboard/lib/queries/script_activity.rb
  dashboard/lib/services/registration_reminder.rb
  dashboard/scripts/ideal_level_sources_to_test_json.rb
Labels: code-hygiene

#50140 stop seeding census tables into dashboard db
  dashboard/lib/tasks/seed.rake
Labels: access report

#50099 stop replicating most census tables to redshift
  aws/dms/tasks.yml
Labels: access report

#50163 Removing useDeprecatedTag from unit calendar button
  apps/src/code-studio/components/progress/UnitCalendarButton.jsx
Labels: accessibility

#50089 I18n sync In & Up 02/06
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/markdown/public/educate/curriculum/csf-transition-guide.md
Labels: i18n

#50176 remove census oneoff scripts and cronjobs
  bin/cron/check_for_census_inaccuracy_reports
  bin/cron/test_access_report_import
  bin/cron/update_census_mapbox
  bin/oneoff/census/ap-data/README.md
  bin/oneoff/census/ap-data/check-school-codes.rb
  bin/oneoff/census/ap-data/dedupe-ap-school-codes.rb
  bin/oneoff/census/ap-data/load-ap-school-data.rb
  bin/oneoff/census/ap-data/map-ap-school-data.rb
  bin/oneoff/census/ap-data/merge-ap-school-codes.rb
  bin/oneoff/census/ap-data/upload-ap-offering-data.rb
  bin/oneoff/census/ap-data/upload-ap-school-code-data.rb
  bin/oneoff/census/export-summaries.rb
  bin/oneoff/census/ib-data/upload-ib-offering-data.rb
  bin/oneoff/census/ib-data/upload-ib-school-code-data.rb
  bin/oneoff/census/state-data/README.md
  bin/oneoff/census/state-data/preprocess-ca-data.rb
  bin/oneoff/census/state-data/reseed-state-data.rb
  bin/oneoff/census/state-data/upload-state-data.rb
  bin/oneoff/census/summarize.rb
  cookbooks/cdo-apps/templates/default/crontab.erb
Labels: access report

#49964 Use an Argument in Image Block
  dashboard/lib/certificate_image.rb
Labels: Ruby Update

#49961 Stop Using Deprecated `bundle --without`
  lib/cdo/rake_utils.rb
Labels: Ruby Update

#50063 P20 32 making teaching tips translatable
  dashboard/app/models/activity_section.rb
  dashboard/test/models/activity_section_test.rb
Labels: translate-csd

#50318 Unassign useDeprecatedTag remove, fix styling placement on teacher banner
  apps/src/templates/TeacherInfoBanner.jsx
  apps/src/templates/UnassignSectionDialog.jsx
Labels: accessibility

#49629 Fix Violations of and Reenable `Lint/UriEscapeUnescape`
  .rubocop_todo.yml
  dashboard/app/controllers/curriculum_tracking_pixel_controller.rb
  lib/cdo/contact_rollups/v2/pardot.rb
Labels: code-hygiene

#50380 Fix Violations of and Reenable `Style/RedundantSort`
  .rubocop_todo.yml
  bin/oneoff/backfill_data/school_info_id
  dashboard/app/models/teacher_score.rb
  dashboard/app/models/unit_group.rb
  dashboard/lib/queries/user_school_info.rb
  dashboard/scripts/archive/sync_dash
  lib/cdo/rack/locale.rb
Labels: code-hygiene

#50386 I18n sync In & Up 02/22
  i18n/locales/source/blockly-mooc/applab.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/javalab.json
  i18n/locales/source/course_content/2022/coursee-2022.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/markdown/public/ai.md
  i18n/locales/source/markdown/public/coldplay.md
  i18n/locales/source/markdown/public/educate/csc.md
  i18n/locales/source/markdown/public/educate/it.md
  i18n/locales/source/markdown/public/international/about.md
Labels: i18n

#50407 make assessment_opportunities translatable
  dashboard/app/models/lesson.rb
  dashboard/lib/services/i18n/curriculum_sync_utils/serializers.rb
  dashboard/test/models/lesson_test.rb
Labels: translate-csd

#50450 adding courses.yml to the sync in
  bin/i18n-codeorg/in.sh
Labels: translate-csd
