Repository code-dot-org/code-dot-org, pull requests merged in 2023-01, with the labels that each got.

#49489 Fix Violations of and Reenable `Style/SlicingWithRange`
  .rubocop_todo.yml
  bin/dashboard-csv
  bin/pegasus-csv
  cookbooks/cdo-home-ubuntu/recipes/default.rb
  cookbooks/cdo-users/recipes/default.rb
  dashboard/app/models/levels/widget.rb
  dashboard/app/models/user.rb
  dashboard/db/migrate/20160818190145_add_unique_constraint_to_pd_workshop_attendance.rb
  dashboard/lib/pd/foorm/helper.rb
  dashboard/lib/single_sign_on.rb
  dashboard/scripts/generate_fixtures.rb
  dashboard/test/factories/factories.rb
  dashboard/test/models/pd/application/teacher_application_test.rb
  dashboard/test/models/user_script_test.rb
  dashboard/test/ui/features/step_definitions/steps.rb
  dashboard/test/ui/runner.rb
  lib/cdo/data/csv_to_sql_table.rb
  lib/cdo/markdown/renderer.rb
  lib/cdo/mysql_console_helper.rb
  lib/cdo/pegasus/graphics.rb
  lib/cdo/pegasus/string.rb
  lib/cdo/poste.rb
  lib/cdo/slack.rb
  lib/rake/circle.rake
  lib/rake/test.rake
  pegasus/router.rb
  pegasus/src/text_render.rb
  shared/middleware/shared_resources.rb
Labels: code-hygiene

#49593 Adding labels and improving HTML semantics in various places
  apps/i18n/weblab/en_us.json
  apps/src/p5lab/AnimationPicker/AnimationPickerListItem.jsx
  apps/src/p5lab/poetry/PoemSelector.jsx
  apps/src/weblab/WebLabView.jsx
Labels: accessibility

#49567 Make project rename input/submit keyboard accessible
  apps/src/code-studio/components/header/EditableProjectName.jsx
Labels: accessibility

#49535 Remove facilitator models
  apps/script/generateSharedConstants.rb
  dashboard/app/models/ability.rb
  dashboard/app/models/pd/application/active_application_models.rb
  dashboard/app/models/pd/application/facilitator1819_application.rb
  dashboard/app/models/pd/application/facilitator1920_application.rb
  dashboard/app/models/pd/application/facilitator_application_base.rb
  dashboard/app/models/pd/enrollment.rb
  dashboard/app/serializers/api/v1/pd/fit_cohort_view_serializer.rb
  dashboard/app/serializers/api/v1/pd/workshop_enrollment_serializer.rb
  dashboard/test/factories/pd_factories.rb
  dashboard/test/helpers/pd/application/pd_workshop_helper_test.rb
  dashboard/test/serializers/api/v1/pd/workshop_enrollment_serializer_test.rb
  lib/cdo/shared_constants/pd/facilitator1819_application_constants.rb
  lib/cdo/shared_constants/pd/facilitator1920_application_constants.rb
Labels: remove-facilitator-apps

#49631 I18n sync In & Up 01/04
  i18n/locales/source/animations/spritelab_animation_library.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/weblab.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/markdown/public/helloworld.md
  i18n/locales/source/markdown/public/poetry.md
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#49253 Remove `poise-python` Cookbooks Dependency
  cookbooks/cdo-awscli/metadata.rb
  cookbooks/cdo-awscli/recipes/default.rb
Labels: Chef 17

#49584 Remove duplicate run/reset buttons from app lab
  apps/src/applab/ApplabVisualizationColumn.jsx
  apps/src/templates/GameButtons.jsx
Labels: accessibility

#49641 A11y 35 alt text circuit playground images
  apps/i18n/applab/en_us.json
  apps/src/lib/kits/maker/ui/SetupGuide.jsx
Labels: accessibility

#49473 Add label and aria-expanded for Javalab file options toggle button
  apps/i18n/common/en_us.json
  apps/src/javalab/JavalabEditor.jsx
Labels: accessibility

#49476 Add aria-label to progress bubble links
  apps/src/templates/progress/BubbleFactory.jsx
Labels: accessibility

#49544 Fix tab-navigation for ContentContainer links
  apps/src/templates/ContentContainer.jsx
Labels: accessibility

#49546 Add alt text to SectionLoginInfo images
  apps/i18n/common/en_us.json
  apps/src/templates/teacherDashboard/SectionLoginInfo.jsx
  apps/src/templates/teacherDashboard/teacherSectionsRedux.js
Labels: accessibility

#49547 Set html lang attribute
  dashboard/app/views/layouts/application.html.haml
Labels: accessibility

#49640 Revert "Revert "Remove `poise-python` Cookbooks Dependency""
  cookbooks/Berksfile.lock
  cookbooks/cdo-awscli/metadata.rb
  cookbooks/cdo-awscli/recipes/default.rb
Labels: Chef 17

#49690 I18n sync In & Up 01/07
  i18n/locales/source/blockly-mooc/applab.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2022/coursec-2022.json
  i18n/locales/source/course_content/2022/coursef-2022.json
  i18n/locales/source/course_content/2022/express-2022.json
  i18n/locales/source/course_content/other/csd6-2022.json
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#49218 I18n sync loads the AI lab UI and datasets-manifest.json strings
  apps/i18n/fish/README.md
  apps/i18n/mlPlayground/README.md
  apps/i18n/mlPlayground/en_us.json
  apps/i18n/mlPlayground/es_es.json
  apps/package.json
  apps/src/ailab/Ailab.js
  apps/src/ailab/mlPlayground_locale.js
  apps/yarn.lock
  bin/i18n-codeorg/in.sh
  bin/i18n/codeorg_crowdin.yml
  bin/i18n/sync-in.rb
  bin/i18n/sync-out.rb
  dashboard/app/helpers/levels_helper.rb
  dashboard/app/views/levels/_apps_dependencies.html.haml
Labels: translate-csd

#49709 I18n sync In & Up 01/09
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/markdown/public/educate/it.md
Labels: i18n

#49668 Fix Violations of and Reenable `Lint/SymbolConversion`
  .rubocop_todo.yml
  aws/lambda/ssm_session_slack/ssm_session_slack.rb
  bin/animation_assets/manifest_builder.rb
  bin/animation_assets/rebuild_default_sprites.rb
  bin/i18n/i18n_script_utils.rb
  bin/oneoff/backfill_data/principalapproval1920_application_pay_fee_changes.rb
  bin/oneoff/backfill_data/teacher1920_application_pay_fee_changes
  bin/oneoff/upload_non_en_videos.rb
  dashboard/app/controllers/concerns/azure_text_to_speech.rb
  dashboard/app/controllers/levels_controller.rb
  dashboard/app/controllers/test_controller.rb
  dashboard/app/models/backpack.rb
  dashboard/legacy/middleware/files_api.rb
  dashboard/legacy/middleware/helpers/firebase_helper.rb
  dashboard/legacy/test/middleware/test_channels.rb
  dashboard/legacy/test/middleware/test_sources.rb
  dashboard/lib/announcements.rb
  dashboard/scripts/update_tts_i18n_static_messages.rb
  dashboard/scripts/update_under_13_students.rb
  dashboard/test/config/application_test.rb
  dashboard/test/controllers/activities_controller_test.rb
  dashboard/test/controllers/api/v1/assessments_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshop_survey_foorm_report_controller_test.rb
  dashboard/test/controllers/api/v1/pd/workshop_survey_report_controller_test.rb
  dashboard/test/controllers/api_controller_test.rb
  dashboard/test/controllers/datasets_controller_test.rb
  dashboard/test/controllers/javabuilder_sessions_controller_test.rb
  dashboard/test/controllers/lessons_controller_test.rb
  dashboard/test/controllers/levels_controller_test.rb
  dashboard/test/controllers/script_levels_controller_test.rb
  dashboard/test/factories/pd_factories.rb
  dashboard/test/integration/db_query_test.rb
  dashboard/test/lib/pd/foorm/rollup_creator_test.rb
  dashboard/test/lib/pd/foorm/rollup_helper_test.rb
  dashboard/test/lib/pd/survey_pipeline/daily_survey_decorator_test.rb
  dashboard/test/lib/policies/script_activity_test.rb
  dashboard/test/lib/projects_list_test.rb
  dashboard/test/lib/services/complete_application_reminder_test.rb
  dashboard/test/models/blockly_test.rb
  dashboard/test/models/concerns/text_to_speech_test.rb
  dashboard/test/models/foorm/simple_survey_submission_test.rb
  dashboard/test/models/lesson_test.rb
  dashboard/test/models/level_test.rb
  dashboard/test/models/multi_test.rb
  dashboard/test/models/pd/application/teacher_application_test.rb
  dashboard/test/models/pd/workshop_survey_foorm_submission_test.rb
  dashboard/test/models/plc/course_unit_module_selection_test.rb
  dashboard/test/models/unit_test.rb
  dashboard/test/models/user_test.rb
  lib/cdo/aws/dms.rb
  lib/cdo/contact_rollups/v2/pardot_helpers.rb
  lib/cdo/newrelic.rb
  lib/cdo/png_utils.rb
  lib/dynamic_config/dcdo.rb
  pegasus/src/homepage.rb
  shared/test/test_dms.rb
  shared/test/test_rds.rb
  tools/scripts/rebuildSoundLibraryManifest.rb
Labels: code-hygiene

#49670 Revert "Revert "Update Chef Infra Client to 17.6.18""
  aws/chef-bootstrap.sh
  cookbooks/Gemfile
  cookbooks/Gemfile.lock
  cookbooks/cdo-analytics/.kitchen.yml
  cookbooks/cdo-apps/.kitchen.yml
  cookbooks/cdo-apps/attributes/default.rb
  cookbooks/cdo-awscli/.kitchen.yml
  cookbooks/cdo-cloudwatch-agent/.kitchen.yml
  cookbooks/cdo-i18n/.kitchen.yml
  cookbooks/cdo-jemalloc/.kitchen.yml
  cookbooks/cdo-mysql/.kitchen.yml
  cookbooks/cdo-nginx/.kitchen.yml
  cookbooks/cdo-nodejs/.kitchen.yml
  cookbooks/cdo-postfix/.kitchen.yml
  cookbooks/cdo-redis/.kitchen.yml
  cookbooks/cdo-repository/.kitchen.yml
  cookbooks/cdo-ruby/.kitchen.yml
  cookbooks/cdo-syslog/.kitchen.yml
  cookbooks/cdo-tippecanoe/.kitchen.yml
  cookbooks/cdo-users/.kitchen.yml
  cookbooks/cdo-varnish/.kitchen.yml
  lib/cdo/cloud_formation/cdo_app.rb
Labels: Chef 17

#49686 Revert "Revert "Updating and restyling buttons on unit overview page""
  apps/src/templates/progress/HiddenForSectionToggle.jsx
  apps/src/templates/progress/LessonLock.jsx
  apps/src/templates/progress/ProgressLessonTeacherInfo.jsx
  apps/src/templates/progress/SendLesson.jsx
  apps/test/unit/templates/progress/HiddenForSectionToggleTest.jsx
Labels: accessibility

#49765 Updating accessibility of Manage Code Groups button
  apps/src/templates/manageStudents/CodeReviewGroupsDialog.jsx
Labels: accessibility

#49788 Fix Violations of and Reenable `Performance/TimesMap`
  .rubocop_todo.yml
  bin/i18n/translation_monitor/config_helper.rb
  dashboard/test/controllers/activities_controller_test.rb
  dashboard/test/helpers/pd/application/pd_workshop_helper_test.rb
  dashboard/test/helpers/pd/page_helper_test.rb
  dashboard/test/lib/pd/jot_form/form_questions_test.rb
  dashboard/test/models/concerns/pd/jot_form_backed_form_test.rb
  dashboard/test/models/pd/session_test.rb
  dashboard/test/models/pd/workshop_test.rb
  dashboard/test/models/sections/section_test.rb
  lib/cdo/aws/glue.rb
  lib/rake/test.rake
  lib/test/cdo/test_code_generation.rb
Labels: code-hygiene

#49835 I18n sync In & Up 01/17
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/gamelab.json
  i18n/locales/source/blockly-mooc/mlPlayground.json
  i18n/locales/source/blockly-mooc/spritelab.json
  i18n/locales/source/course_content/2022/csd3-2022.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#49790 Fix Violations of and Reenable `Style/FileRead` and `Style/FileWrite`
  .rubocop_todo.yml
  bin/animation_assets/manifest_builder.rb
  bin/animation_assets/rebuild_default_sprites.rb
  bin/i18n-codeorg/lib/csv-to-yml.rb
  bin/i18n-codeorg/lib/merge-all-locales.rb
  bin/i18n/sync-in.rb
  bin/i18n/sync-out.rb
  bin/i18n/translation_monitor/data_io_helper.rb
  bin/remove_script_remnants
  dashboard/app/controllers/pd/workshop_enrollment_controller.rb
  dashboard/legacy/test/middleware/test_assets.rb
  dashboard/scripts/archive/count_lines
  dashboard/test/lib/image_lib_test.rb
  dashboard/test/ui/runner.rb
  lib/cdo/poste.rb
  lib/cdo/rake_utils.rb
  lib/cdo/test_flakiness.rb
  lib/dynamic_config/adapters/json_file_adapter.rb
  lib/dynamic_config/loaders/dcdo_loader.rb
  lib/dynamic_config/loaders/gatekeeper_loader.rb
  shared/test/test_s3_packaging.rb
  tools/scripts/rebuildSoundLibraryManifest.rb
Labels: code-hygiene

#49789 Update Chef Git Customizations for Chef Client 17 Compatibility
  cookbooks/cdo-repository/libraries/git.rb
Labels: Chef 17, Ruby Update

#49741 Update Rails to 6.0.6 (targeted)
  Gemfile
  Gemfile.lock
Labels: Rails 6

#49947 note alternative to AWS SecretsManager
  SETUP.md
  locals.yml.default
Labels: dev-experience

#49980 I18n sync In & Up 01/30
  i18n/locales/source/course_content/2022/coursec-2022.json
  i18n/locales/source/course_content/2022/coursee-2022.json
  i18n/locales/source/course_content/2022/csd2-2022.json
  i18n/locales/source/course_content/2022/csd3-2022.json
  i18n/locales/source/course_content/2022/express-2022.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/external-sources/ml-playground/datasets/abalone.json
  i18n/locales/source/external-sources/ml-playground/datasets/auto_mpg.json
  i18n/locales/source/external-sources/ml-playground/datasets/basketball_shots.json
  i18n/locales/source/external-sources/ml-playground/datasets/bike_sharing.json
  i18n/locales/source/external-sources/ml-playground/datasets/billionaires.json
  i18n/locales/source/external-sources/ml-playground/datasets/boba_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/car_evaluation.json
  i18n/locales/source/external-sources/ml-playground/datasets/census_part.json
  i18n/locales/source/external-sources/ml-playground/datasets/club_biased_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/club_random_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/club_sparse_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/club_specific_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/cookies_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/exoplanets.json
  i18n/locales/source/external-sources/ml-playground/datasets/global_happiness_raw.json
  i18n/locales/source/external-sources/ml-playground/datasets/heart.json
  i18n/locales/source/external-sources/ml-playground/datasets/housing_data.json
  i18n/locales/source/external-sources/ml-playground/datasets/icecream_toppings_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/insurance_cost.json
  i18n/locales/source/external-sources/ml-playground/datasets/jeans.json
  i18n/locales/source/external-sources/ml-playground/datasets/loneliness_interests.json
  i18n/locales/source/external-sources/ml-playground/datasets/loneliness_movies.json
  i18n/locales/source/external-sources/ml-playground/datasets/loneliness_music.json
  i18n/locales/source/external-sources/ml-playground/datasets/loneliness_personality.json
  i18n/locales/source/external-sources/ml-playground/datasets/loneliness_phobias.json
  i18n/locales/source/external-sources/ml-playground/datasets/medical_priority.json
  i18n/locales/source/external-sources/ml-playground/datasets/movies.json
  i18n/locales/source/external-sources/ml-playground/datasets/naan_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/nutrition.json
  i18n/locales/source/external-sources/ml-playground/datasets/pizza_toppings_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/poke_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/poutine_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/raspado_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/safari_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/salad_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/salsa_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/shapes_v1_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/shapes_v2_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/shoe_survey_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/songs.json
  i18n/locales/source/external-sources/ml-playground/datasets/student_alcohol_consumption.json
  i18n/locales/source/external-sources/ml-playground/datasets/student_survey.json
  i18n/locales/source/external-sources/ml-playground/datasets/taco_toppings_toy.json
  i18n/locales/source/external-sources/ml-playground/datasets/thanksgiving.json
  i18n/locales/source/external-sources/ml-playground/datasets/zoo.json
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#50000 I18n sync In & Up 01/31
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/markdown/public/educate/it.md
Labels: i18n
