Repository code-dot-org/code-dot-org, pull requests merged in 2024-01, with the labels that each got.

#55495 Updating alt text as a followup to enabling alt text linter check
  apps/src/code-studio/components/header/SignInCallout.jsx
  apps/src/lab2/views/ErrorFallbackPage.tsx
  apps/src/templates/instructions/PromptIcon.jsx
  apps/test/unit/templates/instructions/PromptIconTest.jsx
  apps/test/unit/templates/studioHomepages/CourseCardTest.js
  apps/test/unit/templates/studioHomepages/TopCourseTest.js
Labels: accessibility

#55408 Fix Violations of and Reenable `jsx-a11y/heading-has-content`
  apps/.eslintrc.js
  apps/src/lib/ui/Headings.jsx
Labels: code-hygiene, hackathon, accessibility

#55312 Run Linting in Drone CI
  Gemfile
  docker/unit_tests.sh
  tools/hooks/hooks_utils.rb
  tools/hooks/lint.rb
Labels: code-hygiene, dev-experience

#55479 Restrict pegasus and dashboard requires
  .rubocop.yml
  dashboard/test/helpers/delete_accounts_helper_test.rb
  lib/cdo/web_purify.rb
  lib/rake/eyes.rake
  pegasus/test/fixtures/fake_dashboard.rb
  pegasus/test/test_minecraft_certificates.rb
  shared/test/test_poste.rb
  tools/customLinters/rubocop_dashboard_requires.rb
  tools/customLinters/rubocop_pegasus_requires.rb
Labels: separating-pegasus

#55560 Restrict Drone Linting to Just Existing Files
  tools/hooks/lint.rb
Labels: code-hygiene, bug-fix, dev-experience

#54239 Use Keyword Argument for `student_facing` in Curriculum PDFs
  dashboard/app/models/lesson.rb
  dashboard/lib/services/curriculum_pdfs.rb
  dashboard/lib/services/curriculum_pdfs/lesson_plans.rb
  dashboard/test/lib/services/curriculum_pdfs/lesson_plans_test.rb
Labels: code-hygiene

#50710 CanCanCan 3.5
  Gemfile
  Gemfile.lock
Labels: dependencies, Rails Upgrade

#55543 I18n sync In & Up 01/03
  i18n/locales/source/blockly-mooc/applab.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/dance.json
  i18n/locales/source/dashboard/marketing_announcements.json
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#55642 Use Ubuntu 20 in All Managed Environments
  lib/cdo/cloud_formation/cdo_app.rb
Labels: Ubuntu Update

#55723 Update `SETUP.md` for Ubuntu 20
  SETUP.md
Labels: Ubuntu Update

#55756 I18n sync In & Up 01/16
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/applab.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2023/csc-ecosystems-2023.json
  i18n/locales/source/course_content/2023/csd3-2023.json
  i18n/locales/source/course_content/2023/csd4-2023.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#55747 Undo Custom DNS Patch for Ubuntu 18
  cookbooks/cdo-apps/files/default/resolved
Labels: code-hygiene, Ubuntu Update

#54427 Remove Deprecated Patch for an Ubuntu 18 Bug
  cookbooks/cdo-apps/files/default/resolved
  cookbooks/cdo-apps/recipes/default.rb
  cookbooks/cdo-apps/recipes/resolved.rb
Labels: code-hygiene, Ubuntu Update

#55969 I18n sync In & Up 01/25
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/course_content/2023/csc-mappinglandmarks-2023.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#55982 broaden db lint rules to include POSTE_DB and helper methods
  dashboard/test/testing/poste_assertions.rb
  lib/cdo/poste.rb
  lib/test/test_deliverer.rb
  pegasus/helper_modules/dashboard.rb
  pegasus/helpers.rb
  pegasus/helpers/email_preference_helpers.rb
  pegasus/helpers/form_helpers.rb
  pegasus/router.rb
  pegasus/routes/v2_forms_routes.rb
  pegasus/test/test_dashboard.rb
  pegasus/test/test_email_preference_helpers.rb
  shared/test/test_poste.rb
  tools/customLinters/rubocop_dashboard_db_usage.rb
  tools/customLinters/rubocop_dashboard_requires.rb
  tools/customLinters/rubocop_pegasus_db_usage.rb
  tools/customLinters/rubocop_pegasus_requires.rb
Labels: separating-pegasus

#56053 Enable custom rubocop rules in haml lint
  .haml-lint.yml
  .haml-lint_todo.yml
  lib/rake/lint.rake
  pegasus/sites.v3/code.org/public/courses-draft.haml
  pegasus/sites.v3/code.org/public/review-hociyskvuwa/index.haml
  pegasus/sites.v3/code.org/public/review-hociyskvuwa/splat.haml
  pegasus/sites.v3/code.org/views/header.haml
  shared/haml/user_header.haml
Labels: separating-pegasus
