Repository code-dot-org/code-dot-org, pull requests merged in 2024-02, with the labels that each got.

#56084 MySQL 8 Compatibility in Pegasus
  pegasus/src/database.rb
  pegasus/test/test_form_routes.rb
  pegasus/test/test_hoc_event_review.rb
Labels: MySQL Upgrade

#56349 Refresh DataViews after each data modifying action
  apps/src/applab/applab.js
  apps/src/storage/dataBrowser/AddKeyRow.jsx
  apps/src/storage/dataBrowser/AddTableRow.jsx
  apps/src/storage/dataBrowser/DataOverview.jsx
  apps/src/storage/dataBrowser/DataTable.jsx
  apps/src/storage/dataBrowser/DataTableView.jsx
  apps/src/storage/dataBrowser/EditKeyRow.jsx
  apps/src/storage/dataBrowser/EditTableListRow.jsx
  apps/src/storage/dataBrowser/EditTableRow.jsx
  apps/src/storage/dataBrowser/loadDataForView.js
  apps/src/storage/datablockStorage.js
  apps/src/storage/storage.js
Labels: unfirebase

#56464 Use DataStorageTable.columns in all controller methods instead of inferring from data
  apps/src/storage/datablockStorage.js
  dashboard/app/controllers/datablock_storage_controller.rb
  dashboard/app/models/datablock_storage_record.rb
  dashboard/app/models/datablock_storage_table.rb
Labels: unfirebase

#56466 DatablockStorage: switch to fat models
  apps/src/storage/datablockStorage.js
  dashboard/app/controllers/datablock_storage_controller.rb
  dashboard/app/models/datablock_storage_record.rb
  dashboard/app/models/datablock_storage_table.rb
Labels: unfirebase

#56469 Re-group DatablockStorage API to look more REST-ish
  dashboard/app/controllers/datablock_storage_controller.rb
  dashboard/config/routes.rb
Labels: unfirebase

#56471 Rework DatablockStorage methods to not use Firebase-isms
  apps/src/storage/dataBrowser/EditTableListRow.jsx
  apps/src/storage/dataBrowser/loadDataForView.js
  apps/src/storage/datablockStorage.js
  apps/src/storage/firebaseStorage.js
  apps/src/storage/firebaseStorageInterface.js
  apps/src/storage/storage.js
Labels: unfirebase

#56473 Redirected-Read and Copy-On-Write support makes Shared Tables Work
  apps/src/applab/applab.js
  apps/src/storage/GetColumnParamPicker.jsx
  apps/src/storage/dataBrowser/DataLibraryPane.jsx
  apps/src/storage/datablockStorage.js
  apps/src/storage/firebaseStorage.js
  dashboard/app/controllers/datablock_storage_controller.rb
  dashboard/app/models/datablock_storage_table.rb
Labels: unfirebase

#56481 I18n sync In & Up 02/09
  i18n/locales/source/blockly-mooc/applab.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/dance.json
  i18n/locales/source/course_content/2023/csc-mappinglandmarks-2023.json
  i18n/locales/source/course_content/2023/csd6a-2023.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/markdown/public/athome.md
  i18n/locales/source/markdown/public/break.md
  i18n/locales/source/markdown/public/curriculum/unplugged.md
  i18n/locales/source/markdown/public/helloworld.md
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#56514 I18n sync In & Up 02/12
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#56535 Adding amplitude events for update school dialog
  apps/src/lib/ui/SchoolInfoConfirmationDialog.jsx
  apps/src/lib/util/AnalyticsConstants.js
  apps/test/unit/lib/ui/SchoolInfoConfirmationDialogTest.js
Labels: accessibility

#56384 Fix Violations of and Reenable `jsx-a11y/no-noninteractive-tabindex`
  apps/.eslintrc.js
  apps/src/applab/Visualization.jsx
  apps/src/code-studio/components/header/DisplayProjectName.jsx
  apps/src/componentLibrary/tags/_Tag.tsx
  apps/src/dance/ai/DanceAiModalHeader.tsx
  apps/src/templates/HourOfCodeGuideEmailDialog.jsx
  apps/src/templates/InlineDropdownMenu.jsx
  apps/src/templates/MultipleSectionsAssigner.jsx
  apps/src/templates/curriculumCatalog/CardLabels.jsx
  apps/src/templates/instructions/InstructionsCsfLeftCol.jsx
  apps/src/templates/sectionsRefresh/coteacherSettings/CoteacherTable.jsx
Labels: code-hygiene, hackathon

#56536 Per-project `appOptions.useDatablockStorage` stored in DB
  apps/src/applab/applab.js
  dashboard/app/helpers/levels_helper.rb
  dashboard/app/models/game.rb
  dashboard/app/models/project_use_datablock_storage.rb
  dashboard/db/migrate/20240215100626_create_project_use_datablock_storages.rb
  dashboard/db/schema.rb
  dashboard/db/schema_cache.yml
Labels: unfirebase

#56609 Datablock Storage: switch DB from channel_id to project_id
  dashboard/app/controllers/datablock_storage_controller.rb
  dashboard/app/models/datablock_storage_kvp.rb
  dashboard/app/models/datablock_storage_record.rb
  dashboard/app/models/datablock_storage_table.rb
  dashboard/db/migrate/20240110234501_create_datablock_storage_kvps.rb
  dashboard/db/migrate/20240111002910_create_datablock_storage_records.rb
  dashboard/db/migrate/20240111003957_create_datablock_storage_tables.rb
  dashboard/db/schema.rb
Labels: unfirebase

#56618 DRY up datablock_storage routes
  apps/src/applab/applab.js
  apps/src/storage/datablockStorage.js
  dashboard/app/controllers/datablock_storage_controller.rb
  dashboard/config/routes.rb
Labels: unfirebase

#56621 Store "Data Library" info in `DatablockStorageLibraryManifest`
  apps/src/storage/datablockStorage.js
  dashboard/app/controllers/datablock_storage_controller.rb
  dashboard/app/models/datablock_storage_library_manifest.rb
  dashboard/app/views/datablock_storage/index.html.haml
  dashboard/config/routes.rb
  dashboard/db/migrate/20240216053618_create_datablock_storage_library_manifest.rb
  dashboard/db/schema.rb
Labels: unfirebase

#56622 Migration: seed library manifest data from Firebase
  dashboard/db/migrate/20240216071353_seed_datasets_from_firebase.rb
  firebase_data.json
Labels: unfirebase

#56380 Fix Violations of and Reenable `Performance/MethodObjectAsBlock`
  .rubocop_todo.yml
  dashboard/app/models/concerns/solution_blocks.rb
  dashboard/config/initializers/no_transform_paths.rb
  lib/cdo/app_server_metrics.rb
  lib/cdo/buffer.rb
  lib/cdo/cloud_formation/lambda.rb
  lib/cdo/config.rb
  lib/cdo/create_header.rb
  lib/cdo/hash_utils.rb
  lib/cdo/secrets.rb
  lib/cdo/secrets_config.rb
  lib/rake/test.rake
  lib/test/cdo/test_buffer.rb
  pegasus/helpers/page_helpers.rb
  pegasus/test/test_pegasus_documents.rb
Labels: code-hygiene, performance

#56699 DCDO flag `fraction_of_new_projects_use_datablock_storage` controls whether projects use_datablock_storage
  dashboard/legacy/middleware/helpers/projects.rb
Labels: unfirebase

#56700 Disable CSRF on DatablockStorageController
  apps/src/storage/datablockStorage.js
  dashboard/app/controllers/datablock_storage_controller.rb
Labels: unfirebase

#56669 I18n sync In & Up 02/20
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/dance.json
  i18n/locales/source/blockly-mooc/music.json
  i18n/locales/source/course_content/2023/coursee-2023.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#56723 chore(deps): bump all cloudformation dependencies to the latest.
  aws/cloudformation/package.json
  aws/cloudformation/yarn.lock
Labels: infrastructure, eng-excellence

#56814 I18n sync In & Up 02/26
  i18n/locales/source/blockly-mooc/applab.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#56898 Datablock Storage: make coercion tests pass
  dashboard/app/controllers/datablock_storage_controller.rb
  dashboard/app/models/datablock_storage_table.rb
  dashboard/test/controllers/datablock_storage_controller_test.rb
Labels: unfirebase

#56901 Fix all coerce, populate and import issues founds with new tests
  apps/src/storage/datablockStorage.js
  dashboard/app/controllers/datablock_storage_controller.rb
  dashboard/app/models/datablock_storage_kvp.rb
  dashboard/app/models/datablock_storage_table.rb
  dashboard/test/controllers/datablock_storage_controller_test.rb
Labels: unfirebase

#56902 Datablock Storage: auto-cast values on import_csv
  dashboard/app/models/datablock_storage_table.rb
  dashboard/test/controllers/datablock_storage_controller_test.rb
Labels: unfirebase

#56897 Updating a11y linter to remove unnecessary toggled off blob rule
  apps/.eslintrc.js
Labels: accessibility
