Repository code-dot-org/code-dot-org, pull requests merged in 2024-03, with the labels that each got.

#56964 I18n sync In & Up 03/04
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/markdown/public/poetry.md
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#57169 I18n sync In & Up 03/11
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/2023/csc-mappinglandmarks-2023.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#56746 Update Rails to 6.1.7.7
  Gemfile.lock
Labels: Rails Upgrade

#56364 Avoid `utf8` Alias in Schema Dump
  dashboard/config/initializers/mysql_avoid_utf8_alias_in_schema_dump.rb
  dashboard/db/schema.rb
  dashboard/test/config/initializers/mysql_avoid_utf8_alias_in_schema_dump_test.rb
Labels: MySQL Upgrade

#57216 I18n sync In & Up 03/12
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/course_content/2023/csd4-2023.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#57260 Datablock Storage: index tables by project_id
  dashboard/app/controllers/datablock_storage_controller.rb
  dashboard/app/models/datablock_storage_kvp.rb
  dashboard/app/models/datablock_storage_record.rb
  dashboard/app/models/datablock_storage_table.rb
  dashboard/db/migrate/20240110234501_create_datablock_storage_kvps.rb
  dashboard/db/migrate/20240111002910_create_datablock_storage_records.rb
  dashboard/db/migrate/20240111003957_create_datablock_storage_tables.rb
  dashboard/db/schema.rb
Labels: unfirebase

#57279 Fix Violations of and Reenable `Style/HashEachMethods`
  .rubocop_todo.yml
  bin/curriculum/remove_lesson_yml.rb
  bin/i18n/resources/dashboard/courses/sync_in.rb
  bin/i18n/resources/dashboard/scripts/sync_in.rb
  bin/oneoff/backfill_data/user_proficiencies
  bin/oneoff/compute_master_metrics_user_proficiencies
  cookbooks/Berksfile
  cookbooks/local_cookbooks.rb
  cookbooks/update_cookbook_versions
  dashboard/app/controllers/openai_chat_controller.rb
  dashboard/app/models/concerns/seeded.rb
  dashboard/app/models/levels/ailab.rb
  dashboard/app/models/levels/blockly.rb
  dashboard/app/models/levels/fish.rb
  dashboard/app/models/levels/javalab.rb
  dashboard/app/models/levels/weblab.rb
  dashboard/app/models/pd/application/teacher_application.rb
  dashboard/app/models/unit.rb
  dashboard/lib/projects_list.rb
  dashboard/lib/quick_assign_helper.rb
  dashboard/test/controllers/authored_hint_view_requests_controller_test.rb
  dashboard/test/controllers/notes_controller_test.rb
  dashboard/test/models/pd/application/teacher_application_test.rb
  lib/cdo.rb
  lib/cdo/aws/metrics.rb
  lib/cdo/config.rb
  lib/cdo/rack/allowlist.rb
  pegasus/src/curriculum_router.rb
Labels: code-hygiene

#57303 Fix a Few More Violations of `Style/HashEachMethods`
  dashboard/app/views/notes/index.html.haml
  dashboard/app/views/shared/_school_info.html.haml
  pegasus/sites.v3/code.org/views/school_info.haml
Labels: code-hygiene

#56279 Datablock Storage: replace firebase for applab data features
  apps/src/applab/Exporter.js
  apps/src/applab/PlaySpaceHeader.jsx
  apps/src/applab/applab.js
  apps/src/applab/commands.js
  apps/src/code-studio/appOptions.js
  apps/src/p5lab/P5Lab.js
  apps/src/storage/GetColumnParamPicker.jsx
  apps/src/storage/dataBrowser/AddKeyRow.jsx
  apps/src/storage/dataBrowser/AddTableRow.jsx
  apps/src/storage/dataBrowser/DataLibraryPane.jsx
  apps/src/storage/dataBrowser/DataOverview.jsx
  apps/src/storage/dataBrowser/DataTable.jsx
  apps/src/storage/dataBrowser/DataTableView.jsx
  apps/src/storage/dataBrowser/EditKeyRow.jsx
  apps/src/storage/dataBrowser/EditTableListRow.jsx
  apps/src/storage/dataBrowser/EditTableRow.jsx
  apps/src/storage/dataBrowser/loadDataForView.js
  apps/src/storage/datablockStorage.js
  apps/src/storage/firebaseCounters.js
  apps/src/storage/firebaseMetadata.js
  apps/src/storage/firebaseStorage.js
  apps/src/storage/redux/data.js
  apps/src/storage/storage.js
  apps/test/integration/levelTests.js
  apps/test/unit/storage/FirebaseStorageTest.js
  apps/webpackKarma.config.js
  bin/cron/applab_datasets/covid19
  bin/cron/applab_datasets/daily_weather
  bin/cron/applab_datasets/spotify
  dashboard/app/controllers/datablock_storage_controller.rb
  dashboard/app/controllers/datasets_controller.rb
  dashboard/app/controllers/levels_controller.rb
  dashboard/app/controllers/projects_controller.rb
  dashboard/app/helpers/levels_helper.rb
  dashboard/app/models/datablock_storage_kvp.rb
  dashboard/app/models/datablock_storage_library_manifest.rb
  dashboard/app/models/datablock_storage_record.rb
  dashboard/app/models/datablock_storage_table.rb
  dashboard/app/models/game.rb
  dashboard/app/models/project_use_datablock_storage.rb
  dashboard/app/views/datablock_storage/index.html.haml
  dashboard/config/routes.rb
  dashboard/legacy/middleware/helpers/firebase_helper.rb
  dashboard/legacy/middleware/helpers/projects.rb
  dashboard/legacy/middleware/tables_api.rb
  dashboard/legacy/test/middleware/helpers/test_firebase_helper.rb
  dashboard/legacy/test/middleware/test_tables.rb
  dashboard/test/controllers/datablock_storage_controller_test.rb
  dashboard/test/controllers/datasets_controller_test.rb
  dashboard/test/factories/factories.rb
  dashboard/test/helpers/delete_accounts_helper_test.rb
  lib/cdo/delete_accounts_helper.rb
Labels: unfirebase

#57204 Update Redis gem to 4.8.1
  Gemfile
  Gemfile.lock
Labels: dependencies

#57549 Add Several Small `test/` Directories to Eslint Import Order Rule
  apps/.eslintrc.js
  apps/test/storybook/renderStoriesTest.js
Labels: code-hygiene

#57567 Fix Violations of and Reenable `Style/GlobalStdStream`
  .rubocop_todo.yml
  bin/dotd
  bin/oneoff/backfill_data/backfill_pilot_section_course_id
  bin/oneoff/backfill_data/backfill_section_instructors
  bin/oneoff/data_fix/csedweek_event_to_hoc_signup_2013
  bin/oneoff/data_fix/fix_bad_school_info_in_users
  bin/oneoff/data_fix/fix_invalid_users
  bin/oneoff/data_fix/update_last_seen_school_info_interstitial
  bin/oneoff/nces_data/export_school_districts
  bin/oneoff/nces_data/export_schools
  bin/oneoff/nces_data/import_school_districts
  bin/oneoff/nces_data/import_school_stats_by_years_2014_2015_ccd
  bin/oneoff/nces_data/import_school_stats_by_years_2015_2016_pss
  bin/oneoff/nces_data/import_school_stats_by_years_2017_2018_ccd
  bin/oneoff/nces_data/import_school_stats_by_years_2018_2019_ccd
  bin/oneoff/nces_data/import_school_stats_by_years_2019_2020_ccd
  bin/oneoff/nces_data/import_school_stats_by_years_2019_2020_pss
  bin/oneoff/nces_data/import_school_stats_by_years_2020_2021_ccd
  bin/oneoff/nces_data/import_school_stats_by_years_2021_2022_ccd
  bin/oneoff/nces_data/import_schools
  bin/test/animation_assets/test_manifest_builder.rb
  bin/test/test_helper.rb
  bin/update-contact-email
  cookbooks/cdo-users/templates/default/chef_knife.rb.erb
  dashboard/lib/account_purger.rb
  dashboard/scripts/archive/chicago_stats
  dashboard/test/lib/account_purger_test.rb
  lib/cdo.rb
  lib/cdo/aws/cloud_formation.rb
  lib/cdo/aws/s3_packaging.rb
  lib/cdo/delete_accounts_helper.rb
  lib/cdo/google/sheet.rb
  lib/cdo/honeybadger.rb
  lib/cdo/rake_utils.rb
  pegasus/Rakefile
  pegasus/src/env.rb
  shared/test/test_log.rb
Labels: code-hygiene

#57616 Enable Eslint `import-order` for Various `tutorialExplorer` Directories
  apps/.eslintrc.js
  apps/src/tutorialExplorer/filterChoice.jsx
  apps/src/tutorialExplorer/filterGroup.jsx
  apps/src/tutorialExplorer/filterGroupContainer.jsx
  apps/src/tutorialExplorer/filterGroupHeaderSelection.jsx
  apps/src/tutorialExplorer/filterGroupOrgNames.jsx
  apps/src/tutorialExplorer/filterGroupSortBy.jsx
  apps/src/tutorialExplorer/filterHeader.jsx
  apps/src/tutorialExplorer/filterSet.jsx
  apps/src/tutorialExplorer/locale-do-not-import.js
  apps/src/tutorialExplorer/responsive.jsx
  apps/src/tutorialExplorer/search.jsx
  apps/src/tutorialExplorer/toggleAllTutorialsButton.jsx
  apps/src/tutorialExplorer/tutorial.jsx
  apps/src/tutorialExplorer/tutorialDetail.jsx
  apps/src/tutorialExplorer/tutorialExplorer.js
  apps/src/tutorialExplorer/tutorialSet.jsx
  apps/src/tutorialExplorer/util.jsx
  apps/test/unit/tutorialExplorer/TutorialExplorerTest.js
  apps/test/unit/tutorialExplorer/filterChoiceTest.jsx
  apps/test/unit/tutorialExplorer/filterGroupContainerTest.jsx
  apps/test/unit/tutorialExplorer/filterGroupHeaderSelectionTest.jsx
  apps/test/unit/tutorialExplorer/filterGroupOrgNamesTest.jsx
  apps/test/unit/tutorialExplorer/filterGroupSortByTest.jsx
  apps/test/unit/tutorialExplorer/filterGroupTest.jsx
  apps/test/unit/tutorialExplorer/filterHeaderTest.jsx
  apps/test/unit/tutorialExplorer/filterSetTest.jsx
  apps/test/unit/tutorialExplorer/imageTest.jsx
  apps/test/unit/tutorialExplorer/toggleAllTutorialsButtonTest.jsx
  apps/test/unit/tutorialExplorer/tutorialSetTest.jsx
  apps/test/unit/tutorialExplorer/tutorialTest.jsx
Labels: code-hygiene

#57550 Update Devise Gem to 4.9.3
  Gemfile
  Gemfile.lock
Labels: dependencies
