Repository code-dot-org/code-dot-org, pull requests merged in 2024-04, with the labels that each got.

#57728 [ProgressV2] Add accessible icon labels
  apps/i18n/common/en_us.json
  apps/src/templates/sectionProgressV2/ItemType.jsx
  apps/src/templates/sectionProgressV2/LevelDataCell.jsx
  apps/src/templates/sectionProgressV2/ProgressIcon.jsx
  apps/test/unit/templates/sectionProgressV2/ExpandedProgressDataColumnTest.jsx
  apps/test/unit/templates/sectionProgressV2/LegendItemTest.jsx
  apps/test/unit/templates/sectionProgressV2/LevelDataCellTest.jsx
  apps/test/unit/templates/sectionProgressV2/ProgressIconTest.jsx
Labels: accessibility

#57784 [ProgressV2] Making small accessibility changes
  apps/src/templates/sectionProgressV2/ExpandedProgressColumnHeader.jsx
  apps/src/templates/sectionProgressV2/LevelProgressHeader.jsx
  apps/src/templates/sectionProgressV2/MoreDetailsDialog.jsx
  apps/src/templates/sectionProgressV2/progress-table-v2.module.scss
Labels: accessibility

#57745 Fix Violations of and Reenable `Style/ExplicitBlockArgument`
  .rubocop_todo.yml
  bin/animation_assets/manifest_builder.rb
  bin/cron/deliver_poste_messages
  bin/i18n/i18n_script_utils.rb
  bin/test/i18n/utils/test_malformed_i18n_reporter.rb
  bin/test/i18n/utils/test_pegasus_markdown.rb
  dashboard/app/controllers/application_controller.rb
  dashboard/app/helpers/pd/application/pd_workshop_helper.rb
  dashboard/lib/services/database_connections.rb
  dashboard/test/test_helper.rb
  lib/cdo/github.rb
  lib/cdo/rake_utils.rb
  pegasus/migrations/092_drop_on_columns_from_contacts.rb
  tools/scripts/rebuildSoundLibraryManifest.rb
Labels: code-hygiene

#57740 [ProgressV2] Make lesson headers tab navigable
  apps/i18n/common/en_us.json
  apps/src/templates/sectionProgressV2/ExpandedProgressColumnHeader.jsx
  apps/src/templates/sectionProgressV2/LessonProgressColumnHeader.jsx
  apps/src/templates/sectionProgressV2/ProgressIcon.jsx
  apps/src/templates/sectionProgressV2/progress-table-legend.module.scss
  apps/src/templates/sectionProgressV2/progress-table-v2.module.scss
  apps/test/unit/templates/sectionProgressV2/LessonProgressColumnHeaderTest.jsx
Labels: accessibility

#57899 [ProgressV2] Make expanding choice levels tab navigable
  apps/src/templates/sectionProgressV2/LevelProgressHeader.jsx
  apps/src/templates/sectionProgressV2/progress-table-v2.module.scss
Labels: accessibility

#57846 Enable `import-order` and Fix Violations for `turtle`, `maze`, and `jigsaw` directories
  apps/.eslintrc.js
  apps/src/jigsaw/JigsawVisualizationColumn.jsx
  apps/src/jigsaw/jigsaw.js
  apps/src/jigsaw/locale.js
  apps/src/maze/CollectorGemCounter.jsx
  apps/src/maze/MazeVisualizationColumn.jsx
  apps/src/maze/SpellingControls.jsx
  apps/src/maze/StepButton.jsx
  apps/src/maze/Visualization.jsx
  apps/src/maze/api.js
  apps/src/maze/beeBlocks.js
  apps/src/maze/blocks.js
  apps/src/maze/collectorBlocks.js
  apps/src/maze/harvesterBlocks.js
  apps/src/maze/locale.js
  apps/src/maze/maze.js
  apps/src/maze/planterBlocks.js
  apps/src/maze/results/bee.js
  apps/src/maze/results/collector.js
  apps/src/maze/results/gatherer.js
  apps/src/maze/results/harvester.js
  apps/src/maze/results/planter.js
  apps/src/maze/results/utils.js
  apps/src/maze/skins.js
  apps/src/turtle/ArtistVisualizationColumn.jsx
  apps/src/turtle/SaveImageButton.jsx
  apps/src/turtle/api.js
  apps/src/turtle/artist.js
  apps/src/turtle/blocks.js
  apps/src/turtle/levels.js
  apps/src/turtle/locale.js
  apps/src/turtle/skins.js
  apps/test/unit/maze/executionInfoTest.js
  apps/test/unit/maze/mazeTest.js
  apps/test/unit/maze/resultsHandlerTest.js
  apps/test/unit/turtle/turtleTest.js
Labels: code-hygiene

#57901 I18n sync In & Up 04/09
  dashboard/config/locales/blocks.en.yml
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/spritelab.json
  i18n/locales/source/course_content/2023/coursed-2023.json
  i18n/locales/source/course_content/2023/express-2023.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/blocks.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/marketing_announcements.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/pegasus/mobile.yml
Labels: i18n

#57985 Updated all blocks strings
  apps/i18n/common/id_id.json
  apps/i18n/common/ko_kr.json
  apps/i18n/common/th_th.json
  apps/i18n/maze/ko_kr.json
  apps/i18n/studio/id_id.json
  apps/i18n/studio/ko_kr.json
  apps/i18n/tutorialExplorer/id_id.json
  apps/lib/blockly/ko_kr.js
  bin/i18n/crowdin/etags/apps/external_sources.codeorg.json
  bin/i18n/crowdin/etags/apps/labs.codeorg.json
  bin/i18n/crowdin/etags/dashboard/base_content.codeorg.json
  bin/i18n/crowdin/etags/dashboard/blocks.codeorg.json
  bin/i18n/crowdin/etags/dashboard/course_content.codeorg.json
  bin/i18n/crowdin/etags/dashboard/data_content.codeorg.json
  bin/i18n/crowdin/etags/dashboard/scripts.codeorg.json
  dashboard/config/locales/behavior_names.ko-KR.json
  dashboard/config/locales/block_categories.th-TH.yml
  dashboard/config/locales/blocks.id-ID.yml
  dashboard/config/locales/blocks.ko-KR.yml
  dashboard/config/locales/callouts.ko-KR.json
  dashboard/config/locales/data.es-MX.yml
  dashboard/config/locales/data.id-ID.yml
  dashboard/config/locales/dsls.th-TH.yml
  dashboard/config/locales/long_instructions.hu-HU.json
  dashboard/config/locales/long_instructions.ko-KR.json
  dashboard/config/locales/scripts.th-TH.yml
  dashboard/config/locales/short_instructions.ko-KR.json
  i18n/locales/es-MX/dashboard/data.yml
  i18n/locales/id-ID/blockly-mooc/common.json
  i18n/locales/id-ID/blockly-mooc/studio.json
  i18n/locales/id-ID/blockly-mooc/tutorialExplorer.json
  i18n/locales/id-ID/dashboard/blocks.yml
  i18n/locales/id-ID/dashboard/data.yml
  i18n/locales/ko-KR/blockly-core/core.json
  i18n/locales/ko-KR/blockly-mooc/common.json
  i18n/locales/ko-KR/blockly-mooc/maze.json
  i18n/locales/ko-KR/blockly-mooc/studio.json
  i18n/locales/ko-KR/dashboard/blocks.yml
  i18n/locales/th-TH/blockly-mooc/common.json
  i18n/locales/th-TH/dashboard/block_categories.yml
  i18n/locales/th-TH/dashboard/scripts.yml
Labels: i18n

#57991 Upgraded version of redact/restore external repos
  bin/i18n/package-lock.json
  bin/i18n/package.json
Labels: i18n

#58000 Enable `import-order` Eslint Rule for `craft/` and `studio/`
  apps/.eslintrc.js
  apps/src/craft/CraftDialog.jsx
  apps/src/craft/PlayerSelectionDialog.jsx
  apps/src/craft/agent/CraftVisualizationColumn.jsx
  apps/src/craft/agent/blocks.js
  apps/src/craft/agent/craft.js
  apps/src/craft/agent/skins.js
  apps/src/craft/aquatic/craft.js
  apps/src/craft/code-connection/CraftVisualizationColumn.jsx
  apps/src/craft/code-connection/blocks.js
  apps/src/craft/code-connection/craft.js
  apps/src/craft/designer/CraftVisualizationColumn.jsx
  apps/src/craft/designer/blocks.js
  apps/src/craft/designer/craft.js
  apps/src/craft/locale.js
  apps/src/craft/simple/CraftVisualizationColumn.jsx
  apps/src/craft/simple/blocks.js
  apps/src/craft/simple/craft.js
  apps/src/craft/utils.js
  apps/src/studio/Item.js
  apps/src/studio/Sprite.js
  apps/src/studio/StudioAnimation.js
  apps/src/studio/StudioVisualizationColumn.jsx
  apps/src/studio/api.js
  apps/src/studio/blocks.js
  apps/src/studio/collidable.js
  apps/src/studio/collisionMaskWalls.js
  apps/src/studio/customLogic/bigGameLogic.js
  apps/src/studio/customLogic/customGameLogic.js
  apps/src/studio/customLogic/rocketHeightLogic.js
  apps/src/studio/customLogic/samBatLogic.js
  apps/src/studio/levels.js
  apps/src/studio/locale.js
  apps/src/studio/paramLists.js
  apps/src/studio/projectile.js
  apps/src/studio/skins.js
  apps/src/studio/spriteActions.js
  apps/src/studio/starwars/GlowFilter.js
  apps/src/studio/starwars/ImageFilter.js
  apps/src/studio/studio.js
  apps/test/unit/craft/code-connection/ccTest.js
  apps/test/unit/craft/code-connection/utilsTest.js
  apps/test/unit/craft/craftTest.js
  apps/test/unit/craft/i18nTest.js
  apps/test/unit/craft/utilsTest.js
  apps/test/unit/studio/collisionMaskWallsTest.js
  apps/test/unit/studio/itemTest.js
  apps/test/unit/studio/studioTest.js
Labels: code-hygiene

#57847 Fix Violations of and Reenable `Style/RescueModifier`
  .rubocop_todo.yml
  aws/cloudformation/update_certs
  bin/cron/deliver_poste_messages
  bin/cron/update_hoc_map
  bin/i18n/utils/malformed_i18n_reporter.rb
  cookbooks/cdo-apps/ohai/sudo_user.rb
  dashboard/app/helpers/locale_helper.rb
  dashboard/app/models/datablock_storage_table.rb
  dashboard/app/models/user.rb
  dashboard/db/migrate/20160818232419_add_relative_position_to_stages.rb
  dashboard/legacy/middleware/files_api.rb
  dashboard/legacy/middleware/helpers/firebase_helper.rb
  dashboard/legacy/middleware/net_sim_api.rb
  dashboard/lib/json_value.rb
  dashboard/scripts/archive/count_lines
  dashboard/scripts/import_course_facilitators.rb
  dashboard/test/ui/utils/selenium_browser.rb
  lib/cdo/aws/cloud_formation.rb
  lib/cdo/cloud_formation/lambda.rb
  lib/cdo/cloud_formation/tail_logs.rb
  lib/cdo/geocoder.rb
  lib/cdo/i18n_string_url_tracker.rb
  lib/cdo/optimizer.rb
  lib/cdo/rack/request.rb
  lib/cdo/rake_utils.rb
  pegasus/helpers/hourofcode_survey_helpers.rb
Labels: code-hygiene, ruby

#58006 Fix Violation of and Reenable `Layout/SpaceAroundEqualsInParameterDefault`
  .rubocop_todo.yml
  dashboard/app/models/datablock_storage_table.rb
Labels: code-hygiene

#58104 I18n sync In & Up 04/18
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/course_content/projects.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
  i18n/locales/source/markdown/public/educate/it.md
Labels: i18n

#58146 I18n sync In & Up 04/22
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/music.json
  i18n/locales/source/course_content/2024/music-intro-2024.json
  i18n/locales/source/course_content/other/music-onboard.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/progressions.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#58235 Remove Violation of and Reenable `Lint/EmptyFile`
  .rubocop_todo.yml
  pegasus/helpers/i18n_site_helpers.rb
Labels: code-hygiene
