Repository code-dot-org/code-dot-org, pull requests merged in 2025-05, with the labels that each got.

#65590 [PythonLab] Adding aria expanded status to pythonlab dropdowns
  apps/src/codebridge/InfoPanel/InfoPanel.tsx
  apps/src/codebridge/PopUpButton/PopUpButton.tsx
  apps/src/codebridge/components/ToggleFileBrowserButton.tsx
Labels: accessibility

#65510 A11Y-134 Remove __useDeprecatedTag from syncOmniAuthSectionControl
  apps/src/accounts/SyncOmniAuthSectionControl.jsx
Labels: accessibility

#65532 Adding Auth to Write-access Animation Library POSTs
  dashboard/legacy/middleware/animation_library_api.rb
  dashboard/legacy/test/middleware/test_animation_library_api.rb
Labels: levelbuilder-improvements, security

#65681 I18n sync In & Up 05/06
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#65648 [PythonLab] Keyboard nav on file organizer files
  apps/src/codebridge/FileBrowser/Draggable.tsx
  apps/src/codebridge/FileBrowser/InnerFileBrowser.tsx
Labels: accessibility

#65099 [Code Standards] Rails controller report_abuse routes
  dashboard/config/routes.rb
Labels: code-hygiene, ruby

#65356 Created EmailPreferences User concern
  dashboard/app/models/concerns/user/email_preferences.rb
  dashboard/app/models/user.rb
  dashboard/test/models/concerns/user/email_preferences_test.rb
Labels: code-hygiene, ruby, refactor

#65847 fix(Footer): update logo image size in Safari and add mobile story
  frontend/packages/component-library/src/cms/footer/footer.module.scss
  frontend/packages/component-library/src/cms/footer/stories/Footer.story.tsx
Labels: marketing-sites

#65853 feat(marketing): add placeholders for HeroBanner and SkinnyBanner
  frontend/apps/marketing/src/components/contentful/heroBanner/HeroBannerContentfulDefinition.ts
  frontend/apps/marketing/src/components/contentful/skinnyBanner/SkinnyBannerContentfulDefinition.ts
Labels: infrastructure, marketing-sites

#65863 fix(marketing): fixes fork slug and updates the all-the-things json
  frontend/apps/marketing/tests/e2e/__snapshots__/2rnXDDT2HB8MmwM6u1L4bH.json
  frontend/apps/marketing/tests/e2e/scripts/commands/fork.ts
Labels: marketing-sites

#65839 [Codebridge] Added weblab and pythonlab shortcuts for run button, console, and editor
  apps/src/codebridge/Codebridge.tsx
  apps/src/codebridge/Workspace/Workspace.tsx
Labels: accessibility

#65814 [PythonLab] Fixing ellipsis focus
  apps/src/codebridge/FileBrowser/styles/filebrowser.module.scss
  apps/src/codebridge/PopUpButton/pop-up-button.module.scss
Labels: accessibility

#65379 P20 1478 create password validations concern
  dashboard/app/models/concerns/user/password_validations.rb
  dashboard/app/models/user.rb
  dashboard/test/models/concerns/user/password_validations_test.rb
  dashboard/test/models/user_test.rb
Labels: code-hygiene, ruby, refactor

#65971 I18n sync In & Up 05/20
  i18n/locales/source/blockly-mooc/codebridge.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/markdown/public/educate/it.md
Labels: i18n

#65989 I18n sync In & Up 05/20
  i18n/locales/source/course_content/other/self-paced-pl-aiml1.json
  i18n/locales/source/course_content/other/self-paced-pl-aiml2.json
  i18n/locales/source/course_content/other/self-paced-pl-k5-getting-started.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/progressions.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#66020 I18n sync In & Up 05/21
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#65936 Gzip Cached Drone Artifacts
  .drone.yml
Labels: testing, UI Testing

#65765 Always Use Drone Cache In PRs
  .drone.yml
  .gitignore
  dashboard/lib/tasks/seed.rake
  docker/ci/scripts/prepare_ui_tests.sh
  k8s/docker/code-dot-org.dockerfile.dockerignore
  lib/rake/ci.rake
  lib/rake/install.rake
Labels: testing, UI Testing

#65932 P20-1481 Create User::Nameable concern
  dashboard/app/models/concerns/user/nameable.rb
  dashboard/app/models/concerns/user/username.rb
  dashboard/app/models/user.rb
  dashboard/test/models/concerns/user/nameable_test.rb
  dashboard/test/models/concerns/user/username_test.rb
  dashboard/test/models/user_test.rb
Labels: code-hygiene, refactor

#66117 I18n sync In & Up 05/26
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/music.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#66144 Cache `apps/build` in CI
  .drone.yml
Labels: testing

#66176 [MusicLab] Blockly user can now Escape out of SoundsPanel
  apps/src/music/blockly/FieldSounds.js
  apps/src/music/views/SoundsPanel.tsx
Labels: accessibility

#66179 [MusicLab] Adds keyboard nav link to Incubator to replace PythonLab
  apps/i18n/common/en_us.json
  apps/src/templates/studioHomepages/Incubator.jsx
  shared/images/teacher-announcement/incubator-codebridge-python.png
  shared/images/teacher-announcement/incubator-musiclab-keyboard.png
Labels: accessibility
