Repository code-dot-org/code-dot-org, pull requests merged in 2025-01, with the labels that each got.

#63072 A11y - Updating GDPR dialog to use new DSCO buttons
  apps/src/templates/GDPRDialog.jsx
Labels: accessibility

#62999 Fix duplicate links in project cards
  apps/src/templates/projects/ProjectCard.jsx
  apps/src/templates/projects/project-card.module.scss
Labels: accessibility

#63129 I18n sync In & Up 01/07
  i18n/locales/source/blockly-mooc/codebridge.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/pegasus/mobile.json
Labels: i18n

#60329 Upgrade to Ruby 3.3.4
  .drone.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  bin/test/i18n/test_i18n_script_utils.rb
  cookbooks/.ruby-version
  cookbooks/Gemfile
  cookbooks/Gemfile.lock
  cookbooks/cdo-ruby/README.md
  cookbooks/cdo-ruby/attributes/default.rb
  cookbooks/cdo-ruby/recipes/bundler.rb
  cookbooks/cdo-ruby/recipes/ruby-build.rb
  cookbooks/cdo-ruby/test/integration/default/inspec/ruby_spec.rb
  dashboard/config/application.rb
  dashboard/config/monkeypatch_state_machine.rb
  docker/README.md
  docker/ci/Dockerfile
  docker/setup-compose.yml
  docker/site-compose.yml
  docker/ui-tests-compose.yml
  docker/unit-tests-compose.yml
Labels: Ruby Update

#62983 Add skip link to dashboard
  dashboard/app/assets/stylesheets/application.scss
  dashboard/app/views/layouts/application.html.haml
  dashboard/config/locales/en.yml
Labels: accessibility

#63271 I18n sync In & Up 01/13
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#63315 Updating drum color to comply with WCAG AA contrast requirements
  apps/src/music/views/SoundStyle.module.scss
Labels: accessibility

#62878 Fix Violations of and Reenable `Style/ReturnNilInPredicateMethodDefinition`
  .config/rubocop/todo.yml
  dashboard/app/controllers/omniauth_callbacks_controller.rb
  dashboard/app/models/experiments/teacher_based_experiment.rb
  dashboard/app/models/school_stats_by_year.rb
  dashboard/app/models/unit.rb
  dashboard/app/models/unit_group.rb
  dashboard/config/initializers/refresh_activemodel_cached_attributes.rb
  dashboard/lib/pd/payment/payment_calculator_unpaid.rb
  dashboard/lib/policies/races.rb
  dashboard/test/helpers/delete_accounts_helper_test.rb
  dashboard/test/models/user_test.rb
Labels: code-hygiene

#62579 Docker-Compose-Based MySQL and Redis for Local Development
  .github/dependabot.yml
  bin/mysql-client-admin
  bin/mysql-client-dashboard-reader
  bin/mysql-client-dashboard-reporting
  bin/mysql-client-dashboard-writer
  bin/mysql-client-pegasus-reader
  bin/mysql-client-pegasus-reporting
  bin/mysql-client-pegasus-writer
  docker-compose.yml
  docker/developers/.env
  docker/developers/README.md
  docker/developers/docker-compose.dashboard.yml
  docker/developers/docker-compose.mysql.yml
  docker/developers/docker-compose.networks.yml
  docker/developers/docker-compose.redis.yml
Labels: dev-experience

#63459 Remove __useDeprecatedTag from SchoolInfoInterstitial
  apps/src/schoolInfo/SchoolInfoInterstitial.jsx
Labels: accessibility

#63425 I18n sync In & Up 01/20
  i18n/locales/source/blockly-mooc/aichat.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/signup.json
  i18n/locales/source/course_content/2024/exploring-gen-ai2-2024.json
  i18n/locales/source/course_content/2024/foundations-gen-ai-2024.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/data.yml
  i18n/locales/source/dashboard/progressions.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#63506 A11 y 98 semantic button project app type area
  apps/src/templates/projects/ProjectAppTypeArea.jsx
  apps/src/templates/projects/ProjectCardRow.jsx
  apps/test/unit/templates/projects/ProjectAppTypeAreaTest.js
Labels: accessibility

#63548 Updating toggles to be screen reader accessible
  apps/src/templates/ToggleButton.jsx
  apps/src/templates/ToggleGroup.jsx
Labels: accessibility

#63528 I18n sync In & Up 01/27
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n
