Repository code-dot-org/code-dot-org, pull requests merged in 2025-08, with the labels that each got.

#67330 Update More Config Values for Rails 7.0
  dashboard/config/application.rb
  dashboard/config/initializers/new_framework_defaults_7_0.rb
Labels: Rails Upgrade

#67523 I18n sync In & Up 08/04
  i18n/locales/source/blockly-mooc/aichat.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/music.json
  i18n/locales/source/blockly-mooc/signup.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/course_content/other/self-paced-pl-k5-getting-started.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#66251 stop adding levels to unit fixtures in dashboard unit tests
  dashboard/test/controllers/levels_controller_test.rb
  dashboard/test/controllers/script_levels_controller_test.rb
  dashboard/test/controllers/scripts_controller_test.rb
  dashboard/test/helpers/script_levels_helper_test.rb
  dashboard/test/integration/caching_test.rb
  dashboard/test/integration/db_query_test.rb
  dashboard/test/integration/session_cookie_test.rb
  dashboard/test/lib/queries/script_activity_test.rb
  dashboard/test/models/script_level_test.rb
  dashboard/test/models/unit_test.rb
  dashboard/test/test_helper.rb
Labels: fixtures-to-factories

#67117 Revert "Revert "Install Bundled Gems in Deployment Mode""
  .github/actions/install-test-variables/action.yml
  .github/workflows/dev_test_docker.yml
  .github/workflows/run_ui_tests.yml
  bin/oneoff/update_ubuntu/02-postupdate.sh
  config.yml.erb
  cookbooks/cdo-apps/recipes/bundle_bootstrap.rb
  cookbooks/cdo-nginx/test/cookbooks/nginx_test/recipes/default.rb
  cookbooks/cdo-ruby/recipes/switch-to-deployment-mode.rb
  docker/ci/scripts/prepare_ui_tests.sh
  docker/ci/scripts/prepare_unit_tests.sh
  lib/cdo/rake_utils.rb
  locals.yml.default
Labels: Ruby Update

#67517 Disable Some Overrides for Rails 5.2 Config Options
  dashboard/config/application.rb
Labels: Rails Upgrade

#67509 Allow Overriding Local Webdriver Tests
  lib/rake/ci.rake
Labels: UI Testing, dev-experience

#67642 Revert "Revert "Revert "Revert "Install Bundled Gems in Deployment Mode""""
  .github/actions/install-test-variables/action.yml
  .github/workflows/dev_test_docker.yml
  .github/workflows/run_ui_tests.yml
  bin/oneoff/update_ubuntu/02-postupdate.sh
  config.yml.erb
  cookbooks/cdo-apps/recipes/bundle_bootstrap.rb
  cookbooks/cdo-nginx/test/cookbooks/nginx_test/recipes/default.rb
  cookbooks/cdo-ruby/recipes/switch-to-deployment-mode.rb
  docker/ci/scripts/prepare_ui_tests.sh
  docker/ci/scripts/prepare_unit_tests.sh
  lib/cdo/rake_utils.rb
  locals.yml.default
Labels: Ruby Update

#67623 Remove Temporary Transitional Deployment Install
  cookbooks/cdo-ruby/recipes/bundler.rb
  cookbooks/cdo-ruby/recipes/switch-to-deployment-mode.rb
Labels: Ruby Update

#67796 [All Labs] Making match levels keyboard navigable
  apps/src/code-studio/levels/match.js
  dashboard/app/assets/stylesheets/application.scss
  dashboard/app/views/levels/_single_match.html.haml
Labels: accessibility

#67833 Revert "Revert "Making mult choice levels keyboard navigable""
  apps/src/code-studio/levels/multi.js
  dashboard/app/views/levels/_dialog.html.haml
  dashboard/app/views/levels/_single_multi.html.haml
  dashboard/test/ui/features/step_definitions/pd.rb
Labels: accessibility

#67970 I18n sync In & Up 08/26
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/music.json
  i18n/locales/source/blockly-mooc/signup.json
  i18n/locales/source/course_content/2023/k5-onlinepd-2023.json
  i18n/locales/source/course_content/2024/foundations-gen-ai-2024.json
  i18n/locales/source/course_content/2024/k5-ai-data-2024.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/devise.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#67891 Updating Blockly shortcuts menu to fit our styling
  apps/src/blockly/addons/cdoKeyboardNavigation.ts
  apps/src/blockly/addons/shortcutMenuStyles.scss
Labels: accessibility
