Repository code-dot-org/code-dot-org, pull requests merged in 2025-06, with the labels that each got.

#66218 Add Compatibility for Psych 4
  lib/cdo/yaml.rb
Labels: Ruby Update

#65533 update Ruby to 3.1
  .drone.yml
  .ruby-version
  Gemfile.lock
  SETUP.md
  bin/test/i18n/test_i18n_script_utils.rb
  cookbooks/cdo-ruby/attributes/default.rb
  cookbooks/cdo-ruby/recipes/ruby-build.rb
  cookbooks/cdo-ruby/test/integration/default/inspec/ruby_spec.rb
  docker/ci/Dockerfile
  docker/ui-tests-compose.yml
  docker/unit-tests-compose.yml
Labels: Ruby Update

#65370 reorganize access_logs stack template
  aws/cloudformation/standalone/access_logs/README.md
  aws/cloudformation/standalone/access_logs/access_logs.rb
  aws/cloudformation/standalone/access_logs/access_logs.yml
  aws/cloudformation/standalone/access_logs/access_logs_partition.rb
  aws/cloudformation/standalone/access_logs/parameters.json
Labels: infrastructure

#66617 [Google Blockly] Disable cross-tab copy/paste when using keyboard navigation
  apps/src/blockly/googleBlocklyWrapper.ts
Labels: accessibility

#66638 Fixing regression to experiment flag string and cleaning up
  apps/src/blockly/addons/cdoUtils.ts
  apps/src/blockly/googleBlocklyWrapper.ts
  apps/src/util/experiments.js
Labels: accessibility

#66656 I18n sync In & Up 06/23
  i18n/locales/source/blockly-mooc/aichat.json
  i18n/locales/source/blockly-mooc/lab2.json
  i18n/locales/source/blockly-mooc/music.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#66667 [MusicLab] Adding new analytics event for spacebar play button
  apps/src/music/views/KeyHandler.tsx
Labels: accessibility

#66694 Adds focus lock to AITA
  apps/src/aiDifferentiation/AiDiffContainer.tsx
Labels: accessibility

#66727 Music Lab: Fix focus on feedback and make it more generic
  apps/src/aichat/views/AichatView.tsx
  apps/src/dance/lab2/views/DanceView.tsx
  apps/src/lab2/views/components/Instructions.tsx
  apps/src/lab2/views/components/InstructionsPanel.tsx
  apps/src/music/views/MusicLabView.tsx
Labels: accessibility

#66480 [User Model Improvements] AI Accesible Concern
  dashboard/app/models/concerns/user/ai_accessible.rb
  dashboard/app/models/user.rb
  dashboard/config/initializers/devise.rb
  dashboard/lib/metrics/events.rb
  dashboard/lib/queries/user/enabled_experiments.rb
  dashboard/lib/queries/user/teacher_enabled_experiments.rb
  dashboard/test/lib/queries/user/enabled_experiments_test.rb
  dashboard/test/lib/queries/user/teacher_enabled_experiments_test.rb
  dashboard/test/models/concerns/user/ai_accessible_test.rb
  dashboard/test/models/user_test.rb
Labels: code-hygiene, ruby, refactor
