Repository code-dot-org/code-dot-org, pull requests merged in 2025-03, with the labels that each got.

#64261 I18n sync In & Up 03/03
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/lab2.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#64511 I18n sync In & Up 03/12
  i18n/locales/source/blockly-mooc/codebridge.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/pythonlab.json
  i18n/locales/source/course_content/2018/K5-OnlinePD.json
  i18n/locales/source/course_content/2019/k5-onlinepd-2019.json
  i18n/locales/source/course_content/2021/kodea-pd-2021.json
  i18n/locales/source/course_content/2024/elem-game-design-2024.json
  i18n/locales/source/course_content/2024/k5-ai-data-2024.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/course_content/other/k5howaimakesdecisions.json
  i18n/locales/source/course_content/other/k5plgamedesign.json
  i18n/locales/source/course_content/other/self-paced-pl-csd1-2024.json
  i18n/locales/source/course_content/other/self-paced-pl-csd2-2024.json
  i18n/locales/source/course_content/other/self-paced-pl-csd3-2024.json
  i18n/locales/source/course_content/other/self-paced-pl-csd4-2024.json
  i18n/locales/source/course_content/other/self-paced-pl-csd5-2024.json
  i18n/locales/source/course_content/other/self-paced-pl-exploring-gen-ai.json
  i18n/locales/source/dashboard/base.yml
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/progressions.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/dashboard/variable_names.yml
  i18n/locales/source/hourofcode/en.yml
Labels: i18n

#63621 A11Y-131 updated Buttons in ConfirmCancelFooter
  apps/src/accounts/AddParentEmailModal.jsx
  apps/src/accounts/AdminAccountDialog.jsx
  apps/src/accounts/ChangeUserTypeModal.jsx
  apps/src/accounts/DeleteAccountDialog.jsx
  apps/src/accounts/PersonalLoginDialog.jsx
  apps/src/sharedComponents/SystemDialog/ConfirmCancelFooter.jsx
  apps/src/templates/manageStudents/ConfirmRemoveStudentDialog.jsx
  apps/src/templates/manageStudents/ConfirmRemoveStudentDialog.story.jsx
  apps/test/unit/accounts/AddParentEmailModalTest.jsx
  apps/test/unit/accounts/ChangeUserTypeModalTest.jsx
  apps/test/unit/accounts/DeleteAccountTest.jsx
  apps/test/unit/templates/manageStudents/ConfirmRemoveStudentDialogTest.jsx
Labels: accessibility

#64398 Removing hidden empty button in Musiclab dialog
  apps/src/music/views/SoundsPanel.tsx
  apps/src/music/views/soundsPanel.module.scss
Labels: accessibility

#64444 Use Latest Stable Chromedriver in CI
  .drone.yml
  docker/ci/Dockerfile
  docker/unit-tests-compose.yml
Labels: testing

#64701 Adding role and tab navigability to callout buttons
  apps/src/templates/EnhancedSafeMarkdown.jsx
  dashboard/app/assets/stylesheets/application.scss
Labels: accessibility

#64856 I18n sync In & Up 03/27
  i18n/locales/source/blockly-mooc/codebridge.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/blockly-mooc/pythonlab.json
  i18n/locales/source/course_content/other/allthethings.json
  i18n/locales/source/dashboard/course_offerings.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/scripts.yml
Labels: i18n

#64773 [Code Standards] Rails resourceful maker routes
  dashboard/config/routes.rb
Labels: code-hygiene

#64906 I18n sync In & Up 03/31
  i18n/locales/source/blockly-mooc/aichat.json
  i18n/locales/source/blockly-mooc/common.json
  i18n/locales/source/dashboard/courses.yml
  i18n/locales/source/dashboard/scripts.yml
  i18n/locales/source/markdown/public/educate/it.md
Labels: i18n
